### ISSUE TITLE
assertion error len(tx_counts) == size

### ISSUE THREAD

**Issue by accumulator** [kyuupichan/electrumx#1009]
I noticed my old installation of electrumx (0.9.5) stopped working. I upgraded to 0.14.0 and after upgrading the database it still can't start. 

Do I have a database corruption? 

Using bitcoind, COIN="BitcoinSegwit"

```
mei 23 12:53:06 skunk electrumx_server[1672]:     await self._read_tx_counts()
mei 23 12:53:06 skunk electrumx_server[1672]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.14.0-py3.7.egg/electrumx/server/db.py", line 115, in _read_tx_counts
mei 23 12:53:06 skunk electrumx_server[1672]:     assert len(tx_counts) == size
mei 23 12:53:06 skunk electrumx_server[1672]: AssertionError

```

Also, running contrib/query.py, I get a similar error:
```

$ ./query.py 
Traceback (most recent call last):
  File "./query.py", line 113, in <module>
    main()
  File "./query.py", line 110, in main
    loop.run_until_complete(query(args))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "./query.py", line 65, in query
    await db.open_for_serving()
  File "/usr/local/lib/python3.7/dist-packages/electrumX-1.14.0-py3.7.egg/electrumx/server/db.py", line 170, in open_for_serving
  File "/usr/local/lib/python3.7/dist-packages/electrumX-1.14.0-py3.7.egg/electrumx/server/db.py", line 147, in _open_dbs
  File "/usr/local/lib/python3.7/dist-packages/electrumX-1.14.0-py3.7.egg/electrumx/server/db.py", line 115, in _read_tx_counts
AssertionError

```

Is this repairable? I'd rather not resync the entire chain...

**Comment by accumulator** [comment]
I remember seeing the log entries as described in #185
