### ISSUE TITLE
Electrumx 1.14.0 - ill formed response keeps crashing server

### ISSUE THREAD

**Issue by spiccioli** [kyuupichan/electrumx#1023]
ERROR:electrumx:ElectrumX server terminated abnormally
Jun 25 11:38:57 host.my.net electrumx_server[21579]: Traceback (most recent call last):
Jun 25 11:38:57 host.my.net electrumx_server[21579]:   File "/home/electrumx/electrumx/electrumx_server", line 35, in main
Jun 25 11:38:57 host.my.net electrumx_server[21579]:     asyncio.run(controller.run())
Jun 25 11:38:57 host.my.net electrumx_server[21579]:   File "/usr/lib64/python3.7/asyncio/runners.py", line 43, in run
Jun 25 11:38:57 host.my.net electrumx_server[21579]:     return loop.run_until_complete(main)
Jun 25 11:38:57 host.my.net electrumx_server[21579]:   File "/usr/lib64/python3.7/asyncio/base_events.py", line 584, in run_until_complete
Jun 25 11:38:57 host.my.net electrumx_server[21579]:     return future.result()
Jun 25 11:38:57 host.my.net electrumx_server[21579]:   File "/home/electrumx/electrumx/electrumx/lib/server_base.py", line 125, in run
Jun 25 11:38:57 host.my.net electrumx_server[21579]:     await server_task
Jun 25 11:38:57 host.my.net electrumx_server[21579]:   File "/home/electrumx/electrumx/electrumx/lib/server_base.py", line 98, in serve
Jun 25 11:38:57 host.my.net electrumx_server[21579]:     await self.serve(shutdown_event)
Jun 25 11:38:57 host.my.net electrumx_server[21579]:   File "/home/electrumx/electrumx/electrumx/server/controller.py", line 134, in serve
Jun 25 11:38:57 host.my.net electrumx_server[21579]:     await group.spawn(wait_for_catchup())
Jun 25 11:38:57 host.my.net electrumx_server[21579]:   File "/usr/local/lib64/python3.7/site-packages/aiorpcx/curio.py", line 242, in __aexit__
Jun 25 11:38:57 host.my.net electrumx_server[21579]:     await self.join()
Jun 25 11:38:57 host.my.net electrumx_server[21579]:   File "/usr/local/lib64/python3.7/site-packages/aiorpcx/curio.py", line 211, in join
Jun 25 11:38:57 host.my.net electrumx_server[21579]:     raise task.exception()
Jun 25 11:38:57 host.my.net electrumx_server[21579]:   File "/home/electrumx/electrumx/electrumx/server/session.py", line 611, in serve
Jun 25 11:38:57 host.my.net electrumx_server[21579]:     await group.spawn(self._manage_servers())
Jun 25 11:38:57 host.my.net electrumx_server[21579]:   File "/usr/local/lib64/python3.7/site-packages/aiorpcx/curio.py", line 242, in __aexit__
Jun 25 11:38:57 host.my.net electrumx_server[21579]:     await self.join()
Jun 25 11:38:57 host.my.net electrumx_server[21579]:   File "/usr/local/lib64/python3.7/site-packages/aiorpcx/curio.py", line 211, in join
Jun 25 11:38:57 host.my.net electrumx_server[21579]:     raise task.exception()
Jun 25 11:38:57 host.my.net electrumx_server[21579]:   File "/home/electrumx/electrumx/electrumx/server/peers.py", line 459, in discover_peers
Jun 25 11:38:57 host.my.net electrumx_server[21579]:     await group.spawn(self._import_peers())
Jun 25 11:38:57 host.my.net electrumx_server[21579]:   File "/usr/local/lib64/python3.7/site-packages/aiorpcx/curio.py", line 242, in __aexit__
Jun 25 11:38:57 host.my.net electrumx_server[21579]:     await self.join()
Jun 25 11:38:57 host.my.net electrumx_server[21579]:   File "/usr/local/lib64/python3.7/site-packages/aiorpcx/curio.py", line 211, in join
Jun 25 11:38:57 host.my.net electrumx_server[21579]:     raise task.exception()
Jun 25 11:38:57 host.my.net electrumx_server[21579]:   File "/home/electrumx/electrumx/electrumx/server/peers.py", line 234, in _monitor_peer
Jun 25 11:38:57 host.my.net electrumx_server[21579]:     if await self._should_drop_peer(peer):
Jun 25 11:38:57 host.my.net electrumx_server[21579]:   File "/home/electrumx/electrumx/electrumx/server/peers.py", line 277, in _should_drop_peer
Jun 25 11:38:57 host.my.net electrumx_server[21579]:     await self._verify_peer(session, peer)
Jun 25 11:38:57 host.my.net electrumx_server[21579]:   File "/home/electrumx/electrumx/electrumx/server/peers.py", line 383, in _verify_peer
Jun 25 11:38:57 host.my.net electrumx_server[21579]:     await session.send_request('server.add_peer', [features])
Jun 25 11:38:57 host.my.net electrumx_server[21579]:   File "/usr/local/lib64/python3.7/site-packages/aiorpcx/session.py", line 525, in send_request
Jun 25 11:38:57 host.my.net electrumx_server[21579]:     return await self._send_concurrent(message, future, 1)
Jun 25 11:38:57 host.my.net electrumx_server[21579]:   File "/usr/local/lib64/python3.7/site-packages/aiorpcx/session.py", line 495, in _send_concurrent
Jun 25 11:38:57 host.my.net electrumx_server[21579]:     return await future
Jun 25 11:38:57 host.my.net electrumx_server[21579]:   File "/usr/local/lib64/python3.7/site-packages/aiorpcx/jsonrpc.py", line 722, in receive_message
Jun 25 11:38:57 host.my.net electrumx_server[21579]:     item, request_id = self._protocol.message_to_item(message)
Jun 25 11:38:57 host.my.net electrumx_server[21579]:   File "/usr/local/lib64/python3.7/site-packages/aiorpcx/jsonrpc.py", line 274, in message_to_item
Jun 25 11:38:57 host.my.net electrumx_server[21579]:     return cls._process_response(payload)
Jun 25 11:38:57 host.my.net electrumx_server[21579]:   File "/usr/local/lib64/python3.7/site-packages/aiorpcx/jsonrpc.py", line 221, in _process_response
Jun 25 11:38:57 host.my.net electrumx_server[21579]:     raise cls._error(code, message, False, request_id)
Jun 25 11:38:57 host.my.net electrumx_server[21579]: aiorpcx.jsonrpc.ProtocolError: (-32600, 'ill-formed response error object: no new valid entries')

**Comment by spiccioli** [comment]
Sorry,
I was not aware you've dropped bitcoin support for some other altcoin with a similar name.
