### ISSUE TITLE
Crashing on LTC v0.18.1 - ImportError: Error relocating /usr/lib/libleveldb.so.1: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found

### ISSUE THREAD

**Issue by kobrien** [kyuupichan/electrumx#1037]
```
INFO:electrumx:ElectrumX server starting
INFO:electrumx:logging level: INFO
INFO:Controller:Python version: 3.7.6 (default, Dec 21 2019, 02:28:04)  [GCC 8.3.0]
INFO:Controller:software version: ElectrumX 1.15.0
INFO:Controller:aiorpcX version: 0.18.4
INFO:Controller:supported protocol versions: 1.4-1.4.2
INFO:Controller:event loop policy: None
INFO:Controller:reorg limit is 4,000 blocks
INFO:Daemon:daemon #1 at litecoind:19332/ (current)
INFO:DB:switching current directory to /data
INFO:Controller:shutting down
INFO:Controller:shutdown complete
ERROR:electrumx:ElectrumX server terminated abnormally

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/electrumX-1.15.0-py3.7.egg/EGG-INFO/scripts/electrumx_server", line 35, in main
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/site-packages/electrumX-1.15.0-py3.7.egg/electrumx/lib/server_base.py", line 125, in run
    await server_task
  File "/usr/local/lib/python3.7/site-packages/electrumX-1.15.0-py3.7.egg/electrumx/lib/server_base.py", line 98, in serve
    await self.serve(shutdown_event)
  File "/usr/local/lib/python3.7/site-packages/electrumX-1.15.0-py3.7.egg/electrumx/server/controller.py", line 101, in serve
    db = DB(env)
  File "/usr/local/lib/python3.7/site-packages/electrumX-1.15.0-py3.7.egg/electrumx/server/db.py", line 79, in __init__
    self.db_class = db_class(self.env.db_engine)
  File "/usr/local/lib/python3.7/site-packages/electrumX-1.15.0-py3.7.egg/electrumx/server/storage.py", line 20, in db_class
    db_class.import_module()
  File "/usr/local/lib/python3.7/site-packages/electrumX-1.15.0-py3.7.egg/electrumx/server/storage.py", line 76, in import_module
    import plyvel
  File "/usr/local/lib/python3.7/site-packages/plyvel/__init__.py", line 6, in <module>
    from ._plyvel import (  # noqa
ImportError: Error relocating /usr/lib/libleveldb.so.1: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
```

**Comment by kobrien** [comment]
fixed by upgrading my docker image from alpine3.9 to alpine3.12
