### ISSUE TITLE
assertion failure - tx.py: assert self.binary_length >= end

### ISSUE THREAD

**Issue by monkey-jsun** [kyuupichan/electrumx#1038]
I'm using v1.15.0, together with bitcoin core v0.20.1.  Bitcoin core is at top of chain.  ElectrumX crashed in the middle, probably for a different reason.  It is now catching up with bitcoin core, during which this error happened.  And it could not pass beyond this point.

Here are the env variables:

```
export DB_DIRECTORY=$HOME/.electrumx/db
export DAEMON_URL="http://$(cat "$HOME/.bitcoin/.cookie")@localhost:8332"
export COIN=BitcoinSV
export SERVICES=tcp://:50001,ssl://:50002
export SSL_CERTFILE=/etc/ssl/certs/ssl-cert-snakeoil.pem
export SSL_KEYFILE=/etc/ssl/private/ssl-cert-snakeoil.key
```
Console output: 

```
INFO:DB:flushed filesystem data in 0.02s
INFO:History:flushed history in 3.8s for 1,202,912 addrs
INFO:DB:flush #1,317 took 3.8s.  Height 481,636 txs: 248,660,740 (+483,610)
INFO:DB:tx/sec since genesis: 1,279, since last flush: 2,606
INFO:DB:sync time: 2d 05h 59m  ETA: 07h 35m 38s
INFO:BlockProcessor:processed 20 blocks size 19.98 MB in 12.1s
INFO:BlockProcessor:processed 20 blocks size 19.98 MB in 8.0s
INFO:BlockProcessor:processed 20 blocks size 19.95 MB in 7.2s
INFO:BlockProcessor:processed 21 blocks size 19.98 MB in 7.5s
INFO:BlockProcessor:our height: 481,717 daemon: 656,166 UTXOs 213MB hist 94MB
INFO:BlockProcessor:processed 20 blocks size 19.45 MB in 7.1s
INFO:BlockProcessor:processed 11 blocks size 10.99 MB in 4.4s
INFO:BlockProcessor:processed 20 blocks size 19.72 MB in 7.9s
INFO:BlockProcessor:processed 20 blocks size 19.95 MB in 9.0s
INFO:BlockProcessor:our height: 481,788 daemon: 656,166 UTXOs 244MB hist 166MB
INFO:BlockProcessor:processed 20 blocks size 19.95 MB in 6.8s
INFO:BlockProcessor:processed 20 blocks size 19.88 MB in 10.5s
INFO:Prefetcher:cancelled; prefetcher stopping 
INFO:Controller:shutting down
INFO:Controller:shutdown complete
ERROR:electrumx:ElectrumX server terminated abnormally
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/EGG-INFO/scripts/electrumx_server", line 35, in main
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/electrumx/lib/server_base.py", line 125, in run
    await server_task
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/electrumx/lib/server_base.py", line 98, in serve
    await self.serve(shutdown_event)
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/electrumx/server/controller.py", line 134, in serve
    await group.spawn(wait_for_catchup())
  File "/usr/local/lib/python3.8/dist-packages/aiorpcX-0.18.4-py3.8.egg/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/usr/local/lib/python3.8/dist-packages/aiorpcX-0.18.4-py3.8.egg/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/electrumx/server/block_processor.py", line 682, in fetch_and_process_blocks
    await group.spawn(self._process_prefetched_blocks())
  File "/usr/local/lib/python3.8/dist-packages/aiorpcX-0.18.4-py3.8.egg/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/usr/local/lib/python3.8/dist-packages/aiorpcX-0.18.4-py3.8.egg/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/electrumx/server/block_processor.py", line 643, in _process_prefetched_blocks
    await self.check_and_advance_blocks(blocks)
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/electrumx/server/block_processor.py", line 211, in check_and_advance_blocks
    blocks = [self.coin.block(raw_block, first + n)
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/electrumx/server/block_processor.py", line 211, in <listcomp>
    blocks = [self.coin.block(raw_block, first + n)
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/electrumx/lib/coins.py", line 257, in block
    txs = cls.DESERIALIZER(raw_block, start=len(header)).read_tx_block()
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/electrumx/lib/tx.py", line 134, in read_tx_block
    return [read() for _ in range(self._read_varint())]
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/electrumx/lib/tx.py", line 134, in <listcomp>
    return [read() for _ in range(self._read_varint())]
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/electrumx/lib/tx.py", line 124, in read_tx_and_hash
    return self.read_tx(), self.TX_HASH_FN(self.binary[start:self.cursor])
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/electrumx/lib/tx.py", line 112, in read_tx
    self._read_inputs(),    # inputs
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/electrumx/lib/tx.py", line 138, in _read_inputs
    return [read_input() for i in range(self._read_varint())]
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/electrumx/lib/tx.py", line 138, in <listcomp>
    return [read_input() for i in range(self._read_varint())]
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/electrumx/lib/tx.py", line 144, in _read_input
    self._read_varbytes(),   # script
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/electrumx/lib/tx.py", line 170, in _read_varbytes
    return self._read_nbytes(self._read_varint())
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/electrumx/lib/tx.py", line 166, in _read_nbytes
    assert self.binary_length >= end
AssertionError
```

**Comment by monkey-jsun** [comment]
I started a brand new second instance on arm64 and got exactly the same error around the same blockchain height (481,788).  So it must be a deterministic error.  Given that bitcoin is so popular, it is strange why only I got this error.

I start bitcoin with this command with no bitcoin.conf file.

`bitcoin-qt -server -txindex  &`

**Comment by monkey-jsun** [comment]
I added some print statements.  The problem seems to be that when read variable integer, we ended up reading a 64bit integer, which is very large.

```
_read_nbytes : self.binary_length == 989323; n=32, cursor=27163
_read_varint : n = 187; cursor=27200; 
_read_nbytes : self.binary_length == 989323; n=187, cursor=27200
_read_nbytes : self.binary_length == 989323; n=32, cursor=27391
_read_varint : n = 255; cursor=27428; 
_read_nbytes : self.binary_length == 989323; n=8653327013092091391, cursor=27436
INFO:Prefetcher:cancelled; prefetcher stopping 
INFO:Controller:shutting down
INFO:Controller:shutdown complete
ERROR:electrumx:ElectrumX server terminated abnormally
Traceback (most recent call last):
  File "./electrumx_server", line 35, in main
    asyncio.run(controller.run())
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
```

**Comment by SomberNight** [comment]
> I'm using v1.15.0, together with bitcoin core v0.20.1

> export COIN=BitcoinSV

BitcoinSV is not what you want, it's an altcoin. This repo no longer supports bitcoin, you can use https://github.com/spesmilo/electrumx instead. If you use master HEAD there, you can set COIN to "Bitcoin", or the legacy name "BitcoinSegwit" is also still supported.

Your issue is presumably to do with segwit tx serialisation.

**Comment by monkey-jsun** [comment]
Thanks for pointing this out.  Switching to the other repo solved the problem.
