### ISSUE TITLE
Sst file size mismatch

### ISSUE THREAD

**Issue by Deathorn** [kyuupichan/electrumx#168]
So I synced electrumx with rocksdb (see #167):
```
electrumx-server[9381]: INFO:Prefetcher:new block height 460,805 hash 000000000000000000aef339d75c0db711632d1c20904c840bb9d712bcc3a6a1

```
and stopped it to make backup:
```
systemd[1]: Stopping ElectrumX Server...
electrumx-server[9381]: INFO:LocalRPC:[0] RPC xx.xx.xx.xx:xx, 1 total
electrumx-server[9381]: INFO:Controller:shutting down
electrumx-server[9381]: INFO:Controller:closing down RPC listening servers
electrumx-rpc[22254]: "stopping"
electrumx-server[9381]: WARNING:root:received SIGTERM signal, initiating shutdown
electrumx-server[9381]: INFO:Controller:shutdown complete
electrumx-server[9381]: INFO:root:ElectrumX server terminated normally
systemd[1]: Stopped ElectrumX Server.
```

Now when I try to start electrumx server, I get this:
```
systemd[1]: Started ElectrumX Server.
electrumx-server[26349]: INFO:root:ElectrumX server starting
electrumx-server[26349]: INFO:Daemon:daemon #1 at 127.0.0.1:8332/ (current)
electrumx-server[26349]: INFO:BlockProcessor:switching current directory to /srv/electrumx
electrumx-server[26349]: INFO:BlockProcessor:using rocksdb for DB backend
electrumx-server[26349]: Traceback (most recent call last):
electrumx-server[26349]:   File "/usr/bin/electrumx-server", line 75, in main
electrumx-server[26349]:     main_loop()
electrumx-server[26349]:   File "/usr/bin/electrumx-server", line 56, in main_loop
electrumx-server[26349]:     controller = Controller(Env())
electrumx-server[26349]:   File "/usr/lib/python3.6/site-packages/server/controller.py", line 54, in __init__
electrumx-server[26349]:     self.bp = BlockProcessor(env, self, self.daemon)
electrumx-server[26349]:   File "/usr/lib/python3.6/site-packages/server/block_processor.py", line 144, in __init__
electrumx-server[26349]:     super().__init__(env)
electrumx-server[26349]:   File "/usr/lib/python3.6/site-packages/server/db.py", line 64, in __init__
electrumx-server[26349]:     self.open_dbs()
electrumx-server[26349]:   File "/usr/lib/python3.6/site-packages/server/db.py", line 112, in open_dbs
electrumx-server[26349]:     self.utxo_db = self.db_class('utxo', for_sync)
electrumx-server[26349]:   File "/usr/lib/python3.6/site-packages/server/storage.py", line 31, in __init__
electrumx-server[26349]:     self.open(name, create=self.is_new)
electrumx-server[26349]:   File "/usr/lib/python3.6/site-packages/server/storage.py", line 107, in open
electrumx-server[26349]:     self.db = self.module.DB(name, options)
electrumx-server[26349]:   File "rocksdb/_rocksdb.pyx", line 1318, in rocksdb._rocksdb.DB.__cinit__ (rocksdb/_rocksdb.cpp:21679)
electrumx-server[26349]:   File "rocksdb/_rocksdb.pyx", line 73, in rocksdb._rocksdb.check_status (rocksdb/_rocksdb.cpp:3117)
electrumx-server[26349]: rocksdb.errors.Corruption: b'Corruption: Sst file size mismatch: utxo/000547.sst. Size recorded in manifest 33725974, actual size 33726464\nSst file size mismatch: utxo/000551.sst. Size recorded in manifest 33725263, actual size 33726464\nSst file size mismatch: utxo/000552.sst. Size recorded in manifest 33723907, actual size 33726464\nSst file size mismatch: utxo/000553.sst. Size recorded in manifest 33724895, actual size 33726464\nSst file size mismatch: utxo/000554.sst. Size recorded in manifest 33725205, actual size 33726464\nSst file size mismatch: utxo/000555.sst. Size recorded in manifest 33726059, actual size 33726464\nSst file size mismatch: utxo/000563.sst. Size recorded in manifest 26046516, actual size 26050560\nSst file size mismatch: utxo/000574.sst. Size recorded in manifest 26999637, actual size 27000832\nSst file size mismatch: utxo/000645.sst. Size recorded in manifest 33765116, actual size 33767424\nSst file size mismatch: utxo/000646.sst. Size recorded in manifest 33764891, actual size 33767424\nSst file size mismatch: utxo/000647.sst. Size recorded in manifest 33765532, actual size 33767424\nSst file size mismatch: utxo/000648.sst. Size recorded in manifest 8669622, actual size 8671232\nSst file size mismatch: utxo/000586.sst. Size recorded in manifest 33763752, actual size 33767424\nSst file size mismatch: utxo/000614.sst. Size recorded in manifest 33765633, actual size 33767424\nSst file size mismatch: utxo/000615.sst. Size recorded in manifest 33766176, actual size 33767424\nSst file size mismatch: utxo/000616.sst. Size recorded in manifest 33764676, actual size 33767424\nSst file size mismatch: utxo/000617.sst. Size recorded in manifest 17096448, actual size 17096704\nSst file size mismatch: utxo/000649.sst. Size recorded in manifest 33764586, actual size 33767424\nSst file size mismatch: utxo/000650.sst. Size recorded in manifest 33765080, actual size 33767424\nSst file size mismatch: utxo/000651.sst. Size recorded in manifest 15284032, actual size 15286272\nSst file size mismatch: utxo/
electrumx-server[26349]: 000607.sst. Size recorded in manifest 33765805, actual size 33767424\nSst file size mismatch: utxo/000608.sst. Size recorded in manifest 33763344, actual size 33767424\nSst file size mismatch: utxo/000610.sst. Size recorded in manifest 33763643, actual size 33767424\nSst file size mismatch: utxo/000611.sst. Size recorded in manifest 33765625, actual size 33767424\nSst file size mismatch: utxo/000612.sst. Size recorded in manifest 33764050, actual size 33767424\nSst file size mismatch: utxo/000613.sst. Size recorded in manifest 15126986, actual size 15130624\nSst file size mismatch: utxo/000582.sst. Size recorded in manifest 33763588, actual size 33767424\nSst file size mismatch: utxo/000593.sst. Size recorded in manifest 33763533, actual size 33767424\nSst file size mismatch: utxo/000594.sst. Size recorded in manifest 33765309, actual size 33767424\nSst file size mismatch: utxo/000595.sst. Size recorded in manifest 33763664, actual size 33767424\nSst file size mismatch: utxo/000602.sst. Size recorded in manifest 33762721, actual size 33763328\nSst file size mismatch: utxo/000603.sst. Size recorded in manifest 33764145, actual size 33767424\nSst file size mismatch: utxo/000604.sst. Size recorded in manifest 33764440, actual size 33767424\nSst file size mismatch: utxo/000605.sst. Size recorded in manifest 6649685, actual size 6651904\nSst file size mismatch: utxo/000598.sst. Size recorded in manifest 33765883, actual size 33767424\nSst file size mismatch: utxo/000599.sst. Size recorded in manifest 33868383, actual size 33869824\nSst file size mismatch: utxo/000600.sst. Size recorded in manifest 33876154, actual size 33878016\nSst file size mismatch: utxo/000601.sst. Size recorded in manifest 6109847, actual size 6111232\nSst file size mismatch: utxo/000509.sst. Size recorded in manifest 17377208, actual size 17379328\nSst file size mismatch: utxo/000578.sst. Size recorded in manifest 33869169, actual size 33869824\nSst file size mismatch: utxo/000579.sst. Size recorded in manifest 33866268, actual size 33869824\nSs
electrumx-server[26349]: t file size mismatch: utxo/000580.sst. Size recorded in manifest 16315605, actual size 16318464\nSst file size mismatch: utxo/000589.sst. Size recorded in manifest 33872186, actual size 33873920\nSst file size mismatch: utxo/000590.sst. Size recorded in manifest 33869087, actual size 33869824\nSst file size mismatch: utxo/000637.sst. Size recorded in manifest 33869029, actual size 33869824\nSst file size mismatch: utxo/000638.sst. Size recorded in manifest 33866711, actual size 33869824\nSst file size mismatch: utxo/000641.sst. Size recorded in manifest 33872410, actual size 33873920\nSst file size mismatch: utxo/000642.sst. Size recorded in manifest 33871824, actual size 33873920\nSst file size mismatch: utxo/000643.sst. Size recorded in manifest 33871300, actual size 33873920\nSst file size mismatch: utxo/000644.sst. Size recorded in manifest 24495828, actual size 24498176\nSst file size mismatch: utxo/000627.sst. Size recorded in manifest 33870608, actual size 33873920\nSst file size mismatch: utxo/000630.sst. Size recorded in manifest 33867842, actual size 33869824\nSst file size mismatch: utxo/000631.sst. Size recorded in manifest 33869535, actual size 33869824\nSst file size mismatch: utxo/000632.sst. Size recorded in manifest 33868308, actual size 33869824\nSst file size mismatch: utxo/000633.sst. Size recorded in manifest 7241920, actual size 7245824\nSst file size mismatch: utxo/000623.sst. Size recorded in manifest 33867091, actual size 33869824\nSst file size mismatch: utxo/000634.sst. Size recorded in manifest 33869137, actual size 33869824\nSst file size mismatch: utxo/000635.sst. Size recorded in manifest 33869257, actual size 33869824\nSst file size mismatch: utxo/000636.sst. Size recorded in manifest 12833550, actual size 12836864\nSst file size mismatch: utxo/000619.sst. Size recorded in manifest 33864881, actual size 33865728\nSst file size mismatch: utxo/000620.sst. Size recorded in manifest 33884285, actual size 33886208\nSst file size mismatch: utxo/000621.sst. Size recorded in manifest 19753
electrumx-server[26349]: 66, actual size 1978368\n'
electrumx-server[26349]: CRITICAL:root:ElectrumX server terminated abnormally
```

What is this? Can I fix it?

**Comment by kyuupichan** [comment]
Not sure, never seen it before.  Did you not have a single unclean shutdown?

http://pyrocksdb.readthedocs.io/en/v0.4/api/database.html#repair-db

might be worth a try.

**Comment by Deathorn** [comment]
No, since I first start syncing, no shutdown or reboot was made.

I'm not sure how to use that repair thing, I'm not a python programmer, can you suggest something?

**Comment by kyuupichan** [comment]
Just above where the DB is opened at

https://github.com/kyuupichan/electrumx/blob/master/server/storage.py#L107

try to add the line:

self.module.repair_db(name, options)

It only has a small chance of working I guess.  If it doesn't help I can only suggest restarting; sorry you're having these issues, it is not normal at all.

**Comment by kyuupichan** [comment]
For the record can you please state your distro, filesystem and whether you're running in a VM configuration of some kind.

**Comment by Deathorn** [comment]
With that line I have this
```
electrumx-server[4648]: INFO:root:ElectrumX server starting
electrumx-server[4648]: INFO:Daemon:daemon #1 at 127.0.0.1:8332/ (current)
electrumx-server[4648]: INFO:BlockProcessor:switching current directory to /srv/electrumx
electrumx-server[4648]: INFO:BlockProcessor:using rocksdb for DB backend
electrumx-server[4648]: INFO:BlockProcessor:opened DB for serving
electrumx-server[4648]: INFO:BlockProcessor:software version: ElectrumX 1.0.5
electrumx-server[4648]: INFO:BlockProcessor:DB version: 5
electrumx-server[4648]: INFO:BlockProcessor:coin: Bitcoin
electrumx-server[4648]: INFO:BlockProcessor:network: mainnet
electrumx-server[4648]: INFO:BlockProcessor:height: 460,794
electrumx-server[4648]: INFO:BlockProcessor:tip: 0000000000000000012b3f9003783e9e33ca30743a42147b83f311253c703c1e
electrumx-server[4648]: INFO:BlockProcessor:tx count: 211,313,622
electrumx-server[4648]: INFO:BlockProcessor:reorg limit is 200 blocks
electrumx-server[4648]: INFO:PeerManager:accepted 15/15 new peers of 15 from coins.py
electrumx-server[4648]: INFO:Controller:RPC server listening on localhost:8000
electrumx-server[4648]: INFO:Prefetcher:catching up to daemon height 460,818 (24 blocks behind)
electrumx-server[4648]: ERROR:Controller:Traceback (most recent call last):
electrumx-server[4648]:   File "/usr/lib/python3.6/site-packages/server/controller.py", line 160, in on_future_done
electrumx-server[4648]:     future.result()
electrumx-server[4648]:   File "/usr/lib/python3.6/site-packages/server/block_processor.py", line 201, in main_loop
electrumx-server[4648]:     await task()
electrumx-server[4648]:   File "/usr/lib/python3.6/site-packages/server/block_processor.py", line 243, in check_and_advance_blocks
electrumx-server[4648]:     await self.controller.run_in_executor(self.advance_blocks, blocks)
electrumx-server[4648]:   File "/usr/lib/python3.6/site-packages/server/controller.py", line 140, in run_in_executor
electrumx-server[4648]:     return await self.loop.run_in_executor(None, func, *args)
electrumx-server[4648]:   File "/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
electrumx-server[4648]:     result = self.fn(*self.args, **self.kwargs)
electrumx-server[4648]:   File "/usr/lib/python3.6/site-packages/server/block_processor.py", line 493, in advance_blocks
electrumx-server[4648]:     undo_info = self.advance_txs(block.transactions)
electrumx-server[4648]:   File "/usr/lib/python3.6/site-packages/server/block_processor.py", line 535, in advance_txs
electrumx-server[4648]:     cache_value = spend_utxo(txin.prev_hash, txin.prev_idx)
electrumx-server[4648]:   File "/usr/lib/python3.6/site-packages/server/block_processor.py", line 720, in spend_utxo
electrumx-server[4648]:     .format(hash_to_str(tx_hash), tx_idx))
electrumx-server[4648]: server.block_processor.ChainError: UTXO bd95f5ded6cac57ddd225a5276cf86bd80d65147acc3824b41ea3a53cba196f1 / 0 not found in "h" table
```
I guess I need to do sync once more.

Arch Linux, XFS on SSD, no VM. Could it be hardware problem of some kind?

**Comment by kyuupichan** [comment]
I don't know.  It could be hardware, filesystem, kernel or even obsolete BIOS settings (this happened to me on my O/S).  If it corrupts again then for sure something isn't right.

**Comment by Deathorn** [comment]
It happened again. I did not wait for the whole sync, just restart electrumx server few times. And after second restart I got this:
```
electrumx-server[2089]: INFO:BlockProcessor:flushed to FS in 0.1s
electrumx-server[2089]: INFO:BlockProcessor:flushed history in 5.9s for 1,096,588 addrs
electrumx-server[2089]: INFO:BlockProcessor:flush #16 took 6.2s.  Height 242,250 txs: 19,637,395
electrumx-server[2089]: INFO:BlockProcessor:tx/sec since genesis: 5,327, since last flush: 4,986
electrumx-server[2089]: INFO:BlockProcessor:sync time: 01h 01m 25s  ETA: 15h 59m 22s
electrumx-server[2089]: INFO:BlockProcessor:our height: 242,818 daemon: 460,830 UTXOs 423MB hist 43MB
electrumx-server[2089]: INFO:BlockProcessor:our height: 243,530 daemon: 460,830 UTXOs 435MB hist 83MB
systemd[1]: Stopping ElectrumX Server...
electrumx-server[2089]: INFO:LocalRPC:[0] RPC xx.xx.xx.xx:xx, 1 total
electrumx-rpc[9720]: "stopping"
electrumx-server[2089]: INFO:Controller:shutting down
electrumx-server[2089]: INFO:Controller:closing down RPC listening servers
electrumx-server[2089]: ERROR:Controller:Traceback (most recent call last):
electrumx-server[2089]:   File "/usr/lib/python3.6/site-packages/server/daemon.py", line 105, in _send
electrumx-server[2089]:     result = await self._send_data(data)
electrumx-server[2089]:   File "/usr/lib/python3.6/site-packages/server/daemon.py", line 74, in _send_data
electrumx-server[2089]:     async with session.post(self.url(), data=data) as resp:
electrumx-server[2089]:   File "/usr/lib/python3.6/site-packages/aiohttp/client.py", line 626, in __aenter__
electrumx-server[2089]:     self._resp = yield from self._coro
electrumx-server[2089]:   File "/usr/lib/python3.6/site-packages/aiohttp/client.py", line 235, in _request
electrumx-server[2089]:     yield from resp.start(conn, read_until_eof)
electrumx-server[2089]:   File "/usr/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 528, in start
electrumx-server[2089]:     (message, payload) = yield from self._protocol.read()
electrumx-server[2089]:   File "/usr/lib/python3.6/site-packages/aiohttp/streams.py", line 489, in read
electrumx-server[2089]:     yield from self._waiter
electrumx-server[2089]: concurrent.futures._base.CancelledError
electrumx-server[2089]: During handling of the above exception, another exception occurred:
electrumx-server[2089]: Traceback (most recent call last):
electrumx-server[2089]:   File "/usr/lib/python3.6/site-packages/server/controller.py", line 160, in on_future_done
electrumx-server[2089]:     future.result()
electrumx-server[2089]:   File "/usr/lib/python3.6/site-packages/server/block_processor.py", line 50, in main_loop
electrumx-server[2089]:     if not await self._prefetch_blocks():
electrumx-server[2089]:   File "/usr/lib/python3.6/site-packages/server/block_processor.py", line 87, in _prefetch_blocks
electrumx-server[2089]:     daemon_height = await daemon.height(self.bp.caught_up_event.is_set())
electrumx-server[2089]:   File "/usr/lib/python3.6/site-packages/server/daemon.py", line 226, in height
electrumx-server[2089]:     self._height = await self._send_single('getblockcount')
electrumx-server[2089]:   File "/usr/lib/python3.6/site-packages/server/daemon.py", line 151, in _send_single
electrumx-server[2089]:     return await self._send(payload, processor)
electrumx-server[2089]:   File "/usr/lib/python3.6/site-packages/server/daemon.py", line 117, in _send
electrumx-server[2089]:     except aiohttp.ClientHttpProcessingError:
electrumx-server[2089]: AttributeError: module 'aiohttp' has no attribute 'ClientHttpProcessingError'
electrumx-server[2089]: WARNING:root:received SIGTERM signal, initiating shutdown
electrumx-server[2089]: INFO:BlockProcessor:flushing state to DB for a clean shutdown...
electrumx-server[2089]: INFO:BlockProcessor:flushed to FS in 0.0s
electrumx-server[2089]: INFO:BlockProcessor:flushed history in 1.9s for 486,049 addrs
electrumx-server[2089]: INFO:BlockProcessor:flushed 10,145 blocks with 3,154,825 txs, 1,902,165 UTXO adds, 499,981 spends in 8.8s, committing...
electrumx-server[2089]: INFO:BlockProcessor:flush #17 took 25.9s.  Height 244,046 txs: 20,132,367
electrumx-server[2089]: INFO:BlockProcessor:tx/sec since genesis: 5,292, since last flush: 4,192
electrumx-server[2089]: INFO:BlockProcessor:sync time: 01h 03m 24s  ETA: 18h 55m 16s
electrumx-server[2089]: INFO:Controller:shutdown complete
electrumx-server[2089]: INFO:root:ElectrumX server terminated normally
systemd[1]: Stopped ElectrumX Server.
systemd[1]: Started ElectrumX Server.
electrumx-server[9815]: INFO:root:ElectrumX server starting
electrumx-server[9815]: INFO:Daemon:daemon #1 at 127.0.0.1:8332/ (current)
electrumx-server[9815]: INFO:BlockProcessor:switching current directory to /srv/electrumx
electrumx-server[9815]: INFO:BlockProcessor:using rocksdb for DB backend
electrumx-server[9815]: Traceback (most recent call last):
electrumx-server[9815]:   File "/usr/bin/electrumx-server", line 75, in main
electrumx-server[9815]:     main_loop()
electrumx-server[9815]:   File "/usr/bin/electrumx-server", line 56, in main_loop
electrumx-server[9815]:     controller = Controller(Env())
electrumx-server[9815]:   File "/usr/lib/python3.6/site-packages/server/controller.py", line 54, in __init__
electrumx-server[9815]:     self.bp = BlockProcessor(env, self, self.daemon)
electrumx-server[9815]:   File "/usr/lib/python3.6/site-packages/server/block_processor.py", line 144, in __init__
electrumx-server[9815]:     super().__init__(env)
electrumx-server[9815]:   File "/usr/lib/python3.6/site-packages/server/db.py", line 64, in __init__
electrumx-server[9815]:     self.open_dbs()
electrumx-server[9815]:   File "/usr/lib/python3.6/site-packages/server/db.py", line 113, in open_dbs
electrumx-server[9815]:     self.hist_db = self.db_class('hist', for_sync)
electrumx-server[9815]:   File "/usr/lib/python3.6/site-packages/server/storage.py", line 31, in __init__
electrumx-server[9815]:     self.open(name, create=self.is_new)
electrumx-server[9815]:   File "/usr/lib/python3.6/site-packages/server/storage.py", line 107, in open
electrumx-server[9815]:     self.db = self.module.DB(name, options)
electrumx-server[9815]:   File "rocksdb/_rocksdb.pyx", line 1318, in rocksdb._rocksdb.DB.__cinit__ (rocksdb/_rocksdb.cpp:21679)
electrumx-server[9815]:   File "rocksdb/_rocksdb.pyx", line 73, in rocksdb._rocksdb.check_status (rocksdb/_rocksdb.cpp:3117)
electrumx-server[9815]: rocksdb.errors.Corruption: b'Corruption: Sst file size mismatch: hist/000035.sst. Size recorded in manifest 33726410, actual size 33726464\nSst file size mismatch: hist/000037.sst. Size recorded in manifest 33674361, actual size 33677312\nSst file size mismatch: hist/000038.sst. Size recorded in manifest 33704081, actual size 33705984\nSst file size mismatch: hist/000040.sst. Size recorded in manifest 33717020, actual size 33718272\nSst file size mismatch: hist/000041.sst. Size recorded in manifest 33726820, actual size 33730560\nSst file size mismatch: hist/000042.sst. Size recorded in manifest 33678061, actual size 33681408\nSst file size mismatch: hist/000044.sst. Size recorded in manifest 33725050, actual size 33726464\nSst file size mismatch: hist/000050.sst. Size recorded in manifest 3494511, actual size 3497984\nSst file size mismatch: hist/000034.sst. Size recorded in manifest 33733387, actual size 33734656\nSst file size mismatch: hist/000036.sst. Size recorded in manifest 33733147, actual size 33734656\nSst file size mismatch: hist/000039.sst. Size recorded in manifest 33728047, actual size 33730560\nSst file size mismatch: hist/000043.sst. Size recorded in manifest 33819082, actual size 33820672\nSst file size mismatch: hist/000045.sst. Size recorded in manifest 33741593, actual size 33742848\nSst file size mismatch: hist/000046.sst. Size recorded in manifest 34006365, actual size 34009088\nSst file size mismatch: hist/000047.sst. Size recorded in manifest 33731809, actual size 33734656\nSst file size mismatch: hist/000048.sst. Size recorded in manifest 33738789, actual size 33742848\nSst file size mismatch: hist/000049.sst. Size recorded in manifest 33727298, actual size 33730560\n'
electrumx-server[9815]: CRITICAL:root:ElectrumX server terminated abnormally

```

I don't understand it. It says "ElectrumX server terminated normally", and then after start "Sst file size mismatch" messages...All other things are working on this server, bitcoind at least does not complain and crash at all.

**Comment by bauerj** [comment]
What version of RocksDB do you use?

**Comment by Deathorn** [comment]
5.2.1

**Comment by Deathorn** [comment]
As for kernels, I tried 
linux 4.10.8
linux-lts 4.9.20
linux-zen 4.10.6

Also I tried with `libata.force=noncq` kernel parameter and without it.

**Comment by Deathorn** [comment]
Ok, so I replaced SSD with the new one, no difference. So I don't think it is hardware issue.

**Comment by Deathorn** [comment]
Well, I'm out of ideas. Leveldb is segfaulting, Rocksdb is corrupting. I guess no electrum server for me :(

**Comment by epichub** [comment]
@Deathorn I have the same problems with my arch installation, Leveldb is segfaulting and Rocksdb is corrupting. Up-to-date Arch linux cannot run ElectrumX it seems.

**Comment by mdcallag** [comment]
Maybe fixed by this - https://github.com/facebook/rocksdb/pull/2102
