### ISSUE TITLE
TypeError: '<' not supported between instances of 'int' and 'tuple'

### ISSUE THREAD

**Issue by shsmith** [kyuupichan/electrumx#180]
I see this from time to time:
```
 ERROR:ElectrumX:[1588] Traceback (most recent call last):
   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.10-py3.6.egg/lib/jsonrpc.py", line 528, in process_single_request
     result = await self.handle_payload(payload, self.request_handler)
   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.10-py3.6.egg/lib/jsonrpc.py", line 610, in handle_payload
     return handler(**kw_args)
   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.0.10-py3.6.egg/server/session.py", line 266, in block_get_chunk
     if self.client_version < (2, 8, 3):
 TypeError: '<' not supported between instances of 'int' and 'tuple'

```

**Comment by erasmospunk** [comment]
The server incorrectly assumes a particular structure for the version string, the parsing should be more robust.

To reproduce in REPL:
```
>>> client_version = (1, 2, 3)
>>> client_version < (2, 8, 3)
True
>>> client_version = (1)
>>> client_version < (2, 8, 3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '<' not supported between instances of 'int' and 'tuple'
```
