### ISSUE TITLE
Error on sessions rpc command (v1.1)

### ISSUE THREAD

**Issue by luggs-co** [kyuupichan/electrumx#250]
```
# electrumx_rpc.py -p 8000 sessions
ID     Flags            Client Proto  Reqs   Txs    Subs    Recv Recv KB    Sent Sent KB      Time                  Peer
[0] Traceback (most recent call last):
  File "/opt/python/lib/python3.6/site-packages/electrumx-1.1rc1-py3.6.egg/lib/jsonrpc.py", line 557, in process_single_response
    self.version.handle_response(handler, payload)
  File "/opt/python/lib/python3.6/site-packages/electrumx-1.1rc1-py3.6.egg/lib/jsonrpc.py", line 178, in handle_response
    handler(payload['result'], None)
  File "/opt/python/lib/python3.6/site-packages/electrumx-1.1rc1-py3.6.egg/EGG-INFO/scripts/electrumx_rpc.py", line 41, in handle_response
  File "/opt/python/lib/python3.6/site-packages/electrumx-1.1rc1-py3.6.egg/server/controller.py", line 539, in sessions_text_lines
    recv_count, recv_size, send_count, send_size, time) in data:
ValueError: not enough values to unpack (expected 13, got 12)
```

**Comment by kyuupichan** [comment]
I think you are running the script and the server with different code bases

**Comment by luggs-co** [comment]
I use the electrumx-installer and never had any issues upgrading before... just checked it's only version that exists, and moth *appear* to run the 1.1rc1

**Comment by luggs-co** [comment]
ok, had a stale process running that i hadn't spotted... ignore me!
