### ISSUE TITLE
ChainError: UTXO not found in "h" table

### ISSUE THREAD

**Issue by zaventh** [kyuupichan/electrumx#256]
```
Sep 09 15:45:14 electrum electrumx_server.py[1840]: INFO:BlockProcessor:flushed 1,907 blocks with 1,490,644 txs, 4,297,559 UTXO adds, 1,056,163 spends in 13.5s, committing...
Sep 09 15:45:51 electrum electrumx_server.py[1840]: INFO:BlockProcessor:flush #95 took 58.4s.  Height 370,234 txs: 80,186,394
Sep 09 15:45:51 electrum electrumx_server.py[1840]: INFO:BlockProcessor:tx/sec since genesis: 5,612, since last flush: 3,025
Sep 09 15:45:51 electrum electrumx_server.py[1840]: INFO:BlockProcessor:sync time: 03h 58m 08s  ETA: 20h 28m 34s
Sep 09 15:46:31 electrum electrumx_server.py[1840]: INFO:BlockProcessor:our height: 370,358 daemon: 484,423 UTXOs 39MB hist 49MB
Sep 09 15:47:06 electrum electrumx_server.py[1840]: INFO:BlockProcessor:our height: 370,519 daemon: 484,423 UTXOs 73MB hist 104MB
Sep 09 15:47:37 electrum electrumx_server.py[1840]: INFO:BlockProcessor:our height: 370,719 daemon: 484,423 UTXOs 105MB hist 156MB
Sep 09 15:47:45 electrum electrumx_server.py[1840]: ERROR:Controller:Traceback (most recent call last):
Sep 09 15:47:45 electrum electrumx_server.py[1840]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.1-py3.6.egg/server/controller.py", line 163, in on_future_done
Sep 09 15:47:45 electrum electrumx_server.py[1840]:     future.result()
Sep 09 15:47:45 electrum electrumx_server.py[1840]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.1-py3.6.egg/server/block_processor.py", line 206, in main_loop
Sep 09 15:47:45 electrum electrumx_server.py[1840]:     await task()
Sep 09 15:47:45 electrum electrumx_server.py[1840]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.1-py3.6.egg/server/block_processor.py", line 250, in check_and_advance_blocks
Sep 09 15:47:45 electrum electrumx_server.py[1840]:     await self.controller.run_in_executor(self.advance_blocks, blocks)
Sep 09 15:47:45 electrum electrumx_server.py[1840]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.1-py3.6.egg/server/controller.py", line 143, in run_in_executor
Sep 09 15:47:45 electrum electrumx_server.py[1840]:     return await self.loop.run_in_executor(None, func, *args)
Sep 09 15:47:45 electrum electrumx_server.py[1840]:   File "/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
Sep 09 15:47:45 electrum electrumx_server.py[1840]:     result = self.fn(*self.args, **self.kwargs)
Sep 09 15:47:45 electrum electrumx_server.py[1840]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.1-py3.6.egg/server/block_processor.py", line 500, in advance_blocks
Sep 09 15:47:45 electrum electrumx_server.py[1840]:     undo_info = self.advance_txs(block.transactions)
Sep 09 15:47:45 electrum electrumx_server.py[1840]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.1-py3.6.egg/server/block_processor.py", line 542, in advance_txs
Sep 09 15:47:45 electrum electrumx_server.py[1840]:     cache_value = spend_utxo(txin.prev_hash, txin.prev_idx)
Sep 09 15:47:45 electrum electrumx_server.py[1840]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.1-py3.6.egg/server/block_processor.py", line 727, in spend_utxo
Sep 09 15:47:45 electrum electrumx_server.py[1840]:     .format(hash_to_str(tx_hash), tx_idx))
Sep 09 15:47:45 electrum electrumx_server.py[1840]: server.block_processor.ChainError: UTXO f680dcd5eb03307216896da3ce872f3dafcd73745109f1c2bc8a11706336571c / 1 not found in "h" table
```

```sh
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

$ python3.6 --version
Python 3.6.2

$ bitcoind --version
Bitcoin Core Daemon version v0.14.2.0-gfc61c83
Copyright (C) 2009-2017 The Bitcoin Core developers

$ git show --shortstat  HEAD
commit 131344715ab753af6fef5bc3b74186f2e4bab9da
Author: Neil Booth <kyuupichan@gmail.com>
Date:   Sat Sep 9 21:53:03 2017 +0900
```

Trying to sync from scratch. I believe I was getting this with `1.0.17` as well but I updated to `1.1` and am still having this issue. Targeting BitcoinSegwit and mainnet.

**Comment by kyuupichan** [comment]
Your DB is corrupt.  What is your O/S, filesystem and DB?

**Comment by kyuupichan** [comment]
You will need to start again

**Comment by zaventh** [comment]
```sh
$ dpkg -l | grep leveldb
ii  libleveldb-dev:amd64               1.18-5                                     amd64        fast key-value storage library (development files)
ii  libleveldb1v5:amd64                1.18-5                                     amd64        fast key-value storage library

$ pip3.6 freeze | grep plyvel
plyvel==0.9
```

Ubuntu 16.04, ext4 filesystem, using LevelDB. I've removed the data files and started over twice now with the same result. FWIW, if I restart electrumx it appears to recover for a while and processes more blocks until the same error is reported with a different UTXO.

**Comment by kyuupichan** [comment]
The only reports of this happening are with an O/S crash.  I would suspect you have faulty hardware - either bad RAM or a bad disk - or your O/S has bugs.

**Comment by zaventh** [comment]
To my surprise some of my RAM has failed memtest86. Slightly odd as I was not seeing any other issues with several other vms, but I suppose leveldb is less fault tolerant than other processes.
