### ISSUE TITLE
Strange error on ElectrumX stop -> start | ERROR:Controller:Traceback (most recent call last):

### ISSUE THREAD

**Issue by zilveer** [kyuupichan/electrumx#258]
Hi,
I have been running ElectrumX without any issue until I stopped it with the command `systemctl stop electrumx`.
When I start it again with `systemctl start electrumx` I get the following error `ERROR:Controller:Traceback (most recent call last):`, what is causing the issue?

Please help me.

```
blk@9eb9:~/explorer$ sudo systemctl stop electrumx
blk@9eb9:~/explorer$ sudo journalctl -u electrumx -f
-- Logs begin at Mon 2017-09-11 04:26:15 EEST. --
Sep 11 13:17:17 server.ip electrumx_server.py[23136]: server.daemon.DaemonError: [{'code': -5, 'message': 'No information available about transaction'}, {'code': -5, 'message': 'No informa
tion available about transaction'}]
Sep 11 13:17:23 server.ip electrumx_server.py[23136]: INFO:Prefetcher:new block height 1,345,595 hash f964a22cf1719d2eabccfaa7546bce05ca4b99d695192025322b04a0468f0988
Sep 11 13:18:54 server.ip electrumx_server.py[23136]: INFO:Prefetcher:new block height 1,345,596 hash 0daf7f84919fd6f1dbbc1fdc0f156d35e524dd88ae84e3245da1f72f6f19a4c4
Sep 11 13:19:06 server.ip systemd[1]: Stopping Electrumx...
Sep 11 13:19:06 server.ip electrumx_server.py[23136]: WARNING:Controller:received SIGTERM signal, initiating shutdown
Sep 11 13:19:06 server.ip electrumx_server.py[23136]: INFO:Controller:shutting down
Sep 11 13:19:06 server.ip electrumx_server.py[23136]: INFO:Controller:closing down RPC listening servers
Sep 11 13:19:06 server.ip electrumx_server.py[23136]: INFO:Controller:shutdown complete
Sep 11 13:19:06 server.ip electrumx_server.py[23136]: INFO:root:ElectrumX server terminated normally
Sep 11 13:19:06 server.ip systemd[1]: Stopped Electrumx.
^C
blk@9eb9:~/explorer$ sudo systemctl start electrumx
blk@9eb9:~/explorer$ sudo journalctl -u electrumx -f
-- Logs begin at Mon 2017-09-11 04:26:15 EEST. --
Sep 11 13:19:25 server.ip electrumx_server.py[23298]: INFO:BlockProcessor:software version: ElectrumX 1.1
Sep 11 13:19:25 server.ip electrumx_server.py[23298]: INFO:BlockProcessor:DB version: 5
Sep 11 13:19:25 server.ip electrumx_server.py[23298]: INFO:BlockProcessor:coin: Blackcoin
Sep 11 13:19:25 server.ip electrumx_server.py[23298]: INFO:BlockProcessor:network: mainnet
Sep 11 13:19:25 server.ip electrumx_server.py[23298]: INFO:BlockProcessor:height: 1,345,584
Sep 11 13:19:25 server.ip electrumx_server.py[23298]: INFO:BlockProcessor:tip: c44cca4ade1802b8f979407e7d545675c0bf9c20750524be3f6a550ec47a0a10
Sep 11 13:19:25 server.ip electrumx_server.py[23298]: INFO:BlockProcessor:tx count: 2,704,093
Sep 11 13:19:25 server.ip electrumx_server.py[23298]: INFO:BlockProcessor:flush count: 10
Sep 11 13:19:25 server.ip electrumx_server.py[23298]: INFO:BlockProcessor:reorg limit is 5,000 blocks
Sep 11 13:19:25 server.ip electrumx_server.py[23298]: INFO:Controller:RPC server listening on localhost:9999
Sep 11 13:19:25 server.ip electrumx_server.py[23298]: INFO:Prefetcher:catching up to daemon height 1,345,596 (12 blocks behind)
Sep 11 13:19:28 server.ip electrumx_server.py[23298]: INFO:BlockProcessor:chain reorg detected
Sep 11 13:19:28 server.ip electrumx_server.py[23298]: INFO:BlockProcessor:chain was reorganised replacing 1 block at heights 1,345,584-1,345,584
Sep 11 13:19:28 server.ip electrumx_server.py[23298]: ERROR:Controller:Traceback (most recent call last):
Sep 11 13:19:28 server.ip electrumx_server.py[23298]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.1-py3.6.egg/server/controller.py", line 163, in on_future_done
Sep 11 13:19:28 server.ip electrumx_server.py[23298]:     future.result()
Sep 11 13:19:28 server.ip electrumx_server.py[23298]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.1-py3.6.egg/server/block_processor.py", line 206, in main_loop
Sep 11 13:19:28 server.ip electrumx_server.py[23298]:     await task()
Sep 11 13:19:28 server.ip electrumx_server.py[23298]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.1-py3.6.egg/server/block_processor.py", line 257, in check_and_advance_bloc
Sep 11 13:19:28 server.ip electrumx_server.py[23298]:     await self.reorg_chain()
Sep 11 13:19:28 server.ip electrumx_server.py[23298]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.1-py3.6.egg/server/block_processor.py", line 293, in reorg_chain
Sep 11 13:19:28 server.ip electrumx_server.py[23298]:     blocks = await self.daemon.raw_blocks(hex_hashes)
Sep 11 13:19:28 server.ip electrumx_server.py[23298]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.1-py3.6.egg/server/daemon.py", line 309, in raw_blocks
Sep 11 13:19:28 server.ip electrumx_server.py[23298]:     raw_block = await self.make_raw_block(i)
Sep 11 13:19:28 server.ip electrumx_server.py[23298]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.1-py3.6.egg/server/daemon.py", line 334, in make_raw_block
Sep 11 13:19:28 server.ip electrumx_server.py[23298]:     transactions = await self.getrawtransactions(b.get('tx'), False)
Sep 11 13:19:28 server.ip electrumx_server.py[23298]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.1-py3.6.egg/server/daemon.py", line 241, in getrawtransactions
Sep 11 13:19:28 server.ip electrumx_server.py[23298]:     replace_errs=replace_errs)
Sep 11 13:19:28 server.ip electrumx_server.py[23298]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.1-py3.6.egg/server/daemon.py", line 194, in _send_vector
Sep 11 13:19:28 server.ip electrumx_server.py[23298]:     return await self._send(payload, processor)
Sep 11 13:19:28 server.ip electrumx_server.py[23298]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.1-py3.6.egg/server/daemon.py", line 129, in _send
Sep 11 13:19:28 server.ip electrumx_server.py[23298]:     result = processor(result)
Sep 11 13:19:28 server.ip electrumx_server.py[23298]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.1-py3.6.egg/server/daemon.py", line 189, in processor
Sep 11 13:19:28 server.ip electrumx_server.py[23298]:     raise DaemonError(errs)
Sep 11 13:19:28 server.ip electrumx_server.py[23298]: server.daemon.DaemonError: [{'code': -5, 'message': 'No information available about transaction'}, {'code': -5, 'message': 'No information available about transaction'}]
Sep 11 13:20:50 server.ip electrumx_server.py[23298]: INFO:Prefetcher:new block height 1,345,597 hash c0fc96e670604ffe9c13f275271b984eeccbc5978c0ed9982c072cbb73aac4ed
Sep 11 13:21:16 server.ip electrumx_server.py[23298]: INFO:Prefetcher:new block height 1,345,598 hash e16adae6575434b872ec5f892e4f7392236eec3f404dbefc79a920bc1c39eee6
Sep 11 13:21:41 server.ip electrumx_server.py[23298]: INFO:Prefetcher:new block height 1,345,599 hash eb783345bfab98925d6717d9260c9df27af57ea2da366a94e5c791dba7d6e05b
Sep 11 13:22:41 server.ip electrumx_server.py[23298]: INFO:Prefetcher:new block height 1,345,600 hash 15aadd8b3387c164c5a9849d7b2efe79f9ffb332db0f084b60a8d6f691283f4a
Sep 11 13:23:51 server.ip electrumx_server.py[23298]: INFO:Prefetcher:new block height 1,345,601 hash 38f48e74ca82581b220e40fd481c6d69378281cb7d01280e67db8c48ed8d1aab
Sep 11 13:24:41 server.ip electrumx_server.py[23298]: INFO:Prefetcher:new block height 1,345,602 hash 6a13e70b2d7fc97c5e3556fe436f39eaff68059ab583a8d004673d03d63d973c
Sep 11 13:24:51 server.ip electrumx_server.py[23298]: INFO:Prefetcher:new block height 1,345,603 hash 90f0ff2a1b9bce202071aef91cf404f1f479697e6f54d13fa12f16f7ce417516
Sep 11 13:25:22 server.ip electrumx_server.py[23298]: INFO:Prefetcher:new block height 1,345,604 hash 61ac3a6011199a78eb0a60922e95d45d5140fac4dd2ebd20d845fdc5c72f1759
Sep 11 13:26:17 server.ip electrumx_server.py[23298]: INFO:Prefetcher:new block height 1,345,605 hash 6ea42a9894ac6646999084c42cab7521a1098afe608deea0263b625fd47ec3ce
```

**Comment by kyuupichan** [comment]
It looks like reorgs might not work properly for Blackcoin.  Best to get it to support recent RPC APIs so it doesn't need special cases.  I don't run Blackcoin so cannot fix this.

**Comment by zilveer** [comment]
@kyuupichan thanks for your reply.
When you say  
"Best to get it to support recent RPC APIs "

What is the recent RPC APIs blackcoin needs to implement ?

**Comment by kyuupichan** [comment]
https://github.com/kyuupichan/electrumx/blob/562e1a3ac8fe656be2a9b1cb2ffdb87ec2022e25/server/daemon.py#L296-L300

**Comment by zilveer** [comment]
@kyuupichan thanks for the help.
I checked up the RPC API calls and get_block is there and Blackcoin has also the most recent RPC APIs.

I deleted the legacyRPC var from the coins.py file.
Instead I get the following message now:
Error message:
```
return [hex_to_bytes(block) for block in blocks], line 211 daemon.py
TypeError: fromhex() argument must be str, not dict
```

Log:
```
Sep 12 09:13:17 server.ip systemd[1]: Started Electrumx.
Sep 12 09:13:17 server.ip electrumx_server.py[10260]: INFO:root:ElectrumX server starting
Sep 12 09:13:17 server.ip electrumx_server.py[10260]: INFO:Controller:event loop policy: None
Sep 12 09:13:17 server.ip electrumx_server.py[10260]: INFO:Daemon:daemon #1 at 127.0.0.1:19913/ (current)
Sep 12 09:13:17 server.ip electrumx_server.py[10260]: INFO:BlockProcessor:switching current directory to /db
Sep 12 09:13:17 server.ip electrumx_server.py[10260]: INFO:BlockProcessor:using leveldb for DB backend
Sep 12 09:13:17 server.ip electrumx_server.py[10260]: INFO:BlockProcessor:opened DB for serving
Sep 12 09:13:17 server.ip electrumx_server.py[10260]: INFO:BlockProcessor:software version: ElectrumX 1.1
Sep 12 09:13:17 server.ip electrumx_server.py[10260]: INFO:BlockProcessor:DB version: 5
Sep 12 09:13:17 server.ip electrumx_server.py[10260]: INFO:BlockProcessor:coin: Blackcoin
Sep 12 09:13:17 server.ip electrumx_server.py[10260]: INFO:BlockProcessor:network: mainnet
Sep 12 09:13:17 server.ip electrumx_server.py[10260]: INFO:BlockProcessor:height: 1,345,584
Sep 12 09:13:17 server.ip electrumx_server.py[10260]: INFO:BlockProcessor:tip: c44cca4ade1802b8f979407e7d545675c0bf9c20750524be3f6a550ec47a0a10
Sep 12 09:13:17 server.ip electrumx_server.py[10260]: INFO:BlockProcessor:tx count: 2,704,093
Sep 12 09:13:17 server.ip electrumx_server.py[10260]: INFO:BlockProcessor:flush count: 10
Sep 12 09:13:17 server.ip electrumx_server.py[10260]: INFO:BlockProcessor:reorg limit is 5,000 blocks
Sep 12 09:13:17 server.ip electrumx_server.py[10260]: INFO:Controller:RPC server listening on localhost:9999
Sep 12 09:13:17 server.ip electrumx_server.py[10260]: INFO:Prefetcher:catching up to daemon height 1,346,672 (1,088 blocks behind)
Sep 12 09:13:17 server.ip electrumx_server.py[10260]: ERROR:Controller:Traceback (most recent call last):
Sep 12 09:13:17 server.ip electrumx_server.py[10260]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.1-py3.6.egg/server/controller.py", line 163, in on_future_done
Sep 12 09:13:17 server.ip electrumx_server.py[10260]:     future.result()
Sep 12 09:13:17 server.ip electrumx_server.py[10260]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.1-py3.6.egg/server/block_processor.py", line 50, in main_loop
Sep 12 09:13:17 server.ip electrumx_server.py[10260]:     if not await self._prefetch_blocks():
Sep 12 09:13:17 server.ip electrumx_server.py[10260]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.1-py3.6.egg/server/block_processor.py", line 107, in _prefetch_blocks
Sep 12 09:13:17 server.ip electrumx_server.py[10260]:     blocks = await daemon.raw_blocks(hex_hashes)
Sep 12 09:13:17 server.ip electrumx_server.py[10260]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.1-py3.6.egg/server/daemon.py", line 211, in raw_blocks
Sep 12 09:13:17 server.ip electrumx_server.py[10260]:     return [hex_to_bytes(block) for block in blocks]
Sep 12 09:13:17 server.ip electrumx_server.py[10260]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.1-py3.6.egg/server/daemon.py", line 211, in <listcomp>
Sep 12 09:13:17 server.ip electrumx_server.py[10260]:     return [hex_to_bytes(block) for block in blocks]
Sep 12 09:13:17 server.ip electrumx_server.py[10260]: TypeError: fromhex() argument must be str, not dict
```

What could be the issue be now?

**Comment by kyuupichan** [comment]
I believe that is the problem - the daemon doesn't return raw blocks, it returns an annotated decomposed block.

**Comment by zilveer** [comment]
@kyuupichan
Hmm.ok.
How can we solve this then ?

I really appreciate your help.

**Comment by zilveer** [comment]
isnt it possible to getblocks through "decomposed block" ?

**Comment by anoxxxy** [comment]
@zilveer 
Have a look here of how I solved it for Bitbay:
[https://github.com/anoxxxy/BitBay/blob/master/src/rpcblockchain.cpp#L231](https://github.com/anoxxxy/BitBay/blob/master/src/rpcblockchain.cpp#L231)

**Comment by erasmospunk** [comment]
@zilveer @kyuupichan for blackcoin we use `LegacyRPCDaemon` that takes the decomposed block and creates a fake/simulated raw block so it can be processed by the rest of the code.

The problem you are facing is due to the blackcoin daemon not returning the coinbase transaction from an orphaned block (because it is not correctly indexed due to a bug). In issue #315 I wrote about a potential solution.

If you want to make blackcoin work right now you have to rebuild it with the following patch. Keep in mind that it doesn't have great performance.

```
diff --git a/src/main.cpp b/src/main.cpp
index dbb54d5e..f02382ba 100644
--- a/src/main.cpp
+++ b/src/main.cpp
@@ -860,6 +860,24 @@ bool GetTransaction(const uint256 &hash, CTransaction &tx, uint256 &hashBlock)
                 hashBlock = block.GetHash();
             return true;
         }
+        // look for transaction in disconnected blocks to find orphaned CoinBase and CoinStake transactions
+        BOOST_FOREACH(PAIRTYPE(const uint256, CBlockIndex*)& item, mapBlockIndex)
+        {
+            CBlockIndex* pindex = item.second;
+            if (pindex == pindexBest || pindex->pnext != 0)
+                continue;
+            CBlock block;
+            if (!block.ReadFromDisk(pindex))
+                continue;
+            BOOST_FOREACH(const CTransaction& txOrphan, block.vtx)
+            {
+                if (txOrphan.GetHash() == hash)
+                {
+                    tx = txOrphan;
+                    return true;
+                }
+            }
+        }
     }
     return false;
 }
```
