### ISSUE TITLE
lib.coins.CoinError: unknown coin BitcoinSegwit and network mainnet combination

### ISSUE THREAD

**Issue by nathaniel-mahieu** [kyuupichan/electrumx#264]
Cloned 1.1 and can't get past this error. lib/coins.py appears to have an entry which would correspond to the combination of COIN=BitcoinSegwit and NET=mainnet.  These are set in /etc/electrumx.conf.

```
Sep 16 19:07:00 ubuntu electrumx_server.py[29695]: INFO:root:ElectrumX server starting
Sep 16 19:07:00 ubuntu electrumx_server.py[29695]: Traceback (most recent call last):
Sep 16 19:07:00 ubuntu electrumx_server.py[29695]:   File "/home/electrum/electrumx/electrumx_server.py", line 24, in main
Sep 16 19:07:00 ubuntu electrumx_server.py[29695]:     controller = Controller(Env())
Sep 16 19:07:00 ubuntu electrumx_server.py[29695]:   File "/home/electrum/electrumx/server/env.py", line 36, in __init__
Sep 16 19:07:00 ubuntu electrumx_server.py[29695]:     self.coin = Coin.lookup_coin_class(coin_name, network)
Sep 16 19:07:00 ubuntu electrumx_server.py[29695]:   File "/home/electrum/electrumx/lib/coins.py", line 99, in lookup_coin_class
Sep 16 19:07:00 ubuntu electrumx_server.py[29695]:     .format(name, net))
Sep 16 19:07:00 ubuntu electrumx_server.py[29695]: lib.coins.CoinError: unknown coin BitcoinSegwit  # lib/coins.py and network mainnet  # lib/coins.py combination
Sep 16 19:07:00 ubuntu electrumx_server.py[29695]: CRITICAL:root:ElectrumX server terminated abnormally

```

**Comment by nathaniel-mahieu** [comment]
Just figured it out - the comments on that line were being included (as seen in the output, I just didn't catch it.)  Those being there by default is confusing, the comment implies they wont be included.  Might consider removing them.

**Comment by lichtamberg** [comment]
Hm I have the same, but I get following error and dont have any comments?

> lib.coins.CoinError: unknown coin BitcoinSegwit and network mainnet combination

**Comment by lichtamberg** [comment]
Found the issue, I just had an old version of electrum installed and linked, afterwards it worked fine.
