### ISSUE TITLE
VIA: list index out of range

### ISSUE THREAD

**Issue by cipig** [kyuupichan/electrumx#272]
Syncing Viacoin gives me this error
```
ERROR:Controller:Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/electrumx-1.1-py3.5.egg/server/controller.py", line 166, in on_future_done
    future.result()
  File "uvloop/future.pyx", line 146, in uvloop.loop.BaseFuture.result (uvloop/loop.c:109407)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108946)
  File "uvloop/future.pyx", line 374, in uvloop.loop.BaseTask._fast_step (uvloop/loop.c:112750)
  File "/usr/local/lib/python3.5/dist-packages/electrumx-1.1-py3.5.egg/server/block_processor.py", line 206, in main_loop
    await task()
  File "/usr/local/lib/python3.5/dist-packages/electrumx-1.1-py3.5.egg/server/block_processor.py", line 250, in check_and_advance_blocks
    await self.controller.run_in_executor(self.advance_blocks, blocks)
  File "/usr/local/lib/python3.5/dist-packages/electrumx-1.1-py3.5.egg/server/controller.py", line 146, in run_in_executor
    return await self.loop.run_in_executor(None, func, *args)
  File "uvloop/future.pyx", line 241, in __await__ (uvloop/loop.c:110832)
  File "uvloop/future.pyx", line 432, in uvloop.loop.BaseTask._fast_wakeup (uvloop/loop.c:114026)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108946)
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/electrumx-1.1-py3.5.egg/server/block_processor.py", line 500, in advance_blocks
    undo_info = self.advance_txs(block.transactions)
  File "/usr/local/lib/python3.5/dist-packages/electrumx-1.1-py3.5.egg/server/block_processor.py", line 540, in advance_txs
    if not tx.is_coinbase:
  File "/usr/local/lib/python3.5/dist-packages/electrumx-1.1-py3.5.egg/lib/util.py", line 76, in __get__
    value = self.f(obj)
  File "/usr/local/lib/python3.5/dist-packages/electrumx-1.1-py3.5.egg/lib/tx.py", line 44, in is_coinbase
    return self.inputs[0].is_coinbase
IndexError: list index out of range

```
I tried it couple of times (also without uvloop) and it seems to always happen at a specific block. The last working output from electrumx was this

`INFO:BlockProcessor:our height: 3,944,426 daemon: 4,150,741 UTXOs 17MB hist 133MB`

**Comment by kyuupichan** [comment]
You might try setting DESERIALIZER = DeserializerSegWit in the Viacoin definition in lib/coins.py.

If that doesn't fix it and no one steps up to fix this then I will remove this coin as it cannot sync.

**Comment by cipig** [comment]
Unfortunately that didn't help. I forgot about the exact error message, but it was showing up at startup.

**Comment by kyuupichan** [comment]
Can you give me the error message that you had with DESERIALIZER = DeserializerSegWit?

**Comment by cipig** [comment]
Here it is:

```
ERROR:Controller:Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/electrumx-1.2-py3.5.egg/server/controller.py", line 178, in on_future_done
    future.result()
  File "uvloop/future.pyx", line 146, in uvloop.loop.BaseFuture.result (uvloop/loop.c:109407)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108946)
  File "uvloop/future.pyx", line 372, in uvloop.loop.BaseTask._fast_step (uvloop/loop.c:112715)
  File "/usr/local/lib/python3.5/dist-packages/electrumx-1.2-py3.5.egg/server/block_processor.py", line 50, in main_loop
    if not await self._prefetch_blocks():
  File "/usr/local/lib/python3.5/dist-packages/electrumx-1.2-py3.5.egg/server/block_processor.py", line 113, in _prefetch_blocks
    blocks[0] = self.bp.coin.genesis_block(blocks[0])
  File "/usr/local/lib/python3.5/dist-packages/electrumx-1.2-py3.5.egg/lib/coins.py", line 125, in genesis_block
    header = cls.block_header(block, 0)
  File "/usr/local/lib/python3.5/dist-packages/electrumx-1.2-py3.5.egg/lib/coins.py", line 319, in block_header
    return deserializer.read_header(height, cls.BASIC_HEADER_SIZE)
AttributeError: 'DeserializerSegWit' object has no attribute 'read_header'
```

**Comment by kyuupichan** [comment]
Can you please try with git HEAD?  You'll need to rebuild your DB by syncing from scratch, or you could git rebase out the DB version change for a quicker test.

https://github.com/kyuupichan/electrumx/commit/5c7bf3cce9ba5735f413517a27d845e2459d531e

**Comment by kyuupichan** [comment]
Oh and it now requires 3.6, unfortunately for you it seems.  You can rebase that out too as no code requires it yet...

**Comment by kyuupichan** [comment]
Any luck with this?

**Comment by cipig** [comment]
Sorry for the delay, was pretty busy the last week. I installed python 3.6, managed to sync VIA and it looks good, basic calls like listunspent are showing correct values. I think this issue can be closed.

**Comment by kyuupichan** [comment]
Thanks for confirming!
