### ISSUE TITLE
Error when calling server.features

### ISSUE THREAD

**Issue by cipig** [kyuupichan/electrumx#302]
I am getting this error when calling server.features
```
ERROR:ElectrumX:[36] Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2-py3.6.egg/lib/jsonrpc.py", line 528, in process_single_request
    result = await self.handle_payload(payload, self.request_handler)
  File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2-py3.6.egg/lib/jsonrpc.py", line 610, in handle_payload
    return handler(**kw_args)
  File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2-py3.6.egg/server/session.py", line 248, in server_features
    return self.controller.peer_mgr.my_clearnet_peer().features
AttributeError: 'NoneType' object has no attribute 'features'
```

**Comment by kyuupichan** [comment]
What is your config?  Do you have a clearnet address?

**Comment by cipig** [comment]
```
COIN = DigiByte
DB_DIRECTORY = /home/xxx/electrumdb/DGB
DAEMON_URL = http://xxx:xxx@127.0.0.1:14022/
RPC_HOST = 127.0.0.1
RPC_PORT = 8022
HOST = 127.0.0.1,173.212.xxx.xxx
TCP_PORT = 50022
EVENT_LOOP_POLICY = uvloop
PEER_DISCOVERY = self
```

**Comment by benma** [comment]
Got the same issue. Setting `REPORT_HOST=127.0.0.1` results in `"127.0.0.1" is not a valid REPORT_HOST`.

**Comment by kyuupichan** [comment]
REPORT_HOST is how you advertise to the outside world, so yes a local-only address is not valid.

**Comment by benma** [comment]
So how to fix the original issue?

**Comment by ttytyper** [comment]
I get practically the same error message:
```
ERROR:ElectrumX:[186] Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2-py3.6.egg/lib/jsonrpc.py", line 530, in process_single_request
    result = await self.handle_payload(payload, self.request_handler)
  File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2-py3.6.egg/lib/jsonrpc.py", line 612, in handle_payload
    return handler(**kw_args)
  File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2-py3.6.egg/server/session.py", line 248, in server_features
    return self.controller.peer_mgr.my_clearnet_peer().features
AttributeError: 'NoneType' object has no attribute 'features'
```
Config:
```
DB_DIRECTORY = /var/lib/bitcoin/electrumx
DAEMON_URL = http://xxx:xxx@localhost:8332/
COIN = BitcoinSegwit
HOST =
REPORT_HOST_TOR = xxx.onion
TCP_PORT = 50001
DB_CACHE=1800
DONATION_ADDRESS = 1xxx
BANNER_FILE = banner.txt
```
This is on a Debian stretch system, with python3.6 installed from sid. I wonder if the error happens because the machine does not have IPv4 connectivity, only IPv6? Tor is installed and working (ElectrumX successfully verified some onion peers. Incoming requests to the hidden ElectrumX service are also successful).

**Comment by kyuupichan** [comment]
Confirmed as a bug.
