### ISSUE TITLE
ImportError: No module named 'aiohttp'

### ISSUE THREAD

**Issue by griswaalt** [kyuupichan/electrumx#308]
So I am trying to run electrumx on a RPi3. After managing to set up a new install of Raspbian Stretch, along with bitcoind, Python3.6, Electrumx and its dependencies, I am getting the following error when I run the electrumx server - 

`Traceback (most recent call last):
  File "/home/pi/src/electrumx_1.2/electrumx_server.py", line 15, in <module>
    from server.env import Env
  File "/home/pi/src/electrumx_1.2/server/env.py", line 15, in <module>
    from lib.coins import Coin
  File "/home/pi/src/electrumx_1.2/lib/coins.py", line 43, in <module>
    from server.block_processor import BlockProcessor
  File "/home/pi/src/electrumx_1.2/server/block_processor.py", line 19, in <module>
    from server.daemon import DaemonError
  File "/home/pi/src/electrumx_1.2/server/daemon.py", line 19, in <module>
    import aiohttp
ImportError: No module named 'aiohttp'`

However, I see that aiohttp is already available as I get a requirement already satisfied message when I try to install it again with `python3.6 -m pip install aiohttp`

I am guessing that there is some missing link due to which electrumx isn't able to find aiohttp. Any ideas how to fix this?

**Comment by griswaalt** [comment]
So looks like I should have installed Python3.6 using `sudo make install` instead of using `sudo make altinstall`
