### ISSUE TITLE
AssertionError while syncing with Florincoin 

### ISSUE THREAD

**Issue by vivekteega** [kyuupichan/electrumx#334]
I've been trying to setup an ElectrumX server for Florincoin. [Florincoin](https://github.com/florincoin/florincoin) is a clone of Litecoin with one extra feature : it has an optional transaction comment feature. ElectrumX gives an AssertionError when run with Florincoin though. Could you help me regarding the same 

Here is my coins.py class
```
class Florincoin(Coin):
    NAME = "Florincoin"
    SHORTNAME = "FLO"
    NET = "mainnet"
    XPUB_VERBYTES = bytes.fromhex("0488b21e")
    XPRV_VERBYTES = bytes.fromhex("0488ade4")
    P2PKH_VERBYTE = bytes.fromhex("23")
    P2SH_VERBYTES = [bytes.fromhex("08")]
    WIF_BYTE = bytes.fromhex("b0")
    GENESIS_HASH = ('09c7781c9df90708e278c35d38ea5c9041d7ecfcdd1c56ba67274b7cff3e1cea')
    DESERIALIZER = lib_tx.DeserializerSegWit
    TX_COUNT = 8908766
    TX_COUNT_HEIGHT = 1105256
    TX_PER_BLOCK = 10
    RPC_PORT = 7313
    REORG_LIMIT = 800
    PEERS = [
    ]
```

And here are the logs 
```
Dec 17 18:45:22 Teega systemd[1]: Started Electrumx.
Dec 17 18:45:22 Teega electrumx_server.py[11111]: INFO:root:ElectrumX server starting
Dec 17 18:45:22 Teega electrumx_server.py[11111]: INFO:Controller:event loop policy: None
Dec 17 18:45:22 Teega electrumx_server.py[11111]: INFO:Daemon:daemon #1 at localhost:7313/ (current)
Dec 17 18:45:22 Teega electrumx_server.py[11111]: INFO:BlockProcessor:switching current directory to /home/vivek/.electrumx/
Dec 17 18:45:22 Teega electrumx_server.py[11111]: INFO:BlockProcessor:using leveldb for DB backend
Dec 17 18:45:22 Teega electrumx_server.py[11111]: INFO:BlockProcessor:created new database
Dec 17 18:45:22 Teega electrumx_server.py[11111]: INFO:BlockProcessor:creating metadata directory
Dec 17 18:45:22 Teega electrumx_server.py[11111]: INFO:BlockProcessor:software version: ElectrumX 1.2.1
Dec 17 18:45:22 Teega electrumx_server.py[11111]: INFO:BlockProcessor:DB version: 6
Dec 17 18:45:22 Teega electrumx_server.py[11111]: INFO:BlockProcessor:coin: Florincoin
Dec 17 18:45:22 Teega electrumx_server.py[11111]: INFO:BlockProcessor:network: mainnet
Dec 17 18:45:22 Teega electrumx_server.py[11111]: INFO:BlockProcessor:height: -1
Dec 17 18:45:22 Teega electrumx_server.py[11111]: INFO:BlockProcessor:tip: 0000000000000000000000000000000000000000000000000000000000000000
Dec 17 18:45:22 Teega electrumx_server.py[11111]: INFO:BlockProcessor:tx count: 0
Dec 17 18:45:22 Teega electrumx_server.py[11111]: INFO:BlockProcessor:flush count: 0
Dec 17 18:45:22 Teega electrumx_server.py[11111]: INFO:BlockProcessor:sync time so far: 00s
Dec 17 18:45:22 Teega electrumx_server.py[11111]: INFO:BlockProcessor:reorg limit is 800 blocks
Dec 17 18:45:22 Teega electrumx_server.py[11111]: INFO:BlockProcessor:flushing DB cache at 1,800 MB
Dec 17 18:45:22 Teega electrumx_server.py[11111]: INFO:Controller:RPC server listening on localhost:8000
Dec 17 18:45:22 Teega electrumx_server.py[11111]: INFO:Prefetcher:catching up to daemon height 2,493,179 (2,493,180 blocks behind)
Dec 17 18:45:22 Teega electrumx_server.py[11111]: INFO:Prefetcher:verified genesis block with hash 09c7781c9df90708e278c35d38ea5c9041d7ecfcdd1c56ba67274b7cff3e1cea
Dec 17 18:45:22 Teega electrumx_server.py[11111]: INFO:BlockProcessor:our height: 9 daemon: 2,493,179 UTXOs 0MB hist 0MB
Dec 17 18:45:23 Teega electrumx_server.py[11111]: ERROR:Controller:Traceback (most recent call last):
Dec 17 18:45:23 Teega electrumx_server.py[11111]:   File "/home/vivek/source/electrumx/server/controller.py", line 177, in on_future_done
Dec 17 18:45:23 Teega electrumx_server.py[11111]:     future.result()
Dec 17 18:45:23 Teega electrumx_server.py[11111]:   File "/home/vivek/source/electrumx/server/block_processor.py", line 206, in main_loop
Dec 17 18:45:23 Teega electrumx_server.py[11111]:     await task()
Dec 17 18:45:23 Teega electrumx_server.py[11111]:   File "/home/vivek/source/electrumx/server/block_processor.py", line 243, in check_and_advance_blocks
Dec 17 18:45:23 Teega electrumx_server.py[11111]:     for n, raw_block in enumerate(raw_blocks)]
Dec 17 18:45:23 Teega electrumx_server.py[11111]:   File "/home/vivek/source/electrumx/server/block_processor.py", line 243, in <listcomp>
Dec 17 18:45:23 Teega electrumx_server.py[11111]:     for n, raw_block in enumerate(raw_blocks)]
Dec 17 18:45:23 Teega electrumx_server.py[11111]:   File "/home/vivek/source/electrumx/lib/coins.py", line 272, in block
Dec 17 18:45:23 Teega electrumx_server.py[11111]:     txs = cls.DESERIALIZER(raw_block, start=len(header)).read_tx_block()
Dec 17 18:45:23 Teega electrumx_server.py[11111]:   File "/home/vivek/source/electrumx/lib/tx.py", line 103, in read_tx_block
Dec 17 18:45:23 Teega electrumx_server.py[11111]:     txs = [read_tx() for _ in range(self._read_varint())]
Dec 17 18:45:23 Teega electrumx_server.py[11111]:   File "/home/vivek/source/electrumx/lib/tx.py", line 103, in <listcomp>
Dec 17 18:45:23 Teega electrumx_server.py[11111]:     txs = [read_tx() for _ in range(self._read_varint())]
Dec 17 18:45:23 Teega electrumx_server.py[11111]:   File "/home/vivek/source/electrumx/lib/tx.py", line 220, in read_tx
Dec 17 18:45:23 Teega electrumx_server.py[11111]:     inputs = self._read_inputs()
Dec 17 18:45:23 Teega electrumx_server.py[11111]:   File "/home/vivek/source/electrumx/lib/tx.py", line 109, in _read_inputs
Dec 17 18:45:23 Teega electrumx_server.py[11111]:     return [read_input() for i in range(self._read_varint())]
Dec 17 18:45:23 Teega electrumx_server.py[11111]:   File "/home/vivek/source/electrumx/lib/tx.py", line 109, in <listcomp>
Dec 17 18:45:23 Teega electrumx_server.py[11111]:     return [read_input() for i in range(self._read_varint())]
Dec 17 18:45:23 Teega electrumx_server.py[11111]:   File "/home/vivek/source/electrumx/lib/tx.py", line 113, in _read_input
Dec 17 18:45:23 Teega electrumx_server.py[11111]:     self._read_nbytes(32),   # prev_hash
Dec 17 18:45:23 Teega electrumx_server.py[11111]:   File "/home/vivek/source/electrumx/lib/tx.py", line 137, in _read_nbytes
Dec 17 18:45:23 Teega electrumx_server.py[11111]:     assert self.binary_length >= end
Dec 17 18:45:23 Teega electrumx_server.py[11111]: AssertionError
```

**Comment by kyuupichan** [comment]
Does this work now?  If not you need to take it up with whoever added FlorinCoin support initially.

**Comment by erasmospunk** [comment]
@vivekteega you need to create a `DESERIALIZER` that correctly parses the transaction, I see that FlorinCoin has an extra field `strTxComment` that you need to parse/skip. Look in `lib/tx.py` for how to implement your own deserializer.

@vivekteega, @kyuupichan this is not an issue with ElectrumX, so I suggest closing this issue to avoid clutter
