### ISSUE TITLE
ElectrumX server error

### ISSUE THREAD

**Issue by fact0real** [kyuupichan/electrumx#355]
hi all,
when I want to start Electrumx server I got this error:
```
root@ASIS:~# journalctl -u electrumx -f
-- Logs begin at Sat 2018-01-27 11:45:22 +0330. --
Jan 27 17:21:36 ASIS systemd[1]: Started Electrumx.
Jan 27 17:21:37 ASIS electrumx_server.py[20739]: INFO:root:ElectrumX server starting
Jan 27 17:21:37 ASIS electrumx_server.py[20739]: Traceback (most recent call last):
Jan 27 17:21:37 ASIS electrumx_server.py[20739]: File "/opt/python/lib/python3.6/site-packages/electrumx-1.2.1-py3.6.egg/EGG-INFO/scripts/electrumx_server.py", line 24, in main
Jan 27 17:21:37 ASIS electrumx_server.py[20739]: File "/opt/python/lib/python3.6/site-packages/electrumx-1.2.1-py3.6.egg/server/env.py", line 36, in __init__
Jan 27 17:21:37 ASIS electrumx_server.py[20739]: coin_name = self.required('COIN').strip()
Jan 27 17:21:37 ASIS electrumx_server.py[20739]: File "/opt/python/lib/python3.6/site-packages/electrumx-1.2.1-py3.6.egg/lib/env_base.py", line 39, in required
Jan 27 17:21:37 ASIS electrumx_server.py[20739]: raise self.Error('required envvar {} not set'.format(envvar))
Jan 27 17:21:37 ASIS electrumx_server.py[20739]: lib.env_base.EnvBase.Error: required envvar COIN not set
Jan 27 17:21:37 ASIS electrumx_server.py[20739]: CRITICAL:root:ElectrumX server terminated abnormally
```

What's the problem? Please note that I have installed the Electrumx with Debian installer.
Thanks

**Comment by fact0real** [comment]
hi all, 
thanks to `tiagotrs` in _#electrum_ IRC, I should set **COIN Environment Variables** in `electrumx.conf`.
