### ISSUE TITLE
Corruption: corrutped compressed block contents

### ISSUE THREAD

**Issue by brocktice** [kyuupichan/electrumx#361]
Not sure if this is a database corruption or a bug.

ERROR:Controller:Traceback (most recent call last): 
  File "/home/brock/elextrumx-ve/lib/python3.6/site-packages/electrumx-1.2.1-py3.6.egg/server/controller.py", line 177, in on_future_done
    future.result()
  File "/home/brock/elextrumx-ve/lib/python3.6/site-packages/electrumx-1.2.1-py3.6.egg/server/block_processor.py", line 206, in main_loop
    await task()
  File "/home/brock/elextrumx-ve/lib/python3.6/site-packages/electrumx-1.2.1-py3.6.egg/server/block_processor.py", line 250, in check_and_advance_blocks
    await self.controller.run_in_executor(self.advance_blocks, blocks)
  File "/home/brock/elextrumx-ve/lib/python3.6/site-packages/electrumx-1.2.1-py3.6.egg/server/controller.py", line 157, in run_in_executor
    return await self.loop.run_in_executor(None, func, *args)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)  
  File "/home/brock/elextrumx-ve/lib/python3.6/site-packages/electrumx-1.2.1-py3.6.egg/server/block_processor.py", line 502, in advance_blocks
    undo_info = self.advance_txs(block.transactions)
  File "/home/brock/elextrumx-ve/lib/python3.6/site-packages/electrumx-1.2.1-py3.6.egg/server/block_processor.py", line 543, in advance_txs
    cache_value = spend_utxo(txin.prev_hash, txin.prev_idx)
  File "/home/brock/elextrumx-ve/lib/python3.6/site-packages/electrumx-1.2.1-py3.6.egg/server/block_processor.py", line 720, in spend_utxo
    utxo_value_packed = self.utxo_db.get(udb_key)
  File "_plyvel.pyx", line 299, in plyvel._plyvel.DB.get (plyvel/_plyvel.cpp:4025)
  File "_plyvel.pyx", line 103, in plyvel._plyvel.db_get (plyvel/_plyvel.cpp:1891)
  File "_plyvel.pyx", line 83, in plyvel._plyvel.raise_for_status (plyvel/_plyvel.cpp:1733)
plyvel._plyvel.CorruptionError: b'Corruption: corrupted compressed block contents'

**Comment by kyuupichan** [comment]
Looks like something corrupted your leveldb.  I don't believe this is an e-x bug as plyvel is supposedly mutli-threaded and I use its API only

**Comment by Redamancyer** [comment]
i have the same log with you ,and i have try many times and sure the database is right, I haven't solved it until now
