### ISSUE TITLE
TypeError: 'str' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by cipig** [kyuupichan/electrumx#371]
It's me again. Sorry to bother you again, but there is a "new" error message in syslog from electrumx:
```
ERROR:ElectrumX:[92] Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2.1-py3.6.egg/lib/jsonrpc.py", line 530, in process_single_request
    result = await self.handle_payload(payload, self.request_handler)
  File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2.1-py3.6.egg/lib/jsonrpc.py", line 610, in handle_payload
    return await handler(**kw_args)
  File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2.1-py3.6.egg/server/controller.py", line 806, in address_listunspent
    return await self.hashX_listunspent(hashX)
  File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2.1-py3.6.egg/server/controller.py", line 800, in hashX_listunspent
    for utxo in utxos
  File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2.1-py3.6.egg/server/controller.py", line 801, in <listcomp>
    if (utxo.tx_hash, utxo.tx_pos) not in spends]
  File "/usr/local/lib/python3.6/dist-packages/electrumx-1.2.1-py3.6.egg/lib/hash.py", line 74, in hash_to_hex_str
    return bytes(reversed(x)).hex()
TypeError: 'str' object cannot be interpreted as an integer
```

**Comment by kyuupichan** [comment]
Thanks; sorry for that.  I thought I tested the original change from Electron Cash (as Apple removed telnet...).  Just reproduced the issue; did a send, and confirmed it now works via telnet.
