### ISSUE TITLE
Deserialization Error for Decred Tx

### ISSUE THREAD

**Issue by cipherzzz** [kyuupichan/electrumx#386]
Hello! I am attempting to add Decred to the list of coins... I added the following:

**Environment**
_Note, I am running the decred testnet_
```
DAEMON_URL="http://<rpcuser>:<rpcpass>@127.0.0.1:19119/"
DB_DIRECTORY="/Users/macuser/.electrumx/"
DB_ENGINE="leveldb"
HOST="0.0.0.0"
COIN="Decred"
NET="testnet"
```

**coins.py**
```
...
class Decred(Coin):
    NAME = "Decred"
    SHORTNAME = "DCR"
    NET = "mainnet"
    TX_COUNT = 217380620
    TX_COUNT_HEIGHT = 464000
    TX_PER_BLOCK = 1800


class DecredTestnet(Decred):
    SHORTNAME = "XDCR"
    NET = "testnet"
    TX_COUNT = 3061451
    TX_COUNT_HEIGHT = 245079
    TX_PER_BLOCK = 1800  
    RPC_PORT = 19119
    GENESIS_HASH = ('1965835dd55cfdb4dcd9957a3675f3d7d97023e5b5564fb31aaa21b773b6f7f7')
...
```

**electrumx**
```
macuser@macusersmacbook:~/Projects/Decred/electrumx (master *)$ python3 ./electrumx_server.py
INFO:root:ElectrumX server starting
WARNING:Env:lowered maximum sessions from 1,000 to 0 because your open file limit is 256
INFO:Controller:event loop policy: None
INFO:Daemon:daemon #1 at 127.0.0.1:19119/ (current)
INFO:BlockProcessor:switching current directory to /Users/macuser/.electrumx/
INFO:BlockProcessor:using leveldb for DB backend
INFO:BlockProcessor:opened DB for serving
INFO:BlockProcessor:closing DB to re-open for sync
INFO:BlockProcessor:opened DB for sync
INFO:BlockProcessor:software version: ElectrumX 1.2.1
INFO:BlockProcessor:DB version: 6
INFO:BlockProcessor:coin: Decred
INFO:BlockProcessor:network: testnet
INFO:BlockProcessor:height: -1
INFO:BlockProcessor:tip: 0000000000000000000000000000000000000000000000000000000000000000
INFO:BlockProcessor:tx count: 0
INFO:BlockProcessor:flush count: 0
INFO:BlockProcessor:sync time so far: 00s
INFO:BlockProcessor:reorg limit is 200 blocks
INFO:BlockProcessor:flushing DB cache at 1,200 MB
INFO:Controller:RPC server listening on localhost:8000
INFO:Prefetcher:catching up to daemon height 245,187 (245,188 blocks behind)
INFO:Prefetcher:verified genesis block with hash 4261602a9d07d80ad47621a64ba6a07754902e496777edc4ff581946bd7bc29c
WARNING:BlockProcessor:daemon blocks do not form a chain; resetting the prefetcher
INFO:Prefetcher:catching up to daemon height 245,187 (245,188 blocks behind)
WARNING:BlockProcessor:ignoring 500 blocks starting height 10, expected 0
WARNING:BlockProcessor:ignoring 500 blocks starting height 510, expected 0
WARNING:BlockProcessor:ignoring 500 blocks starting height 1,010, expected 0
WARNING:BlockProcessor:ignoring 500 blocks starting height 1,510, expected 0
WARNING:BlockProcessor:ignoring 500 blocks starting height 2,010, expected 0
INFO:Prefetcher:verified genesis block with hash 4261602a9d07d80ad47621a64ba6a07754902e496777edc4ff581946bd7bc29c
ERROR:Controller:Traceback (most recent call last):
  File "/Users/macuser/Projects/Decred/electrumx/server/controller.py", line 176, in on_future_done
    future.result()
  File "/Users/macuser/Projects/Decred/electrumx/server/block_processor.py", line 206, in main_loop
    await task()
  File "/Users/macuser/Projects/Decred/electrumx/server/block_processor.py", line 243, in check_and_advance_blocks
    for n, raw_block in enumerate(raw_blocks)]
  File "/Users/macuser/Projects/Decred/electrumx/server/block_processor.py", line 243, in <listcomp>
    for n, raw_block in enumerate(raw_blocks)]
  File "/Users/macuser/Projects/Decred/electrumx/lib/coins.py", line 272, in block
    txs = cls.DESERIALIZER(raw_block, start=len(header)).read_tx_block()
  File "/Users/macuser/Projects/Decred/electrumx/lib/tx.py", line 112, in read_tx_block
    return [read() for _ in range(self._read_varint())]
  File "/Users/macuser/Projects/Decred/electrumx/lib/tx.py", line 112, in <listcomp>
    return [read() for _ in range(self._read_varint())]
  File "/Users/macuser/Projects/Decred/electrumx/lib/tx.py", line 102, in read_tx_and_hash
    return self.read_tx(), double_sha256(self.binary[start:self.cursor])
  File "/Users/macuser/Projects/Decred/electrumx/lib/tx.py", line 90, in read_tx
    self._read_inputs(),    # inputs
  File "/Users/macuser/Projects/Decred/electrumx/lib/tx.py", line 116, in _read_inputs
    return [read_input() for i in range(self._read_varint())]
  File "/Users/macuser/Projects/Decred/electrumx/lib/tx.py", line 116, in <listcomp>
    return [read_input() for i in range(self._read_varint())]
  File "/Users/macuser/Projects/Decred/electrumx/lib/tx.py", line 122, in _read_input
    self._read_varbytes(),   # script
  File "/Users/macuser/Projects/Decred/electrumx/lib/tx.py", line 148, in _read_varbytes
    return self._read_nbytes(self._read_varint())
  File "/Users/macuser/Projects/Decred/electrumx/lib/tx.py", line 144, in _read_nbytes
    assert self.binary_length >= end
AssertionError
```

Decred uses blake for their hashing so I attempted to replace the sha256 with blake2 to no avail... 

**tx.py**
```
def read_tx_and_hash(self):
        '''Return a (deserialized TX, tx_hash) pair.

        The hash needs to be reversed for human display; for efficiency
        we process it in the natural serialized order.
        '''
        start = self.cursor
        return self.read_tx(), double_blake(self.binary[start:self.cursor])
```

Any ideas why i would be getting this?

Thanks!
Mark

**Comment by kyuupichan** [comment]
I suspect you need it for the header hash not tx hash. Look at other examples. This is not a bug in ElectrumX, obviously

**Comment by cipherzzz** [comment]
Thanks for your feedback, you are right - it is not a bug. We have additional fields in our transaction that are not in the btc tx. I guess we will need to write a custom de-serializer...
