### ISSUE TITLE
Crash in 0.7.3

### ISSUE THREAD

**Issue by tunkaflux** [kyuupichan/electrumx#40]
Hello,

After a crash of 0.7.1 yesterday during a reorg, I upgraded to 0.7.3 and restarted electrumx. This resulted in another crash. Full log below:

```
INFO:root:ElectrumX server starting
INFO:BlockServer:switching current directory to /home/bitcoin/electrumx_db
INFO:BlockServer:successfully opened leveldb database Bitcoin-mainnet
INFO:BlockServer:software version: ElectrumX 0.7.3
INFO:BlockServer:DB version: 3
INFO:BlockServer:coin: Bitcoin
INFO:BlockServer:network: mainnet
INFO:BlockServer:height: 439,973
INFO:BlockServer:tip: 0000000000000000023dc99537a9f3e565a06256ca29a85cb82c028633249f8f
INFO:BlockServer:tx count: 172,573,500
INFO:Daemon:daemon at 162.210.198.184:8332/
INFO:BlockServer:reorg limit is 200 blocks
INFO:BlockServer:deleting 119 stale undo entries
INFO:ServerManager:max subscriptions across all sessions: 250,000
INFO:ServerManager:max subscriptions per session: 50,000
INFO:Prefetcher:catching up to daemon height 440,085...
INFO:BlockServer:chain reorg detected
INFO:BlockServer:finding common height...
INFO:BlockServer:chain was reorganised for 1 blocks from height 439,973 to height 439,973
INFO:BlockServer:backing up 1 blocks
INFO:BlockServer:backed up to height 439,972
INFO:BlockServer:backing up history to height 439,972  tx_count 172,571,879
INFO:BlockServer:removed 13,636 history entries from 12,664 addresses
INFO:BlockServer:flush #713 took 109.6s.  Height 439,972 txs: 172,571,879
INFO:BlockServer:backed up to height 439,972
ERROR:Daemon:disconnected.  Retrying between sleeps...
INFO:Daemon:connection restored
INFO:BlockServer:prefetcher reset
INFO:BlockServer:our height: 439,972 daemon: 440,085 UTXOs 0MB hist -1MB
ERROR:Daemon:HTTP error.  Retrying between sleeps...
INFO:BlockServer:our height: 439,982 daemon: 440,085 UTXOs 13MB hist 15MB
INFO:Daemon:connection restored
ERROR:Daemon:HTTP error.  Retrying between sleeps...
INFO:BlockServer:our height: 439,994 daemon: 440,086 UTXOs 26MB hist 32MB
INFO:Daemon:connection restored
ERROR:Daemon:HTTP error.  Retrying between sleeps...
INFO:BlockServer:our height: 440,005 daemon: 440,087 UTXOs 36MB hist 46MB
INFO:Daemon:connection restored
INFO:BlockServer:our height: 440,016 daemon: 440,087 UTXOs 47MB hist 60MB
INFO:BlockServer:our height: 440,026 daemon: 440,087 UTXOs 55MB hist 72MB
INFO:BlockServer:our height: 440,036 daemon: 440,087 UTXOs 66MB hist 86MB
ERROR:Daemon:HTTP error.  Retrying between sleeps...
INFO:BlockServer:our height: 440,047 daemon: 440,087 UTXOs 74MB hist 98MB
INFO:Daemon:connection restored
INFO:BlockServer:our height: 440,057 daemon: 440,087 UTXOs 82MB hist 108MB
INFO:BlockServer:our height: 440,068 daemon: 440,087 UTXOs 92MB hist 118MB
INFO:BlockServer:our height: 440,079 daemon: 440,087 UTXOs 99MB hist 131MB
INFO:BlockServer:our height: 440,087 daemon: 440,087 UTXOs 106MB hist 140MB
ERROR:Daemon:HTTP error.  Retrying between sleeps...
INFO:Daemon:connection restored
Traceback (most recent call last):
  File "/home/bitcoin/electrumx/electrumx_server.py", line 67, in main
    main_loop()
  File "/home/bitcoin/electrumx/electrumx_server.py", line 58, in main_loop
    loop.run_until_complete(future)
  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/bitcoin/electrumx/server/block_processor.py", line 195, in main_loop
    await self._wait_for_update()
  File "/home/bitcoin/electrumx/server/block_processor.py", line 219, in _wait_for_update
    await self.first_caught_up()
  File "/home/bitcoin/electrumx/server/protocol.py", line 44, in first_caught_up
    await super().first_caught_up()
  File "/home/bitcoin/electrumx/server/block_processor.py", line 250, in first_caught_up
    self.flush(True)
  File "/home/bitcoin/electrumx/server/block_processor.py", line 391, in flush
    flush_history(batch)
  File "/home/bitcoin/electrumx/server/block_processor.py", line 430, in flush_history
    self.fs_flush()
  File "/home/bitcoin/electrumx/server/block_processor.py", line 457, in fs_flush
    assert len(self.tx_counts) == self.height + 1
AssertionError
CRITICAL:root:ElectrumX server terminated abnormally
Exception ignored in: <bound method BaseEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 431, in __del__
  File "/usr/local/lib/python3.5/asyncio/unix_events.py", line 58, in close
  File "/usr/local/lib/python3.5/asyncio/unix_events.py", line 139, in remove_signal_handler
  File "/usr/local/lib/python3.5/signal.py", line 47, in signal
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<Prefetcher.main_loop() running at /home/bitcoin/electrumx/server/block_processor.py:84> wait_for=<Future pending cb=[Task._wakeup()]>>
```

**Comment by tunkaflux** [comment]
Update: Started ElectrumX again and server started without issues now...

**Comment by kyuupichan** [comment]
Yes I've still not got the in-memory state quite right yet when transitioning from backing up to going forwards again.  Your DB is fine.  It'll be an easy fix; I'll try and get it done today.

**Comment by kyuupichan** [comment]
Glad I put these assertions in; without them you would have a corrupted DB...
