### ISSUE TITLE
Controller object has no attribute 'get_chunk'

### ISSUE THREAD

**Issue by spiccioli** [kyuupichan/electrumx#401]
Today I did a git pull to update my electrumx server, now from time to time I get this error:

```
ERROR:ElectrumX:[1399] Traceback (most recent call last):
Mar 06 16:09:40 fedora26.myhost.com electrumx_server.py[26424]:   File "/home/electrumx/electrumx/lib/jsonrpc.py", line 530, in process_single_request
Mar 06 16:09:40 fedora26.myhost.com electrumx_server.py[26424]:     result = await self.handle_payload(payload, self.request_handler)
Mar 06 16:09:40 fedora26.myhost.com electrumx_server.py[26424]:   File "/home/electrumx/electrumx/lib/jsonrpc.py", line 612, in handle_payload
Mar 06 16:09:40 fedora26.myhost.com electrumx_server.py[26424]:     return handler(**kw_args)
Mar 06 16:09:40 fedora26.myhost.com electrumx_server.py[26424]:   File "/home/electrumx/electrumx/server/session.py", line 287, in block_get_chunk
Mar 06 16:09:40 fedora26.myhost.com electrumx_server.py[26424]:     return self.controller.get_chunk(index)
Mar 06 16:09:40 fedora26.myhost.com electrumx_server.py[26424]: AttributeError: 'Controller' object has no attribute 'get_chunk'
```

commit 19e0f9bce27ee24603e46c71265c60f8046537a7 (HEAD -> master, origin/master, origin/HEAD)

**Comment by kyuupichan** [comment]
Was fixed by https://github.com/kyuupichan/electrumx/commit/521227c2b853b05ec6f4f388e06abf8f3bafde4c, thanks

**Comment by spiccioli** [comment]
You're welcome!
