### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by GiorgosK** [kyuupichan/electrumx#408]
> Mar 10 09:52:06 vps503121 electrumx_server.py[22707]: 2018-03-10 09:52:06,891 INFO    ElectrumX server starting                                                                            [electrumx_server.py:24]
> Mar 10 09:52:06 vps503121 electrumx_server.py[22707]: 2018-03-10 09:52:06,892 INFO    event loop policy: None                                                                              [server_base.py:57]
> Mar 10 09:52:06 vps503121 electrumx_server.py[22707]: 2018-03-10 09:52:06,893 INFO    daemon #1 at 127.0.0.1:19913/ (current)                                                              [daemon.py:75]
> Mar 10 09:52:06 vps503121 electrumx_server.py[22707]: 2018-03-10 09:52:06,894 INFO    switching current directory to /db                                                                   [db.py:57]
> Mar 10 09:52:06 vps503121 electrumx_server.py[22707]: 2018-03-10 09:52:06,897 INFO    using leveldb for DB backend                                                                         [db.py:61]
> Mar 10 09:52:06 vps503121 electrumx_server.py[22707]: 2018-03-10 09:52:06,946 INFO    opened DB for serving                                                                                [db.py:103]
> Mar 10 09:52:06 vps503121 electrumx_server.py[22707]: 2018-03-10 09:52:06,947 INFO    closing DB to re-open for sync                                                                       [db.py:103]
> Mar 10 09:52:07 vps503121 electrumx_server.py[22707]: 2018-03-10 09:52:07,018 INFO    opened DB for sync                                                                                   [db.py:103]
> Mar 10 09:52:07 vps503121 electrumx_server.py[22707]: 2018-03-10 09:52:07,020 INFO    software version: ElectrumX 1.3+                                                                     [db.py:133]
> Mar 10 09:52:07 vps503121 electrumx_server.py[22707]: 2018-03-10 09:52:07,020 INFO    supported protocol versions: 0.9-1.2                                                                 [db.py:135]
> Mar 10 09:52:07 vps503121 electrumx_server.py[22707]: 2018-03-10 09:52:07,020 INFO    DB version: 6                                                                                        [db.py:136]
> Mar 10 09:52:07 vps503121 electrumx_server.py[22707]: 2018-03-10 09:52:07,020 INFO    coin: Bitbay                                                                                         [db.py:137]
> Mar 10 09:52:07 vps503121 electrumx_server.py[22707]: 2018-03-10 09:52:07,021 INFO    network: mainnet                                                                                     [db.py:138]
> Mar 10 09:52:07 vps503121 electrumx_server.py[22707]: 2018-03-10 09:52:07,021 INFO    height: -1                                                                                           [db.py:139]
> Mar 10 09:52:07 vps503121 electrumx_server.py[22707]: 2018-03-10 09:52:07,021 INFO    tip: 0000000000000000000000000000000000000000000000000000000000000000                                [db.py:140]
> Mar 10 09:52:07 vps503121 electrumx_server.py[22707]: 2018-03-10 09:52:07,022 INFO    tx count: 0                                                                                          [db.py:141]
> Mar 10 09:52:07 vps503121 electrumx_server.py[22707]: 2018-03-10 09:52:07,022 INFO    flush count: 0                                                                                       [db.py:142]
> Mar 10 09:52:07 vps503121 electrumx_server.py[22707]: 2018-03-10 09:52:07,022 INFO    sync time so far: 00s                                                                                [db.py:145]
> Mar 10 09:52:07 vps503121 electrumx_server.py[22707]: 2018-03-10 09:52:07,023 INFO    reorg limit is 5,000 blocks                                                                          [db.py:71]
> Mar 10 09:52:07 vps503121 electrumx_server.py[22707]: 2018-03-10 09:52:07,023 INFO    flushing DB cache at 1,200 MB                                                                        [block_processor.py:185]
> Mar 10 09:52:07 vps503121 electrumx_server.py[22707]: 2018-03-10 09:52:07,027 INFO    RPC server listening on localhost:9999                                                               [controller.py:241]
> Mar 10 09:52:07 vps503121 electrumx_server.py[22707]: 2018-03-10 09:52:07,035 INFO    catching up to daemon height 1,577,945 (1,577,946 blocks behind)                                     [block_processor.py:76]
> Mar 10 09:52:07 vps503121 electrumx_server.py[22707]: 2018-03-10 09:52:07,062 ERROR   Traceback (most recent call last):
> Mar 10 09:52:07 vps503121 electrumx_server.py[22707]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.3_-py3.6.egg/server/controller.py", line 176, in on_future_done
> Mar 10 09:52:07 vps503121 electrumx_server.py[22707]:     future.result()
> Mar 10 09:52:07 vps503121 electrumx_server.py[22707]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.3_-py3.6.egg/server/block_processor.py", line 50, in main_loop
> Mar 10 09:52:07 vps503121 electrumx_server.py[22707]:     if not await self._prefetch_blocks():
> Mar 10 09:52:07 vps503121 electrumx_server.py[22707]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.3_-py3.6.egg/server/block_processor.py", line 107, in _prefetch_blocks
> Mar 10 09:52:07 vps503121 electrumx_server.py[22707]:     blocks = await daemon.raw_blocks(hex_hashes)
> Mar 10 09:52:07 vps503121 electrumx_server.py[22707]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.3_-py3.6.egg/server/daemon.py", line 343, in raw_blocks
> Mar 10 09:52:07 vps503121 electrumx_server.py[22707]:     raw_block = await self.make_raw_block(i)
> Mar 10 09:52:07 vps503121 electrumx_server.py[22707]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.3_-py3.6.egg/server/daemon.py", line 364, in make_raw_block
> Mar 10 09:52:07 vps503121 electrumx_server.py[22707]:     header = await self.make_raw_header(b)
> Mar 10 09:52:07 vps503121 electrumx_server.py[22707]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.3_-py3.6.egg/server/daemon.py", line 350, in make_raw_header
> Mar 10 09:52:07 vps503121 electrumx_server.py[22707]:     pbh = b.get('previousblockhash')
> Mar 10 09:52:07 vps503121 electrumx_server.py[22707]: AttributeError: 'str' object has no attribute 'get'
> Mar 10 09:52:07 vps503121 electrumx_server.py[22707]:  [util.py:63]

What does this error mean ?
Or how can I go about debugging it ?

**Comment by erasmospunk** [comment]
The problem is that ElectrumX is trying to build a raw block for a legacy daemon and doesn't get the expected JSON reply. It seems that you are running Bitbay and it is defined [here](https://github.com/kyuupichan/electrumx/blob/master/lib/coins.py#L1023) as:
```
class Bitbay(ScryptMixin, Coin):
    NAME = "Bitbay"
    SHORTNAME = "BAY"
    NET = "mainnet"
    P2PKH_VERBYTE = bytes.fromhex("19")
    P2SH_VERBYTES = [bytes.fromhex("55")]
    WIF_BYTE = bytes.fromhex("99")
    GENESIS_HASH = ('0000075685d3be1f253ce777174b1594'
                    '354e79954d2a32a6f77fe9cba00e6467')
    DAEMON = daemon.LegacyRPCDaemon # <------- this could be wrong
    TX_COUNT = 4594999
    TX_COUNT_HEIGHT = 1667070
    TX_PER_BLOCK = 3
    RPC_PORT = 19914
    REORG_LIMIT = 5000
```
Maybe the Bitbay daemon was updated and now supports the compatible `getblock` RPC call. Try calling `getblock <a-block-hash> false` and check if the output is a hex string. If that is the case, then the following line must be removed:
```
DAEMON = daemon.LegacyRPCDaemon
```

**Comment by GiorgosK** [comment]
Thanks @erasmospunk it seems that was the case.

**Comment by kyuupichan** [comment]
@GiorgosK are you going to submit a PR?

**Comment by GiorgosK** [comment]
@kyuupichan yes I will if this is the recommended way of requesting code changes

**Comment by kyuupichan** [comment]
@GiorgosK yes please
