### ISSUE TITLE
Decred mainnet fails to sync.

### ISSUE THREAD

**Issue by dajohi** [kyuupichan/electrumx#414]
```
Mar 15 00:20:29 dcrd-cf-test1.localdomain electrumx_server.py[2409]: INFO:BlockProcessor:our height: 78,009 daemon: 221,072 UTXOs 193MB hist 41MB
Mar 15 00:21:00 dcrd-cf-test1.localdomain electrumx_server.py[2409]: INFO:BlockProcessor:our height: 78,509 daemon: 221,072 UTXOs 195MB hist 42MB
Mar 15 00:21:33 dcrd-cf-test1.localdomain electrumx_server.py[2409]: INFO:BlockProcessor:our height: 79,009 daemon: 221,072 UTXOs 196MB hist 44MB
Mar 15 00:22:04 dcrd-cf-test1.localdomain electrumx_server.py[2409]: INFO:BlockProcessor:our height: 79,509 daemon: 221,072 UTXOs 197MB hist 45MB
Mar 15 00:23:08 dcrd-cf-test1.localdomain electrumx_server.py[2409]: INFO:BlockProcessor:our height: 80,009 daemon: 221,072 UTXOs 199MB hist 48MB
Mar 15 00:23:47 dcrd-cf-test1.localdomain electrumx_server.py[2409]: INFO:BlockProcessor:our height: 80,509 daemon: 221,072 UTXOs 200MB hist 50MB
Mar 15 00:24:15 dcrd-cf-test1.localdomain electrumx_server.py[2409]: ERROR:Controller:Traceback (most recent call last):
Mar 15 00:24:15 dcrd-cf-test1.localdomain electrumx_server.py[2409]:   File "/usr/lib/python3.6/site-packages/electrumx-1.3_-py3.6.egg/server/controller.py", line 176, in on_future_done
Mar 15 00:24:15 dcrd-cf-test1.localdomain electrumx_server.py[2409]:     future.result()
Mar 15 00:24:15 dcrd-cf-test1.localdomain electrumx_server.py[2409]:   File "/usr/lib/python3.6/site-packages/electrumx-1.3_-py3.6.egg/server/block_processor.py", line 206, in main_loop
Mar 15 00:24:15 dcrd-cf-test1.localdomain electrumx_server.py[2409]:     await task()
Mar 15 00:24:15 dcrd-cf-test1.localdomain electrumx_server.py[2409]:   File "/usr/lib/python3.6/site-packages/electrumx-1.3_-py3.6.egg/server/block_processor.py", line 250, in check_and_advance_blocks
Mar 15 00:24:15 dcrd-cf-test1.localdomain electrumx_server.py[2409]:     await self.controller.run_in_executor(self.advance_blocks, blocks)
Mar 15 00:24:15 dcrd-cf-test1.localdomain electrumx_server.py[2409]:   File "/usr/lib/python3.6/site-packages/electrumx-1.3_-py3.6.egg/server/controller.py", line 156, in run_in_executor
Mar 15 00:24:15 dcrd-cf-test1.localdomain electrumx_server.py[2409]:     return await self.loop.run_in_executor(None, func, *args)
Mar 15 00:24:15 dcrd-cf-test1.localdomain electrumx_server.py[2409]:   File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
Mar 15 00:24:15 dcrd-cf-test1.localdomain electrumx_server.py[2409]:     result = self.fn(*self.args, **self.kwargs)
Mar 15 00:24:15 dcrd-cf-test1.localdomain electrumx_server.py[2409]:   File "/usr/lib/python3.6/site-packages/electrumx-1.3_-py3.6.egg/server/block_processor.py", line 502, in advance_blocks
Mar 15 00:24:15 dcrd-cf-test1.localdomain electrumx_server.py[2409]:     undo_info = self.advance_txs(block.transactions)
Mar 15 00:24:15 dcrd-cf-test1.localdomain electrumx_server.py[2409]:   File "/usr/lib/python3.6/site-packages/electrumx-1.3_-py3.6.egg/server/block_processor.py", line 543, in advance_txs
Mar 15 00:24:15 dcrd-cf-test1.localdomain electrumx_server.py[2409]:     cache_value = spend_utxo(txin.prev_hash, txin.prev_idx)
Mar 15 00:24:15 dcrd-cf-test1.localdomain electrumx_server.py[2409]:   File "/usr/lib/python3.6/site-packages/electrumx-1.3_-py3.6.egg/server/block_processor.py", line 728, in spend_utxo
Mar 15 00:24:15 dcrd-cf-test1.localdomain electrumx_server.py[2409]:     .format(hash_to_str(tx_hash), tx_idx))
Mar 15 00:24:15 dcrd-cf-test1.localdomain electrumx_server.py[2409]: server.block_processor.ChainError: UTXO 38c81dd1cff07f3fb4d628b77fc234dd65bc812309ba9ce486ca1a3d852a063d / 2 not found in "h" table
```

**Comment by kyuupichan** [comment]
Indeed, I'll remove it next release if not fixed

**Comment by dajohi** [comment]
I am working on a fix.

**Comment by dajohi** [comment]
@kyuupichan - how do I retrieve the previous block's transactions and "unspend" them?  This is what I have so far:

```diff
diff --git a/server/block_processor.py b/server/block_processor.py
index ea4265e..2f9a5f0 100644
--- a/server/block_processor.py
+++ b/server/block_processor.py
@@ -499,6 +499,23 @@ class BlockProcessor(server.db.DB):
 
         for block in blocks:
             height += 1
+
+            // DECRED START
+
+            // Retrieve VoteBits (ushort) from the block header
+            vbits = unpack("<H", block.header[100:102])
+            votebits = int.from_bytes(vbits, byteorder='little')
+
+            // Check if previous block was invalidated.
+            txtreevalid = bool(votebits & (1<<0) != 0)
+            if txtreevalid == False:
+               // Unspend the previous block's transactions
+                prevblock = self.coin.block(raw_block, height-1)
+                undo_info = self.backup_txs(prevblock.transactions)
+                self.undo_infos.append((invalidateinfo, height))
+
+            // DECRED END
+
             undo_info = self.advance_txs(block.transactions)
             if height >= min_height:
                 self.undo_infos.append((undo_info, height))
```

**Comment by kyuupichan** [comment]
Does the previous block still exist?  Or is it a reorg?

**Comment by dajohi** [comment]
exists

**Comment by dajohi** [comment]
@kyuupichan 
Is the code sample above enough for you to create a diff or is this a much larger project?  I have never attempted Python :|

Just need the chunk for `if txtreevalid == False:` that unspends/invalidates the previous blocks transactions...

**Comment by kyuupichan** [comment]
Well I'm not going to write anything and I have no way to test.  Does this only apply to the previous block?  Can it apply to the block 10 earlier?  Can more than one block at a time be invalidated?

**Comment by dajohi** [comment]
Only to the previous block.

**Comment by kyuupichan** [comment]
OK so the loop in backup_blocks backs up blocks one at a time.  So that's a good place to start.  However as you're not really backing up, just undoing transactions, I think the only line you need is

self.backup_txs(block.transactions)

That should be enough (presumably this is done before processing any transactions in the new block?).

So you need to get the raw block (the "block" variable here), probably from a daemon request - see other code in block_processor.py, and then that line should be enough.

**Comment by dajohi** [comment]
I guess I do not know how to use python.  coroutine is not subscriptable...

```diff
diff --git a/server/block_processor.py b/server/block_processor.py
index ea4265e..2245f9c 100644
--- a/server/block_processor.py
+++ b/server/block_processor.py
@@ -499,6 +499,23 @@ class BlockProcessor(server.db.DB):
 
         for block in blocks:
             height += 1
+
+            if self.coin.NAME == 'Decred' and height != 0:
+                # Retrieve VoteBits (ushort) from the block header
+                vb = unpack("<H", block.header[100:102])
+                votebits = int.from_bytes(vb, byteorder='little')
+
+                # Check if previous block was invalidated.
+                validtxtree = bool(votebits & (1<<0) != 0)
+                if not validtxtree:
+                    self.logger.info('block {:,d} invalidates previous block'.format(height))
+                    prevhash = self.coin.header_prevhash(block.header)
+                    prevblock = self.daemon.deserialised_block(prevhash)
+                    self.logger.info('{}'.format(prevblock))
+                    self.backup_txs(prevblock['tx'])
+
             undo_info = self.advance_txs(block.transactions)
             if height >= min_height:
                 self.undo_infos.append((undo_info, height))
```

**Comment by kyuupichan** [comment]
You're missing an await. But that will give you a syntax error when you add it because that function is not a coroutine itself... I think it's not going to be quite as simple as you might have thought. 

The current code is based on the assumption everything it needs is available without waiting

**Comment by erasmospunk** [comment]
@dajohi check my [original code](https://github.com/erasmospunk/electrumx) that passes the problematic points by using a hack (cannot be merged here though). Please feel free to make any PR there.

The biggest challenge is to handle reorgs i.e. when the `validtxtree == false` block is replaced by a `validtxtree == true`, the previously removed transactions must be added again.

**Comment by dajohi** [comment]
Got
```
Mar 19 18:57:40 dcrd-cf-test1.localdomain electrumx_server.py[21342]: TypeError: Object of type 'bytes' is not JSON serializable
```
with
```python
            if self.coin.NAME == 'Decred' and height != 0:
                def decred_loop(loop):
                    asyncio.set_event_loop(loop)
                    loop.run_forever()

                # Retrieve VoteBits (ushort) from the block header
                vb = unpack("<H", block.header[100:102])
                votebits = int.from_bytes(vb, byteorder='little')

                # Check if previous block was invalidated.
                validtxtree = bool(votebits & (1<<0) != 0)
                if not validtxtree:
                    self.logger.info('block {:,d} invalidates previous block'.format(height))
                    prevhash = self.coin.header_prevhash(block.header)
                    newloop = asyncio.new_event_loop()
                    Thread(target=decred_loop, args=(newloop,)).start()
                    prevblock = asyncio.run_coroutine_threadsafe(self.daemon.deserialised_block(prevhash), newloop).result()
                    self.logger.info('{}'.format(prevblock))
                    self.backup_txs(prevblock['tx'])

**Comment by dajohi** [comment]
This diff got me closer I think, or not at all?

```diff
diff --git a/server/block_processor.py b/server/block_processor.py
index ea4265e..9d89a2a 100644
--- a/server/block_processor.py
+++ b/server/block_processor.py
@@ -11,6 +11,7 @@
 
 import array
 import asyncio
+from threading import Thread
 from struct import pack, unpack
 import time
 from collections import defaultdict
@@ -499,9 +500,35 @@ class BlockProcessor(server.db.DB):
 
         for block in blocks:
             height += 1
+
+            if self.coin.NAME == 'Decred' and height != 0:
+                def decred_loop(loop):
+                    asyncio.set_event_loop(loop)
+                    loop.run_forever()
+
+                # Retrieve VoteBits (ushort) from the block header
+                vb = unpack("<H", block.header[100:102])
+                votebits = int.from_bytes(vb, byteorder='little')
+
+                # Check if previous block was invalidated.
+                validtxtree = bool(votebits & (1<<0) != 0)
+                if not validtxtree:
+                    ph = hash_to_str(self.coin.header_prevhash(block.header))
+                    self.logger.info('block {:,d} invalidates previous block {}'.format(height, ph))
+                    newloop = asyncio.new_event_loop()
+                    Thread(target=decred_loop, args=(newloop,)).start()
+                    prevblock = asyncio.run_coroutine_threadsafe(self.daemon.deserialised_block(ph), newloop).result()
+                    self.logger.info('{}'.format(prevblock))
+                    tmph = self.height
+                    self.height = height - 1
+                    self.backup_txs(prevblock['tx'])
+                    self.height = tmph
+
             undo_info = self.advance_txs(block.transactions)
-            if height >= min_height:
-                self.undo_infos.append((undo_info, height))
+            self.logger.info('height {:,d} min_height {:,d}'.format(height, min_height))
+            #if height >= min_height or self.coin.NAME == 'Decred':
+            self.undo_infos.append((undo_info, height))
+            self.logger.info('added undo_info for height {:,d}'.format(height))
 
         headers = [block.header for block in blocks]
         self.height = height
```

```
Mar 19 23:29:57 dcrd-cf-test1.localdomain electrumx_server.py[22012]: INFO:BlockProcessor:added undo_info for height 80,733
Mar 19 23:29:57 dcrd-cf-test1.localdomain electrumx_server.py[22012]: INFO:BlockProcessor:height 80,734 min_height 222,327
Mar 19 23:29:57 dcrd-cf-test1.localdomain electrumx_server.py[22012]: INFO:BlockProcessor:added undo_info for height 80,734
Mar 19 23:29:57 dcrd-cf-test1.localdomain electrumx_server.py[22012]: INFO:BlockProcessor:height 80,735 min_height 222,327
Mar 19 23:29:57 dcrd-cf-test1.localdomain electrumx_server.py[22012]: INFO:BlockProcessor:added undo_info for height 80,735
Mar 19 23:29:57 dcrd-cf-test1.localdomain electrumx_server.py[22012]: INFO:BlockProcessor:height 80,736 min_height 222,327
Mar 19 23:29:57 dcrd-cf-test1.localdomain electrumx_server.py[22012]: INFO:BlockProcessor:added undo_info for height 80,736
Mar 19 23:29:57 dcrd-cf-test1.localdomain electrumx_server.py[22012]: INFO:BlockProcessor:height 80,737 min_height 222,327
Mar 19 23:29:57 dcrd-cf-test1.localdomain electrumx_server.py[22012]: INFO:BlockProcessor:added undo_info for height 80,737
Mar 19 23:29:57 dcrd-cf-test1.localdomain electrumx_server.py[22012]: INFO:BlockProcessor:height 80,738 min_height 222,327
Mar 19 23:29:57 dcrd-cf-test1.localdomain electrumx_server.py[22012]: INFO:BlockProcessor:added undo_info for height 80,738
Mar 19 23:29:57 dcrd-cf-test1.localdomain electrumx_server.py[22012]: INFO:BlockProcessor:height 80,739 min_height 222,327
Mar 19 23:29:57 dcrd-cf-test1.localdomain electrumx_server.py[22012]: INFO:BlockProcessor:added undo_info for height 80,739
Mar 19 23:29:57 dcrd-cf-test1.localdomain electrumx_server.py[22012]: INFO:BlockProcessor:height 80,740 min_height 222,327
Mar 19 23:29:57 dcrd-cf-test1.localdomain electrumx_server.py[22012]: INFO:BlockProcessor:added undo_info for height 80,740
Mar 19 23:29:57 dcrd-cf-test1.localdomain electrumx_server.py[22012]: INFO:BlockProcessor:block 80,741 invalidates previous block 00000000000003ae4fa13a6dcd53bf2fddacfac12e86e5b5f98a08a71d3e6caa
Mar 19 23:29:57 dcrd-cf-test1.localdomain electrumx_server.py[22012]: INFO:BlockProcessor:{'hash': '00000000000003ae4fa13a6dcd53bf2fddacfac12e86e5b5f98a08a71d3e6caa', 'confirmations': 141787, 'size': 2088, 'height': 80740, 'version': 1, 'merkleroot': 'c7f517735272c3e4185f0cbcde3d2c4ebd613ca36bcb2e4ee213ad4012380f95', 'stakeroot': '3f0c2268787ae55adc7e4438acd2aad5aad392c4d04a4bdc1ac067472c0d55e3', 'tx': ['2d045cf863a3f813fbe513e5a3d5b24ee447c01d43d8f6d840d2804a053b6d20'], 'stx': ['ae028d7b641bc35fbd26340cc4104450f5bf1af909f4db0572cc476e29f925ad', '03ab600fc197fa1e9b74a1675570926f7ef5e3386dcd0a2941c0c68c7ea93738', 'c7ec4cc725fbf0725ae1e8a303d8b1644612520f3c13adf0bf50ddfa2be26a7f', '981febc6b44a1b5ab3f8d598f368bb60f602cb89cd7471efdd1e6492a05da098', '789f7e97c9b3c350159bb1278d6de9c8d57d9627baf78ab359d7197b0450d5a6'], 'time': 1479098839, 'nonce': 73954746, 'votebits': 1, 'finalstate': '9fbf748726e3', 'voters': 5, 'freshstake': 0, 'revocations': 0, 'poolsize': 42860, 'bits': '1a123007', 'sbits': 63.31478942, 'difficulty': 922439.11878336, 'extradata': '2802000000600401003f88660000000000000000000000000000000000000000', 'stakeversion': 0, 'previousblockhash': '0000000000000bbc72cc41a16b14b2d56d61f11eb5aad3180984e212e0246293', 'nextblockhash': '0000000000000f44e1825f0717c9a8758097a511699565192981074a5bc6185d'}
Mar 19 23:29:57 dcrd-cf-test1.localdomain electrumx_server.py[22012]: ERROR:Controller:Traceback (most recent call last):
Mar 19 23:29:57 dcrd-cf-test1.localdomain electrumx_server.py[22012]:   File "/usr/lib/python3.6/site-packages/electrumx-1.3_-py3.6.egg/server/controller.py", line 176, in on_future_done
Mar 19 23:29:57 dcrd-cf-test1.localdomain electrumx_server.py[22012]:     future.result()
Mar 19 23:29:57 dcrd-cf-test1.localdomain electrumx_server.py[22012]:   File "/usr/lib/python3.6/site-packages/electrumx-1.3_-py3.6.egg/server/block_processor.py", line 207, in main_loop
Mar 19 23:29:57 dcrd-cf-test1.localdomain electrumx_server.py[22012]:     await task()
Mar 19 23:29:57 dcrd-cf-test1.localdomain electrumx_server.py[22012]:   File "/usr/lib/python3.6/site-packages/electrumx-1.3_-py3.6.egg/server/block_processor.py", line 251, in check_and_advance_blocks
Mar 19 23:29:57 dcrd-cf-test1.localdomain electrumx_server.py[22012]:     await self.controller.run_in_executor(self.advance_blocks, blocks)
Mar 19 23:29:57 dcrd-cf-test1.localdomain electrumx_server.py[22012]:   File "/usr/lib/python3.6/site-packages/electrumx-1.3_-py3.6.egg/server/controller.py", line 156, in run_in_executor
Mar 19 23:29:57 dcrd-cf-test1.localdomain electrumx_server.py[22012]:     return await self.loop.run_in_executor(None, func, *args)
Mar 19 23:29:57 dcrd-cf-test1.localdomain electrumx_server.py[22012]:   File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
Mar 19 23:29:57 dcrd-cf-test1.localdomain electrumx_server.py[22012]:     result = self.fn(*self.args, **self.kwargs)
Mar 19 23:29:57 dcrd-cf-test1.localdomain electrumx_server.py[22012]:   File "/usr/lib/python3.6/site-packages/electrumx-1.3_-py3.6.egg/server/block_processor.py", line 524, in advance_blocks
Mar 19 23:29:57 dcrd-cf-test1.localdomain electrumx_server.py[22012]:     self.backup_txs(prevblock['tx'])
Mar 19 23:29:57 dcrd-cf-test1.localdomain electrumx_server.py[22012]:   File "/usr/lib/python3.6/site-packages/electrumx-1.3_-py3.6.egg/server/block_processor.py", line 627, in backup_txs
Mar 19 23:29:57 dcrd-cf-test1.localdomain electrumx_server.py[22012]:     .format(self.height))
Mar 19 23:29:57 dcrd-cf-test1.localdomain electrumx_server.py[22012]: server.block_processor.ChainError: no undo information found for height 80,740
```

**Comment by kyuupichan** [comment]
Perhaps... but we don't want threads in the code; it will need to be done properly.

The problem now is that undo information isn't stored until the last N blocks of initial sync because other coins don't need it.

**Comment by kyuupichan** [comment]
And what @erasmospunk said about reorg handling - it looks like doing this properly is quite hard...

**Comment by jrick** [comment]
In dcrwallet, the way stake validation/invalidation is handled is that it is treated similarly to a reorg, but rather than discarding the data, it is saved to another database index.  If the next block invalidates the previous, the regular transactions of the previous block are removed and saved to the invalidated index, and if a reorg later validates the invalidated block, those transactions are looked up again and reattached.

Based on how the electrumx code is organized, it doesn't sound like making database calls here is possible (except when flushing), so these would need to be saved to memory and written to the database at a later time.  Since electrumx doesn't handle reorgs longer than some number of blocks, it's fine to let that in-memory data be lost during initial sync as the block depth exceeds this limit.

However, this code will need to touch the database.  When the database is written on the ticker, or when synced, and when opening and closing the program, any invalidated regular txs from the last however many blocks will need to be saved to the database so they can be restored on startup.  Otherwise, if the program is restarted, and one of the last recent invalidated blocks becomes validated, the previously-invalidated transactions will be nowhere to be found.

I don't have the python skills to complete this task, but I'm hoping this design is accurate and helpful to anyone who can code this.

**Comment by erasmospunk** [comment]
I am talking with the Decred team in case they want to lend a hand.

@dajohi thanks for the code snippets. This needs to be architectured in a way that is configurable from the `coins.py`, we should not put coin specific code in the `BlockProcessor`. Set a subclass in the Decred definition as `BLOCK_PROCESSOR = DecredBlockProcessor`.
