### ISSUE TITLE
TypeError: 'NoneType'object is not iterable

### ISSUE THREAD

**Issue by wakiyamap** [kyuupichan/electrumx#428]
on git master a2635f4df96b3f1e876cb98f884b1e85ce94f45c

```
ERROR:Controller:Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/electrumx-1.3.1-py3.6.egg/server/controller.py", line 176, in on_future_done
    future.result()
  File "/usr/local/lib/python3.6/dist-packages/electrumx-1.3.1-py3.6.egg/server/peers.py", line 466, in main_loop
    await self.maybe_detect_proxy()
  File "/usr/local/lib/python3.6/dist-packages/electrumx-1.3.1-py3.6.egg/server/peers.py", line 443, in maybe_detect_proxy
    for failure_msg in result:
TypeError: 'NoneType'object is not iterable
```

**Comment by kyuupichan** [comment]
Ugh; some code for unreleased aiorpcX crept in there...
