### ISSUE TITLE
ImportError: cannot import name 'TaskSet' and ModuleNotFoundError: No module named 'apt_pkg'

### ISSUE THREAD

**Issue by shsmith** [kyuupichan/electrumx#441]
I had no problem installing 1.4, but 1.4.1 fails on  `sudo python3.6 setup.py install` with this traceback:
```
Checking connectivity... done.
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from server.controller import Controller
  File "/home/shsmith/electrumx/server/controller.py", line 22, in <module>
    from aiorpcx import RPCError, TaskSet
ImportError: cannot import name 'TaskSet'

Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from server.controller import Controller
  File "/home/shsmith/electrumx/server/controller.py", line 22, in <module>
    from aiorpcx import RPCError, TaskSet
ImportError: cannot import name 'TaskSet'
```
I tried to fix it with this:
```
$ sudo apt-get install python-apt
python-apt is already the newest version (1.1.0~beta1ubuntu0.16.04.1).

$ sudo python3.6 -m pip install aiorpc
Collecting aiorpc
  Downloading aiorpc-0.1.2.tar.gz
Collecting msgpack-python (from aiorpc)
  Downloading msgpack-python-0.5.6.tar.gz (138kB)
Collecting uvloop (from aiorpc)
  Downloading uvloop-0.9.1-cp36-cp36m-manylinux1_x86_64.whl (3.2MB)
Installing collected packages: msgpack-python, uvloop, aiorpc
  Running setup.py install for msgpack-python ... done
  Running setup.py install for aiorpc ... done
Successfully installed aiorpc-0.1.2 msgpack-python-0.5.6 uvloop-0.9.1

$ sudo python3.6 -m pip install aiorpc==0.5.4
  Could not find a version that satisfies the requirement aiorpc==0.5.4 (from versions: 0.1.2)
No matching distribution found for aiorpc==0.5.4
```
This is the change that caused this:
https://github.com/kyuupichan/electrumx/commit/4eebf420e82973e7ac29185ceccffe51991b7a94#diff-33f312461bb94be9bc978220deca8774R22

What am I missing?

**Comment by kyuupichan** [comment]
wrong package - you want aiorpcX 0.5.4
