### ISSUE TITLE
(1.4.3) ImportError: cannot import name 'JSONRPC'

### ISSUE THREAD

**Issue by randomnonsense** [kyuupichan/electrumx#444]
Hi, just pulled the most recent 1.4.3 requiring aiorpcx, updating from 1.2, and I've run into unexpected problems. I've been running the server for months now.

Obviously 1.4.3 requires aiorpcx. Without it I get the obvious error.
```
@400000005acbca292a96f634 Launching ElectrumX server...
@400000005acbca293096127c Traceback (most recent call last):
@400000005acbca2930961a4c   File "/home/electrumx/electrumx/electrumx_server.py", line 15, in <module>
@400000005acbca2930961e34     from server.env import Env
@400000005acbca293096221c   File "/home/electrumx/electrumx/server/env.py", line 16, in <module>
@400000005acbca29309629ec     from lib.coins import Coin
@400000005acbca2930962dd4   File "/home/electrumx/electrumx/lib/coins.py", line 45, in <module>
@400000005acbca29309631bc     from server.block_processor import BlockProcessor
@400000005acbca293096d5cc   File "/home/electrumx/electrumx/server/block_processor.py", line 20, in <module>
@400000005acbca293096dd9c     from server.daemon import DaemonError
@400000005acbca293096e184   File "/home/electrumx/electrumx/server/daemon.py", line 23, in <module>
@400000005acbca293096e56c     from aiorpcx import JSONRPC
@400000005acbca293096e954 ModuleNotFoundError: No module named 'aiorpcx'
```

So I simply installed aiorpcx via pip, running Python 3.6 (package aiorpcX (0.5.5)) and I am getting the following error:
```
@400000005acbcae136a78de4 Launching ElectrumX server...
@400000005acbcae200ed28e4 Traceback (most recent call last):
@400000005acbcae200ed2ccc   File "/home/electrumx/electrumx/electrumx_server.py", line 15, in <module>
@400000005acbcae200ed30b4     from server.env import Env
@400000005acbcae200ed349c   File "/home/electrumx/electrumx/server/env.py", line 16, in <module>
@400000005acbcae200ed3884     from lib.coins import Coin
@400000005acbcae200ed3c6c   File "/home/electrumx/electrumx/lib/coins.py", line 45, in <module>
@400000005acbcae200ed443c     from server.block_processor import BlockProcessor
@400000005acbcae200edd8ac   File "/home/electrumx/electrumx/server/block_processor.py", line 20, in <module>
@400000005acbcae200edffbc     from server.daemon import DaemonError
@400000005acbcae200ee078c   File "/home/electrumx/electrumx/server/daemon.py", line 23, in <module>
@400000005acbcae200ee0b74     from aiorpcx import JSONRPC
@400000005acbcae200ee0f5c ImportError: cannot import name 'JSONRPC'
```
Can somebody please advice what to do about it? Looks like there's some problem with how RCP is handled, i.e. aiorpcx. Many thanks.

**Comment by randomnonsense** [comment]
Sorted. I was a chmod problem.
