### ISSUE TITLE
error in systemctl start electrumx : Unit electrumx.service is not loaded properly, service lacks both ExecStart= and ExecStop= setting. Refusing 

### ISSUE THREAD

**Issue by FEskandariGM** [kyuupichan/electrumx#478]
**Hi, I have installed both  Electrumx and bitcoind on Ubuntu 16.04  in root user. I want to run electrumx using systemd. The installation didn't launch any error and it was successful. 
My electrumx.service file seetings are as below**  
```
i[Unit]
Description=Electrumx
After=network.target
[service]
EnvironmentFile=/etc/electrumx.conf
ExecStart=/root/electrumx/electrumx_server.py
User=root
LimitNOFILE=8192
TimeoutStopSec=30min
[Install]
WantedBy=multi-user.target
```

**And my electrumx.conf file  settings are as below:**
```
DAEMON_URL=http://<bitcoin.conf rpcuser>:<bitcoin.conf rpcpassowrd>@localhost:8332/
DB_DIRECTORY=/root/.electrumx
DB_ENGINE=leveldb
USERNAME=root
ELECTRUMX=/root/electrumx/electrumx_server.py
HOST=0.0.0.0
BANNER_FILE=/root/.electrumx/banner.txt
SSL_CERTFILE=/root/.electrumx/server.crt
SSL_KEYFILE=/root/.electrumx/server.key
SSL_PORT=50002
TCP_PORT=50001

```
**But when I run the systemctl start electrumx . this error appeares for me** 
```
# systemctl start electrumx
Failed to start electrumx.service: Unit electrumx.service is not loaded properly: Invalid argument.
See system logs and 'systemctl status electrumx.service' for details.
```
**And by running  systemctl status electrumx.service this log  appeares:**

```
#systemctl status electrumx.service

● electrumx.service
   Loaded: error (Reason: Invalid argument)
   Active: inactive (dead)

May 27 04:23:10 natashapourhaji.com4 systemd[1]: [/etc/systemd/system/electrumx.service:2] Assignment outside of section. Ignoring.
May 27 04:23:10 natashapourhaji.com4 systemd[1]: [/etc/systemd/system/electrumx.service:3] Assignment outside of section. Ignoring.
May 27 04:23:10 natashapourhaji.com4 systemd[1]: [/etc/systemd/system/electrumx.service:5] Unknown section 'service'. Ignoring.
May 27 04:23:10 natashapourhaji.com4 systemd[1]: electrumx.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.
May 27 04:40:06 natashapourhaji.com4 systemd[1]: [/etc/systemd/system/electrumx.service:1] Assignment outside of section. Ignoring.
May 27 04:40:06 natashapourhaji.com4 systemd[1]: [/etc/systemd/system/electrumx.service:2] Assignment outside of section. Ignoring.
May 27 04:40:06 natashapourhaji.com4 systemd[1]: [/etc/systemd/system/electrumx.service:3] Assignment outside of section. Ignoring.
May 27 04:40:06 natashapourhaji.com4 systemd[1]: [/etc/systemd/system/electrumx.service:5] Unknown section 'service'. Ignoring.
May 27 04:40:06 natashapourhaji.com4 systemd[1]: electrumx.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.
May 27 04:41:52 natashapourhaji.com4 systemd[1]: [/etc/systemd/system/electrumx.service:1] Assignment outside of section. Ignoring.



```

**Comment by kyuupichan** [comment]
This looks like a configuration issue and not an ElectrumX problem

**Comment by FEskandariGM** [comment]
thanks. do you have any idea about   installing  and runing  both electrumx and bitcoind in a special user for example electrumx user instead of root ,to solve this problem?  I am trying to run electrumx using electrumx-installer, but this time another error occures. 
```
# systemctl enable electrumx
# service electrumx status
● electrumx.service - Electrumx
   Loaded: loaded (/etc/systemd/system/electrumx.service; enabled; vendor preset: enabled)
   **Active: active (running)** since Wed 2018-05-30 02:51:39 EDT; 1min 15s ago
 Main PID: 2742 (electrumx_serve)
   CGroup: /system.slice/electrumx.service
           └─2742 /usr/local/bin/python3 /usr/local/bin/electrumx_server.py

May 30 02:51:39  electrumx_server.py[2742]: ERROR:Controller:Traceback (most recent call last):
May 30 02:51:39  electrumx_server.py[2742]:   File "/usr/local/lib/python3.6/site-packages/electrumx-1.2.1-py3.6.egg/server/controller.py", line 177
May 30 02:51:39  electrumx_server.py[2742]:     future.result()
May 30 02:51:39 electrumx_server.py[2742]:   File "/usr/local/lib/python3.6/site-packages/electrumx-1.2.1-py3.6.egg/server/block_processor.py", lin
May 30 02:51:39 electrumx_server.py[2742]:     await task()
May 30 02:51:39 electrumx_server.py[2742]:   File "/usr/local/lib/python3.6/site-packages/electrumx-1.2.1-py3.6.egg/server/block_processor.py", lin
May 30 02:51:39  electrumx_server.py[2742]:     for n, raw_block in enumerate(raw_blocks)]
May 30 02:51:39  electrumx_server.py[2742]:   File "/usr/local/lib/python3.6/site-packages/electrumx-1.2.1-py3.6.egg/server/block_processor.py", lin
May 30 02:51:39  electrumx_server.py[2742]:     for n, raw_block in enumerate(raw_blocks)]
May 30 02:51:39  electrumx_server.py[2742]: **AttributeError: type object 'Bitcoin' has no attribute 'block'**
 
`` `
would you please help me to find the cause of this error.  if all steps will be successful, in server side and client side what should i do to client can successfully connect my server.

**Comment by kyuupichan** [comment]
You have an extra i at the start of your file - is that a problem?  It seems related to the syntax errors.

Why are line numbers cut off in your last dump?

**Comment by FEskandariGM** [comment]
OK. that's right. I delete the extra i. 
I don't no why the line numbers are cut off!!
where is saved the electrumx running log file in ubuntu? I can't find it because I have installed electrumx via installer.

**Comment by FEskandariGM** [comment]
My complete log file is as follow: 
```
May 30 06:30:29 natashapourhaji.com4 electrumx_server.py[6458]: INFO:root:ElectrumX server starting
May 30 06:30:29 natashapourhaji.com4 electrumx_server.py[6458]: INFO:Controller:event loop policy: None
May 30 06:30:29 natashapourhaji.com4 electrumx_server.py[6458]: INFO:Daemon:daemon #1 at localhost:8332/ (current)
May 30 06:30:29 natashapourhaji.com4 electrumx_server.py[6458]: INFO:BlockProcessor:switching current directory to /etc/electrumx
May 30 06:30:30 natashapourhaji.com4 electrumx_server.py[6458]: INFO:BlockProcessor:using rocksdb for DB backend
May 30 06:30:31 natashapourhaji.com4 electrumx_server.py[6458]: INFO:BlockProcessor:opened DB for serving
May 30 06:30:31 natashapourhaji.com4 electrumx_server.py[6458]: INFO:BlockProcessor:closing DB to re-open for sync
May 30 06:30:31 natashapourhaji.com4 electrumx_server.py[6458]: INFO:BlockProcessor:opened DB for sync
May 30 06:30:31 natashapourhaji.com4 electrumx_server.py[6458]: INFO:BlockProcessor:software version: ElectrumX 1.2.1
May 30 06:30:31 natashapourhaji.com4 electrumx_server.py[6458]: INFO:BlockProcessor:DB version: 6
May 30 06:30:31 natashapourhaji.com4 electrumx_server.py[6458]: INFO:BlockProcessor:coin: Bitcoin
May 30 06:30:31 natashapourhaji.com4 electrumx_server.py[6458]: INFO:BlockProcessor:network: mainnet
May 30 06:30:31 natashapourhaji.com4 electrumx_server.py[6458]: INFO:BlockProcessor:height: -1
May 30 06:30:31 natashapourhaji.com4 electrumx_server.py[6458]: INFO:BlockProcessor:tip: 0000000000000000000000000000000000000000000000000000000000000000
May 30 06:30:31 natashapourhaji.com4 electrumx_server.py[6458]: INFO:BlockProcessor:tx count: 0
May 30 06:30:31 natashapourhaji.com4 electrumx_server.py[6458]: INFO:BlockProcessor:flush count: 0
May 30 06:30:31 natashapourhaji.com4 electrumx_server.py[6458]: INFO:BlockProcessor:sync time so far: 00s
May 30 06:30:31 natashapourhaji.com4 electrumx_server.py[6458]: INFO:BlockProcessor:reorg limit is 200 blocks
May 30 06:30:31 natashapourhaji.com4 electrumx_server.py[6458]: INFO:BlockProcessor:flushing DB cache at 1,200 MB
May 30 06:30:31 natashapourhaji.com4 electrumx_server.py[6458]: INFO:PeerManager:accepted new peer 1/15 btc.smsys.me from coins.py
May 30 06:30:31 natashapourhaji.com4 electrumx_server.py[6458]: INFO:PeerManager:accepted new peer 2/15 electrum.be from coins.py
May 30 06:30:31 natashapourhaji.com4 electrumx_server.py[6458]: INFO:PeerManager:accepted new peer 3/15 ELECTRUM.not.fyi from coins.py
May 30 06:30:31 natashapourhaji.com4 electrumx_server.py[6458]: INFO:PeerManager:accepted new peer 4/15 electrum.vom-stausee.de from coins.py
May 30 06:30:31 natashapourhaji.com4 electrumx_server.py[6458]: INFO:PeerManager:accepted new peer 5/15 electrum3.hachre.de from coins.py
May 30 06:30:31 natashapourhaji.com4 electrumx_server.py[6458]: INFO:PeerManager:accepted new peer 6/15 electrum.hsmiths.com from coins.py
May 30 06:30:31 natashapourhaji.com4 electrumx_server.py[6458]: INFO:PeerManager:accepted new peer 7/15 erbium1.sytes.net from coins.py
May 30 06:30:31 natashapourhaji.com4 electrumx_server.py[6458]: INFO:PeerManager:accepted new peer 8/15 fdkhv2bb7hqel2e7.onion from coins.py
May 30 06:30:31 natashapourhaji.com4 electrumx_server.py[6458]: INFO:PeerManager:accepted new peer 9/15 h.1209k.com from coins.py
May 30 06:30:31 natashapourhaji.com4 electrumx_server.py[6458]: INFO:PeerManager:accepted new peer 10/15 helicarrier.bauerj.eu from coins.py
May 30 06:30:31 natashapourhaji.com4 electrumx_server.py[6458]: INFO:PeerManager:accepted new peer 11/15 hsmiths4fyqlw5xw.onion from coins.py
May 30 06:30:31 natashapourhaji.com4 electrumx_server.py[6458]: INFO:PeerManager:accepted new peer 12/15 ozahtqwp25chjdjd.onion from coins.py
May 30 06:30:31 natashapourhaji.com4 electrumx_server.py[6458]: INFO:PeerManager:accepted new peer 13/15 us11.einfachmalnettsein.de from coins.py
May 30 06:30:31 natashapourhaji.com4 electrumx_server.py[6458]: INFO:PeerManager:accepted new peer 14/15 ELEX01.blackpole.online from coins.py
May 30 06:30:31 natashapourhaji.com4 electrumx_server.py[6458]: INFO:PeerManager:accepted new peer 15/15 electrum_abc.criptolayer.net from coins.py
May 30 06:30:31 natashapourhaji.com4 electrumx_server.py[6458]: INFO:Controller:RPC server listening on localhost:8000
May 30 06:30:32 natashapourhaji.com4 electrumx_server.py[6458]: INFO:Prefetcher:catching up to daemon height 525,090 (525,091 blocks behind)
May 30 06:30:32 natashapourhaji.com4 electrumx_server.py[6458]: INFO:Prefetcher:verified genesis block with hash 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f
May 30 06:30:32 natashapourhaji.com4 electrumx_server.py[6458]: ERROR:Controller:Traceback (most recent call last):
May 30 06:30:32 natashapourhaji.com4 electrumx_server.py[6458]:   File "/usr/local/lib/python3.6/site-packages/electrumx-1.2.1-py3.6.egg/server/controller.py", line 177, in on_future_done
May 30 06:30:32 natashapourhaji.com4 electrumx_server.py[6458]:     future.result()
May 30 06:30:32 natashapourhaji.com4 electrumx_server.py[6458]:   File "/usr/local/lib/python3.6/site-packages/electrumx-1.2.1-py3.6.egg/server/block_processor.py", line 206, in main_loop
May 30 06:30:32 natashapourhaji.com4 electrumx_server.py[6458]:     await task()
May 30 06:30:32 natashapourhaji.com4 electrumx_server.py[6458]:   File "/usr/local/lib/python3.6/site-packages/electrumx-1.2.1-py3.6.egg/server/block_processor.py", line 243, in check_and_advance_blocks
May 30 06:30:32 natashapourhaji.com4 electrumx_server.py[6458]:     for n, raw_block in enumerate(raw_blocks)]
May 30 06:30:32 natashapourhaji.com4 electrumx_server.py[6458]:   File "/usr/local/lib/python3.6/site-packages/electrumx-1.2.1-py3.6.egg/server/block_processor.py", line 243, in <listcomp>
May 30 06:30:32 natashapourhaji.com4 electrumx_server.py[6458]:     for n, raw_block in enumerate(raw_blocks)]
May 30 06:30:32 natashapourhaji.com4 electrumx_server.py[6458]: AttributeError: type object 'Bitcoin' has no attribute 'block'
May 30 07:17:38 natashapourhaji.com4 electrumx_server.py[6458]: INFO:LocalRPC:[0] RPC [::1]:59056, 1 total

```

**Comment by kyuupichan** [comment]
Not sure.  It definitely has a member function called block.  I suggest you update to the latest version.

**Comment by FEskandariGM** [comment]
OK. thank's very much. I think it's better to install electrumx latest version  instead of electumx-installer ready script.
