### ISSUE TITLE
Error chain reorganised

### ISSUE THREAD

**Issue by ElpidioMC** [kyuupichan/electrumx#479]
Hi, my electrumx server work fine before chain reorganised:

```
May 27 03:25:11 ArepaCoinSecondVPS electrumx_server.py[3965]: INFO:BlockProcessor:chain was reorganised replacing 1 block at heights 299,462-299,462
May 27 03:25:11 ArepaCoinSecondVPS electrumx_server.py[3965]: ERROR:Controller:uncaught task exception: [{'code': -5, 'message': 'No information available about transaction'}, {'code': -5, 'message': 'No informat
May 27 03:25:11 ArepaCoinSecondVPS electrumx_server.py[3965]: Traceback (most recent call last):
May 27 03:25:11 ArepaCoinSecondVPS electrumx_server.py[3965]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.5.1-py3.6.egg/server/controller.py", line 192, in check_task_exception
May 27 03:25:11 ArepaCoinSecondVPS electrumx_server.py[3965]:     task.result()
May 27 03:25:11 ArepaCoinSecondVPS electrumx_server.py[3965]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.5.1-py3.6.egg/server/block_processor.py", line 203, in main_loop
May 27 03:25:11 ArepaCoinSecondVPS electrumx_server.py[3965]:     await task()
May 27 03:25:11 ArepaCoinSecondVPS electrumx_server.py[3965]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.5.1-py3.6.egg/server/block_processor.py", line 256, in check_and_advance_blocks
May 27 03:25:11 ArepaCoinSecondVPS electrumx_server.py[3965]:     await self.reorg_chain()
May 27 03:25:11 ArepaCoinSecondVPS electrumx_server.py[3965]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.5.1-py3.6.egg/server/block_processor.py", line 292, in reorg_chain
May 27 03:25:11 ArepaCoinSecondVPS electrumx_server.py[3965]:     blocks = await self.daemon.raw_blocks(hex_hashes)
May 27 03:25:11 ArepaCoinSecondVPS electrumx_server.py[3965]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.5.1-py3.6.egg/server/daemon.py", line 343, in raw_blocks
May 27 03:25:11 ArepaCoinSecondVPS electrumx_server.py[3965]:     raw_block = await self.make_raw_block(i)
May 27 03:25:11 ArepaCoinSecondVPS electrumx_server.py[3965]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.5.1-py3.6.egg/server/daemon.py", line 368, in make_raw_block
May 27 03:25:11 ArepaCoinSecondVPS electrumx_server.py[3965]:     transactions = await self.getrawtransactions(b.get('tx'), False)
May 27 03:25:11 ArepaCoinSecondVPS electrumx_server.py[3965]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.5.1-py3.6.egg/server/daemon.py", line 275, in getrawtransactions
May 27 03:25:11 ArepaCoinSecondVPS electrumx_server.py[3965]:     replace_errs=replace_errs)
May 27 03:25:11 ArepaCoinSecondVPS electrumx_server.py[3965]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.5.1-py3.6.egg/server/daemon.py", line 197, in _send_vector
May 27 03:25:11 ArepaCoinSecondVPS electrumx_server.py[3965]:     return await self._send(payload, processor)
May 27 03:25:11 ArepaCoinSecondVPS electrumx_server.py[3965]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.5.1-py3.6.egg/server/daemon.py", line 132, in _send
May 27 03:25:11 ArepaCoinSecondVPS electrumx_server.py[3965]:     result = processor(result)
May 27 03:25:11 ArepaCoinSecondVPS electrumx_server.py[3965]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.5.1-py3.6.egg/server/daemon.py", line 192, in processor
May 27 03:25:11 ArepaCoinSecondVPS electrumx_server.py[3965]:     raise DaemonError(errs)
May 27 03:25:11 ArepaCoinSecondVPS electrumx_server.py[3965]: server.daemon.DaemonError: [{'code': -5, 'message': 'No information available about transaction'}, {'code': -5, 'message': 'No information available a
May 27 03:25:42 ArepaCoinSecondVPS electrumx_server.py[3965]: INFO:Prefetcher:new block height 299,464 hash c5645ee7e43bea8ceaab0f1babdf84508d0858e3f42f8fa8e4a87148d33bd5d3
```

If reboot the service:
```
May 27 13:25:45 ArepaCoinSecondVPS systemd[1]: Started Electrumx.
May 27 13:25:46 ArepaCoinSecondVPS electrumx_server.py[13592]: INFO:root:ElectrumX server starting
May 27 13:25:46 ArepaCoinSecondVPS electrumx_server.py[13592]: INFO:Controller:software version: ElectrumX 1.5.1
May 27 13:25:46 ArepaCoinSecondVPS electrumx_server.py[13592]: INFO:Controller:supported protocol versions: 1.0-1.2
May 27 13:25:46 ArepaCoinSecondVPS electrumx_server.py[13592]: INFO:Controller:event loop policy: None
May 27 13:25:46 ArepaCoinSecondVPS electrumx_server.py[13592]: INFO:LegacyRPCDaemon:daemon #1 at 127.0.0.1:8586/ (current)
May 27 13:25:46 ArepaCoinSecondVPS electrumx_server.py[13592]: INFO:BlockProcessor:switching current directory to /db
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]: INFO:BlockProcessor:using leveldb for DB backend
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]: INFO:BlockProcessor:opened DB for serving
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]: INFO:History:flush count: 278
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]: INFO:History:history DB version: 0
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]: INFO:BlockProcessor:deleted 433 stale undo entries
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]: INFO:BlockProcessor:DB version: 6
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]: INFO:BlockProcessor:coin: Arepacoin
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]: INFO:BlockProcessor:network: mainnet
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]: INFO:BlockProcessor:height: 300,059
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]: INFO:BlockProcessor:tip: d6f6d948faec62733fbf9163c908a258269213ace73de7476f804a3fc2a173e2
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]: INFO:BlockProcessor:tx count: 488,291
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]: INFO:BlockProcessor:reorg limit is 200 blocks
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]: INFO:Controller:RPC server listening on localhost:8000
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]: INFO:Prefetcher:catching up to daemon height 300,626 (567 blocks behind)
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]: INFO:BlockProcessor:chain reorg detected
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]: INFO:BlockProcessor:chain was reorganised replacing 1 block at heights 300,059-300,059
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]: ERROR:Controller:uncaught task exception: [{'code': -5, 'message': 'No information available about transaction'}, {'code': -5, 'message': 'No informa
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]: Traceback (most recent call last):
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.5.1-py3.6.egg/server/controller.py", line 192, in check_task_exception
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]:     task.result()
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.5.1-py3.6.egg/server/block_processor.py", line 203, in main_loop
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]:     await task()
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.5.1-py3.6.egg/server/block_processor.py", line 256, in check_and_advance_blocks
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]:     await self.reorg_chain()
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.5.1-py3.6.egg/server/block_processor.py", line 292, in reorg_chain
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]:     blocks = await self.daemon.raw_blocks(hex_hashes)
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.5.1-py3.6.egg/server/daemon.py", line 343, in raw_blocks
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]:     raw_block = await self.make_raw_block(i)
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.5.1-py3.6.egg/server/daemon.py", line 368, in make_raw_block
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]:     transactions = await self.getrawtransactions(b.get('tx'), False)
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.5.1-py3.6.egg/server/daemon.py", line 275, in getrawtransactions
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]:     replace_errs=replace_errs)
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.5.1-py3.6.egg/server/daemon.py", line 197, in _send_vector
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]:     return await self._send(payload, processor)
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.5.1-py3.6.egg/server/daemon.py", line 132, in _send
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]:     result = processor(result)
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.5.1-py3.6.egg/server/daemon.py", line 192, in processor
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]:     raise DaemonError(errs)
May 27 13:25:47 ArepaCoinSecondVPS electrumx_server.py[13592]: server.daemon.DaemonError: [{'code': -5, 'message': 'No information available about transaction'}, {'code': -5, 'message': 'No information available 
May 27 13:26:09 ArepaCoinSecondVPS electrumx_server.py[13592]: INFO:Prefetcher:new block height 300,627 hash 0dde7046f510529b98606d96cdf05322ee958bc72cf9d4555ad003ba77d27e95
May 27 13:26:19 ArepaCoinSecondVPS electrumx_server.py[13592]: INFO:Prefetcher:new block height 300,628 hash 000000000814cc81ef85c0329ceaacca0c8ea761e7de5a3fd81ce339bd9086d9
```

```
class Arepacoin(ScryptMixin, Coin):
    NAME = "Arepacoin"
    SHORTNAME = "AREPA"
    NET = "mainnet"
    P2PKH_VERBYTE = bytes.fromhex("17")
    P2SH_VERBYTES = [bytes.fromhex("55")]
    WIF_BYTE = bytes.fromhex("97")
    GENESIS_HASH = ('000002cac270a01e29300abaaeb7d412'
                    'ca00fa7f43f0d547a57b9ff9c85d95e8')
    DAEMON = daemon.LegacyRPCDaemon
    PEERS = []
    RPC_PORT = 8586
    TX_COUNT = 1
    TX_COUNT_HEIGHT = 1
    TX_PER_BLOCK = 5
```

Coin code:
https://github.com/ElpidioMC/Arepacoin

Can anybody help me please??

**Comment by ElpidioMC** [comment]
I fix the problem with this patch:

```
diff --git a/src/main.cpp b/src/main.cpp
index dbb54d5e..f02382ba 100644
--- a/src/main.cpp
+++ b/src/main.cpp
@@ -860,6 +860,24 @@ bool GetTransaction(const uint256 &hash, CTransaction &tx, uint256 &hashBlock)
                 hashBlock = block.GetHash();
             return true;
         }
+        // look for transaction in disconnected blocks to find orphaned CoinBase and CoinStake transactions
+        BOOST_FOREACH(PAIRTYPE(const uint256, CBlockIndex*)& item, mapBlockIndex)
+        {
+            CBlockIndex* pindex = item.second;
+            if (pindex == pindexBest || pindex->pnext != 0)
+                continue;
+            CBlock block;
+            if (!block.ReadFromDisk(pindex))
+                continue;
+            BOOST_FOREACH(const CTransaction& txOrphan, block.vtx)
+            {
+                if (txOrphan.GetHash() == hash)
+                {
+                    tx = txOrphan;
+                    return true;
+                }
+            }
+        }
     }
     return false;
 }
```
Thank you!
