### ISSUE TITLE
working but output error with electrumx_rpc.py stop command

### ISSUE THREAD

**Issue by gits7r** [kyuupichan/electrumx#480]
`~$ electrumx_rpc.py stop` will stop the ElectrumX daemon properly but even if it does so it will not state that it had, it only returns:

**error making request:**

I am not sure what is wrong here. I tried running the rpc command even from root user but still got the same buggy output as described above.

**Comment by kyuupichan** [comment]
Thanks, it's probably killed itself before it's had a chance to close the connection

**Comment by luggs-co** [comment]
This is what happens when i call the stop command

```2018-05-31_05:02:32.74241 INFO:Controller:shutting down
2018-05-31_05:02:32.79944 INFO:Controller:closing down RPC listening servers
2018-05-31_05:02:32.79945 INFO:BlockProcessor:flushing state to DB for a clean shutdown...
2018-05-31_05:02:32.79945 Traceback (most recent call last):
2018-05-31_05:02:32.79946   File "/opt/python/lib/python3.6/site-packages/electrumx-ElectrumX.1.4.3-py3.6.egg/EGG-INFO/scripts/electrumx_server.py", line 26, in main
2018-05-31_05:02:32.79946   File "/opt/python/lib/python3.6/site-packages/electrumx-ElectrumX.1.4.3-py3.6.egg/lib/server_base.py", line 125, in run
2018-05-31_05:02:32.79946     loop.run_until_complete(self._wait_for_shutdown_event())
2018-05-31_05:02:32.79947   File "/opt/python/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
2018-05-31_05:02:32.79947     return future.result()
2018-05-31_05:02:32.79947   File "/opt/python/lib/python3.6/site-packages/electrumx-ElectrumX.1.4.3-py3.6.egg/lib/server_base.py", line 79, in _wait_for_shutdown_event
2018-05-31_05:02:32.79947     await self.shutdown()
2018-05-31_05:02:32.79948   File "/opt/python/lib/python3.6/site-packages/electrumx-ElectrumX.1.4.3-py3.6.egg/server/controller.py", line 153, in shutdown
2018-05-31_05:02:32.79948     self.bp.shutdown(self.executor)
2018-05-31_05:02:32.79948   File "/opt/python/lib/python3.6/site-packages/electrumx-ElectrumX.1.4.3-py3.6.egg/server/block_processor.py", line 215, in shutdown
2018-05-31_05:02:32.79949     self.flush(True)
2018-05-31_05:02:32.79949   File "/opt/python/lib/python3.6/site-packages/electrumx-ElectrumX.1.4.3-py3.6.egg/server/block_processor.py", line 375, in flush
2018-05-31_05:02:32.79949     self.flush_history(self.history)
2018-05-31_05:02:32.79950   File "/opt/python/lib/python3.6/site-packages/electrumx-ElectrumX.1.4.3-py3.6.egg/server/db.py", line 463, in flush_history
2018-05-31_05:02:32.79950     flush_id = pack('>H', self.flush_count)
2018-05-31_05:02:32.79950 struct.error: 'H' format requires 0 <= number <= 65535
2018-05-31_05:02:32.79950 CRITICAL:root:ElectrumX server terminated abnormally```

**Comment by luggs-co** [comment]
and now when trying to start up (this is for litecoin btw)

```
2018-05-31_05:06:36.44122 INFO:Prefetcher:catching up to daemon height 1,430,984 (357 blocks behind)
2018-05-31_05:06:36.87322 INFO:BlockProcessor:our height: 1,430,637 daemon: 1,430,984 UTXOs 0MB hist 0MB
2018-05-31_05:06:36.87364 INFO:BlockProcessor:processed 10 blocks in 0.4s
2018-05-31_05:06:42.27309 INFO:BlockProcessor:processed 249 blocks in 4.4s
2018-05-31_05:06:44.53132 INFO:BlockProcessor:processed 98 blocks in 1.8s
2018-05-31_05:06:44.54207 ERROR:Controller:uncaught task exception: 'H' format requires 0 <= number <= 65535
2018-05-31_05:06:44.54211 Traceback (most recent call last):
2018-05-31_05:06:44.54211   File "/opt/python/lib/python3.6/site-packages/electrumx-ElectrumX.1.4.3-py3.6.egg/server/controller.py", line 192, in check_task_exception
2018-05-31_05:06:44.54212     task.result()
2018-05-31_05:06:44.54212   File "/opt/python/lib/python3.6/site-packages/electrumx-ElectrumX.1.4.3-py3.6.egg/server/block_processor.py", line 206, in main_loop
2018-05-31_05:06:44.54212     await task()
2018-05-31_05:06:44.54213   File "/opt/python/lib/python3.6/site-packages/electrumx-ElectrumX.1.4.3-py3.6.egg/server/block_processor.py", line 221, in first_caught_up
2018-05-31_05:06:44.54213     await self.controller.run_in_executor(self.flush, True)
2018-05-31_05:06:44.54213   File "/opt/python/lib/python3.6/site-packages/electrumx-ElectrumX.1.4.3-py3.6.egg/server/controller.py", line 176, in run_in_executor
2018-05-31_05:06:44.54214     return await self.loop.run_in_executor(None, func, *args)
2018-05-31_05:06:44.54214   File "/opt/python/lib/python3.6/concurrent/futures/thread.py", line 55, in run
2018-05-31_05:06:44.54214     result = self.fn(*self.args, **self.kwargs)
2018-05-31_05:06:44.54215   File "/opt/python/lib/python3.6/site-packages/electrumx-ElectrumX.1.4.3-py3.6.egg/server/block_processor.py", line 375, in flush
2018-05-31_05:06:44.54216     self.flush_history(self.history)
2018-05-31_05:06:44.54216   File "/opt/python/lib/python3.6/site-packages/electrumx-ElectrumX.1.4.3-py3.6.egg/server/db.py", line 463, in flush_history
2018-05-31_05:06:44.54216     flush_id = pack('>H', self.flush_count)
2018-05-31_05:06:44.54217 struct.error: 'H' format requires 0 <= number <= 65535
```

**Comment by kyuupichan** [comment]
@luggs-co that's #185 .  Run the compaction script

**Comment by luggs-co** [comment]
damnit, was too... forgot about it.
