### ISSUE TITLE
TypeError: fromhex() argument must be str, not dict

### ISSUE THREAD

**Issue by knkrth** [kyuupichan/electrumx#483]
Hi, I got the following error while running electrumx,

```
INFO:root:ElectrumX server starting
WARNING:Env:lowered maximum sessions from 1,000 to 674 because your open file limit is 1,024
INFO:Controller:software version: ElectrumX 1.4.4p2
INFO:Controller:supported protocol versions: 1.1-1.2
INFO:Controller:event loop policy: None
INFO:FakeEstimateFeeDaemon:daemon #1 at 127.0.0.1:10555/ (current)
INFO:BlockProcessor:switching current directory to /root/.electrumx
INFO:BlockProcessor:using leveldb for DB backend
INFO:BlockProcessor:created new database
INFO:BlockProcessor:creating metadata directory
INFO:History:flush count: 0
INFO:History:history DB version: 0
INFO:BlockProcessor:DB version: 6
INFO:BlockProcessor:coin: Geysercoin
INFO:BlockProcessor:network: mainnet
INFO:BlockProcessor:height: -1
INFO:BlockProcessor:tip: 0000000000000000000000000000000000000000000000000000000000000000
INFO:BlockProcessor:tx count: 0
INFO:BlockProcessor:sync time so far: 00s
INFO:BlockProcessor:reorg limit is 1,000 blocks
INFO:BlockProcessor:flushing DB cache at 1,200 MB
INFO:Controller:RPC server listening on localhost:8000
INFO:Prefetcher:catching up to daemon height 462,874 (462,875 blocks behind)
ERROR:Controller:uncaught task exception: fromhex() argument must be str, not dict
Traceback (most recent call last):
  File "/root/electrumx/server/controller.py", line 192, in check_task_exception
    task.result()
  File "/root/electrumx/server/block_processor.py", line 49, in main_loop
    if not await self._prefetch_blocks():
  File "/root/electrumx/server/block_processor.py", line 106, in _prefetch_blocks
    blocks = await daemon.raw_blocks(hex_hashes)
  File "/root/electrumx/server/daemon.py", line 242, in raw_blocks
    return [hex_to_bytes(block) for block in blocks]
  File "/root/electrumx/server/daemon.py", line 242, in <listcomp>
    return [hex_to_bytes(block) for block in blocks]
TypeError: fromhex() argument must be str, not dict
```

This my coin source code https://github.com/geysercoin/geysercoin.git

**Comment by kyuupichan** [comment]
It seems your coin doesn't return raw blocks; see LegacyRPCDaemon
