### ISSUE TITLE
lib.coins.CoinError

### ISSUE THREAD

**Issue by knkrth** [kyuupichan/electrumx#484]
I know it might be linked to old issues but when I start electrumx server I got,

```
INFO:root:ElectrumX server starting
WARNING:Env:lowered maximum sessions from 1,000 to 674 because your open file limit is 1,024
INFO:Controller:software version: ElectrumX 1.4.4p2
INFO:Controller:supported protocol versions: 1.1-1.2
INFO:Controller:event loop policy: None
INFO:LegacyRPCDaemon:daemon #1 at 127.0.0.1:10555/ (current)
INFO:BlockProcessor:switching current directory to /root/.electrumx
INFO:BlockProcessor:using leveldb for DB backend
INFO:BlockProcessor:created new database
INFO:BlockProcessor:creating metadata directory
INFO:History:flush count: 0
INFO:History:history DB version: 0
INFO:BlockProcessor:DB version: 6
INFO:BlockProcessor:coin: Geysercoin
INFO:BlockProcessor:network: mainnet
INFO:BlockProcessor:height: -1
INFO:BlockProcessor:tip: 0000000000000000000000000000000000000000000000000000000000000000
INFO:BlockProcessor:tx count: 0
INFO:BlockProcessor:sync time so far: 00s
INFO:BlockProcessor:reorg limit is 1,000 blocks
INFO:BlockProcessor:flushing DB cache at 1,200 MB
INFO:Controller:RPC server listening on localhost:8000
INFO:Prefetcher:catching up to daemon height 463,366 (463,367 blocks behind)
ERROR:Controller:uncaught task exception: genesis block has hash 5ffc757b24313051961160abdebe847cb3df41dad78e471a388086ec7cfa4465 expected 00000f8c28f5ed6b3097af0be5d00f8cc240e5715322ee332d05722b539c3019
Traceback (most recent call last):
  File "/root/electrumx/server/controller.py", line 192, in check_task_exception
    task.result()
  File "/root/electrumx/server/block_processor.py", line 49, in main_loop
    if not await self._prefetch_blocks():
  File "/root/electrumx/server/block_processor.py", line 112, in _prefetch_blocks
    blocks[0] = self.bp.coin.genesis_block(blocks[0])
  File "/root/electrumx/lib/coins.py", line 126, in genesis_block
    .format(header_hex_hash, cls.GENESIS_HASH))
lib.coins.CoinError: genesis block has hash 5ffc757b24313051961160abdebe847cb3df41dad78e471a388086ec7cfa4465 expected 00000f8c28f5ed6b3097af0be5d00f8cc240e5715322ee332d05722b539c3019
```
The original genesis block of my coin is `00000f8c28f5ed6b3097af0be5d00f8cc240e5715322ee332d05722b539c3019` but the electrumx server gives `5ffc757b24313051961160abdebe847cb3df41dad78e471a388086ec7cfa4465` 

So I did change the genesis block to `5ffc757b24313051961160abdebe847cb3df41dad78e471a388086ec7cfa4465` & I got the following out put,

```
INFO:root:ElectrumX server starting
WARNING:Env:lowered maximum sessions from 1,000 to 674 because your open file limit is 1,024
INFO:Controller:software version: ElectrumX 1.4.4p2
INFO:Controller:supported protocol versions: 1.1-1.2
INFO:Controller:event loop policy: None
INFO:LegacyRPCDaemon:daemon #1 at 127.0.0.1:10555/ (current)
INFO:BlockProcessor:switching current directory to /root/.electrumx
INFO:BlockProcessor:using leveldb for DB backend
    SHORTNAME = "GSR"
INFO:BlockProcessor:created new database
INFO:BlockProcessor:creating metadata directory
INFO:History:flush count: 0
INFO:History:history DB version: 0
INFO:BlockProcessor:DB version: 6
INFO:BlockProcessor:coin: Geysercoin
INFO:BlockProcessor:network: mainnet
INFO:BlockProcessor:height: -1
INFO:BlockProcessor:tip: 0000000000000000000000000000000000000000000000000000000000000000
INFO:BlockProcessor:tx count: 0
INFO:BlockProcessor:sync time so far: 00s
INFO:BlockProcessor:reorg limit is 1,000 blocks
INFO:BlockProcessor:flushing DB cache at 1,200 MB
INFO:Controller:RPC server listening on localhost:8000
INFO:Prefetcher:catching up to daemon height 463,365 (463,366 blocks behind)
INFO:Prefetcher:verified genesis block with hash 00000f8c28f5ed6b3097af0be5d00f8cc240e5715322ee332d05722b539c3019
WARNING:BlockProcessor:daemon blocks do not form a chain; resetting the prefetcher
```
Electrumx server gives the right genesis block using `5ffc757b24313051961160abdebe847cb3df41dad78e471a388086ec7cfa4465` it gives `00000f8c28f5ed6b3097af0be5d00f8cc240e5715322ee332d05722b539c3019` I don't know how? But I got new error `WARNING:BlockProcessor:daemon blocks do not form a chain; resetting the prefetcher`
It keeps repeating  this message.

Do you how to solve this problem?

**Comment by knkrth** [comment]
I'm sorry my mistake adding `ScryptMixin` on the `class <My_Coin>(ScryptMixin, Coin)` fix the problem. Everything woks fine.
