### ISSUE TITLE
Corrupted db? AttributeError: 'History' object has no attribute 'db'

### ISSUE THREAD

**Issue by sangaman** [kyuupichan/electrumx#485]
I started syncing electrumx on a raspi3, got through at least ~250k blocks . After a little less than a day of syncing, the rpi became unresponsive/inaccessible via SSH so I hard rebooted it. Now when I try to restart electrumx, the service immediately stops and here's the log output. Any way I can salvage this or do I just need to delete the `db` folder and start the sync over?

'''shell
INFO:root:ElectrumX server starting
INFO:Controller:software version: ElectrumX 1.4.4p2
INFO:Controller:supported protocol versions: 1.1-1.2
INFO:Controller:event loop policy: None
INFO:Daemon:daemon #1 at 127.0.0.1:8332/ (current)
INFO:BlockProcessor:switching current directory to /mnt/hdd/.electrumx/db
INFO:BlockProcessor:using leveldb for DB backend
INFO:BlockProcessor:opened DB for serving
INFO:BlockProcessor:closing DB to re-open for sync
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.4.4p2-py3.6.egg/EGG-INFO/scripts/electrumx_server.py", line 25, in main
  File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.4.4p2-py3.6.egg/server/controller.py", line 94, in __init__
    self.bp = self.coin.BLOCK_PROCESSOR(env, self, self.daemon)
  File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.4.4p2-py3.6.egg/server/block_processor.py", line 143, in __init__
    super().__init__(env)
  File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.4.4p2-py3.6.egg/server/db.py", line 66, in __init__
    self.open_dbs()
  File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.4.4p2-py3.6.egg/server/db.py", line 110, in open_dbs
    self.history.close_db()
  File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.4.4p2-py3.6.egg/server/history.py", line 41, in close_db
    self.db.close()
AttributeError: 'History' object has no attribute 'db'
CRITICAL:root:ElectrumX server terminated abnormally
'''

**Comment by sangaman** [comment]
That seemed to do the trick! Back up and resuming the sync. Thanks.

**Comment by aitorp6** [comment]
@sangaman How did you fixed this issue? How do you resume the sync? Thanks

**Comment by sangaman** [comment]
I pulled the latest code from master, reinstalled, and restarted electrumx. It started working after that.
