### ISSUE TITLE
AssertionError while first run

### ISSUE THREAD

**Issue by racer2060** [kyuupichan/electrumx#488]
I think electrumX is awesome software! 
But I am facing issue while developing it for [this](https://github.com/motocoin-dev/motocoin) altcoin.
Actually I got AssertionError and I am not sure what happened. Quick look tells me that altcoin source code is just old Litecoin source code (at least in part of **CTransaction** class, **CTxIn**, **CTxOut**). So it has to work with no issue. However it does not.
What I a want is an advice about the cause.
This is coins.py class for my altcoin:
```
class Motocoin(BitcoinMixin, Coin):
    NAME = "Motocoin"
    SHORTNAME = "MOTO"
    NET = "mainnet"
    P2PKH_VERBYTE = bytes.fromhex("0BB6")
    
    P2SH_VERBYTES = [bytes.fromhex("05")]
    WIF_BYTE = bytes.fromhex("8BB6")
    
    # c3c56a31568d82f1f3968c8ac6cc4b3c8c03c930520152fef9be85332380b53a
    GENESIS_HASH = ('c3c56a31568d82f1f3968c8ac6cc4b3c'
                    '8c03c930520152fef9be85332380b53a')
    TX_COUNT = 120000
    TX_COUNT_HEIGHT = 2481000
    TX_PER_BLOCK = 2
    RPC_PORT = 4562 
```

I have also modified _read_nbytes(self,n) to get useful information:
```
    def _read_nbytes(self, n):
        cursor = self.cursor
        print("Log info/ cursor1:", self.cursor)
        self.cursor = end = cursor + n
        print("Log info/ cursor:", self.cursor)
        print("Log info/ end:", end)
        print("Log info/ self.binary_length:", self.binary_length)
        assert self.binary_length >= end
        return self.binary[cursor:end]
```
This is electrumX log:
```
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]: INFO:root:ElectrumX server starting
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]: INFO:Controller:software version: ElectrumX 1.4.4p2
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]: INFO:Controller:aiorpcX version: 0.5.6
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]: INFO:Controller:supported protocol versions: 1.1-1.2
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]: INFO:Controller:event loop policy: None
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]: INFO:Daemon:daemon #1 at 127.0.0.1:4562/ (current)
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]: INFO:BlockProcessor:switching current directory to /home/electrumx/db_directory
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]: INFO:BlockProcessor:using leveldb for DB backend
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]: INFO:BlockProcessor:opened DB for serving
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]: INFO:BlockProcessor:closing DB to re-open for sync
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]: INFO:BlockProcessor:opened DB for sync
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]: INFO:History:flush count: 0
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]: INFO:History:history DB version: 0
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]: INFO:BlockProcessor:DB version: 6
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]: INFO:BlockProcessor:coin: Motocoin
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]: INFO:BlockProcessor:network: mainnet
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]: INFO:BlockProcessor:height: -1
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]: INFO:BlockProcessor:tip: 0000000000000000000000000000000000000000000000000000000000000000
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]: INFO:BlockProcessor:tx count: 0
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]: INFO:BlockProcessor:sync time so far: 00s
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]: INFO:BlockProcessor:reorg limit is 200 blocks
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]: INFO:BlockProcessor:flushing DB cache at 1,200 MB
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]: INFO:Controller:RPC server listening on localhost:8000
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]: INFO:Prefetcher:catching up to daemon height 2,490,997 (2,490,998 blocks behind)
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]: INFO:Prefetcher:verified genesis block with hash c3c56a31568d82f1f3968c8ac6cc4b3c8c03c930520152fef9be85332380b53a
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]: ERROR:Controller:uncaught task exception:
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]: Traceback (most recent call last):
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.4.4p2-py3.6.egg/server/controller.py", line 196, in check_task_exception
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]:     task.result()
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.4.4p2-py3.6.egg/server/block_processor.py", line 203, in main_loop
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]:     await task()
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.4.4p2-py3.6.egg/server/block_processor.py", line 240, in check_and_advance_blocks
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]:     for n, raw_block in enumerate(raw_blocks)]
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.4.4p2-py3.6.egg/server/block_processor.py", line 240, in <listcomp>
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]:     for n, raw_block in enumerate(raw_blocks)]
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.4.4p2-py3.6.egg/lib/coins.py", line 275, in block
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]:     txs = cls.DESERIALIZER(raw_block, start=len(header)).read_tx_block()
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.4.4p2-py3.6.egg/lib/tx.py", line 113, in read_tx_block
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]:     return [read() for _ in range(self._read_varint())]
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.4.4p2-py3.6.egg/lib/tx.py", line 113, in <listcomp>
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]:     return [read() for _ in range(self._read_varint())]
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.4.4p2-py3.6.egg/lib/tx.py", line 103, in read_tx_and_hash
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]:     return self.read_tx(), double_sha256(self.binary[start:self.cursor])
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.4.4p2-py3.6.egg/lib/tx.py", line 91, in read_tx
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]:     self._read_inputs(),    # inputs
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.4.4p2-py3.6.egg/lib/tx.py", line 117, in _read_inputs
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]:     return [read_input() for i in range(self._read_varint())]
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.4.4p2-py3.6.egg/lib/tx.py", line 117, in <listcomp>
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]:     return [read_input() for i in range(self._read_varint())]
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.4.4p2-py3.6.egg/lib/tx.py", line 123, in _read_input
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]:     self._read_varbytes(),   # script
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.4.4p2-py3.6.egg/lib/tx.py", line 153, in _read_varbytes
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]:     return self._read_nbytes(self._read_varint())
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-ElectrumX.1.4.4p2-py3.6.egg/lib/tx.py", line 149, in _read_nbytes
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]:     assert self.binary_length >= end
Jun 06 00:06:52 s052d7392 electrumx_server.py[6741]: AssertionError
Jun 06 00:06:58 s052d7392 electrumx_server.py[6741]: WARNING:Controller:received SIGTERM signal, initiating shutdown
Jun 06 00:06:58 s052d7392 electrumx_server.py[6741]: INFO:Controller:shutting down
Jun 06 00:06:58 s052d7392 electrumx_server.py[6741]: INFO:Controller:closing down RPC listening servers
Jun 06 00:06:58 s052d7392 electrumx_server.py[6741]: INFO:Controller:shutdown complete
Jun 06 00:06:58 s052d7392 electrumx_server.py[6741]: INFO:root:ElectrumX server terminated normally
Jun 06 00:06:58 s052d7392 electrumx_server.py[6741]: Log info/ cursor1: 86
Jun 06 00:06:58 s052d7392 electrumx_server.py[6741]: Log info/ cursor: 118
Jun 06 00:06:58 s052d7392 electrumx_server.py[6741]: Log info/ end: 118
Jun 06 00:06:58 s052d7392 electrumx_server.py[6741]: Log info/ self.binary_length: 265
Jun 06 00:06:58 s052d7392 electrumx_server.py[6741]: Log info/ cursor1: 123
Jun 06 00:06:58 s052d7392 electrumx_server.py[6741]: Log info/ cursor: 359
Jun 06 00:06:58 s052d7392 electrumx_server.py[6741]: Log info/ end: 359
Jun 06 00:06:58 s052d7392 electrumx_server.py[6741]: Log info/ self.binary_length: 265
```

**Comment by kyuupichan** [comment]
If your coin does Segwit you need to do segwit like bitcoinsegwit or litecoin does.

**Comment by racer2060** [comment]
This is not my coin. It does not. As I understand it is based on old Litecoin sources with no segwit compability.

**Comment by kyuupichan** [comment]
OK; then you need to understand the coin and figure out what is going wrong.

**Comment by racer2060** [comment]
@kyuupichan This is first time I do ElectrumX integration for coin. Can you give me suggestion where to look in altcoin source code except **CTransaction** class, **CTxIn**, **CTxOut**?
