### ISSUE TITLE
NameError: name 'height' is not defined

### ISSUE THREAD

**Issue by Talkless** [kyuupichan/electrumx#519]
ElectrumX 1.4.3,
Python 3.6.6 (local build)
Debian 9 Stretch
```
# /opt/python3.6/bin/pip3 freeze
aiohttp==3.3.2
aiorpcX==0.5.6
async-timeout==3.0.0
attrs==18.1.0
chardet==3.0.4
electrumx===ElectrumX.1.4.3
idna==2.7
idna-ssl==1.0.1
multidict==4.3.1
plyvel==0.9
pylru==1.1.0
yarl==1.2.6
```

Got this exception after (presumably ?) finished syncing:
```
Jul 11 10:30:30 odroid-hc1 electrumx_server.py[18601]: INFO:Prefetcher:new block height 531,447 hash 00000000000000000033236728cb97744f76d2c7f06c085c015e25af8d5581f3
Jul 11 10:30:40 odroid-hc1 electrumx_server.py[18601]: INFO:BlockProcessor:flushed history in 13.3s for 600,124 addrs
Jul 11 10:31:18 odroid-hc1 electrumx_server.py[18601]: INFO:BlockProcessor:flushed 763 blocks with 955,905 txs, 903,064 UTXO adds, 1,002,694 spends in 37.6s, committing...
Jul 11 10:31:49 odroid-hc1 electrumx_server.py[18601]: INFO:BlockProcessor:flush #953 took 82.5s.  Height 531,443 txs: 327,390,883
Jul 11 10:31:49 odroid-hc1 electrumx_server.py[18601]: INFO:BlockProcessor:tx/sec since genesis: 81, since last flush: 48
Jul 11 10:31:49 odroid-hc1 electrumx_server.py[18601]: INFO:BlockProcessor:sync time: 46d 10h 25m  ETA: 02m 30s
Jul 11 10:31:49 odroid-hc1 electrumx_server.py[18601]: ERROR:Controller:uncaught task exception: name 'height' is not defined
Jul 11 10:31:49 odroid-hc1 electrumx_server.py[18601]: Traceback (most recent call last):
Jul 11 10:31:49 odroid-hc1 electrumx_server.py[18601]:   File "/opt/python3.6/lib/python3.6/site-packages/electrumx-ElectrumX.1.4.3-py3.6.egg/server/controller.py", line 192, in check_task_exception
Jul 11 10:31:49 odroid-hc1 electrumx_server.py[18601]:     task.result()
Jul 11 10:31:49 odroid-hc1 electrumx_server.py[18601]:   File "/opt/python3.6/lib/python3.6/site-packages/electrumx-ElectrumX.1.4.3-py3.6.egg/server/block_processor.py", line 206, in main_loop
Jul 11 10:31:49 odroid-hc1 electrumx_server.py[18601]:     await task()
Jul 11 10:31:49 odroid-hc1 electrumx_server.py[18601]:   File "/opt/python3.6/lib/python3.6/site-packages/electrumx-ElectrumX.1.4.3-py3.6.egg/server/block_processor.py", line 223, in first_caught_up
Jul 11 10:31:49 odroid-hc1 electrumx_server.py[18601]:     self.logger.info(f'{self.controller.VERSION} synced to '
Jul 11 10:31:49 odroid-hc1 electrumx_server.py[18601]: NameError: name 'height' is not defined
Jul 11 10:36:40 odroid-hc1 electrumx_server.py[18601]: INFO:Prefetcher:new block height 531,448 hash 000000000000000000261252b795d3d8f6f3872f2eef3a5f9e3f966676d15dca
Jul 11 11:02:30 odroid-hc1 electrumx_server.py[18601]: INFO:Prefetcher:new block height 531,449 hash 0000000000000000002dbd0db1ce5532ca200f8f054b4395376a5c82e9d05310

```

**Comment by kyuupichan** [comment]
This is fixed in git
