### ISSUE TITLE
Error during chain reorg

### ISSUE THREAD

**Issue by awam** [kyuupichan/electrumx#532]
Hello. At the time of chain reorg, I am getting the following error:

ERROR:Tasks:uncaught task exception: unsupported operand type(s) for +: 'int' and 'NoneType'
Jul 23 20:52:11  electrumx_server[9020]: Traceback (most recent call last):
Jul 23 20:52:11  electrumx_server[9020]:   File "/usr/local/lib/python3.6/dist-packages/electrumX-1.6-py3.6.egg/electrumx/lib/tasks.py", line 59, in _check_task_exception
Jul 23 20:52:11  electrumx_server[9020]:     task.result()
Jul 23 20:52:11  electrumx_server[9020]:   File "/usr/local/lib/python3.6/dist-packages/electrumX-1.6-py3.6.egg/electrumx/server/block_processor.py", line 758, in _process_queue
Jul 23 20:52:11  electrumx_server[9020]:     await self.check_and_advance_blocks(raw_blocks, first)
Jul 23 20:52:11  electrumx_server[9020]:   File "/usr/local/lib/python3.6/dist-packages/electrumX-1.6-py3.6.egg/electrumx/server/block_processor.py", line 233, in check_and_advance_blocks
Jul 23 20:52:11  electrumx_server[9020]:     await self.reorg_chain()
Jul 23 20:52:11  electrumx_server[9020]:   File "/usr/local/lib/python3.6/dist-packages/electrumX-1.6-py3.6.egg/electrumx/server/block_processor.py", line 267, in reorg_chain
Jul 23 20:52:11  electrumx_server[9020]:     last = start + count - 1
Jul 23 20:52:11  electrumx_server[9020]: TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

Any hint or suggestion is really appreciated. Please let me know if any other info is required related to the config or coin.

**Comment by awam** [comment]
It's the recent version i.e git cloned. Following is the coin class:

class Nitrous(BitcoinMixin, Coin):
    NAME = "Nitrous"
    SHORTNAME = "N2O"
    NET = "mainnet"
    P2PKH_VERBYTE = bytes.fromhex("35")
    P2SH_VERBYTE = [bytes.fromhex("70")]
    WIF_BYTE =  bytes.fromhex("C1")
    GENESIS_HASH = ('00000e46b1276e3db5197e5935800cd2'
                    '2761c1321e06e841c164f205b9497fbe')
    TX_COUNT = 1000
    TX_COUNT_HEIGHT = 10000
    TX_PER_BLOCK = 1
    RPC_PORT = 32324

    @classmethod
    def header_hash(cls, header):
        '''Given a header return the hash.'''
        import quark_hash
        return quark_hash.getPoWHash(header)

**Comment by awam** [comment]
Thank you.

**Comment by shsmith** [comment]
I pulled HEAD a few minutes ago and on my two BitcoinSegwit mainnet servers I got this traceback:
```
Jul 25 08:54:46 electrumd electrumx_server[60946]: INFO:BlockProcessor:backup flush #42,208 took 5.1s.  Height 533,546 txs: 330,312,908
Jul 25 08:54:46 electrumd electrumx_server[60946]: INFO:Prefetcher:catching up to daemon height 533,625 (79 blocks behind)
Jul 25 08:54:46 electrumd electrumx_server[60946]: ERROR:Tasks:uncaught task exception: list index out of range
Jul 25 08:54:46 electrumd electrumx_server[60946]: Traceback (most recent call last):
Jul 25 08:54:46 electrumd electrumx_server[60946]:   File "/usr/local/lib/python3.6/dist-packages/electrumX-1.7-py3.6.egg/electrumx/lib/tasks.py", line 60, in _check_task
Jul 25 08:54:46 electrumd electrumx_server[60946]:     task.result()
Jul 25 08:54:46 electrumd electrumx_server[60946]:   File "/usr/local/lib/python3.6/dist-packages/electrumX-1.7-py3.6.egg/electrumx/server/block_processor.py", line 766,
Jul 25 08:54:46 electrumd electrumx_server[60946]:     await self.check_and_advance_blocks(blocks)
Jul 25 08:54:46 electrumd electrumx_server[60946]:   File "/usr/local/lib/python3.6/dist-packages/electrumX-1.7-py3.6.egg/electrumx/server/block_processor.py", line 224,
Jul 25 08:54:46 electrumd electrumx_server[60946]:     elif hprevs[0] != chain[0]:
Jul 25 08:54:46 electrumd electrumx_server[60946]: IndexError: list index out of range
```
When I restarted the service a second time it seemed ok, though I worry I may have database corruption due to the interrupted reorg processing.

**Comment by kyuupichan** [comment]
@shsmith thanks for the info.  To be sure you're OK please do:

electrumx_rpc reorg N

where N is current height - 533545

If unsure, add a couple.  You'll need to do it before N exceeds 200

**Comment by kyuupichan** [comment]
@shsmith I believe that is now fixed
