### ISSUE TITLE
'async for' received an object from __aiter__ that does not implement __anext__: coroutine

### ISSUE THREAD

**Issue by shsmith** [kyuupichan/electrumx#537]
Possibly a missing setup dependency?
```
Jul 28 05:33:49 abc1 systemd[1]: Started Electrumx.
Jul 28 05:33:49 abc1 electrumx_server[86958]: INFO:Controller:Python version: 3.7.0b3 (default, Mar 30 2018, 04:35:22)
Jul 28 05:33:49 abc1 electrumx_server[86958]: [GCC 7.3.0]
Jul 28 05:33:49 abc1 electrumx_server[86958]: INFO:Controller:software version: ElectrumX 1.7.1
Jul 28 05:33:49 abc1 electrumx_server[86958]: INFO:Controller:aiorpcX version: 0.5.8
Jul 28 05:33:49 abc1 electrumx_server[86958]: INFO:Controller:supported protocol versions: 1.1-1.4
Jul 28 05:33:49 abc1 electrumx_server[86958]: INFO:Controller:event loop policy: None
Jul 28 05:33:49 abc1 electrumx_server[86958]: INFO:Controller:reorg limit is 200 blocks
Jul 28 05:33:49 abc1 electrumx_server[86958]: INFO:Daemon:daemon #1 at 127.0.0.1:8332/ (current)
Jul 28 05:33:49 abc1 electrumx_server[86958]: INFO:BlockProcessor:switching current directory to /home/shsmith/.electrumx/db
Jul 28 05:33:49 abc1 electrumx_server[86958]: INFO:BlockProcessor:using leveldb for DB backend
Jul 28 05:33:49 abc1 electrumx_server[86958]: INFO:BlockProcessor:opened UTXO DB (for sync: True)
Jul 28 05:33:49 abc1 electrumx_server[86958]: INFO:BlockProcessor:DB version: 6
Jul 28 05:33:49 abc1 electrumx_server[86958]: INFO:BlockProcessor:coin: BitcoinCash
Jul 28 05:33:49 abc1 electrumx_server[86958]: INFO:BlockProcessor:network: mainnet
Jul 28 05:33:49 abc1 electrumx_server[86958]: INFO:BlockProcessor:height: 540,935
Jul 28 05:33:49 abc1 electrumx_server[86958]: INFO:BlockProcessor:tip: 0000000000000000010808aa29317f84d6b4ee269d79e701a9027e215a6f1ceb
Jul 28 05:33:49 abc1 electrumx_server[86958]: INFO:BlockProcessor:tx count: 251,137,166
Jul 28 05:33:49 abc1 electrumx_server[86958]: INFO:History:history DB version: 0
Jul 28 05:33:49 abc1 electrumx_server[86958]: INFO:History:flush count: 33,557
Jul 28 05:33:49 abc1 electrumx_server[86958]: INFO:BlockProcessor:deleted 205 stale undo entries
Jul 28 05:33:49 abc1 electrumx_server[86958]: INFO:BlockProcessor:flushing DB cache at 128 MB
Jul 28 05:33:49 abc1 electrumx_server[86958]: INFO:SessionManager:RPC server listening on localhost:8000
Jul 28 05:33:49 abc1 electrumx_server[86958]: INFO:BlockProcessor:caught up to height 540935
Jul 28 05:33:49 abc1 electrumx_server[86958]: INFO:BlockProcessor:closing DBs to re-open for serving
Jul 28 05:33:50 abc1 electrumx_server[86958]: INFO:BlockProcessor:opened UTXO DB (for sync: False)
Jul 28 05:33:50 abc1 electrumx_server[86958]: INFO:BlockProcessor:DB version: 6
Jul 28 05:33:50 abc1 electrumx_server[86958]: INFO:BlockProcessor:coin: BitcoinCash
Jul 28 05:33:50 abc1 electrumx_server[86958]: INFO:BlockProcessor:network: mainnet
Jul 28 05:33:50 abc1 electrumx_server[86958]: INFO:BlockProcessor:height: 540,935
Jul 28 05:33:50 abc1 electrumx_server[86958]: INFO:BlockProcessor:tip: 0000000000000000010808aa29317f84d6b4ee269d79e701a9027e215a6f1ceb
Jul 28 05:33:50 abc1 electrumx_server[86958]: INFO:BlockProcessor:tx count: 251,137,166
Jul 28 05:33:50 abc1 electrumx_server[86958]: INFO:History:history DB version: 0
Jul 28 05:33:50 abc1 electrumx_server[86958]: INFO:History:flush count: 33,557
Jul 28 05:33:53 abc1 electrumx_server[86958]: INFO:BlockProcessor:populated header merkle cache
Jul 28 05:33:53 abc1 electrumx_server[86958]: INFO:MemPool:beginning processing of daemon mempool.  This can take some time...
Jul 28 05:33:53 abc1 electrumx_server[86958]: INFO:Prefetcher:caught up to daemon height 540,935
Jul 28 05:33:53 abc1 electrumx_server[86958]: /usr/local/lib/python3.7/dist-packages/electrumX-1.7.1-py3.7.egg/electrumx/server/mempool.py:174: RuntimeWarning: coroutine 'TaskGroup.__aiter__' was never awaited
Jul 28 05:33:53 abc1 electrumx_server[86958]: ERROR:TaskGroup:task crashed: <Task finished coro=<MemPool._refresh_hashes() done, defined at /usr/local/lib/python3.7/dist-packages/electrumX-1.7.1-py3.7.egg/electrumx/server/mempool.py:130> exception=TypeError("'async for' received an object from __aiter__ that does not implement __anext__: coroutine")>
Jul 28 05:33:53 abc1 electrumx_server[86958]: Traceback (most recent call last):
Jul 28 05:33:53 abc1 electrumx_server[86958]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcX-0.5.8-py3.7.egg/aiorpcx/curio.py", line 138, in _on_done
Jul 28 05:33:53 abc1 electrumx_server[86958]:     task.result()
Jul 28 05:33:53 abc1 electrumx_server[86958]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.7.1-py3.7.egg/electrumx/server/mempool.py", line 140, in _refresh_hashes
Jul 28 05:33:53 abc1 electrumx_server[86958]:     touched = await self._process_mempool(hashes)
Jul 28 05:33:53 abc1 electrumx_server[86958]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.7.1-py3.7.egg/electrumx/server/mempool.py", line 174, in _process_mempool
Jul 28 05:33:53 abc1 electrumx_server[86958]:     async for task in group:
Jul 28 05:33:53 abc1 electrumx_server[86958]: TypeError: 'async for' received an object from __aiter__ that does not implement __anext__: coroutine
Jul 28 05:34:13 abc1 electrumx_server[86958]: INFO:Prefetcher:new block height 540,936 hash 0000000000000000016c7077bfa13a6ca0a19e80e6b52fe6d4120a5df10cded1
Jul 28 05:34:13 abc1 electrumx_server[86958]: INFO:BlockProcessor:flush #33,558 took 0.0s.  Height 540,936 txs: 251,137,388
Jul 28 05:34:13 abc1 electrumx_server[86958]: INFO:BlockProcessor:processed 1 block in 0.4s
Jul 28 05:35:02 abc1 electrumx_server[86958]: INFO:LocalRPC:[0] RPC [::1]:48804, 1 total
Jul 28 05:35:03 abc1 electrumx_server[86958]: INFO:LocalRPC:[1] RPC [::1]:48806, 1 total
Jul 28 05:35:03 abc1 electrumx_server[86958]: INFO:LocalRPC:[2] RPC [::1]:48812, 1 total

```

**Comment by shsmith** [comment]
This seems specific to Python 3.7. On two other instances still using Python 3.6 I did not get this exception.

**Comment by kyuupichan** [comment]
Hmm I've not seen this and I'm on 3.6.

**Comment by kyuupichan** [comment]
Does this happen reliably?  It seems you were just on startup there.

**Comment by kyuupichan** [comment]
The only instance of __aiter__ in electrumx and aiorpcx codebases is aiorpcx/curio.py, and it clearly has an __anext__.  Can you please recheck there is not some package confusion here with obsolete packages?  pip3 seems to have all kinds of historical crud unless you clean it out manually.

**Comment by shsmith** [comment]
Yes, it happens every time I launch under Python 3.7.
Does not seem to verify any peers, though the exception seems related to mempool.
Here are the full logs from my attempts: https://paste.ee/p/CoZ2Q

**Comment by shsmith** [comment]
Here are all the python3.7 packages I have:
```
shsmith@abc1:/usr/local/lib/python3.7/dist-packages$ ls -l
total 904
drwxr-sr-x 4 root staff   4096 Jul 13 21:28 aiohttp-3.3.2-py3.7-linux-x86_64.egg
drwxr-sr-x 4 root staff   4096 Jul 13 21:27 aiorpcX-0.5.6-py3.7.egg
drwxr-sr-x 4 root staff   4096 Jul 28 05:33 aiorpcX-0.5.8-py3.7.egg
drwxr-sr-x 4 root staff   4096 Jul 13 21:28 async_timeout-3.0.0-py3.7.egg
-rw-r--r-- 1 root staff    262 Jul 28 05:58 easy-install.pth
-rw-r--r-- 1 root staff 212992 Jul 15 06:40 electrumX-1.5.2-py3.7.egg
-rw-r--r-- 1 root staff 220552 Jul 25 04:45 electrumX-1.6-py3.7.egg
-rw-r--r-- 1 root staff 217462 Jul 28 05:56 electrumX-1.7.1-py3.7.egg
-rw-r--r-- 1 root staff 220883 Jul 28 05:58 electrumX-1.7-py3.7.egg
drwxr-sr-x 4 root staff   4096 Jul 13 21:28 multidict-4.3.1-py3.7-linux-x86_64.egg
drwxr-sr-x 4 root staff   4096 Jul 13 21:27 plyvel-1.0.4-py3.7-linux-x86_64.egg
-rw-r--r-- 1 root root   13092 Jul 13 21:27 pylru-1.1.0-py3.7.egg
drwxr-sr-x 4 root staff   4096 Jul 13 21:28 yarl-1.2.6-py3.7-linux-x86_64.egg

```
