### ISSUE TITLE
aiorpcx.curio.TaskGroupError: TaskGroupError(BadPeerError)

### ISSUE THREAD

**Issue by shsmith** [kyuupichan/electrumx#538]
1.7.1 on Python 3.6 seemed ok for a while, but crashed after a couple of hours.
```
Jul 28 05:49:51 electrumd systemd[1]: Started Electrumx.
Jul 28 05:49:51 electrumd electrumx_server[63389]: INFO:Controller:Python version: 3.6.5 (default, May  3 2018, 10:08:28)
Jul 28 05:49:51 electrumd electrumx_server[63389]: [GCC 5.4.0 20160609]
Jul 28 05:49:52 electrumd electrumx_server[63389]: INFO:Controller:software version: ElectrumX 1.7.1
Jul 28 05:49:52 electrumd electrumx_server[63389]: INFO:Controller:aiorpcX version: 0.5.8
...
Jul 28 07:55:02 electrumd electrumx_server[63389]: INFO:LocalRPC:[10340] RPC [::1]:41364, 236 total
Jul 28 07:55:02 electrumd electrumx_server[63389]: INFO:LocalRPC:[10341] RPC [::1]:41366, 236 total
Jul 28 07:55:03 electrumd electrumx_server[63389]: INFO:ElectrumX:[10342] SSL 69.140.183.92:48126, 236 total
Jul 28 07:55:03 electrumd electrumx_server[63389]: INFO:PeerManager:accepted new peer bitnode.pw from electrum.achow101.com
Jul 28 07:55:03 electrumd electrumx_server[63389]: INFO:PeerManager:accepted new peer 207.154.223.80 from electrum.achow101.com
Jul 28 07:55:03 electrumd electrumx_server[63389]: ERROR:TaskGroup:task crashed: <Task finished coro=<PeerManager._send_headers_subscribe() done, defined at /usr/local/lib/python3.6/dist-packages/electrumX-1.7.1-py3.6.egg/electrumx/server/peers.py:310> exception=BadPeerError('bad height 533,547 (ours: 534,103)',)>
Jul 28 07:55:03 electrumd electrumx_server[63389]: Traceback (most recent call last):
Jul 28 07:55:03 electrumd electrumx_server[63389]:   File "/usr/local/lib/python3.6/dist-packages/aiorpcX-0.5.8-py3.6.egg/aiorpcx/curio.py", line 138, in _on_done
Jul 28 07:55:03 electrumd electrumx_server[63389]:     task.result()
Jul 28 07:55:03 electrumd electrumx_server[63389]:   File "/usr/local/lib/python3.6/dist-packages/electrumX-1.7.1-py3.6.egg/electrumx/server/peers.py", line 323, in _send_headers_subscribe
Jul 28 07:55:03 electrumd electrumx_server[63389]:     raise BadPeerError(f'bad height {their_height:,d} '
Jul 28 07:55:03 electrumd electrumx_server[63389]: electrumx.server.peers.BadPeerError: bad height 533,547 (ours: 534,103)
Jul 28 07:55:03 electrumd electrumx_server[63389]: ERROR:TaskGroup:task crashed: <Task finished coro=<PeerManager._monitor_peer() done, defined at /usr/local/lib/python3.6/dist-packages/electrumX-1.7.1-py3.6.egg/electrumx/server/peers.py:185> exception=TaskGroupError([<Task finished coro=<PeerManager._send_headers_subscribe() done, defined at /usr/local/lib/python3.6/dist-packages/electrumX-1.7.1-py3.6.egg/electrumx/server/peers.py:310> exception=BadPeerError('bad height 533,547 (ours: 534,103)',)>],)>
Jul 28 07:55:03 electrumd electrumx_server[63389]: Traceback (most recent call last):
Jul 28 07:55:03 electrumd electrumx_server[63389]:   File "/usr/local/lib/python3.6/dist-packages/aiorpcX-0.5.8-py3.6.egg/aiorpcx/curio.py", line 138, in _on_done
Jul 28 07:55:03 electrumd electrumx_server[63389]:     task.result()
Jul 28 07:55:03 electrumd electrumx_server[63389]:   File "/usr/local/lib/python3.6/dist-packages/electrumX-1.7.1-py3.6.egg/electrumx/server/peers.py", line 188, in _monitor_peer
Jul 28 07:55:03 electrumd electrumx_server[63389]:     if await self._should_drop_peer(peer):
Jul 28 07:55:03 electrumd electrumx_server[63389]:   File "/usr/local/lib/python3.6/dist-packages/electrumX-1.7.1-py3.6.egg/electrumx/server/peers.py", line 227, in _should_drop_peer
Jul 28 07:55:03 electrumd electrumx_server[63389]:     await self._verify_peer(session, peer)
Jul 28 07:55:03 electrumd electrumx_server[63389]:   File "/usr/local/lib/python3.6/dist-packages/electrumX-1.7.1-py3.6.egg/electrumx/server/peers.py", line 308, in _verify_peer
Jul 28 07:55:03 electrumd electrumx_server[63389]:     timeout))
Jul 28 07:55:03 electrumd electrumx_server[63389]:   File "/usr/local/lib/python3.6/dist-packages/aiorpcX-0.5.8-py3.6.egg/aiorpcx/curio.py", line 254, in __aexit__
Jul 28 07:55:03 electrumd electrumx_server[63389]:     await self.join(wait=self._wait)
Jul 28 07:55:03 electrumd electrumx_server[63389]:   File "/usr/local/lib/python3.6/dist-packages/aiorpcX-0.5.8-py3.6.egg/aiorpcx/curio.py", line 228, in join
Jul 28 07:55:03 electrumd electrumx_server[63389]:     raise TaskGroupError(bad_tasks)
Jul 28 07:55:03 electrumd electrumx_server[63389]: aiorpcx.curio.TaskGroupError: TaskGroupError(BadPeerError)
Jul 28 07:55:03 electrumd electrumx_server[63389]: INFO:SessionManager:closing down RPC, TCP, SSL listening servers
Jul 28 07:55:03 electrumd electrumx_server[63389]: INFO:ElectrumX:[9701] disconnected.  Sent 1,919,294 bytes in 31 messages
Jul 28 07:55:03 electrumd electrumx_server[63389]: INFO:ElectrumX:[2447] disconnected whilst throttled.  Sent 2,473,293 bytes in 50,173 messages
Jul 28 07:55:03 electrumd electrumx_server[63389]: INFO:ElectrumX:[10343] SSL 185.9.19.107:58078, 1 total
Jul 28 07:55:03 electrumd electrumx_server[63389]: ERROR:TaskGroup:task crashed: <Task finished coro=<SessionManager.serve() done, defined at /usr/local/lib/python3.6/dist-packages/electrumX-1.7.1-py3.6.egg/electrumx/server/session.py:398> exception=TaskGroupError([<Task finished coro=<PeerManager._monitor_peer() done, defined at /usr/local/lib/python3.6/dist-packages/electrumX-1.7.1-py3.6.egg/electrumx/server/peers.py:185> exception=TaskGroupError([<Task finished coro=<PeerManager._send_headers_subscribe() done, defined at /usr/local/lib/python3.6/dist-packages/electrumX-1.7.1-py3.6.egg/electrumx/server/peers.py:310> exception=BadPeerError('bad height 533,547 (ours: 534,103)',)>],)>],)>
Jul 28 07:55:03 electrumd electrumx_server[63389]: Traceback (most recent call last):
Jul 28 07:55:03 electrumd electrumx_server[63389]:   File "/usr/local/lib/python3.6/dist-packages/aiorpcX-0.5.8-py3.6.egg/aiorpcx/curio.py", line 138, in _on_done
Jul 28 07:55:03 electrumd electrumx_server[63389]:     task.result()
Jul 28 07:55:03 electrumd electrumx_server[63389]:   File "/usr/local/lib/python3.6/dist-packages/electrumX-1.7.1-py3.6.egg/electrumx/server/session.py", line 425, in serve
Jul 28 07:55:03 electrumd electrumx_server[63389]:     await group.spawn(self._housekeeping())
Jul 28 07:55:03 electrumd electrumx_server[63389]:   File "/usr/local/lib/python3.6/dist-packages/aiorpcX-0.5.8-py3.6.egg/aiorpcx/curio.py", line 254, in __aexit__
Jul 28 07:55:03 electrumd electrumx_server[63389]:     await self.join(wait=self._wait)
Jul 28 07:55:03 electrumd electrumx_server[63389]:   File "/usr/local/lib/python3.6/dist-packages/aiorpcX-0.5.8-py3.6.egg/aiorpcx/curio.py", line 228, in join
Jul 28 07:55:03 electrumd electrumx_server[63389]:     raise TaskGroupError(bad_tasks)
Jul 28 07:55:03 electrumd electrumx_server[63389]: aiorpcx.curio.TaskGroupError: TaskGroupError(TaskGroupError)
Jul 28 07:55:03 electrumd electrumx_server[63389]: INFO:BlockProcessor:flushing to DB for a clean shutdown...
Jul 28 07:55:03 electrumd electrumx_server[63389]: ERROR:TaskGroup:task crashed: <Task finished coro=<Controller.serve() done, defined at /usr/local/lib/python3.6/dist-packages/electrumX-1.7.1-py3.6.egg/electrumx/server/controller.py:80> exception=TaskGroupError([<Task finished coro=<SessionManager.serve() done, defined at /usr/local/lib/python3.6/dist-packages/electrumX-1.7.1-py3.6.egg/electrumx/server/session.py:398> exception=TaskGroupError([<Task finished coro=<PeerManager._monitor_peer() done, defined at /usr/local/lib/python3.6/dist-packages/electrumX-1.7.1-py3.6.egg/electrumx/server/peers.py:185> exception=TaskGroupError([<Task finished coro=<PeerManager._send_headers_subscribe() done, defined at /usr/local/lib/python3.6/dist-packages/electrumX-1.7.1-py3.6.egg/electrumx/server/peers.py:310> exception=BadPeerError('bad height 533,547 (ours: 534,103)',)>],)>],)>],)>
Jul 28 07:55:03 electrumd electrumx_server[63389]: Traceback (most recent call last):
Jul 28 07:55:03 electrumd electrumx_server[63389]:   File "/usr/local/lib/python3.6/dist-packages/aiorpcX-0.5.8-py3.6.egg/aiorpcx/curio.py", line 138, in _on_done
Jul 28 07:55:03 electrumd electrumx_server[63389]:     task.result()
Jul 28 07:55:03 electrumd electrumx_server[63389]:   File "/usr/local/lib/python3.6/dist-packages/electrumX-1.7.1-py3.6.egg/electrumx/server/controller.py", line 116, in serve
Jul 28 07:55:03 electrumd electrumx_server[63389]:     serve_externally_event.set()
Jul 28 07:55:03 electrumd electrumx_server[63389]:   File "/usr/local/lib/python3.6/dist-packages/aiorpcX-0.5.8-py3.6.egg/aiorpcx/curio.py", line 254, in __aexit__
Jul 28 07:55:03 electrumd electrumx_server[63389]:     await self.join(wait=self._wait)
Jul 28 07:55:03 electrumd electrumx_server[63389]:   File "/usr/local/lib/python3.6/dist-packages/aiorpcX-0.5.8-py3.6.egg/aiorpcx/curio.py", line 228, in join
Jul 28 07:55:03 electrumd electrumx_server[63389]:     raise TaskGroupError(bad_tasks)
Jul 28 07:55:03 electrumd electrumx_server[63389]: aiorpcx.curio.TaskGroupError: TaskGroupError(TaskGroupError)
Jul 28 07:55:04 electrumd electrumx_server[63389]: INFO:ElectrumX:[10344] SSL 185.234.217.147:41724, 2 total
```
The log says the server is exiting, but it never actually exited, but stayed in a zombie state until I reverted back to 1.7.

**Comment by SomberNight** [comment]
Something like this would solve it:

```patch
diff --git a/electrumx/server/peers.py b/electrumx/server/peers.py
index 3f1bad6..3a3c540 100644
--- a/electrumx/server/peers.py
+++ b/electrumx/server/peers.py
@@ -16,7 +16,7 @@ from collections import defaultdict, Counter
 
 from aiorpcx import (ClientSession, SOCKSProxy, SOCKSError,
                      RPCError, ConnectionError,
-                     TaskGroup, run_in_thread, ignore_after)
+                     TaskGroup, run_in_thread, ignore_after, TaskGroupError)
 
 from electrumx.lib.peer import Peer
 from electrumx.lib.util import class_logger, protocol_tuple
@@ -299,13 +299,19 @@ class PeerManager(object):
         peer.features['server_version'] = server_version
         ptuple = protocol_tuple(protocol_version)
 
-        async with TaskGroup() as group:
-            await group.spawn(self._send_headers_subscribe(session, peer,
-                                                           timeout, ptuple))
-            await group.spawn(self._send_server_features(session, peer,
-                                                         timeout))
-            await group.spawn(self._send_peers_subscribe(session, peer,
-                                                         timeout))
+        try:
+            async with TaskGroup() as group:
+                await group.spawn(
+                    self._send_headers_subscribe(session, peer, timeout, ptuple),
+                    report_crash=False)
+                await group.spawn(
+                    self._send_server_features(session, peer, timeout),
+                    report_crash=False)
+                await group.spawn(
+                    self._send_peers_subscribe(session, peer, timeout),
+                    report_crash=False)
+        except TaskGroupError as e:
+            raise e.errors.pop() from e
 
     async def _send_headers_subscribe(self, session, peer, timeout, ptuple):
         message = 'blockchain.headers.subscribe'
```

but it would be better if TaskGroupError.errors contained exception instances not just the type:
https://github.com/kyuupichan/aiorpcX/blob/94b42fe3526d64d8042599c45336ce5e3aee76f7/aiorpcx/curio.py#L73
