### ISSUE TITLE
Error: getsockaddrarg() takes exactly 2 arguments (4 given)

### ISSUE THREAD

**Issue by colmo** [kyuupichan/electrumx#547]
Hi, I'm having issues with the latest version of electrumx (1.7.2)
In 1.6, a warning is displayed in the log but electrumx continues to work correctly.

I think this error is related to IPv6 connectivity. (A possible explanation of the problem in another github https://github.com/agoragames/haigha/pull/69)

**Electrumx 1.7.2**
 ```
ERROR:TaskGroup:task crashed: <Task finished coro=<PeerManager._monitor_peer() done, defined at /usr/local/lib/python3.7/site-packages/electrumX-1.7.2-py3.7.egg/electrumx/server/peers.py:185> exception=TypeError('getsockaddrarg() takes exactly 2 arguments (4 given)')>
Jul 31 20:28:24 vmi145639 electrumx_server[27222]: Traceback (most recent call last):
Jul 31 20:28:24 vmi145639 electrumx_server[27222]:   File "/usr/local/lib/python3.7/site-packages/aiorpcX-0.5.9-py3.7.egg/aiorpcx/curio.py", line 138, in _on_done
Jul 31 20:28:24 vmi145639 electrumx_server[27222]:     task.result()
Jul 31 20:28:24 vmi145639 electrumx_server[27222]:   File "/usr/local/lib/python3.7/site-packages/electrumX-1.7.2-py3.7.egg/electrumx/server/peers.py", line 188, in _monitor_peer
Jul 31 20:28:24 vmi145639 electrumx_server[27222]:     if await self._should_drop_peer(peer):
Jul 31 20:28:24 vmi145639 electrumx_server[27222]:   File "/usr/local/lib/python3.7/site-packages/electrumX-1.7.2-py3.7.egg/electrumx/server/peers.py", line 226, in _should_drop_peer
Jul 31 20:28:24 vmi145639 electrumx_server[27222]:     async with PeerSession(peer.host, port, **kwargs) as session:
Jul 31 20:28:24 vmi145639 electrumx_server[27222]:   File "/usr/local/lib/python3.7/site-packages/aiorpcX-0.5.9-py3.7.egg/aiorpcx/session.py", line 328, in __aenter__
Jul 31 20:28:24 vmi145639 electrumx_server[27222]:     await self.create_connection()
Jul 31 20:28:24 vmi145639 electrumx_server[27222]:   File "/usr/local/lib/python3.7/site-packages/aiorpcX-0.5.9-py3.7.egg/aiorpcx/session.py", line 325, in create_connection
Jul 31 20:28:24 vmi145639 electrumx_server[27222]:     self_func, self.host, self.port, **self.kwargs)
Jul 31 20:28:24 vmi145639 electrumx_server[27222]:   File "/usr/local/lib/python3.7/asyncio/base_events.py", line 914, in create_connection
Jul 31 20:28:24 vmi145639 electrumx_server[27222]:     sock.bind(laddr)
Jul 31 20:28:24 vmi145639 electrumx_server[27222]: TypeError: getsockaddrarg() takes exactly 2 arguments (4 given)
```

**Electrum 1.6 log**
```
Jul 31 21:57:18 vmi145639 electrumx_server[5037]: INFO:PeerManager:failed connecting to electrumx.bot.nu at TCP port 50001 in 0.0s: getsockaddrarg() takes exactly 2 arguments (4 given)
Jul 31 21:57:18 vmi145639 electrumx_server[5037]: INFO:PeerManager:failed connecting to ip101.ip-54-37-91.eu at SSL port 50002 in 0.0s: getsockaddrarg() takes exactly 2 arguments (4 given)
Jul 31 21:57:18 vmi145639 electrumx_server[5037]: INFO:PeerManager:failed connecting to spv.48.org at TCP port 50003 in 0.0s: getsockaddrarg() takes exactly 2 arguments (4 given)
Jul 31 21:57:18 vmi145639 electrumx_server[5037]: INFO:PeerManager:failed connecting to ip101.ip-54-37-91.eu at TCP port 50001 in 0.0s: getsockaddrarg() takes exactly 2 arguments (4 given)

```

Thanks for your help!

**Comment by denpamusic** [comment]
I had this issue before on dual-stack server running Ubuntu 16.04.
For me it was resolved by adding `HOST=` (just HOST equals without any value) directive to /etc/electrumx.conf.
If you don't already have this line in your config, try adding it. Maybe it'll help you too.

**Comment by kyuupichan** [comment]
This crash is fixed in git head.
