### ISSUE TITLE
Crash during chain reorg: coroutine 'BlockProcessor.calc_reorg_range' was never awaited

### ISSUE THREAD

**Issue by fr3aker** [kyuupichan/electrumx#560]
using version 1.73 I experienced a crash on BTC mainnet. It occurred when a reorg happened.

	INFO:Prefetcher:new block height 535,511 hash 00000000000000000028d289254e626518e8ead704f1d9a9a4f5122ae535d64d
	INFO:BlockProcessor:chain reorg detected
	/opt/electrumx/electrumx/server/block_processor.py:266: RuntimeWarning: coroutine 'BlockProcessor.calc_reorg_range' was never awaited
	  start, count = self.calc_reorg_range(count)
	ERROR:TaskGroup:task crashed: <Task finished coro=<BlockProcessor._process_prefetched_blocks() done, defined at /opt/electrumx/electrumx/server/block_processor.py:746> exception=TypeError('cannot unpack non-iterable coroutine object')>
	Traceback (most recent call last):
	  File "/opt/electrumx/venv/lib/python3.7/site-packages/aiorpcX-0.5.9-py3.7.egg/aiorpcx/curio.py", line 138, in _on_done
	    task.result()
	  File "/opt/electrumx/electrumx/server/block_processor.py", line 760, in _process_prefetched_blocks
	    await self.check_and_advance_blocks(blocks)
	  File "/opt/electrumx/electrumx/server/block_processor.py", line 215, in check_and_advance_blocks
	    await self.reorg_chain()
	  File "/opt/electrumx/electrumx/server/block_processor.py", line 246, in reorg_chain
	    start, last, hashes = await self.reorg_hashes(count)
	  File "/opt/electrumx/electrumx/server/block_processor.py", line 266, in reorg_hashes
	    start, count = self.calc_reorg_range(count)
	TypeError: cannot unpack non-iterable coroutine object
	INFO:BlockProcessor:flushing to DB for a clean shutdown...
	ERROR:TaskGroup:task crashed: <Task finished coro=<BlockProcessor.fetch_and_process_blocks() done, defined at /opt/electrumx/electrumx/server/block_processor.py:797> exception=TaskGroupError([<Task finished coro=<BlockProcessor._process_prefetched_blocks() done, defined
	at /opt/electrumx/electrumx/server/block_processor.py:746> exception=TypeError('cannot unpack non-iterable coroutine object')>])>
	Traceback (most recent call last):
	  File "/opt/electrumx/venv/lib/python3.7/site-packages/aiorpcX-0.5.9-py3.7.egg/aiorpcx/curio.py", line 138, in _on_done
	    task.result()
	  File "/opt/electrumx/electrumx/server/block_processor.py", line 817, in fetch_and_process_blocks
	    await group.spawn(self._process_prefetched_blocks())
	  File "/opt/electrumx/venv/lib/python3.7/site-packages/aiorpcX-0.5.9-py3.7.egg/aiorpcx/curio.py", line 254, in __aexit__
	    await self.join(wait=self._wait)
	  File "/opt/electrumx/venv/lib/python3.7/site-packages/aiorpcX-0.5.9-py3.7.egg/aiorpcx/curio.py", line 228, in join
	    raise TaskGroupError(bad_tasks)
	aiorpcx.curio.TaskGroupError: TaskGroupError(TypeError)
	INFO:SessionManager:closing down RPC, TCP, SSL listening servers
	ERROR:TaskGroup:task crashed: <Task finished coro=<Controller.serve() done, defined at /opt/electrumx/electrumx/server/controller.py:80> exception=TaskGroupError([<Task finished coro=<BlockProcessor.fetch_and_process_blocks() done, defined at /opt/electrumx/electrumx/server/block_processor.py:797> exception=TaskGroupError([<Task finished coro=<BlockProcessor._process_prefetched_blocks() done, defined at /opt/electrumx/electrumx/server/block_processor.py:746> exception=TypeError('cannot unpack non-iterable coroutine object')>])>])>
	Traceback (most recent call last):
	  File "/opt/electrumx/venv/lib/python3.7/site-packages/aiorpcX-0.5.9-py3.7.egg/aiorpcx/curio.py", line 138, in _on_done
	    task.result()
	  File "/opt/electrumx/electrumx/server/controller.py", line 116, in serve
	    serve_externally_event.set()
	  File "/opt/electrumx/venv/lib/python3.7/site-packages/aiorpcX-0.5.9-py3.7.egg/aiorpcx/curio.py", line 254, in __aexit__
	    await self.join(wait=self._wait)
	  File "/opt/electrumx/venv/lib/python3.7/site-packages/aiorpcX-0.5.9-py3.7.egg/aiorpcx/curio.py", line 228, in join
	    raise TaskGroupError(bad_tasks)
	aiorpcx.curio.TaskGroupError: TaskGroupError(TaskGroupError)

Now this error happens every time I restart Electrumx.

**Comment by fr3aker** [comment]
Fixed by upgrading to 1.8. Sorry for the noise.

**Comment by kyuupichan** [comment]
Yes there were resort bugs in a few revisions before 1.8
