### ISSUE TITLE
electrumX terminated with error: b'Corruption: bad entry in block'

### ISSUE THREAD

**Issue by SimonVrouwe** [kyuupichan/electrumx#561]
A few weeks ago my SSD died while copying the bitcoin blockchain. I cloned the SSD to a new disk, somehow this was successful, and got my system running again. `bitcoind` re synced and all seems normal, but `electrumx v1.4.3` keeps crashing with error `b'Corruption: bad entry in block'`. Perhaps `bitcoind` blockchain files where corrupt, so I copied `blocks` and `chainstate` directories from another system to be sure, but electrumx keeps crashing. Then upgraded to latest `v1.8` using `electrumx-installer` script, but that also didn't solve the crash. Below shows log output from `journalctl -u electrumx` of `v1.4.3` and subsequent `v1.8`.

Should I rebuild the db and is there a command for that?

my system: `Linux HPLaptop 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux`

```
-- Logs begin at Tue 2018-08-07 13:50:20 EEST, end at Tue 2018-08-07 14:27:32 EEST. --
Aug 07 13:50:34 HPLaptop systemd[1]: Started Electrumx.
Aug 07 13:50:46 HPLaptop electrumx_server.py[734]: INFO:root:ElectrumX server starting
Aug 07 13:50:46 HPLaptop electrumx_server.py[734]: INFO:Controller:software version: ElectrumX 1.4.3
Aug 07 13:50:46 HPLaptop electrumx_server.py[734]: INFO:Controller:supported protocol versions: 1.0-1.2
Aug 07 13:50:46 HPLaptop electrumx_server.py[734]: INFO:Controller:event loop policy: None
Aug 07 13:50:46 HPLaptop electrumx_server.py[734]: INFO:Daemon:daemon #1 at localhost:8332/ (current)
Aug 07 13:50:46 HPLaptop electrumx_server.py[734]: INFO:BlockProcessor:switching current directory to /home/electrumx/electrumx-db
Aug 07 13:50:47 HPLaptop electrumx_server.py[734]: INFO:BlockProcessor:using leveldb for DB backend
Aug 07 13:50:50 HPLaptop electrumx_server.py[734]: INFO:BlockProcessor:opened DB for serving
Aug 07 13:50:50 HPLaptop electrumx_server.py[734]: INFO:BlockProcessor:DB version: 6
Aug 07 13:50:50 HPLaptop electrumx_server.py[734]: INFO:BlockProcessor:coin: BitcoinSegwit
Aug 07 13:50:50 HPLaptop electrumx_server.py[734]: INFO:BlockProcessor:network: mainnet
Aug 07 13:50:50 HPLaptop electrumx_server.py[734]: INFO:BlockProcessor:height: 531,942
Aug 07 13:50:50 HPLaptop electrumx_server.py[734]: INFO:BlockProcessor:tip: 000000000000000000108023b38ce720d2519ff6baac4d8de8f994f4674e3e2f
Aug 07 13:50:50 HPLaptop electrumx_server.py[734]: INFO:BlockProcessor:tx count: 328,120,204
Aug 07 13:50:50 HPLaptop electrumx_server.py[734]: INFO:BlockProcessor:flush count: 10,585
Aug 07 13:50:50 HPLaptop electrumx_server.py[734]: INFO:BlockProcessor:DB shut down uncleanly.  Scanning for excess history flushes...
Aug 07 13:52:37 HPLaptop electrumx_server.py[734]: Traceback (most recent call last):
Aug 07 13:52:37 HPLaptop electrumx_server.py[734]:   File "/opt/python/lib/python3.6/site-packages/electrumx-ElectrumX.1.4.3-py3.6.egg/EGG-INFO/scripts/electrumx_server.py", line 25, in main
Aug 07 13:52:37 HPLaptop electrumx_server.py[734]:   File "/opt/python/lib/python3.6/site-packages/electrumx-ElectrumX.1.4.3-py3.6.egg/server/controller.py", line 94, in __init__
Aug 07 13:52:37 HPLaptop electrumx_server.py[734]:     self.bp = self.coin.BLOCK_PROCESSOR(env, self, self.daemon)
Aug 07 13:52:37 HPLaptop electrumx_server.py[734]:   File "/opt/python/lib/python3.6/site-packages/electrumx-ElectrumX.1.4.3-py3.6.egg/server/block_processor.py", line 144, in __init__
Aug 07 13:52:37 HPLaptop electrumx_server.py[734]:     super().__init__(env)
Aug 07 13:52:37 HPLaptop electrumx_server.py[734]:   File "/opt/python/lib/python3.6/site-packages/electrumx-ElectrumX.1.4.3-py3.6.egg/server/db.py", line 68, in __init__
Aug 07 13:52:37 HPLaptop electrumx_server.py[734]:     self.clean_db()
Aug 07 13:52:37 HPLaptop electrumx_server.py[734]:   File "/opt/python/lib/python3.6/site-packages/electrumx-ElectrumX.1.4.3-py3.6.egg/server/db.py", line 156, in clean_db
Aug 07 13:52:37 HPLaptop electrumx_server.py[734]:     self.clear_excess_history(self.utxo_flush_count)
Aug 07 13:52:37 HPLaptop electrumx_server.py[734]:   File "/opt/python/lib/python3.6/site-packages/electrumx-ElectrumX.1.4.3-py3.6.egg/server/db.py", line 421, in clear_excess_history
Aug 07 13:52:37 HPLaptop electrumx_server.py[734]:     for key, hist in self.hist_db.iterator(prefix=b''):
Aug 07 13:52:37 HPLaptop electrumx_server.py[734]:   File "plyvel/_plyvel.pyx", line 829, in plyvel._plyvel.Iterator.__next__
Aug 07 13:52:37 HPLaptop electrumx_server.py[734]:   File "plyvel/_plyvel.pyx", line 874, in plyvel._plyvel.Iterator.real_next
Aug 07 13:52:37 HPLaptop electrumx_server.py[734]:   File "plyvel/_plyvel.pyx", line 91, in plyvel._plyvel.raise_for_status
Aug 07 13:52:37 HPLaptop electrumx_server.py[734]: plyvel._plyvel.CorruptionError: b'Corruption: bad entry in block'
Aug 07 13:52:37 HPLaptop electrumx_server.py[734]: CRITICAL:root:ElectrumX server terminated abnormally
```
```
Aug 07 14:24:51 HPLaptop systemd[1]: Started Electrumx.
Aug 07 14:24:52 HPLaptop electrumx_server[3319]: INFO:Controller:Python version: 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19)
Aug 07 14:24:52 HPLaptop electrumx_server[3319]: [GCC 7.2.0]
Aug 07 14:24:52 HPLaptop electrumx_server[3319]: INFO:Controller:software version: ElectrumX 1.8
Aug 07 14:24:52 HPLaptop electrumx_server[3319]: INFO:Controller:aiorpcX version: 0.6.2
Aug 07 14:24:52 HPLaptop electrumx_server[3319]: INFO:Controller:supported protocol versions: 1.1-1.4
Aug 07 14:24:52 HPLaptop electrumx_server[3319]: INFO:Controller:event loop policy: None
Aug 07 14:24:52 HPLaptop electrumx_server[3319]: INFO:Controller:reorg limit is 200 blocks
Aug 07 14:24:52 HPLaptop electrumx_server[3319]: INFO:Daemon:daemon #1 at localhost:8332/ (current)
Aug 07 14:24:52 HPLaptop electrumx_server[3319]: INFO:BlockProcessor:switching current directory to /home/electrumx/electrumx-db
Aug 07 14:24:52 HPLaptop electrumx_server[3319]: INFO:BlockProcessor:using leveldb for DB backend
Aug 07 14:24:52 HPLaptop electrumx_server[3319]: INFO:BlockProcessor:opened UTXO DB (for sync: True)
Aug 07 14:24:52 HPLaptop electrumx_server[3319]: INFO:BlockProcessor:DB version: 6
Aug 07 14:24:52 HPLaptop electrumx_server[3319]: INFO:BlockProcessor:coin: BitcoinSegwit
Aug 07 14:24:52 HPLaptop electrumx_server[3319]: INFO:BlockProcessor:network: mainnet
Aug 07 14:24:52 HPLaptop electrumx_server[3319]: INFO:BlockProcessor:height: 531,942
Aug 07 14:24:52 HPLaptop electrumx_server[3319]: INFO:BlockProcessor:tip: 000000000000000000108023b38ce720d2519ff6baac4d8de8f994f4674e3e2f
Aug 07 14:24:52 HPLaptop electrumx_server[3319]: INFO:BlockProcessor:tx count: 328,120,204
Aug 07 14:24:53 HPLaptop electrumx_server[3319]: INFO:History:history DB version: 0
Aug 07 14:24:53 HPLaptop electrumx_server[3319]: INFO:History:flush count: 10,585
Aug 07 14:24:53 HPLaptop electrumx_server[3319]: INFO:History:DB shut down uncleanly.  Scanning for excess history flushes...
Aug 07 14:25:40 HPLaptop electrumx_server[3319]: ERROR:root:task crashed: <Task finished coro=<BlockProcessor._first_open_dbs() done, defined at /opt/python/lib/python3.6/site-packages/electrumx
Aug 07 14:25:40 HPLaptop electrumx_server[3319]: Traceback (most recent call last):
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:   File "/opt/python/lib/python3.6/site-packages/aiorpcx/util.py", line 118, in check_task
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:     task.result()
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:   File "/opt/python/lib/python3.6/site-packages/electrumx/server/block_processor.py", line 781, in _first_open_dbs
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:     await self.open_for_sync()
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:   File "/opt/python/lib/python3.6/site-packages/electrumx/server/db.py", line 120, in open_for_sync
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:     await self._open_dbs(True)
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:   File "/opt/python/lib/python3.6/site-packages/electrumx/server/db.py", line 107, in _open_dbs
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:     self.utxo_flush_count)
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:   File "/opt/python/lib/python3.6/site-packages/electrumx/server/history.py", line 37, in open_db
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:     self.clear_excess(utxo_flush_count)
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:   File "/opt/python/lib/python3.6/site-packages/electrumx/server/history.py", line 78, in clear_excess
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:     for key, hist in self.db.iterator(prefix=b''):
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:   File "plyvel/_plyvel.pyx", line 829, in plyvel._plyvel.Iterator.__next__
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:   File "plyvel/_plyvel.pyx", line 874, in plyvel._plyvel.Iterator.real_next
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:   File "plyvel/_plyvel.pyx", line 91, in plyvel._plyvel.raise_for_status
Aug 07 14:25:40 HPLaptop electrumx_server[3319]: plyvel._plyvel.CorruptionError: b'Corruption: bad entry in block'
Aug 07 14:25:40 HPLaptop electrumx_server[3319]: ERROR:TaskGroup:task crashed: <Task finished coro=<BlockProcessor._first_open_dbs() done, defined at /opt/python/lib/python3.6/site-packages/elec
Aug 07 14:25:40 HPLaptop electrumx_server[3319]: Traceback (most recent call last):
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:   File "/opt/python/lib/python3.6/site-packages/aiorpcx/util.py", line 118, in check_task
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:     task.result()
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:   File "/opt/python/lib/python3.6/site-packages/aiorpcx/util.py", line 118, in check_task
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:     task.result()
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:   File "/opt/python/lib/python3.6/site-packages/electrumx/server/block_processor.py", line 781, in _first_open_dbs
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:     await self.open_for_sync()
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:   File "/opt/python/lib/python3.6/site-packages/electrumx/server/db.py", line 120, in open_for_sync
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:     await self._open_dbs(True)
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:   File "/opt/python/lib/python3.6/site-packages/electrumx/server/db.py", line 107, in _open_dbs
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:     self.utxo_flush_count)
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:   File "/opt/python/lib/python3.6/site-packages/electrumx/server/history.py", line 37, in open_db
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:     self.clear_excess(utxo_flush_count)
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:   File "/opt/python/lib/python3.6/site-packages/electrumx/server/history.py", line 78, in clear_excess
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:     for key, hist in self.db.iterator(prefix=b''):
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:   File "plyvel/_plyvel.pyx", line 829, in plyvel._plyvel.Iterator.__next__
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:   File "plyvel/_plyvel.pyx", line 874, in plyvel._plyvel.Iterator.real_next
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:   File "plyvel/_plyvel.pyx", line 91, in plyvel._plyvel.raise_for_status
Aug 07 14:25:40 HPLaptop electrumx_server[3319]: plyvel._plyvel.CorruptionError: b'Corruption: bad entry in block'
Aug 07 14:25:40 HPLaptop electrumx_server[3319]: INFO:SessionManager:RPC server listening on localhost:8000
Aug 07 14:25:40 HPLaptop electrumx_server[3319]: ERROR:root:task crashed: <Task finished coro=<BlockProcessor.fetch_and_process_blocks() done, defined at /opt/python/lib/python3.6/site-packages/
Aug 07 14:25:40 HPLaptop electrumx_server[3319]: Traceback (most recent call last):
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:   File "/opt/python/lib/python3.6/site-packages/aiorpcx/util.py", line 118, in check_task
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:     task.result()
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:   File "/opt/python/lib/python3.6/site-packages/electrumx/server/block_processor.py", line 813, in fetch_and_process_blocks
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:     await group.spawn(self.daemon.height())
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:   File "/opt/python/lib/python3.6/site-packages/aiorpcx/curio.py", line 263, in __aexit__
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:     await self.join(wait=self._wait)
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:   File "/opt/python/lib/python3.6/site-packages/aiorpcx/curio.py", line 237, in join
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:     raise TaskGroupError(bad_tasks)
Aug 07 14:25:40 HPLaptop electrumx_server[3319]: aiorpcx.curio.TaskGroupError: TaskGroupError(CorruptionError)
Aug 07 14:25:40 HPLaptop electrumx_server[3319]: ERROR:TaskGroup:task crashed: <Task finished coro=<BlockProcessor.fetch_and_process_blocks() done, defined at /opt/python/lib/python3.6/site-pack
Aug 07 14:25:40 HPLaptop electrumx_server[3319]: Traceback (most recent call last):
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:   File "/opt/python/lib/python3.6/site-packages/aiorpcx/util.py", line 118, in check_task
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:     task.result()
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:   File "/opt/python/lib/python3.6/site-packages/aiorpcx/util.py", line 118, in check_task
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:     task.result()
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:   File "/opt/python/lib/python3.6/site-packages/electrumx/server/block_processor.py", line 813, in fetch_and_process_blocks
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:     await group.spawn(self.daemon.height())
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:   File "/opt/python/lib/python3.6/site-packages/aiorpcx/curio.py", line 263, in __aexit__
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:     await self.join(wait=self._wait)
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:   File "/opt/python/lib/python3.6/site-packages/aiorpcx/curio.py", line 237, in join
Aug 07 14:25:40 HPLaptop electrumx_server[3319]:     raise TaskGroupError(bad_tasks)
Aug 07 14:25:40 HPLaptop electrumx_server[3319]: aiorpcx.curio.TaskGroupError: TaskGroupError(CorruptionError)
```

**Comment by kyuupichan** [comment]
The error message says your ElectrumX DB is corrupt, it's reported by LevelDB.  I suggest you restart from scratch.  If it syncs you're fine, otherwise your bitcoin DB is likely corrupt and you'll need to restart that from scratch first...
