### ISSUE TITLE
ERROR:root:task crashed

### ISSUE THREAD

**Issue by partylana** [kyuupichan/electrumx#595]
`INFO:BlockProcessor:our height: 1,361,532 daemon: 1,491,108 UTXOs 620MB hist 332MB
INFO:BlockProcessor:our height: 1,361,918 daemon: 1,491,109 UTXOs 628MB hist 344MB
ERROR:root:task crashed: <Task finished coro=<Prefetcher.main_loop() done, defined at /usr/local/lib/python3.6/dist-packages/electrumX-1.8.5-py3.6.egg/electrumx/server/block_processor.py:48> exception=ClientPayloadError('Response payload is not completed',)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aiorpcX-0.7.3-py3.6.egg/aiorpcx/util.py", line 118, in check_task
    task.result()
  File "/usr/local/lib/python3.6/dist-packages/electrumX-1.8.5-py3.6.egg/electrumx/server/block_processor.py", line 55, in main_loop
    if not await self._prefetch_blocks():
  File "/usr/local/lib/python3.6/dist-packages/electrumX-1.8.5-py3.6.egg/electrumx/server/block_processor.py", line 115, in _prefetch_blocks
    blocks = await daemon.raw_blocks(hex_hashes)
  File "/usr/local/lib/python3.6/dist-packages/electrumX-1.8.5-py3.6.egg/electrumx/server/daemon.py", line 217, in raw_blocks
    blocks = await self._send_vector('getblock', params_iterable)
  File "/usr/local/lib/python3.6/dist-packages/electrumX-1.8.5-py3.6.egg/electrumx/server/daemon.py", line 185, in _send_vector
    return await self._send(payload, processor)
  File "/usr/local/lib/python3.6/dist-packages/electrumX-1.8.5-py3.6.egg/electrumx/server/daemon.py", line 130, in _send
    result = await self._send_data(data)
  File "/usr/local/lib/python3.6/dist-packages/electrumX-1.8.5-py3.6.egg/electrumx/server/daemon.py", line 100, in _send_data
    return await resp.json()
  File "/usr/local/lib/python3.6/dist-packages/aiohttp-3.4.4-py3.6.egg/aiohttp/client_reqrep.py", line 928, in json
    await self.read()
  File "/usr/local/lib/python3.6/dist-packages/aiohttp-3.4.4-py3.6.egg/aiohttp/client_reqrep.py", line 880, in read
    self._body = await self.content.read()
  File "/usr/local/lib/python3.6/dist-packages/aiohttp-3.4.4-py3.6.egg/aiohttp/streams.py", line 322, in read
    block = await self.readany()
  File "/usr/local/lib/python3.6/dist-packages/aiohttp-3.4.4-py3.6.egg/aiohttp/streams.py", line 338, in readany
    await self._wait('readany')
  File "/usr/local/lib/python3.6/dist-packages/aiohttp-3.4.4-py3.6.egg/aiohttp/streams.py", line 260, in _wait
    await waiter
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed
ERROR:TaskGroup:task crashed: <Task finished coro=<Prefetcher.main_loop() done, defined at /usr/local/lib/python3.6/dist-packages/electrumX-1.8.5-py3.6.egg/electrumx/server/block_processor.py:48> exception=ClientPayloadError('Response payload is not completed',)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aiorpcX-0.7.3-py3.6.egg/aiorpcx/util.py", line 118, in check_task
    task.result()
  File "/usr/local/lib/python3.6/dist-packages/aiorpcX-0.7.3-py3.6.egg/aiorpcx/util.py", line 118, in check_task
    task.result()
  File "/usr/local/lib/python3.6/dist-packages/electrumX-1.8.5-py3.6.egg/electrumx/server/block_processor.py", line 55, in main_loop
    if not await self._prefetch_blocks():
  File "/usr/local/lib/python3.6/dist-packages/electrumX-1.8.5-py3.6.egg/electrumx/server/block_processor.py", line 115, in _prefetch_blocks
    blocks = await daemon.raw_blocks(hex_hashes)
  File "/usr/local/lib/python3.6/dist-packages/electrumX-1.8.5-py3.6.egg/electrumx/server/daemon.py", line 217, in raw_blocks
    blocks = await self._send_vector('getblock', params_iterable)
  File "/usr/local/lib/python3.6/dist-packages/electrumX-1.8.5-py3.6.egg/electrumx/server/daemon.py", line 185, in _send_vector`

i need help.

Thankyou.

**Comment by kyuupichan** [comment]
Please post your startup logs of ElectrumX.  Does it happen every restart?

**Comment by kyuupichan** [comment]
Preserving newines in your logs would help - I can't read the errors

**Comment by partylana** [comment]
Thank you.

Yes this was happening for every restart.

**config file:**

_export ALLOW_ROOT=1
export COIN=Litecoin
export DAEMON_URL=http://usernamepassword@localhost:9332
export NET=mainnet
export CACHE_MB=3000
export DB_DIRECTORY=/mnt/ltc_electrumx/
export DB_ENGINE=leveldb
export BANNER_FILE=/etc/electrumx.banner
export DONATION_ADDRESS=LXA3i9eEAVDbgDqkThCa4D6BUJ3SEULkEr
export HOST=(ipaddress of server)
export TCP_PORT=50001
export RPC_PORT=8000_

And also i can't see port 50001 open mentioned in the config file above. 

**Here is the startup log.**

_INFO:Controller:Python version: 3.6.5 (default, May  3 2018, 10:08:28) 
[GCC 5.4.0 20160609]
INFO:Controller:software version: ElectrumX 1.8.5
INFO:Controller:aiorpcX version: 0.7.3
INFO:Controller:supported protocol versions: 1.1-1.4
INFO:Controller:event loop policy: None
INFO:Controller:reorg limit is 800 blocks
INFO:Daemon:daemon #1 at localhost:9332/ (current)
INFO:DB:switching current directory to /mnt/btcvol/ltc_electrumx/
INFO:DB:using leveldb for DB backend
INFO:DB:opened UTXO DB (for sync: True)
INFO:DB:DB version: 6
INFO:DB:coin: Litecoin
INFO:DB:network: mainnet
INFO:DB:height: 1,332,516
INFO:DB:tip: 8e9445bc766eac6d67f939d68b566c26ba05aa8c501cb006102213ea707a29f2
INFO:DB:tx count: 15,354,921
INFO:DB:flushing DB cache at 3,000 MB
INFO:DB:sync time so far: 20h 22m 50s
INFO:History:history DB version: 0
INFO:History:flush count: 24
INFO:SessionManager:RPC server listening on localhost:8000
INFO:Prefetcher:catching up to daemon height 1,491,004 (158,488 blocks behind)
INFO:BlockProcessor:our height: 1,332,526 daemon: 1,491,004 UTXOs 0MB hist 1MB
INFO:BlockProcessor:our height: 1,332,853 daemon: 1,491,004 UTXOs 19MB hist 30MB_


Thank you.

**Comment by kyuupichan** [comment]
Can you try git HEAD.  It should catch the problem and not crash, but I think the problem is really in the litecoin daemon embedded HTTP server.  It's hard to tell as your initial error was unreadable.  Let me know if it somehow recovers.

**Comment by kyuupichan** [comment]
You will need aiorpcX version 0.8.1.  If you still have issues, what version of aiohttp are you using?

**Comment by partylana** [comment]
Version of aiohttp is aiohttp-3.4.4-py3.6.egg. 
I will install aiorpcX. 
And most of the time the port 50001 is not open. What might be the reason?

**Comment by partylana** [comment]
Again the same above error:

_INFO:BlockProcessor:our height: 1,361,532 daemon: 1,491,108 UTXOs 620MB hist 332MB
INFO:BlockProcessor:our height: 1,361,918 daemon: 1,491,109 UTXOs 628MB hist 344MB
ERROR:root:task crashed: <Task finished coro=<Prefetcher.main_loop() done, defined at /usr/local/lib/python3.6/dist-packages/electrumX-1.8.5-py3.6.egg/electrumx/server
/block_processor.py:48> exception=ClientPayloadError('Response payload is not completed',)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aiorpcX-0.7.3-py3.6.egg/aiorpcx/util.py", line 118, in check_task
    task.result()
  File "/usr/local/lib/python3.6/dist-packages/electrumX-1.8.5-py3.6.egg/electrumx/server/block_processor.py", line 55, in main_loop
    if not await self._prefetch_blocks():
  File "/usr/local/lib/python3.6/dist-packages/electrumX-1.8.5-py3.6.egg/electrumx/server/block_processor.py", line 115, in _prefetch_blocks
    blocks = await daemon.raw_blocks(hex_hashes)
  File "/usr/local/lib/python3.6/dist-packages/electrumX-1.8.5-py3.6.egg/electrumx/server/daemon.py", line 217, in raw_blocks
    blocks = await self._send_vector('getblock', params_iterable)
  File "/usr/local/lib/python3.6/dist-packages/electrumX-1.8.5-py3.6.egg/electrumx/server/daemon.py", line 185, in _send_vector
    return await self._send(payload, processor)
  File "/usr/local/lib/python3.6/dist-packages/electrumX-1.8.5-py3.6.egg/electrumx/server/daemon.py", line 130, in _send
    result = await self._send_data(data)
  File "/usr/local/lib/python3.6/dist-packages/electrumX-1.8.5-py3.6.egg/electrumx/server/daemon.py", line 100, in _send_data
    return await resp.json()
  File "/usr/local/lib/python3.6/dist-packages/aiohttp-3.4.4-py3.6.egg/aiohttp/client_reqrep.py", line 928, in json
    await self.read()
  File "/usr/local/lib/python3.6/dist-packages/aiohttp-3.4.4-py3.6.egg/aiohttp/client_reqrep.py", line 880, in read
    self._body = await self.content.read()
  File "/usr/local/lib/python3.6/dist-packages/aiohttp-3.4.4-py3.6.egg/aiohttp/streams.py", line 322, in read
    block = await self.readany()
  File "/usr/local/lib/python3.6/dist-packages/aiohttp-3.4.4-py3.6.egg/aiohttp/streams.py", line 338, in readany
    await self._wait('readany')
  File "/usr/local/lib/python3.6/dist-packages/aiohttp-3.4.4-py3.6.egg/aiohttp/streams.py", line 260, in _wait
    await waiter
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed
ERROR:TaskGroup:task crashed: <Task finished coro=<Prefetcher.main_loop() done, defined at /usr/local/lib/python3.6/dist-packages/electrumX-1.8.5-py3.6.egg/electrumx/server/block_processor.py:48> exception=ClientPayloadError('Response payload is not completed',)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aiorpcX-0.7.3-py3.6.egg/aiorpcx/util.py", line 118, in check_task
    task.result()_

**Comment by partylana** [comment]
changing aiorpcx version to 0.8.1 solved the issue. closing. Thank you.
