### ISSUE TITLE
CancelledError for new Coin

### ISSUE THREAD

**Issue by DarkMonad** [kyuupichan/electrumx#604]
I am trying to add [Obsidian](https://github.com/obsidianplatform/Obsidian-Qt) to ElectrumX.
I have added it to lib/coins.py, but when I try to run it with the obsidian node, 
I only get the following output:
```
INFO:Controller:Python version: 3.7.0 (default, Sep 21 2018, 09:35:28)                                                                                                    
[GCC 5.4.0 20160609]                                                                                                                                                      
INFO:Controller:software version: ElectrumX 1.8.7                                                                                                                         
INFO:Controller:aiorpcX version: 0.8.1                                                                                                                                    
INFO:Controller:supported protocol versions: 1.1-1.4                                                                                                                      
INFO:Controller:event loop policy: None                                                                                                                                   
INFO:Controller:reorg limit is 200 blocks                                                                                                                                 
INFO:Daemon:daemon #1 at localhost:56661/ (current)                                                                                                                       
INFO:DB:switching current directory to /home/electrumx/                                                                                                                   
INFO:DB:using leveldb for DB backend                                                                                                                                      
INFO:DB:opened UTXO DB (for sync: True)                                                                                                                                   
INFO:DB:DB version: 6                                                                                                                                                     
INFO:DB:coin: Obsidian                                                                                                                                                    
INFO:DB:network: mainnet                                                                                                                                                  
INFO:DB:height: -1                                                                                                                                                        
INFO:DB:tip: 0000000000000000000000000000000000000000000000000000000000000000                                                                                             
INFO:DB:tx count: 0                                                                                                                                                       
INFO:DB:flushing DB cache at 1,200 MB                                                                                                                                     
INFO:DB:sync time so far: 00s                                                                                                                                             
INFO:History:history DB version: 0                                                                                                                                        
INFO:History:flush count: 0                                                                                                                                               
INFO:SessionManager:RPC server listening on localhost:8000                                                                                                                
INFO:Prefetcher:catching up to daemon height 507,631 (507,632 blocks behind)                                                                                              
INFO:Prefetcher:verified genesis block with hash 0000006dd8a92f58e952fa61c9402b74a381a69d1930fb5cc12c73273fab5f0a
INFO:BlockProcessor:flushing to DB for a clean shutdown...                                                                                                                
```
After digging a little bit arround in the code I recogniced that a `CancelledError` is thrown inside the `_send_data` method of the client.
When I catch the error and print the stacktrace, this is the result.
```
Traceback (most recent call last):                                                                                                                                        
  File "/usr/local/lib/python3.7/site-packages/electrumX-1.8.7-py3.7.egg/electrumx/server/daemon.py", line 98, in _send_data                                              
    async with session.post(self.current_url(), data=data) as resp:                                                                                                       
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 855, in __aenter__                                                                                
    self._resp = await self._coro                                                                                                                                         
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 370, in _request                                                                                  
    timeout=timeout                                                                                                                                                       
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 445, in connect                                                                                
    proto = await self._create_connection(req, traces, timeout)                                                                                                           
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 757, in _create_connection                                                                     
    req, traces, timeout)                                                                                                                                                 
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 843, in _create_direct_connection                                                              
    traces=traces), loop=self._loop)                                                                                                                                      
concurrent.futures._base.CancelledError
```
Do you have any clue what could cause this?

**Comment by Manbearpixel** [comment]
Here is the fork and branch we are working with currently:
https://github.com/Manbearpixel/electrumx/tree/obsidian-support

Any assistance would be great! Obsidian and our additional blockchain ODIN would love to be usable on ElectrumX.

**Comment by kyuupichan** [comment]
No idea; perhaps it doesn't like the getblock call?  Can you find out what the request is.

**Comment by kyuupichan** [comment]
I think this might be fixed in git HEAD
