### ISSUE TITLE
ERROR:ElectrumX:[44] exception handling Request('blockchain.headers.subscribe', [])

### ISSUE THREAD

**Issue by vinnyvoo** [kyuupichan/electrumx#614]
What might be the reason? Happened after 5 mins of restart.

```INFO:ElectrumX:[44] SSL 142.177.219.204:64785, 7 total
ERROR:ElectrumX:[44] exception handling Request('blockchain.headers.subscribe', [])
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aiorpcx/session.py", line 186, in _throttled_request
    result = await self.handle_request(request)
  File "/usr/local/lib/python3.6/dist-packages/electrumX-1.8.7-py3.6.egg/electrumx/server/session.py", line 698, in handle_request
    return await coro
  File "/usr/local/lib/python3.6/dist-packages/electrumX-1.8.7-py3.6.egg/electrumx/server/session.py", line 811, in headers_subscribe_False
    return await self._headers_subscribe(raw)
  File "/usr/local/lib/python3.6/dist-packages/electrumX-1.8.7-py3.6.egg/electrumx/server/session.py", line 799, in _headers_subscribe
    return await self.subscribe_headers_result()
  File "/usr/local/lib/python3.6/dist-packages/electrumX-1.8.7-py3.6.egg/electrumx/server/session.py", line 793, in subscribe_headers_result
    return self.session_mgr.hsub_results[self.subscribe_headers_raw]
AttributeError: 'SessionManager' object has no attribute 'hsub_results'```

**Comment by kyuupichan** [comment]
Which coin is this?  Something with almost no mempool?

**Comment by vinnyvoo** [comment]
Its a Litecoin. I got no idea about mempool. 
But now its working fine without any restart.

**Comment by Talkless** [comment]
I've got this with Bitcoin mainnet node, after system was rebooted:
```
Oct 09 20:07:57 odroid-hc1 systemd[1]: Started Electrumx.
Oct 09 20:08:50 odroid-hc1 electrumx_server[935]: INFO:Controller:Python version: 3.6.6 (default, Jun 30 2018, 13:38:37)
Oct 09 20:08:50 odroid-hc1 electrumx_server[935]: [GCC 6.3.0 20170516]
Oct 09 20:08:50 odroid-hc1 electrumx_server[935]: INFO:Controller:software version: ElectrumX 1.8.7
Oct 09 20:08:50 odroid-hc1 electrumx_server[935]: INFO:Controller:aiorpcX version: 0.8.1
Oct 09 20:08:50 odroid-hc1 electrumx_server[935]: INFO:Controller:supported protocol versions: 1.1-1.4
Oct 09 20:08:50 odroid-hc1 electrumx_server[935]: INFO:Controller:event loop policy: None
Oct 09 20:08:50 odroid-hc1 electrumx_server[935]: INFO:Controller:reorg limit is 200 blocks
Oct 09 20:08:50 odroid-hc1 electrumx_server[935]: INFO:Daemon:daemon #1 at 127.0.0.1:8332/ (current)
Oct 09 20:08:50 odroid-hc1 electrumx_server[935]: INFO:DB:switching current directory to /home/electrumx/.electrumx
Oct 09 20:08:50 odroid-hc1 electrumx_server[935]: INFO:DB:using leveldb for DB backend
Oct 09 20:08:50 odroid-hc1 electrumx_server[935]: ERROR:Daemon:starting up checking blocks.  Retrying occasionally...
Oct 09 20:08:51 odroid-hc1 electrumx_server[935]: ERROR:Daemon:starting up checking blocks.  Retrying occasionally...
Oct 09 20:08:51 odroid-hc1 electrumx_server[935]: ERROR:Daemon:starting up checking blocks.  Retrying occasionally...
Oct 09 20:08:52 odroid-hc1 electrumx_server[935]: ERROR:Daemon:starting up checking blocks.  Retrying occasionally...
Oct 09 20:08:54 odroid-hc1 electrumx_server[935]: ERROR:Daemon:starting up checking blocks.  Retrying occasionally...
Oct 09 20:08:58 odroid-hc1 electrumx_server[935]: ERROR:Daemon:starting up checking blocks.  Retrying occasionally...
Oct 09 20:09:02 odroid-hc1 electrumx_server[935]: ERROR:Daemon:starting up checking blocks.  Retrying occasionally...
Oct 09 20:09:06 odroid-hc1 electrumx_server[935]: ERROR:Daemon:starting up checking blocks.  Retrying occasionally...
Oct 09 20:09:10 odroid-hc1 electrumx_server[935]: ERROR:Daemon:starting up checking blocks.  Retrying occasionally...
Oct 09 20:09:14 odroid-hc1 electrumx_server[935]: ERROR:Daemon:starting up checking blocks.  Retrying occasionally...
Oct 09 20:09:19 odroid-hc1 electrumx_server[935]: ERROR:Daemon:starting up checking blocks.  Retrying occasionally...
Oct 09 20:09:23 odroid-hc1 electrumx_server[935]: ERROR:Daemon:starting up checking blocks.  Retrying occasionally...
Oct 09 20:09:27 odroid-hc1 electrumx_server[935]: ERROR:Daemon:starting up checking blocks.  Retrying occasionally...
Oct 09 20:09:31 odroid-hc1 electrumx_server[935]: ERROR:Daemon:starting up checking blocks.  Retrying occasionally...
Oct 09 20:09:35 odroid-hc1 electrumx_server[935]: ERROR:Daemon:starting up checking blocks.  Retrying occasionally...
Oct 09 20:09:39 odroid-hc1 electrumx_server[935]: ERROR:Daemon:starting up checking blocks.  Retrying occasionally...
Oct 09 20:09:43 odroid-hc1 electrumx_server[935]: ERROR:Daemon:starting up checking blocks.  Retrying occasionally...
Oct 09 20:09:47 odroid-hc1 electrumx_server[935]: ERROR:Daemon:starting up checking blocks.  Retrying occasionally...
Oct 09 20:09:51 odroid-hc1 electrumx_server[935]: ERROR:Daemon:starting up checking blocks.  Retrying occasionally...
Oct 09 20:09:55 odroid-hc1 electrumx_server[935]: ERROR:Daemon:starting up checking blocks.  Retrying occasionally...
Oct 09 20:09:59 odroid-hc1 electrumx_server[935]: ERROR:Daemon:starting up checking blocks.  Retrying occasionally...
Oct 09 20:10:03 odroid-hc1 electrumx_server[935]: ERROR:Daemon:starting up checking blocks.  Retrying occasionally...
Oct 09 20:10:07 odroid-hc1 electrumx_server[935]: INFO:Daemon:running normally
Oct 09 20:10:11 odroid-hc1 electrumx_server[935]: INFO:DB:opened UTXO DB (for sync: True)
Oct 09 20:10:11 odroid-hc1 electrumx_server[935]: INFO:DB:DB version: 6
Oct 09 20:10:11 odroid-hc1 electrumx_server[935]: INFO:DB:coin: BitcoinSegwit
Oct 09 20:10:11 odroid-hc1 electrumx_server[935]: INFO:DB:network: mainnet
Oct 09 20:10:11 odroid-hc1 electrumx_server[935]: INFO:DB:height: 545,044
Oct 09 20:10:11 odroid-hc1 electrumx_server[935]: INFO:DB:tip: 0000000000000000000b9717eaa04c6d8f218586d058bb994e3b8d7c47f8f912
Oct 09 20:10:11 odroid-hc1 electrumx_server[935]: INFO:DB:tx count: 347,475,689
Oct 09 20:10:11 odroid-hc1 electrumx_server[935]: INFO:DB:flushing DB cache at 256 MB
Oct 09 20:10:12 odroid-hc1 electrumx_server[935]: INFO:History:history DB version: 0
Oct 09 20:10:12 odroid-hc1 electrumx_server[935]: INFO:History:flush count: 13,432
Oct 09 20:10:23 odroid-hc1 electrumx_server[935]: INFO:DB:deleted 416 stale undo entries
Oct 09 20:10:27 odroid-hc1 electrumx_server[935]: INFO:BlockProcessor:caught up to height 545044
Oct 09 20:10:27 odroid-hc1 electrumx_server[935]: INFO:DB:closing DBs to re-open for serving
Oct 09 20:10:28 odroid-hc1 electrumx_server[935]: INFO:DB:opened UTXO DB (for sync: False)
Oct 09 20:10:28 odroid-hc1 electrumx_server[935]: INFO:DB:DB version: 6
Oct 09 20:10:28 odroid-hc1 electrumx_server[935]: INFO:DB:coin: BitcoinSegwit
Oct 09 20:10:28 odroid-hc1 electrumx_server[935]: INFO:DB:network: mainnet
Oct 09 20:10:28 odroid-hc1 electrumx_server[935]: INFO:DB:height: 545,044
Oct 09 20:10:28 odroid-hc1 electrumx_server[935]: INFO:DB:tip: 0000000000000000000b9717eaa04c6d8f218586d058bb994e3b8d7c47f8f912
Oct 09 20:10:28 odroid-hc1 electrumx_server[935]: INFO:DB:tx count: 347,475,689
Oct 09 20:10:29 odroid-hc1 electrumx_server[935]: INFO:History:history DB version: 0
Oct 09 20:10:29 odroid-hc1 electrumx_server[935]: INFO:History:flush count: 13,432
Oct 09 20:10:29 odroid-hc1 electrumx_server[935]: INFO:DB:populating header merkle cache...
Oct 09 20:10:29 odroid-hc1 electrumx_server[935]: INFO:MemPool:beginning processing of daemon mempool.  This can take some time...
Oct 09 20:10:29 odroid-hc1 electrumx_server[935]: INFO:SessionManager:RPC server listening on localhost:8000
Oct 09 20:11:17 odroid-hc1 electrumx_server[935]: INFO:DB:header merkle cache populated in 47.7s
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]: INFO:Prefetcher:catching up to daemon height 545,045 (1 blocks behind)
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]: INFO:MemPool:compact fee histogram: []
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]: INFO:MemPool:synced in 59.58s
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]: INFO:MemPool:0 txs touching 0 addresses
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]: INFO:SessionManager:max session count: 64
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]: INFO:SessionManager:session timeout: 600 seconds
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]: INFO:SessionManager:session bandwidth limit 2,000,000 bytes
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]: INFO:SessionManager:max response size 1,000,000 bytes
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]: INFO:SessionManager:max subscriptions across all sessions: 250,000
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]: INFO:SessionManager:max subscriptions per session: 50,000
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]: INFO:SessionManager:TCP server listening on 0.0.0.0:50001
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]: INFO:SessionManager:SSL server listening on 0.0.0.0:50002
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]: INFO:PeerManager:beginning peer discovery. Force use of proxy: False
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]: INFO:PeerManager:trying to detect proxy on "localhost" ports [9050, 9150, 1080]
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]: INFO:PeerManager:accepted new peer a.b.c.d from env
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]: INFO:PeerManager:accepted new peer btc.smsys.me from env
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]: INFO:PeerManager:accepted new peer E-X.not.fyi from env
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]: INFO:PeerManager:accepted new peer elec.luggs.co from env
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]: INFO:PeerManager:accepted new peer electrum.vom-stausee.de from env
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]: INFO:PeerManager:accepted new peer electrum3.hachre.de from env
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]: INFO:PeerManager:accepted new peer electrum.hsmiths.com from env
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]: INFO:PeerManager:accepted new peer helicarrier.bauerj.eu from env
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]: INFO:PeerManager:accepted new peer node.arihanc.com from env
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]: INFO:ElectrumX:[0] SSL 192.168.2.1:45833, 1 total
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]: ERROR:ElectrumX:[0] exception handling Request('blockchain.headers.subscribe', [])
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]: Traceback (most recent call last):
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]:   File "/opt/python3.6/lib/python3.6/site-packages/aiorpcX-0.8.1-py3.6.egg/aiorpcx/session.py", line 186, in _throttled_request
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]:     result = await self.handle_request(request)
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]:   File "/opt/python3.6/lib/python3.6/site-packages/electrumX-1.8.7-py3.6.egg/electrumx/server/session.py", line 698, in handle_request
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]:     return await coro
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]:   File "/opt/python3.6/lib/python3.6/site-packages/electrumX-1.8.7-py3.6.egg/electrumx/server/session.py", line 803, in headers_subscribe
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]:     return await self._headers_subscribe(True)
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]:   File "/opt/python3.6/lib/python3.6/site-packages/electrumX-1.8.7-py3.6.egg/electrumx/server/session.py", line 799, in _headers_subscribe
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]:     return await self.subscribe_headers_result()
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]:   File "/opt/python3.6/lib/python3.6/site-packages/electrumX-1.8.7-py3.6.egg/electrumx/server/session.py", line 793, in subscribe_headers_result
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]:     return self.session_mgr.hsub_results[self.subscribe_headers_raw]
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]: AttributeError: 'SessionManager' object has no attribute 'hsub_results'
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]: ERROR:PeerManager:[a.b.c.d:50002 SSL] RPC error: internal server error (-32603)
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]: INFO:ElectrumX:[1] TCP 192.168.2.1:52525, 1 total
Oct 09 20:11:29 odroid-hc1 electrumx_server[935]: INFO:ElectrumX:[2] TCP a.b.c.d:16740, 2 total
```

It does seem that restarting electrumx daemin again, these messages disappear. But if I woundn't have it restarted (being away for example), would it be considered "working", accessable and usable? ( I should have tried to connect with my wallet...)
