### ISSUE TITLE
Crash after invalidateblock

### ISSUE THREAD

**Issue by SomberNight** [kyuupichan/electrumx#655]
On https://github.com/kyuupichan/electrumx/commit/bf279ceaea588de46d94e2ce93f38f797b2af9dc
Using Bitcoin Core 0.17, on regtest, I call invalidateblock on the tip of the chain:

```
bitcoin-cli -rpcport=18332 -regtest invalidateblock $(bitcoin-cli -rpcport=18332 -regtest getblockhash 122)
```
Then ElectrumX crashes:
```
INFO:MemPool:compact fee histogram: []
INFO:MemPool:synced in 0.01s
INFO:MemPool:0 txs touching 0 addresses
INFO:SessionManager:TCP server listening on 127.0.0.1:50001
INFO:SessionManager:SSL server listening on 127.0.0.1:50002
INFO:PeerManager:peer discovery is disabled
cp1 daemon_height 122, self.fetched_height 122, cache_room 40021
cp2 count 0
cp1 daemon_height 122, self.fetched_height 122, cache_room 40021
cp2 count 0
cp1 daemon_height 121, self.fetched_height 122, cache_room 40021
cp2 count -1
cp3 first 123, count -1, hex_hashes []
INFO:BlockProcessor:flushing to DB for a clean shutdown...
INFO:SessionManager:closing down RPC, TCP, SSL listening servers
ERROR:root:task crashed: <Task finished coro=<Controller.serve() done, defined at /home/user/wspace/electrumx/electrumx/server/controller.py:81> exception=IndexError('list index out of range',)>
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/aiorpcx/util.py", line 118, in check_task
    task.result()
  File "/home/user/wspace/electrumx/electrumx/server/controller.py", line 131, in serve
    await group.spawn(wait_for_catchup())
  File "/home/user/.local/lib/python3.6/site-packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join(wait=self._wait)
  File "/home/user/.local/lib/python3.6/site-packages/aiorpcx/curio.py", line 213, in join
    raise task.exception()
  File "/home/user/wspace/electrumx/electrumx/server/block_processor.py", line 661, in fetch_and_process_blocks
    await group.spawn(self._process_prefetched_blocks())
  File "/home/user/.local/lib/python3.6/site-packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join(wait=self._wait)
  File "/home/user/.local/lib/python3.6/site-packages/aiorpcx/curio.py", line 213, in join
    raise task.exception()
  File "/home/user/wspace/electrumx/electrumx/server/block_processor.py", line 56, in main_loop
    if not await self._prefetch_blocks():
  File "/home/user/wspace/electrumx/electrumx/server/block_processor.py", line 118, in _prefetch_blocks
    .format(first + count-1, hex_hashes[-1]))
IndexError: list index out of range
```

Introduced by https://github.com/kyuupichan/electrumx/commit/7f2f9d4b2984266eda86005797254f211f1bc4f3

**Comment by SomberNight** [comment]
After restart, I get https://github.com/kyuupichan/electrumx/issues/653
so that might be related

**Comment by kyuupichan** [comment]
OK thanks, I'll restore the max with 0
