### ISSUE TITLE
Server crashes when syncing BitcoinCashUnlimited 1.5.0.2

### ISSUE THREAD

**Issue by randydu** [kyuupichan/electrumx#661]
Electrumx 1.8.12, Ubuntu 18.04/x64.

```
INFO:DB:flush #375 took 3.0s.  Height 553,581 txs: 262,460,782 (+1,569,393)

INFO:DB:tx/sec since genesis: 1,487, since last flush: 11,222
INFO:DB:sync time: 2d 00h 59m  ETA: 03m 07s

INFO:BlockProcessor:our height: 554,744 daemon: 558,707 UTXOs 863MB hist 63MB

INFO:BlockProcessor:our height: 555,748 daemon: 558,707 UTXOs 866MB hist 125MB

INFO:BlockProcessor:our height: 556,057 daemon: 558,707 UTXOs 882MB hist 194MB

INFO:BlockProcessor:our height: 556,673 daemon: 558,707 UTXOs 897MB hist 240MB

INFO:DB:flushed filesystem data in 0.30s

INFO:History:flushed history in 1.9s for 693,173 addrs

INFO:DB:flush #376 took 2.2s.  Height 556,673 txs: 265,505,929 (+3,045,147)

INFO:DB:tx/sec since genesis: 1,503, since last flush: 18,913
INFO:DB:sync time: 2d 01h 02m  ETA: 43s

INFO:BlockProcessor:flushing to DB for a clean shutdown...

INFO:SessionManager:closing down RPC listening servers

ERROR:root:task crashed: <Task finished coro=<Controller.serve() done, defined at /electrumx/electrumx/server/controller.py:81> exception=AssertionError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiorpcx/util.py", line 118, in check_task
    task.result()
  File "/electrumx/electrumx/server/controller.py", line 131, in serve
    await group.spawn(wait_for_catchup())
  File "/usr/local/lib/python3.7/site-packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join(wait=self._wait)
  File "/usr/local/lib/python3.7/site-packages/aiorpcx/curio.py", line 213, in join
    raise task.exception()
  File "/electrumx/electrumx/server/block_processor.py", line 662, in fetch_and_process_blocks
    await self.flush(True)
  File "/electrumx/electrumx/server/block_processor.py", line 335, in flush
    await self.run_in_thread_with_lock(flush)
  File "/electrumx/electrumx/server/block_processor.py", line 191, in run_in_thread_with_lock
    return await asyncio.shield(run_in_thread_locked())
  File "/electrumx/electrumx/server/block_processor.py", line 190, in run_in_thread_locked
    return await run_in_thread(func, *args)
  File "/usr/local/lib/python3.7/site-packages/aiorpcx/curio.py", line 61, in run_in_thread
    return await get_event_loop().run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/electrumx/electrumx/server/block_processor.py", line 334, in flush
    self.estimate_txs_remaining)
  File "/electrumx/electrumx/server/db.py", line 197, in flush_dbs
    self.flush_fs(flush_data)
  File "/electrumx/electrumx/server/db.py", line 237, in flush_fs
    assert len(flush_data.block_tx_hashes) == len(flush_data.headers)
AssertionError
```
After it crashes, the server cannot restart properly, always crashing at the same point.

If I shutdown the BitcoinCash daemon, wait for a while, restart the daemon, wait for the daemon ready, then start electrumx server, it reports DB not shutdown cleanly, take some time to scan history, then it can continue syncing normally.

It occurs several times, not sure what inputs from daemon could crash the index server. 

Another time it crashes once with the following error message:
```
ERROR:root:task crashed: <Task finished coro=<Controller.serve() done, defined at /electrumx/electrumx/server/controller.py:81> exception=TypeError('string indices must be integers')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiorpcx/util.py", line 118, in check_task
    task.result()
  File "/electrumx/electrumx/server/controller.py", line 131, in serve
    await group.spawn(wait_for_catchup())
  File "/usr/local/lib/python3.7/site-packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join(wait=self._wait)
  File "/usr/local/lib/python3.7/site-packages/aiorpcx/curio.py", line 213, in join
    raise task.exception()
  File "/electrumx/electrumx/server/block_processor.py", line 658, in fetch_and_process_blocks
    await group.spawn(self._process_prefetched_blocks())
  File "/usr/local/lib/python3.7/site-packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join(wait=self._wait)
  File "/usr/local/lib/python3.7/site-packages/aiorpcx/curio.py", line 213, in join
    raise task.exception()
  File "/electrumx/electrumx/server/block_processor.py", line 56, in main_loop
    if not await self._prefetch_blocks():
  File "/electrumx/electrumx/server/block_processor.py", line 116, in _prefetch_blocks
    blocks = await daemon.raw_blocks(hex_hashes)
  File "/electrumx/electrumx/server/daemon.py", line 220, in raw_blocks
    blocks = await self._send_vector('getblock', params_iterable)
  File "/electrumx/electrumx/server/daemon.py", line 188, in _send_vector
    return await self._send(payload, processor)
  File "/electrumx/electrumx/server/daemon.py", line 131, in _send
    result = processor(result)
  File "/electrumx/electrumx/server/daemon.py", line 178, in processor
    errs = [item['error'] for item in result if item['error']]
  File "/electrumx/electrumx/server/daemon.py", line 178, in <listcomp>
    errs = [item['error'] for item in result if item['error']]
TypeError: string indices must be integers
```

**Comment by randydu** [comment]
It just crashes again on the same point: 

```
INFO:History:flushed history in 2.6s for 904,985 addrs

INFO:DB:flush #376 took 2.7s.  Height 555,243 txs: 263,554,018 (+2,012,510)
INFO:DB:tx/sec since genesis: 1,410, since last flush: 5,874
INFO:DB:sync time: 2d 03h 55m  ETA: 04m 06s

INFO:BlockProcessor:our height: 555,909 daemon: 558,787 UTXOs 868MB hist 38MB

INFO:BlockProcessor:our height: 556,057 daemon: 558,787 UTXOs 882MB hist 100MB

INFO:BlockProcessor:our height: 556,499 daemon: 558,787 UTXOs 894MB hist 132MB

INFO:BlockProcessor:our height: 556,673 daemon: 558,787 UTXOs 897MB hist 149MB

INFO:BlockProcessor:flushing to DB for a clean shutdown...
INFO:SessionManager:closing down RPC listening servers

ERROR:root:task crashed: <Task finished coro=<Controller.serve() done, defined at /electrumx/electrumx/server/controller.py:81> exception=AssertionError()>
Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/aiorpcx/util.py", line 118, in check_task
    task.result()
  File "/electrumx/electrumx/server/controller.py", line 131, in serve
    await group.spawn(wait_for_catchup())
  File "/usr/local/lib/python3.7/site-packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join(wait=self._wait)
  File "/usr/local/lib/python3.7/site-packages/aiorpcx/curio.py", line 213, in join
    raise task.exception()
  File "/electrumx/electrumx/server/block_processor.py", line 662, in fetch_and_process_blocks
    await self.flush(True)
  File "/electrumx/electrumx/server/block_processor.py", line 335, in flush
    await self.run_in_thread_with_lock(flush)
  File "/electrumx/electrumx/server/block_processor.py", line 191, in run_in_thread_with_lock
    return await asyncio.shield(run_in_thread_locked())
  File "/electrumx/electrumx/server/block_processor.py", line 190, in run_in_thread_locked
    return await run_in_thread(func, *args)
  File "/usr/local/lib/python3.7/site-packages/aiorpcx/curio.py", line 61, in run_in_thread
    return await get_event_loop().run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/electrumx/electrumx/server/block_processor.py", line 334, in flush
    self.estimate_txs_remaining)
  File "/electrumx/electrumx/server/db.py", line 197, in flush_dbs
    self.flush_fs(flush_data)
  File "/electrumx/electrumx/server/db.py", line 237, in flush_fs
    assert len(flush_data.block_tx_hashes) == len(flush_data.headers)
AssertionError
```


The BitcoinCashUnlimited daemon has the following debug messages:

```
2018-11-30 05:15:16 CheckAndAlertUnknownVersionbits: new signal detected for unknown fork (versionbit 27) - strength 6/100
2018-11-30 05:15:16 CheckAndAlertUnknownVersionbits: 18 of last 100 blocks have unexpected version. One example: 0x2fff8000
2018-11-30 05:15:16 UpdateTip: new best=000000000000000000ad54f3c08ac00e7c14429de31eaab71c8ca42dea7bdca6  height=558779 bits=402935077 log2_work=87.746781  tx=268148446  date=2018-11-30 05:11:28 progress=0.999989  cache=0.1MiB(428txo)
2018-11-30 05:15:16 CheckAndAlertUnknownVersionbits: 17 of last 100 blocks have unexpected version. One example: 0x20400000
2018-11-30 05:15:48 connect() to [2804:d41:4415:9800:759c:c730:42c7:21ed]:8333 failed: Cannot assign requested address (99)
2018-11-30 05:16:26 connect() to [2a02:908:13c6:17c0:bc00:afaf:dd89:9189]:8333 failed: Cannot assign requested address (99)
2018-11-30 05:16:33 connect() to [2002:d420:ea1b::d420:ea1b]:8333 failed: Cannot assign requested address (99)
2018-11-30 05:16:34 connect() to [2804:14c:f426:10f4:243b:6d36:bc92:7328]:8333 failed: Cannot assign requested address (99)
2018-11-30 05:16:58 Acceptable block: ver:20c00000 time:1543554988 size: 13625 Tx:37 Sig:74
2018-11-30 05:16:58 UpdateTip: new best=000000000000000001871f09b7ee2a3aa0ae7201ea0fc29981664e6e81149222  height=558780 bits=402934002 log2_work=87.746787  tx=268148483  date=2018-11-30 05:16:28 progress=0.999999  cache=0.0MiB(113txo)
2018-11-30 05:16:58 CheckAndAlertUnknownVersionbits: 18 of last 100 blocks have unexpected version. One example: 0x20400000
2018-11-30 05:17:14 connect() to [2001:268:c019:28e2:1c67:584e:cb6a:2]:8333 failed: Cannot assign requested address (99)
2018-11-30 05:17:14 connect() to [2003:cb:9701:7c00:51d0:4c31:9d0b:bbc0]:8333 failed: Cannot assign requested address (99)
2018-11-30 05:18:06 connect() to [2001:0:5cf2:8c02:30f8:5c3:f5ff:ff01]:8333 failed: Cannot assign requested address (99)
2018-11-30 05:18:06 connect() to [2620:9b::196f:9396]:8333 failed: Cannot assign requested address (99)
2018-11-30 05:18:26 connect() to [2001:0:9d38:90d7:24ce:3892:ab8a:3c94]:8333 failed: Cannot assign requested address (99)
2018-11-30 05:26:11 connect() to [2600:1f16:625:e00:f67c:d398:5b6:d34f]:8333 failed: Cannot assign requested address (99)
2018-11-30 05:28:00 Acceptable block: ver:20400000 time:1543555670 size: 22376 Tx:24 Sig:70
2018-11-30 05:28:00 UpdateTip: new best=000000000000000001fd1034226b94a65d7222cb199496f4ccb6280484e80aed  height=558781 bits=402931421 log2_work=87.746793  tx=268148507  date=2018-11-30 05:27:50 progress=1.000000  cache=0.0MiB(233txo)
2018-11-30 05:28:00 CheckAndAlertUnknownVersionbits: 19 of last 100 blocks have unexpected version. One example: 0x20400000
2018-11-30 05:29:45 ERROR: AcceptBlockHeader: block 000000000000000001d956714215d96ffc00e0afda4cd0a96c96f8d802b1662b height 556767 is marked invalid
2018-11-30 05:29:45 ERROR: AcceptBlockHeader: block 000000000000000001d956714215d96ffc00e0afda4cd0a96c96f8d802b1662b height 556767 is marked invalid
2018-11-30 05:29:46 ERROR: AcceptBlockHeader: block 000000000000000001d956714215d96ffc00e0afda4cd0a96c96f8d802b1662b height 556767 is marked invalid
2018-11-30 05:30:02 ERROR: AcceptBlockHeader: block 000000000000000001d956714215d96ffc00e0afda4cd0a96c96f8d802b1662b height 556767 is marked invalid
2018-11-30 05:50:26 Acceptable block: ver:20000000 time:1543556998 size: 72505 Tx:149 Sig:262
2018-11-30 05:50:26 UpdateTip: new best=0000000000000000028b0f1228c4f40f1fbfb8ffb1bf20eaaaf504557bb581a0  height=558782 bits=402932275 log2_work=87.746799  tx=268148656  date=2018-11-30 05:49:58 progress=0.999999  cache=0.1MiB(511txo)
2018-11-30 05:50:26 CheckAndAlertUnknownVersionbits: 18 of last 100 blocks have unexpected version. One example: 0x20800000
2018-11-30 05:51:18 connect() to [2a01:4f8:221:801::2]:8333 failed: Cannot assign requested address (99)
2018-11-30 05:52:40 Acceptable block: ver:20000000 time:1543557111 size: 12575 Tx:16 Sig:32
2018-11-30 05:52:40 UpdateTip: new best=0000000000000000041033fda759e705c3c9cd9b70f5210e3a4f89de9ebfbf49  height=558783 bits=402931768 log2_work=87.746805  tx=268148672  date=2018-11-30 05:51:51 progress=0.999998  cache=0.0MiB(122txo)
2018-11-30 05:52:40 CheckAndAlertUnknownVersionbits: 17 of last 100 blocks have unexpected version. One example: 0x20800000
2018-11-30 06:00:53 connect() to [2804:7f4:fb80:c712:3413:fb14:ab5:4db2]:8333 failed: Cannot assign requested address (99)
2018-11-30 06:22:38 connect() to [2600:1700:14b0:1120:996d:bcd1:cf3f:65bc]:8333 failed: Cannot assign requested address (99)
2018-11-30 06:22:49 Acceptable block: ver:20000000 time:1543558940 size: 78867 Tx:131 Sig:456
2018-11-30 06:22:49 UpdateTip: new best=000000000000000000805ebba1432db263d801636bd92bb3b7fdd660ef83cb98  height=558784 bits=402934988 log2_work=87.746811  tx=268148803  date=2018-11-30 06:22:20 progress=0.999999  cache=0.1MiB(958txo)
2018-11-30 06:22:49 CheckAndAlertUnknownVersionbits: 16 of last 100 blocks have unexpected version. One example: 0x20c00000
2018-11-30 06:23:53 connect() to [2a02:168:654f:0:4a7d:cae2:6c89:4926]:8333 failed: Cannot assign requested address (99)
2018-11-30 06:24:49 Acceptable block: ver:20000000 time:1543559067 size: 32115 Tx:4 Sig:4
2018-11-30 06:24:49 UpdateTip: new best=0000000000000000010abc9e21103e53e77c4a2551e1b987acb2899efce83850  height=558785 bits=402934029 log2_work=87.746817  tx=268148807  date=2018-11-30 06:24:27 progress=0.999999  cache=0.0MiB(112txo)
2018-11-30 06:24:49 CheckAndAlertUnknownVersionbits: 16 of last 100 blocks have unexpected version. One example: 0x20c00000
2018-11-30 06:28:16 connect() to [2001:0:9d38:953c:34f6:7b42:e7b5:af7b]:8333 failed: Cannot assign requested address (99)
2018-11-30 06:30:27 ERROR: AcceptBlockHeader: block 000000000000000001d956714215d96ffc00e0afda4cd0a96c96f8d802b1662b height 556767 is marked invalid
2018-11-30 06:30:30 ERROR: AcceptBlockHeader: block 000000000000000001d956714215d96ffc00e0afda4cd0a96c96f8d802b1662b height 556767 is marked invalid
2018-11-30 06:30:40 Acceptable block: ver:20000000 time:1543559413 size: 43239 Tx:40 Sig:68
2018-11-30 06:30:40 UpdateTip: new best=00000000000000000207b3f710abe7a9b7e0c0ab878202a4576b757df0d9e011  height=558786 bits=402938703 log2_work=87.746824  tx=268148847  date=2018-11-30 06:30:13 progress=0.999999  cache=0.0MiB(226txo)
2018-11-30 06:30:40 CheckAndAlertUnknownVersionbits: 16 of last 100 blocks have unexpected version. One example: 0x20c00000
2018-11-30 06:34:17 ERROR: AcceptBlockHeader: block 000000000000000001d956714215d96ffc00e0afda4cd0a96c96f8d802b1662b height 556767 is marked invalid
2018-11-30 06:34:19 ERROR: AcceptBlockHeader: block 000000000000000001d956714215d96ffc00e0afda4cd0a96c96f8d802b1662b height 556767 is marked invalid
2018-11-30 06:37:19 ERROR: AcceptBlockHeader: block 000000000000000001d956714215d96ffc00e0afda4cd0a96c96f8d802b1662b height 556767 is marked invalid
2018-11-30 06:37:21 ERROR: AcceptBlockHeader: block 000000000000000001d956714215d96ffc00e0afda4cd0a96c96f8d802b1662b height 556767 is marked invalid
2018-11-30 06:37:21 ERROR: AcceptBlockHeader: block 000000000000000001d956714215d96ffc00e0afda4cd0a96c96f8d802b1662b height 556767 is marked invalid
2018-11-30 06:37:22 ERROR: AcceptBlockHeader: block 000000000000000001d956714215d96ffc00e0afda4cd0a96c96f8d802b1662b height 556767 is marked invalid
2018-11-30 06:41:44 Acceptable block: ver:20000000 time:1543560037 size: 77406 Tx:61 Sig:110
2018-11-30 06:41:44 UpdateTip: new best=000000000000000003a1d43effd7b6e25b7812f4b0462a19f7a579c918d920e1  height=558787 bits=402938765 log2_work=87.74683  tx=268148908  date=2018-11-30 06:40:37 progress=0.999997  cache=0.1MiB(465txo)
2018-11-30 06:41:44 CheckAndAlertUnknownVersionbits: 16 of last 100 blocks have unexpected version. One example: 0x20c00000
2018-11-30 06:43:06 ERROR: AcceptBlockHeader: block 000000000000000001d956714215d96ffc00e0afda4cd0a96c96f8d802b1662b height 556767 is marked invalid
2018-11-30 06:43:10 ERROR: AcceptBlockHeader: block 000000000000000001d956714215d96ffc00e0afda4cd0a96c96f8d802b1662b height 556767 is marked invalid
2018-11-30 06:45:51 connect() to [2408:8214:118:fd0:13a1:955e:9c08:3d28]:8333 failed: Cannot assign requested address (99)
2018-11-30 06:49:27 Acceptable block: ver:20000000 time:1543560548 size: 85722 Tx:49 Sig:105
2018-11-30 06:49:28 UpdateTip: new best=00000000000000000263e7841124b089ea2436bce31ae4fb3bd992acdc070604  height=558788 bits=402934480 log2_work=87.746836  tx=268148957  date=2018-11-30 06:49:08 progress=0.999999  cache=0.1MiB(634txo)
2018-11-30 06:49:28 CheckAndAlertUnknownVersionbits: 16 of last 100 blocks have unexpected version. One example: 0x20c00000
2018-11-30 06:50:39 Acceptable block: ver:20000000 time:1543560614 size: 693 Tx:2 Sig:5
2018-11-30 06:50:39 UpdateTip: new best=000000000000000003639f957df276f01a563b32fc54ff8ae37747ae181b95ca  height=558789 bits=402935841 log2_work=87.746842  tx=268148959  date=2018-11-30 06:50:14 progress=0.999999  cache=0.0MiB(185txo)
2018-11-30 06:50:39 CheckAndAlertUnknownVersionbits: 16 of last 100 blocks have unexpected version. One example: 0x20c00000
```

Really messy messages, is it possible the built-in coin "BitcoinCash" of electrumx cannot parse the recent fork block #556767 properly? 

The daemon rpc getinfo =>
```
{
  "version": 1050002,
  "protocolversion": 80003,
  "walletversion": 60000,
  "balance": 0.00000000,
  "blocks": 558791,
  "timeoffset": 0,
  "connections": 16,
  "proxy": "",
  "difficulty": 256742196083.8324,
  "testnet": false,
  "keypoololdest": 1524370527,
  "keypoolsize": 101,
  "paytxfee": 0.00000000,
  "relayfee": 0.00000000,
  "status": "ready",
  "errors": "",
  "fork": "Bitcoin Cash"
}
```

I will try restart the daemon and electrumx to see if the block #556767 can be parsed.

**Comment by randydu** [comment]
I just noticed everytime after crash the server restarts syncing from the same height: "512,729", so the fork block #556767 cannot be passed.

```INFO:DB:using leveldb for DB backend
INFO:DB:opened UTXO DB (for sync: True)
INFO:DB:DB version: 6
INFO:DB:coin: BitcoinCash
INFO:DB:network: mainnet
INFO:DB:height: 512,729
INFO:DB:tip: 000000000000000001737461a98c3dec39e8c27766f1166f26aabb2313864607
INFO:DB:tx count: 246,695,069
INFO:DB:flushing DB cache at 1,200 MB
INFO:DB:sync time so far: 2d 03h 55m
INFO:History:history DB version: 0
INFO:History:flush count: 376
INFO:History:DB shut down uncleanly.  Scanning for excess history flushes...
INFO:Controller:Python version: 3.7.1 (default, Nov 16 2018, 06:29:01) 
[GCC 6.4.0]
INFO:Controller:software version: ElectrumX 1.8.12
INFO:Controller:aiorpcX version: 0.10.1
INFO:Controller:supported protocol versions: 1.2-1.4
INFO:Controller:event loop policy: None
INFO:Controller:reorg limit is 200 blocks
INFO:Daemon:daemon #1 at bch:8332/ (current)
INFO:DB:switching current directory to /data
INFO:DB:using leveldb for DB backend
INFO:DB:opened UTXO DB (for sync: True)
INFO:DB:DB version: 6
INFO:DB:coin: BitcoinCash
INFO:DB:network: mainnet
**INFO:DB:height: 512,729**
INFO:DB:tip: 000000000000000001737461a98c3dec39e8c27766f1166f26aabb2313864607
INFO:DB:tx count: 246,695,069
INFO:DB:flushing DB cache at 1,200 MB
INFO:DB:sync time so far: 2d 03h 55m
INFO:History:history DB version: 0
INFO:History:flush count: 376
INFO:History:DB shut down uncleanly.  Scanning for excess history flushes...
```

Which "coin" of electrumx 1.8.12 can be used to sync BitcoinCash-ABC? the coin "BitcoinCash" used to work properly before the latest fork.

Anyone can recommend a proper daemon version that can work with electrumx?

**Comment by randydu** [comment]
The latest src code lib/coins.py adds a new coin "BitcoinCashABC", it can sync the BCH-ABC successfully!

The original "BitcoinCash" should be compatible with BCH-SV.

So it seems Electrumx now support both BCH-ABC and BCH-SV ;-)

```
INFO:LTORBlockProcessor:our height: 556,507 daemon: 558,796 UTXOs 894MB hist 44MB

INFO:LTORBlockProcessor:our height: 556,714 daemon: 558,796 UTXOs 895MB hist 63MB

INFO:LTORBlockProcessor:our height: 557,144 daemon: 558,796 UTXOs 920MB hist 141MB

INFO:LTORBlockProcessor:our height: 557,919 daemon: 558,796 UTXOs 952MB hist 247MB

INFO:DB:flushed filesystem data in 0.56s

INFO:History:flushed history in 2.2s for 733,838 addrs

INFO:DB:flush #377 took 2.8s.  Height 557,919 txs: 268,091,074 (+3,009,539)

INFO:DB:tx/sec since genesis: 1,415, since last flush: 14,807
INFO:DB:sync time: 2d 04h 36m  ETA: 26s

INFO:LTORBlockProcessor:our height: 558,619 daemon: 558,796 UTXOs 965MB hist 31MB

INFO:LTORBlockProcessor:caught up to height 558796

INFO:DB:flushed filesystem data in 0.00s

INFO:History:flushed history in 0.4s for 184,965 addrs

INFO:DB:flushed 46,067 blocks with 21,454,375 txs, 3,149,050 UTXO adds, 2,794,843 spends in 14.0s, committing...

INFO:DB:flush #378 took 34.7s.  Height 558,796 txs: 268,149,444 (+58,370)

INFO:DB:tx/sec since genesis: 1,415, since last flush: 829
INFO:DB:sync time: 2d 04h 38m  ETA: 00s

INFO:LTORBlockProcessor:ElectrumX 1.8.12 synced to height 558,796

INFO:DB:closing DBs to re-open for serving
```
