### ISSUE TITLE
Crash when syncing BU 1.5.0.2 /SV fork 

### ISSUE THREAD

**Issue by randydu** [kyuupichan/electrumx#662]
Electrumx 1.8.12, Python 3.7

Trying to sync BitcoinCashUnlimited 1.5.0.2 with SV fork option on. The client has streamed the latest BSV block #558839, its config has turned on the SV fork settings:  
```
#https://github.com/BitcoinUnlimited/BitcoinUnlimited/blob/dev/doc/bip135-guide.md
consensus.forkNov2018Time=0
consensus.svForkNov2018Time=1
```

However, with coin set to "BitcoinCash", the server ElectrumX 1.8.12 cannot pass the fork block #556767, the error messages are:

```
INFO:DB:sync time: 1d 01h 20m  ETA: 11m 26s
INFO:BlockProcessor:our height: 554,728 daemon: 558,839 UTXOs 207MB hist 27MB
INFO:BlockProcessor:our height: 554,957 daemon: 558,839 UTXOs 212MB hist 56MB
INFO:BlockProcessor:our height: 555,432 daemon: 558,839 UTXOs 222MB hist 82MB
INFO:BlockProcessor:our height: 555,909 daemon: 558,839 UTXOs 232MB hist 106MB
INFO:BlockProcessor:our height: 556,057 daemon: 558,839 UTXOs 248MB hist 168MB
INFO:BlockProcessor:our height: 556,499 daemon: 558,839 UTXOs 272MB hist 199MB
INFO:BlockProcessor:our height: 556,673 daemon: 558,839 UTXOs 285MB hist 215MB
INFO:BlockProcessor:flushing to DB for a clean shutdown...
INFO:DB:flushed filesystem data in 0.26s
INFO:History:flushed history in 2.0s for 600,865 addrs
INFO:DB:flushed 10,674 blocks with 9,579,233 txs, 813,514 UTXO adds, 1,070,259 spends in 5.0s, committing...
INFO:DB:flush #362 took 13.9s.  Height 556,753 txs: 265,524,707 (+2,960,953)
INFO:DB:tx/sec since genesis: 2,896, since last flush: 7,170
INFO:DB:sync time: 1d 01h 27m  ETA: 01m 58s
INFO:SessionManager:closing down RPC listening servers

ERROR:root:task crashed: <Task finished coro=<Controller.serve() done, defined at /electrumx/electrumx/server/controller.py:81> exception=TypeError('string indices must be integers')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiorpcx/util.py", line 118, in check_task
    task.result()
  File "/electrumx/electrumx/server/controller.py", line 131, in serve
    await group.spawn(wait_for_catchup())
  File "/usr/local/lib/python3.7/site-packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join(wait=self._wait)
  File "/usr/local/lib/python3.7/site-packages/aiorpcx/curio.py", line 213, in join
    raise task.exception()
  File "/electrumx/electrumx/server/block_processor.py", line 658, in fetch_and_process_blocks
    await group.spawn(self._process_prefetched_blocks())
  File "/usr/local/lib/python3.7/site-packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join(wait=self._wait)
  File "/usr/local/lib/python3.7/site-packages/aiorpcx/curio.py", line 213, in join
    raise task.exception()
  File "/electrumx/electrumx/server/block_processor.py", line 56, in main_loop
    if not await self._prefetch_blocks():
  File "/electrumx/electrumx/server/block_processor.py", line 116, in _prefetch_blocks
    blocks = await daemon.raw_blocks(hex_hashes)
  File "/electrumx/electrumx/server/daemon.py", line 220, in raw_blocks
    blocks = await self._send_vector('getblock', params_iterable)
  File "/electrumx/electrumx/server/daemon.py", line 188, in _send_vector
    return await self._send(payload, processor)
  File "/electrumx/electrumx/server/daemon.py", line 131, in _send
    result = processor(result)
  File "/electrumx/electrumx/server/daemon.py", line 178, in processor
    errs = [item['error'] for item in result if item['error']]
  File "/electrumx/electrumx/server/daemon.py", line 178, in <listcomp>
    errs = [item['error'] for item in result if item['error']]
TypeError: string indices must be integers

```

How can I sync BSV with ElectrumX ?

**Comment by randydu** [comment]
Restart the server after crashes several times, every time I can see some block advances, finally it catches up with the latest blockchain.
