### ISSUE TITLE
AttributeError: 'BatchRequest' object has no attribute 'CHUNK_SIZE'

### ISSUE THREAD

**Issue by shsmith** [kyuupichan/electrumx#67]
Updated to 0.8.7 and started getting this new exception:

> ERROR:ElectrumX:[221] error handling request <lib.jsonrpc.BatchRequest object at 0x7f80da80af60>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.8.7-py3.5.egg/server/protocol.py", line 623, in serve_requests
    await request.process()
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.8.7-py3.5.egg/lib/jsonrpc.py", line 48, in process
    for n in range(self.CHUNK_SIZE):
AttributeError: 'BatchRequest' object has no attribute 'CHUNK_SIZE'

I reverted to 0.8.6 and things are back to normal.

**Comment by kyuupichan** [comment]
It's a typo, declared as CUHNK_SIZE
