### ISSUE TITLE
Flushing DB for a clean shutdown loop?

### ISSUE THREAD

**Issue by Manbearpixel** [kyuupichan/electrumx#671]
Sometime last night it seems my ElectrumX instance went to suddenly shutdown for no reason. Thinking this was something off, I attempted to reboot it but it hit the same command. I'm running it daemonized via `systemctl` and this solution has been working fine for the past month so I'm not sure what is different now suddenly. I've included my logs below, hopefully I can be directed to a better way to troubleshoot this? Thanks in advance!

Initial random shutdown, triggered a task error:
```
Dec 16 11:14:52 ODN-Electrum2 electrumx_server[24891]: INFO:BlockProcessor:processed 1 block in 0.0s
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]: INFO:Prefetcher:new block height 114,481 hash 50234c567988f6f93498c568bb609b196844fe9ac5e467cbe29a416bd76f5a56
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]: INFO:BlockProcessor:flushing to DB for a clean shutdown...
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]: INFO:SessionManager:closing down RPC, TCP, SSL listening servers
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]: ERROR:root:task crashed: <Task finished coro=<Controller.serve() done, defined at /usr/local/lib/python3.7/site-packages/electrumX-1.8.7-py3.7.egg/electrumx/server/controller.py:79> exception=error("'H' format requires 0 <= number <= 65535")>
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]: Traceback (most recent call last):
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]:   File "/usr/local/lib/python3.7/site-packages/aiorpcx/util.py", line 118, in check_task
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]:     task.result()
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]:   File "/usr/local/lib/python3.7/site-packages/electrumX-1.8.7-py3.7.egg/electrumx/server/controller.py", line 129, in serve
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]:     serve_externally_event.set()
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]:   File "/usr/local/lib/python3.7/site-packages/aiorpcx/curio.py", line 241, in __aexit__
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]:     await self.join(wait=self._wait)
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]:   File "/usr/local/lib/python3.7/site-packages/aiorpcx/curio.py", line 214, in join
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]:     raise task.exception()
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]:   File "/usr/local/lib/python3.7/site-packages/electrumX-1.8.7-py3.7.egg/electrumx/server/block_processor.py", line 664, in fetch_and_process_blocks
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]:     await self.flush(True)
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]:   File "/usr/local/lib/python3.7/site-packages/electrumX-1.8.7-py3.7.egg/electrumx/server/block_processor.py", line 335, in flush
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]:     await self.run_in_thread_with_lock(flush)
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]:   File "/usr/local/lib/python3.7/site-packages/electrumX-1.8.7-py3.7.egg/electrumx/server/block_processor.py", line 191, in run_in_thread_with_lock
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]:     return await asyncio.shield(run_in_thread_locked())
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]:   File "/usr/local/lib/python3.7/site-packages/electrumX-1.8.7-py3.7.egg/electrumx/server/block_processor.py", line 190, in run_in_thread_locked
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]:     return await run_in_thread(func, *args)
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]:   File "/usr/local/lib/python3.7/site-packages/aiorpcx/curio.py", line 61, in run_in_thread
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]:     return await get_event_loop().run_in_executor(None, func, *args)
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]:   File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]:     result = self.fn(*self.args, **self.kwargs)
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]:   File "/usr/local/lib/python3.7/site-packages/electrumX-1.8.7-py3.7.egg/electrumx/server/block_processor.py", line 334, in flush
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]:     self.estimate_txs_remaining)
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]:   File "/usr/local/lib/python3.7/site-packages/electrumX-1.8.7-py3.7.egg/electrumx/server/db.py", line 200, in flush_dbs
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]:     self.flush_history()
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]:   File "/usr/local/lib/python3.7/site-packages/electrumX-1.8.7-py3.7.egg/electrumx/server/db.py", line 269, in flush_history
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]:     self.history.flush()
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]:   File "/usr/local/lib/python3.7/site-packages/electrumX-1.8.7-py3.7.egg/electrumx/server/history.py", line 129, in flush
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]:     flush_id = pack_be_uint16(self.flush_count)
Dec 16 11:15:07 ODN-Electrum2 electrumx_server[24891]: struct.error: 'H' format requires 0 <= number <= 65535
```
After seeing this I manually stopped the service with `service electrumx stop` and then started it up again with `service electrumx start`.
```
Dec 16 19:02:51 ODN-Electrum2 systemd[1]: Stopping Electrumx...
Dec 16 19:02:51 ODN-Electrum2 electrumx_server[24891]: WARNING:Controller:received SIGTERM signal, initiating shutdown
Dec 16 19:02:51 ODN-Electrum2 electrumx_server[24891]: INFO:Controller:shutting down
Dec 16 19:02:51 ODN-Electrum2 electrumx_server[24891]: INFO:Controller:shutdown complete
Dec 16 19:02:52 ODN-Electrum2 systemd[1]: Stopped Electrumx.
Dec 16 19:02:59 ODN-Electrum2 systemd[1]: Started Electrumx.
Dec 16 19:03:00 ODN-Electrum2 electrumx_server[2427]: INFO:Controller:Python version: 3.7.0 (default, Sep 21 2018, 09:35:28)
Dec 16 19:03:00 ODN-Electrum2 electrumx_server[2427]: [GCC 5.4.0 20160609]
Dec 16 19:03:00 ODN-Electrum2 electrumx_server[2427]: INFO:Controller:software version: ElectrumX 1.8.7
Dec 16 19:03:00 ODN-Electrum2 electrumx_server[2427]: INFO:Controller:aiorpcX version: 0.8.1
Dec 16 19:03:00 ODN-Electrum2 electrumx_server[2427]: INFO:Controller:supported protocol versions: 1.1-1.4
Dec 16 19:03:00 ODN-Electrum2 electrumx_server[2427]: INFO:Controller:event loop policy: None
Dec 16 19:03:00 ODN-Electrum2 electrumx_server[2427]: INFO:Controller:reorg limit is 5,000 blocks
Dec 16 19:03:00 ODN-Electrum2 electrumx_server[2427]: INFO:DashDaemon:daemon #1 at localhost:22101/ (current)
Dec 16 19:03:00 ODN-Electrum2 electrumx_server[2427]: INFO:DB:switching current directory to /home/electrumx/Odin
Dec 16 19:03:00 ODN-Electrum2 electrumx_server[2427]: INFO:DB:using leveldb for DB backend
Dec 16 19:03:00 ODN-Electrum2 electrumx_server[2427]: INFO:DB:opened UTXO DB (for sync: True)
Dec 16 19:03:00 ODN-Electrum2 electrumx_server[2427]: INFO:DB:DB version: 6
Dec 16 19:03:00 ODN-Electrum2 electrumx_server[2427]: INFO:DB:coin: Odin
Dec 16 19:03:00 ODN-Electrum2 electrumx_server[2427]: INFO:DB:network: mainnet
Dec 16 19:03:00 ODN-Electrum2 electrumx_server[2427]: INFO:DB:height: 114,480
Dec 16 19:03:00 ODN-Electrum2 electrumx_server[2427]: INFO:DB:tip: 82d25d10c39e08638f701871991c125233003b5e20de485da366071f00208f7e
Dec 16 19:03:00 ODN-Electrum2 electrumx_server[2427]: INFO:DB:tx count: 234,650
Dec 16 19:03:00 ODN-Electrum2 electrumx_server[2427]: INFO:DB:flushing DB cache at 1,200 MB
Dec 16 19:03:00 ODN-Electrum2 electrumx_server[2427]: INFO:History:history DB version: 0
Dec 16 19:03:00 ODN-Electrum2 electrumx_server[2427]: INFO:History:flush count: 65,535
Dec 16 19:03:00 ODN-Electrum2 electrumx_server[2427]: INFO:DB:deleted 50,676 stale undo entries
Dec 16 19:03:00 ODN-Electrum2 electrumx_server[2427]: INFO:Prefetcher:catching up to daemon height 114,956 (476 blocks behind)
Dec 16 19:03:00 ODN-Electrum2 electrumx_server[2427]: INFO:SessionManager:RPC server listening on localhost:8000
Dec 16 19:03:00 ODN-Electrum2 electrumx_server[2427]: INFO:BlockProcessor:our height: 114,490 daemon: 114,956 UTXOs 0MB hist 0MB
Dec 16 19:03:00 ODN-Electrum2 electrumx_server[2427]: INFO:BlockProcessor:processed 10 blocks in 0.0s
Dec 16 19:03:01 ODN-Electrum2 electrumx_server[2427]: INFO:BlockProcessor:processed 466 blocks in 0.1s
Dec 16 19:03:01 ODN-Electrum2 electrumx_server[2427]: INFO:BlockProcessor:caught up to height 114956
Dec 16 19:03:01 ODN-Electrum2 electrumx_server[2427]: INFO:DB:flushed filesystem data in 0.00s
Dec 16 19:03:01 ODN-Electrum2 electrumx_server[2427]: INFO:BlockProcessor:flushing to DB for a clean shutdown...
Dec 16 19:03:01 ODN-Electrum2 electrumx_server[2427]: INFO:DB:flushed filesystem data in 0.00s
```

Then it declared `INFO:BlockProcessor:flushing to DB for a clean shutdown...` again sporadically. I don't have anything running that should be terminating this program automatically.

**Comment by Manbearpixel** [comment]
I've created a new folder and started from scratch and it appears to be working now. Still not sure what happened before. I hope there is a way I can debug what's going on behind the scenes to make sure it doesn't happen again in the future 👍
