### ISSUE TITLE
[BTC][TESTNET] history.py self.flush_count  expected to be in range 0-65535

### ISSUE THREAD

**Issue by cluelessperson** [kyuupichan/electrumx#679]
```Dec 31 00:51:12 bitcoin electrumx_server[12131]: INFO:BlockProcessor:processed 17 blocks in 0.3s
Dec 31 00:51:13 bitcoin electrumx_server[12131]: INFO:BlockProcessor:processed 20 blocks in 0.7s
Dec 31 00:51:14 bitcoin electrumx_server[12131]: INFO:BlockProcessor:processed 14 blocks in 0.3s
Dec 31 00:51:16 bitcoin electrumx_server[12131]: INFO:BlockProcessor:our height: 1,381,416 daemon: 1,450,220 UTXOs 11MB hist 346MB
Dec 31 00:51:17 bitcoin electrumx_server[12131]: INFO:DB:flushed filesystem data in 0.69s
Dec 31 00:51:17 bitcoin electrumx_server[12131]: INFO:BlockProcessor:flushing to DB for a clean shutdown...
Dec 31 00:51:17 bitcoin electrumx_server[12131]: INFO:DB:flushed filesystem data in 0.00s
Dec 31 00:51:17 bitcoin electrumx_server[12131]: INFO:SessionManager:closing down RPC listening servers
Dec 31 00:51:17 bitcoin electrumx_server[12131]: ERROR:root:task crashed: <Task finished coro=<Controller.serve() done, defined at /opt/electrumx_venv/lib/python3.7/site-packages/electrumx/server/controller.py:81> exception=error("'H' format requires 0 <= number <= 65535")>
Dec 31 00:51:17 bitcoin electrumx_server[12131]: Traceback (most recent call last):
Dec 31 00:51:17 bitcoin electrumx_server[12131]:   File "/opt/electrumx_venv/lib/python3.7/site-packages/aiorpcx/util.py", line 118, in check_task
Dec 31 00:51:17 bitcoin electrumx_server[12131]:     task.result()
Dec 31 00:51:17 bitcoin electrumx_server[12131]:   File "/opt/electrumx_venv/lib/python3.7/site-packages/electrumx/server/controller.py", line 134, in serve
Dec 31 00:51:17 bitcoin electrumx_server[12131]:     await group.spawn(wait_for_catchup())
Dec 31 00:51:17 bitcoin electrumx_server[12131]:   File "/opt/electrumx_venv/lib/python3.7/site-packages/aiorpcx/curio.py", line 231, in __aexit__
Dec 31 00:51:17 bitcoin electrumx_server[12131]:     await self.join()
Dec 31 00:51:17 bitcoin electrumx_server[12131]:   File "/opt/electrumx_venv/lib/python3.7/site-packages/aiorpcx/curio.py", line 200, in join
Dec 31 00:51:17 bitcoin electrumx_server[12131]:     raise task.exception()
Dec 31 00:51:17 bitcoin electrumx_server[12131]:   File "/opt/electrumx_venv/lib/python3.7/site-packages/electrumx/server/block_processor.py", line 662, in fetch_and_process_blocks
Dec 31 00:51:17 bitcoin electrumx_server[12131]:     await self.flush(True)
Dec 31 00:51:17 bitcoin electrumx_server[12131]:   File "/opt/electrumx_venv/lib/python3.7/site-packages/electrumx/server/block_processor.py", line 335, in flush
Dec 31 00:51:17 bitcoin electrumx_server[12131]:     await self.run_in_thread_with_lock(flush)
Dec 31 00:51:17 bitcoin electrumx_server[12131]:   File "/opt/electrumx_venv/lib/python3.7/site-packages/electrumx/server/block_processor.py", line 191, in run_in_thread_with_lock
Dec 31 00:51:17 bitcoin electrumx_server[12131]:     return await asyncio.shield(run_in_thread_locked())
Dec 31 00:51:17 bitcoin electrumx_server[12131]:   File "/opt/electrumx_venv/lib/python3.7/site-packages/electrumx/server/block_processor.py", line 190, in run_in_thread_locked
Dec 31 00:51:17 bitcoin electrumx_server[12131]:     return await run_in_thread(func, *args)
Dec 31 00:51:17 bitcoin electrumx_server[12131]:   File "/opt/electrumx_venv/lib/python3.7/site-packages/aiorpcx/curio.py", line 61, in run_in_thread
Dec 31 00:51:17 bitcoin electrumx_server[12131]:     return await get_event_loop().run_in_executor(None, func, *args)
Dec 31 00:51:17 bitcoin electrumx_server[12131]:   File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Dec 31 00:51:17 bitcoin electrumx_server[12131]:     result = self.fn(*self.args, **self.kwargs)
Dec 31 00:51:17 bitcoin electrumx_server[12131]:   File "/opt/electrumx_venv/lib/python3.7/site-packages/electrumx/server/block_processor.py", line 334, in flush
Dec 31 00:51:17 bitcoin electrumx_server[12131]:     self.estimate_txs_remaining)
Dec 31 00:51:17 bitcoin electrumx_server[12131]:   File "/opt/electrumx_venv/lib/python3.7/site-packages/electrumx/server/db.py", line 200, in flush_dbs
Dec 31 00:51:17 bitcoin electrumx_server[12131]:     self.flush_history()
Dec 31 00:51:17 bitcoin electrumx_server[12131]:   File "/opt/electrumx_venv/lib/python3.7/site-packages/electrumx/server/db.py", line 269, in flush_history
Dec 31 00:51:17 bitcoin electrumx_server[12131]:     self.history.flush()
Dec 31 00:51:17 bitcoin electrumx_server[12131]:   File "/opt/electrumx_venv/lib/python3.7/site-packages/electrumx/server/history.py", line 129, in flush
Dec 31 00:51:17 bitcoin electrumx_server[12131]:     flush_id = pack_be_uint16(self.flush_count)
Dec 31 00:51:17 bitcoin electrumx_server[12131]: struct.error: 'H' format requires 0 <= number <= 65535
```

**Comment by cluelessperson** [comment]
Ah, duplicate of https://github.com/kyuupichan/electrumx/issues/185
