### ISSUE TITLE
electrumx Start Error

### ISSUE THREAD

**Issue by mariajohnfranklin** [kyuupichan/electrumx#695]
Please help to fix this issue?

 electrumx_server[20055]: INFO:Controller:Python version: 3.6.7 (default, Oct 22 2018, 11:32:17)
 electrumx_server[20055]: [GCC 8.2.0]
 electrumx_server[20055]: INFO:Controller:software version: ElectrumX 1.9.1
 electrumx_server[20055]: INFO:Controller:aiorpcX version: 0.10.2
 electrumx_server[20055]: INFO:Controller:supported protocol versions: 1.4-1.4
 electrumx_server[20055]: INFO:Controller:event loop policy: None
 electrumx_server[20055]: INFO:Controller:reorg limit is 200 blocks
 electrumx_server[20055]: INFO:Daemon:daemon #1 at 127.0.0.1:9999/ (current)
 electrumx_server[20055]: INFO:DB:switching current directory to /electrumx/db/db_directory
 electrumx_server[20055]: INFO:DB:using leveldb for DB backend
 electrumx_server[20055]: ERROR:root:task crashed: <Task finished coro=<Controller.serve() done, defined at /electrumx/electrumx/electrumx/server/controller.py
 electrumx_server[20055]: Traceback (most recent call last):
 electrumx_server[20055]:   File "/usr/local/lib/python3.6/dist-packages/aiorpcX-0.10.2-py3.6.egg/aiorpcx/util.py", line 118, in check_task
 electrumx_server[20055]:     task.result()
 electrumx_server[20055]:   File "/electrumx/electrumx/electrumx/server/controller.py", line 134, in serve
 electrumx_server[20055]:     await group.spawn(wait_for_catchup())
 electrumx_server[20055]:   File "/usr/local/lib/python3.6/dist-packages/aiorpcX-0.10.2-py3.6.egg/aiorpcx/curio.py", line 231, in __aexit__
 electrumx_server[20055]:     await self.join()
 electrumx_server[20055]:   File "/usr/local/lib/python3.6/dist-packages/aiorpcX-0.10.2-py3.6.egg/aiorpcx/curio.py", line 200, in join
 electrumx_server[20055]:     raise task.exception()
 electrumx_server[20055]:   File "/electrumx/electrumx/electrumx/server/block_processor.py", line 654, in fetch_and_process_blocks
 electrumx_server[20055]:     await self._first_open_dbs()
 electrumx_server[20055]:   File "/electrumx/electrumx/electrumx/server/block_processor.py", line 634, in _first_open_dbs
 electrumx_server[20055]:     await self.db.open_for_sync()
 electrumx_server[20055]:   File "/electrumx/electrumx/electrumx/server/db.py", line 146, in open_for_sync
 electrumx_server[20055]:     await self._open_dbs(True, False)
 electrumx_server[20055]:   File "/electrumx/electrumx/electrumx/server/db.py", line 113, in _open_dbs
 electrumx_server[20055]:     self.utxo_db = self.db_class('utxo', for_sync)
 electrumx_server[20055]:   File "/electrumx/electrumx/electrumx/server/storage.py", line 31, in __init__
 electrumx_server[20055]:     self.open(name, create=self.is_new)
 electrumx_server[20055]:   File "/electrumx/electrumx/electrumx/server/storage.py", line 83, in open
 electrumx_server[20055]:     max_open_files=mof)
 electrumx_server[20055]:   File "plyvel/_plyvel.pyx", line 247, in plyvel._plyvel.DB.__init__
 electrumx_server[20055]:   File "plyvel/_plyvel.pyx", line 88, in plyvel._plyvel.raise_for_status
 electrumx_server[20055]: plyvel._plyvel.IOError: b'IO error: utxo/LOCK: No such file or directory'

**Comment by kyuupichan** [comment]
Try deleting the DB directory

**Comment by mariajohnfranklin** [comment]
It's a permission issue. I gave permission to  db_directory now it's working.

Now the TCP port not working plz help to fix this.
I have added TCP_PORT = 22000 in electrumx.conf
and restarted electrumx but 22000 port not working. But RPC port(8000) working
