### ISSUE TITLE
Windows7 + MSYS + Python 3.6 -- Getting this asyncio:Future exception was never retrieved

### ISSUE THREAD

**Issue by cculianu** [kyuupichan/electrumx#725]
Note: I'm running my ElectrumX server on Windows 7 (don't laugh) because that's the only box I have that's free.  I got it all to work and it's been running great for months.  But after synching to your new commits, I get the following exceptions.. and I think it's related to this commit: 7f1096ae530b464677481b91e358dd0a774f3bcd

If I revert the above commit in my git, everything works 100% as before.  With the above commit, I get the following exceptions (this is with PYTHONASYNCIODEBUG=1)

---

```
socket.gaierror: [Errno 8] Name or service not known
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=gaierror(8, 'Name or service not known') created at /usr/lib/python3.6/asyncio/base_events.py:276>
source_traceback: Object created at (most recent call last):
  File "electrumx_server", line 39, in <module>
    main()
  File "electrumx_server", line 30, in main
    controller.run()
  File "/d/ElectronX/electrumx/lib/server_base.py", line 111, in run
    loop.run_until_complete(self._main(loop))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 455, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 422, in run_forever
    self._run_once()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1426, in _run_once
    handle._run()
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 126, in send
    return self.gen.send(value)
  File "/d/ElectronX/electrumx/server/peers.py", line 196, in _monitor_peer
    if await self._should_drop_peer(peer):
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/d/ElectronX/electrumx/server/peers.py", line 238, in _should_drop_peer
    **kwargs) as session:
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/usr/lib/python3.6/site-packages/aiorpcx/session.py", line 69, in __aenter__
    _transport, self.protocol = await self.create_connection()
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/usr/lib/python3.6/site-packages/aiorpcx/session.py", line 66, in create_connection
    self.session_factory, self.host, self.port, **self.kwargs)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 727, in create_connection
    flags=flags, loop=self)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 174, in _ensure_resolved
    proto=proto, flags=flags)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 673, in getaddrinfo
    host, port, family, type, proto, flags)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 639, in run_in_executor
    return futures.wrap_future(executor.submit(func, *args), loop=self)
  File "/usr/lib/python3.6/asyncio/futures.py", line 431, in wrap_future
    new_future = loop.create_future()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 276, in create_future
    return futures.Future(loop=self)
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 658, in _getaddrinfo_debug
    addrinfo = socket.getaddrinfo(host, port, family, type, proto, flags)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
```

---

Note, I initially got this on ElectronX, but switched over to your branch, latest githead, and it still happens.  

I'm on Windows 7, Python 3.6.6 using MSYS, leveldb DB, with the following modules installed:

```
$ python3 -m pip list
Package           Version
----------------- ----------
aiohttp           3.5.4
aiorpcX           0.10.3
appdirs           1.4.3
async-timeout     3.0.1
attrs             18.2.0
certifi           2018.10.15
chardet           3.0.4
dnspython         1.15.0
ecdsa             0.13
idna              2.7
idna-ssl          1.1.0
jsonrpclib-pelix  0.3.2
multidict         4.4.2
packaging         18.0
pbkdf2            1.3
pip               18.1
plyvel            1.0.5
protobuf          3.6.1
pyaes             1.6.1
Pygments          2.2.0
pylru             1.1.0
pyparsing         2.3.0
PySocks           1.6.8
qrcode            6.0
requests          2.20.1
setuptools        40.5.0
six               1.11.0
typing-extensions 3.7.2
urllib3           1.24.1
yarl              1.2.6
```

I realize my setup is a bit unorthodox but I figure maybe there is some Exception you forgot to catch in aiorpcX or in ElectrumX.. that if you caught, everything would work again, which is triggered by commit 7f1096ae530b464677481b91e358dd0a774f3bcd.

Cheers.

**Comment by kyuupichan** [comment]
It looks to me like that future is being generated inside asyncio itself; not much I can do about that.  Have you tried 3.7?

**Comment by cculianu** [comment]
Hopefully it's a 3.6 thing. I forget why i didn't install 3.7..  I will try 3.7 and if it doesn't fix it, write you back. Thanks.

**Comment by cculianu** [comment]
Good news! Upgraded to Python 3.7.2 and it totally stopped happening.  Must be some extant bug in aiohttp on 3.6 asyncio like you said.

Awesome. Thanks. Closing...
