### ISSUE TITLE
uvloop python errors

### ISSUE THREAD

**Issue by peleion** [kyuupichan/electrumx#743]
ElectrumX 1.9.5 running in Docker based on Debian stretch (Python 3.7.2) using uvloop throws these  regularly but doesn't seem to be affecting server performance:

```
ERROR:asyncio:Fatal error on SSL protocol                                                                                                            
protocol: <uvloop.loop.SSLProtocol object at 0x7f254057eea8>
transport: <TCPTransport closed=False reading=False 0x55706ce5bcf8>
Traceback (most recent call last):             
  File "uvloop/sslproto.pyx", line 652, in uvloop.loop.SSLProtocol._do_read                                                                          
  File "uvloop/sslproto.pyx", line 712, in uvloop.loop.SSLProtocol._do_read__copied                                                                  
  File "/usr/local/lib/python3.7/ssl.py", line 707, in read
    v = self._sslobj.read(len)                                    
ssl.SSLError: [SSL] unknown error (_ssl.c:2484)    
```
                                                                                                  
```
ERROR:asyncio:Exception in callback <bound method SessionBase.connection_lost of <electrumx.server.session.ElectrumX object at 0x7f24c881fe48>>      
handle: <Handle SessionBase.connection_lost>         
Traceback (most recent call last):                      
  File "uvloop/cbhandles.pyx", line 68, in uvloop.loop.Handle._run
  File "/usr/local/lib/python3.7/site-packages/electrumx/server/session.py", line 666, in connection_lost                                            
    self.session_mgr.remove_session(self)                   
  File "/usr/local/lib/python3.7/site-packages/electrumx/server/session.py", line 583, in remove_session                                             
    self.sessions.remove(session) 
KeyError: <electrumx.server.session.ElectrumX object at 0x7f24c881fe48>    
```
```
# pip3 list
Package       Version
------------- -------
aiohttp       3.5.4
aiorpcX       0.10.5
async-timeout 3.0.1
attrs         18.2.0
chardet       3.0.4
electrumX     1.9.5
idna          2.8
multidict     4.5.2
pip           19.0.3
plyvel        1.0.5
pylru         1.1.0
setuptools    40.8.0
uvloop        0.12.1
wheel         0.33.1
yarl          1.3.0
```

**Comment by Rav3nPL** [comment]
Also getting lots of
```
ERROR:asyncio:Exception in callback <bound method SessionBase.connection_lost of <electrumx.server.session.BitcoinSegwitElectrumX object at 0x7fc393fc9d68>>
handle: <Handle SessionBase.connection_lost>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 68, in uvloop.loop.Handle._run
  File "/home/rav3n/electrumx/electrumx/server/session.py", line 672, in connection_lost
    self.session_mgr.remove_session(self)
  File "/home/rav3n/electrumx/electrumx/server/session.py", line 589, in remove_session
    self.sessions.remove(session)
KeyError: <electrumx.server.session.BitcoinSegwitElectrumX object at 0x7fc393fc9d68>

ERROR:asyncio:Exception in callback <bound method SessionBase.connection_lost of <electrumx.server.session.BitcoinSegwitElectrumX object at 0x7fc3803c6320>>
handle: <Handle SessionBase.connection_lost>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 68, in uvloop.loop.Handle._run
  File "/home/rav3n/electrumx/electrumx/server/session.py", line 672, in connection_lost
    self.session_mgr.remove_session(self)
  File "/home/rav3n/electrumx/electrumx/server/session.py", line 589, in remove_session
    self.sessions.remove(session)
KeyError: <electrumx.server.session.BitcoinSegwitElectrumX object at 0x7fc3803c6320>
```

Using Ubuntu 18.04, python 3.6.7, current git code and uvloop
```
aiohttp (3.5.4)
aiorpcX (0.10.5)
uvloop (0.12.1)
```
