### ISSUE TITLE
ERROR:root:task crashed KeyError: <electrumx.server.session.BitcoinSegwitElectrumX object at 0x7fb1bfdf9e10>

### ISSUE THREAD

**Issue by shsmith** [kyuupichan/electrumx#792]
This happened on git-head.
Once this was logged, no RPC commands will function and the service has to be restarted.
```
Apr 11 05:25:26 electrumd electrumx_server[119292]: ERROR:root:task crashed: <Task finished coro=<Controller.serve() done, defined at /usr/local/lib/python3.7/dist-packages/electrumX-1.10.0
Apr 11 05:25:26 electrumd electrumx_server[119292]: Traceback (most recent call last):
Apr 11 05:25:26 electrumd electrumx_server[119292]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcX-0.12.1-py3.7.egg/aiorpcx/util.py", line 128, in check_task
Apr 11 05:25:26 electrumd electrumx_server[119292]:     task.result()
Apr 11 05:25:26 electrumd electrumx_server[119292]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.10.0-py3.7.egg/electrumx/server/controller.py", line 134, in serve
Apr 11 05:25:26 electrumd electrumx_server[119292]:     await group.spawn(wait_for_catchup())
Apr 11 05:25:26 electrumd electrumx_server[119292]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcX-0.12.1-py3.7.egg/aiorpcx/curio.py", line 238, in __aexit__
Apr 11 05:25:26 electrumd electrumx_server[119292]:     await self.join()
Apr 11 05:25:26 electrumd electrumx_server[119292]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcX-0.12.1-py3.7.egg/aiorpcx/curio.py", line 207, in join
Apr 11 05:25:26 electrumd electrumx_server[119292]:     raise task.exception()
Apr 11 05:25:26 electrumd electrumx_server[119292]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.10.0-py3.7.egg/electrumx/server/mempool.py", line 334, in keep_synchronized
Apr 11 05:25:26 electrumd electrumx_server[119292]:     await group.spawn(self._logging(synchronized_event))
Apr 11 05:25:26 electrumd electrumx_server[119292]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcX-0.12.1-py3.7.egg/aiorpcx/curio.py", line 238, in __aexit__
Apr 11 05:25:26 electrumd electrumx_server[119292]:     await self.join()
Apr 11 05:25:26 electrumd electrumx_server[119292]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcX-0.12.1-py3.7.egg/aiorpcx/curio.py", line 207, in join
Apr 11 05:25:26 electrumd electrumx_server[119292]:     raise task.exception()
Apr 11 05:25:26 electrumd electrumx_server[119292]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.10.0-py3.7.egg/electrumx/server/mempool.py", line 231, in _refresh_hashes
Apr 11 05:25:26 electrumd electrumx_server[119292]:     await self.api.on_mempool(touched, height)
Apr 11 05:25:26 electrumd electrumx_server[119292]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.10.0-py3.7.egg/electrumx/server/controller.py", line 67, in on_mempool
Apr 11 05:25:26 electrumd electrumx_server[119292]:     await self._maybe_notify()
Apr 11 05:25:26 electrumd electrumx_server[119292]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.10.0-py3.7.egg/electrumx/server/controller.py", line 55, in _maybe_notify
Apr 11 05:25:26 electrumd electrumx_server[119292]:     await self.notify(height, touched)
Apr 11 05:25:26 electrumd electrumx_server[119292]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.10.0-py3.7.egg/electrumx/server/session.py", line 553, in _notify_sessions
Apr 11 05:25:26 electrumd electrumx_server[119292]:     await group.spawn(session.notify, touched, height_changed)
Apr 11 05:25:26 electrumd electrumx_server[119292]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcX-0.12.1-py3.7.egg/aiorpcx/curio.py", line 238, in __aexit__
Apr 11 05:25:26 electrumd electrumx_server[119292]:     await self.join()
Apr 11 05:25:26 electrumd electrumx_server[119292]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcX-0.12.1-py3.7.egg/aiorpcx/curio.py", line 207, in join
Apr 11 05:25:26 electrumd electrumx_server[119292]:     raise task.exception()
Apr 11 05:25:26 electrumd electrumx_server[119292]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.10.0-py3.7.egg/electrumx/server/session.py", line 754, in notify
Apr 11 05:25:26 electrumd electrumx_server[119292]:     status = await self.address_status(hashX)
Apr 11 05:25:26 electrumd electrumx_server[119292]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.10.0-py3.7.egg/electrumx/server/session.py", line 832, in address_status
Apr 11 05:25:26 electrumd electrumx_server[119292]:     self.bump_cost(1.0 + excess / 50)
Apr 11 05:25:26 electrumd electrumx_server[119292]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcX-0.12.1-py3.7.egg/aiorpcx/session.py", line 230, in bump_cost
Apr 11 05:25:26 electrumd electrumx_server[119292]:     self.recalc_concurrency()
Apr 11 05:25:26 electrumd electrumx_server[119292]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcX-0.12.1-py3.7.egg/aiorpcx/session.py", line 249, in recalc_concurrency
Apr 11 05:25:26 electrumd electrumx_server[119292]:     cost = self.cost + self.extra_cost()
Apr 11 05:25:26 electrumd electrumx_server[119292]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.10.0-py3.7.egg/electrumx/server/session.py", line 735, in extra_cost
Apr 11 05:25:26 electrumd electrumx_server[119292]:     return self.session_mgr.extra_cost(self)
Apr 11 05:25:26 electrumd electrumx_server[119292]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.10.0-py3.7.egg/electrumx/server/session.py", line 491, in extra_cost
Apr 11 05:25:26 electrumd electrumx_server[119292]:     groups = self.sessions[session]
Apr 11 05:25:26 electrumd electrumx_server[119292]: KeyError: <electrumx.server.session.BitcoinSegwitElectrumX object at 0x7fb1bfdf9e10>
A
```

**Comment by ohitz** [comment]
Exactly the same happened here, already twice now, after about 30 minutes uptime.

**Comment by kyuupichan** [comment]
Thanks, taking a look

**Comment by ohitz** [comment]
Fantastic, thanks Neil!
