### ISSUE TITLE
Error when using RPC

### ISSUE THREAD

**Issue by whizz** [kyuupichan/electrumx#798]
After upgrading to 1.10.1, when calling the `sessions` function thru RPC interface, I am getting

```
# /usr/bin/electrumx_rpc.py sessions
error making request: RPCError(-32603, 'internal server error', 0)
```

The logs contain this:
```
Apr 16 09:56:06 b electrumx_server[11585]: Exception ignored in: <coroutine object SessionBase._process_messages at 0x7fde947f15c8>
Apr 16 09:56:06 b electrumx_server[11585]: Traceback (most recent call last):
Apr 16 09:56:06 b electrumx_server[11585]: File "/usr/local/lib/python3.7/site-packages/aiorpcX-0.13.6-py3.7.egg/aiorpcx/session.py", line 186, in _process_messages
Apr 16 09:56:06 b electrumx_server[11585]: await self._group.spawn(self._receive_messages)
Apr 16 09:56:06 b electrumx_server[11585]: File "/usr/local/lib/python3.7/site-packages/aiorpcX-0.13.6-py3.7.egg/aiorpcx/curio.py", line 242, in __aexit__
Apr 16 09:56:06 b electrumx_server[11585]: await self.join()
Apr 16 09:56:06 b electrumx_server[11585]: RuntimeError: coroutine ignored GeneratorExit
Apr 16 09:56:06 b electrumx_server[11585]: ERROR:asyncio:Task was destroyed but it is pending!
Apr 16 09:56:06 b electrumx_server[11585]: task: <Task pending coro=<SessionBase._process_messages() done, defined at /usr/local/lib/python3.7/site-packages/aiorpcX-0.13.6-py3.7.egg/aiorpcx/session.py:184> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fde946e6be8>()]> cb=[check_task(<module 'logg.../__init__.py'>)() at /usr/local/lib/python3.7/site-packages/aiorpcX-0.13.6-py3.7.egg/aiorpcx/util.py:88]>
Apr 16 09:56:06 b electrumx_server[11585]: ERROR:asyncio:Task was destroyed but it is pending!
Apr 16 09:56:06 b electrumx_server[11585]: task: <Task pending coro=<RPCSession._receive_messages() done, defined at /usr/local/lib/python3.7/site-packages/aiorpcX-0.13.6-py3.7.egg/aiorpcx/session.py:536> wait_for=<Future cancelled> cb=[TaskGroup._on_done()]>
Apr 16 09:56:06 b electrumx_server[11585]: INFO:LocalRPC:[1] RPC [::1]:50836, 1 total
Apr 16 09:56:06 b electrumx_server[11585]: ERROR:asyncio:Exception in callback _SelectorSocketTransport._call_connection_lost(None)
Apr 16 09:56:06 b electrumx_server[11585]: handle: <Handle _SelectorSocketTransport._call_connection_lost(None)>
Apr 16 09:56:06 b electrumx_server[11585]: Traceback (most recent call last):
Apr 16 09:56:06 b electrumx_server[11585]: File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
Apr 16 09:56:06 b electrumx_server[11585]: self._context.run(self._callback, *self._args)
Apr 16 09:56:06 b electrumx_server[11585]: File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 924, in _call_connection_lost
Apr 16 09:56:06 b electrumx_server[11585]: super()._call_connection_lost(exc)
Apr 16 09:56:06 b electrumx_server[11585]: File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 698, in _call_connection_lost
Apr 16 09:56:06 b electrumx_server[11585]: self._protocol.connection_lost(exc)
Apr 16 09:56:06 b electrumx_server[11585]: File "/usr/local/lib/python3.7/site-packages/electrumX-1.10.1-py3.7.egg/electrumx/server/session.py", line 698, in connection_lost
Apr 16 09:56:06 b electrumx_server[11585]: if self._concurrency.max_concurrent != self.initial_concurrent:
Apr 16 09:56:06 b electrumx_server[11585]: AttributeError: 'LocalRPC' object has no attribute '_concurrency'
```

**Comment by kyuupichan** [comment]
You probably have the wrong version of aiorpcx.  Use exactly 0.13.5

**Comment by whizz** [comment]
OK, thanks, I will manually downgrade. setup.py specifies 'aiorpcX>=0.13.5,<0.14', so it grabbed 0.13.6. May I suggest, if a specific version is really required, to put that in the dependencies?

**Comment by kyuupichan** [comment]
Yes I do, but given the rapid development to try and help with the DoS attacks things slip through the cracks.  I'll be releasing a new version soon
