### ISSUE TITLE
Crash: history too large

### ISSUE THREAD

**Issue by ohitz** [kyuupichan/electrumx#799]
I just stumbled over a crash with the latest version:

```
Apr 16 14:16:13 btcnode electrumx_server[31487]: ERROR:root:task crashed: <Task finished coro=<Controller.serve() done, defined at /usr/local/lib/python3.6/dist-packages/electrumx/server/controller.py:81> exception=RPCError(1, 'history too large')>
Apr 16 14:16:13 btcnode electrumx_server[31487]: Traceback (most recent call last):
Apr 16 14:16:13 btcnode electrumx_server[31487]:   File "/usr/local/lib/python3.6/dist-packages/aiorpcx/util.py", line 91, in check_task
Apr 16 14:16:13 btcnode electrumx_server[31487]:     task.result()
Apr 16 14:16:13 btcnode electrumx_server[31487]:   File "/usr/local/lib/python3.6/dist-packages/electrumx/server/controller.py", line 134, in serve
Apr 16 14:16:13 btcnode electrumx_server[31487]:     await group.spawn(wait_for_catchup())
Apr 16 14:16:13 btcnode electrumx_server[31487]:   File "/usr/local/lib/python3.6/dist-packages/aiorpcx/curio.py", line 242, in __aexit__
Apr 16 14:16:13 btcnode electrumx_server[31487]:     await self.join()
Apr 16 14:16:13 btcnode electrumx_server[31487]:   File "/usr/local/lib/python3.6/dist-packages/aiorpcx/curio.py", line 211, in join
Apr 16 14:16:13 btcnode electrumx_server[31487]:     raise task.exception()
Apr 16 14:16:13 btcnode electrumx_server[31487]:   File "/usr/local/lib/python3.6/dist-packages/electrumx/server/mempool.py", line 335, in keep_synchronized
Apr 16 14:16:13 btcnode electrumx_server[31487]:     await group.spawn(self._logging(synchronized_event))
Apr 16 14:16:13 btcnode electrumx_server[31487]:   File "/usr/local/lib/python3.6/dist-packages/aiorpcx/curio.py", line 242, in __aexit__
Apr 16 14:16:13 btcnode electrumx_server[31487]:     await self.join()
Apr 16 14:16:13 btcnode electrumx_server[31487]:   File "/usr/local/lib/python3.6/dist-packages/aiorpcx/curio.py", line 211, in join
Apr 16 14:16:13 btcnode electrumx_server[31487]:     raise task.exception()
Apr 16 14:16:13 btcnode electrumx_server[31487]:   File "/usr/local/lib/python3.6/dist-packages/electrumx/server/mempool.py", line 232, in _refresh_hashes
Apr 16 14:16:13 btcnode electrumx_server[31487]:     await self.api.on_mempool(touched, height)
Apr 16 14:16:13 btcnode electrumx_server[31487]:   File "/usr/local/lib/python3.6/dist-packages/electrumx/server/controller.py", line 67, in on_mempool
Apr 16 14:16:13 btcnode electrumx_server[31487]:     await self._maybe_notify()
Apr 16 14:16:13 btcnode electrumx_server[31487]:   File "/usr/local/lib/python3.6/dist-packages/electrumx/server/controller.py", line 55, in _maybe_notify
Apr 16 14:16:13 btcnode electrumx_server[31487]:     await self.notify(height, touched)
Apr 16 14:16:13 btcnode electrumx_server[31487]:   File "/usr/local/lib/python3.6/dist-packages/electrumx/server/session.py", line 690, in _notify_sessions
Apr 16 14:16:13 btcnode electrumx_server[31487]:     await group.spawn(session.notify, touched, height_changed)
Apr 16 14:16:13 btcnode electrumx_server[31487]:   File "/usr/local/lib/python3.6/dist-packages/aiorpcx/curio.py", line 242, in __aexit__
Apr 16 14:16:13 btcnode electrumx_server[31487]:     await self.join()
Apr 16 14:16:13 btcnode electrumx_server[31487]:   File "/usr/local/lib/python3.6/dist-packages/aiorpcx/curio.py", line 211, in join
Apr 16 14:16:13 btcnode electrumx_server[31487]:     raise task.exception()
Apr 16 14:16:13 btcnode electrumx_server[31487]:   File "/usr/local/lib/python3.6/dist-packages/electrumx/server/session.py", line 893, in notify
Apr 16 14:16:13 btcnode electrumx_server[31487]:     status = await self.address_status(hashX)
Apr 16 14:16:13 btcnode electrumx_server[31487]:   File "/usr/local/lib/python3.6/dist-packages/electrumx/server/session.py", line 947, in address_status
Apr 16 14:16:13 btcnode electrumx_server[31487]:     db_history, cost = await self.session_mgr.limited_history(hashX)
Apr 16 14:16:13 btcnode electrumx_server[31487]:   File "/usr/local/lib/python3.6/dist-packages/electrumx/server/session.py", line 669, in limited_history
Apr 16 14:16:13 btcnode electrumx_server[31487]:     raise result
Apr 16 14:16:13 btcnode electrumx_server[31487]: aiorpcx.jsonrpc.RPCError: (1, 'history too large')

```

Had to restart electrumx after this has happened.

**Comment by ohitz** [comment]
By the way, this was with git-head until ddfc87ecc9e1551aecefb690613d10ea8387b98c. It is possible that the subsequent commits have fixed the issue. I will report back if it crashes again.

**Comment by kyuupichan** [comment]
They do.  Please use https://github.com/kyuupichan/electrumx/commit/f6e0962262c56d1879498f71add5ceb6821d171b or later
