### ISSUE TITLE
Error while attempting to bind cannot assign requested address

### ISSUE THREAD

**Issue by theblains** [kyuupichan/electrumx#825]
Hi,

Not sure if this is the same as https://github.com/kyuupichan/electrumx/issues/822

On the newist version I cannot connect to any peers getting the below outputs; Reverting resolves the issue.

Ubuntu 18.04 LTS -  Python3.7

```
May 14 18:56:00 core electrumx_server[14374]: INFO:PeerManager:accepted new peer btc.theblains.org from env
May 14 18:56:00 core electrumx_server[14374]: INFO:PeerManager:accepted new peer btc.smsys.me from env
May 14 18:56:00 core electrumx_server[14374]: INFO:PeerManager:accepted new peer E-X.not.fyi from env
May 14 18:56:00 core electrumx_server[14374]: INFO:PeerManager:accepted new peer electrum.vom-stausee.de from env
May 14 18:56:00 core electrumx_server[14374]: INFO:PeerManager:accepted new peer electrum.hsmiths.com from env
May 14 18:56:00 core electrumx_server[14374]: INFO:PeerManager:accepted new peer helicarrier.bauerj.eu from env
May 14 18:56:00 core electrumx_server[14374]: INFO:PeerManager:accepted new peer node.arihanc.com from env
May 14 18:56:00 core electrumx_server[14374]: INFO:PeerManager:[helicarrier.bauerj.eu:50002 SSL] [Errno 99] error while attempting to bind on address ('81.174.133.68', 0): cannot assign requested address
May 14 18:56:00 core electrumx_server[14374]: INFO:PeerManager:[btc.theblains.org:50006 SSL] [Errno 99] error while attempting to bind on address ('81.174.133.68', 0): cannot assign requested address
May 14 18:56:00 core electrumx_server[14374]: INFO:PeerManager:[btc.smsys.me:995 SSL] [Errno -5] No address associated with hostname
May 14 18:56:00 core electrumx_server[14374]: INFO:PeerManager:[electrum.vom-stausee.de:50002 SSL] [Errno 99] error while attempting to bind on address ('81.174.133.68', 0): cannot assign requested address
May 14 18:56:00 core electrumx_server[14374]: INFO:PeerManager:[electrum.hsmiths.com:50002 SSL] [Errno 99] error while attempting to bind on address ('81.174.133.68', 0): cannot assign requested address
May 14 18:56:00 core electrumx_server[14374]: INFO:PeerManager:[node.arihanc.com:50002 SSL] [Errno 99] error while attempting to bind on address ('81.174.133.68', 0): cannot assign requested address
May 14 18:56:00 core electrumx_server[14374]: INFO:PeerManager:[E-X.not.fyi:50002 SSL] [Errno -2] Name or service not known
May 14 18:56:00 core electrumx_server[14374]: INFO:PeerManager:[node.arihanc.com:50002 SSL] [Errno -2] Name or service not known
May 14 18:56:00 core electrumx_server[14374]: INFO:PeerManager:[node.arihanc.com:50001 TCP] [Errno 99] error while attempting to bind on address ('81.174.133.68', 0): cannot assign requested address
May 14 18:56:00 core electrumx_server[14374]: INFO:PeerManager:[node.arihanc.com:50001 TCP] [Errno -2] Name or service not known
May 14 18:56:00 core electrumx_server[14374]: INFO:PeerManager:[btc.smsys.me:995 SSL] [Errno -5] No address associated with hostname
May 14 18:56:00 core electrumx_server[14374]: INFO:PeerManager:[btc.theblains.org:50006 SSL] [Errno -5] No address associated with hostname
May 14 18:56:00 core electrumx_server[14374]: INFO:PeerManager:[electrum.hsmiths.com:50002 SSL] [Errno -5] No address associated with hostname
May 14 18:56:00 core electrumx_server[14374]: INFO:PeerManager:[electrum.vom-stausee.de:50002 SSL] [Errno -5] No address associated with hostname
May 14 18:56:00 core electrumx_server[14374]: INFO:PeerManager:[btc.theblains.org:50005 TCP] [Errno 99] error while attempting to bind on address ('81.174.133.68', 0): cannot assign requested address
May 14 18:56:00 core electrumx_server[14374]: INFO:PeerManager:[electrum.hsmiths.com:50001 TCP] [Errno 99] error while attempting to bind on address ('81.174.133.68', 0): cannot assign requested address
May 14 18:56:00 core electrumx_server[14374]: INFO:PeerManager:[electrum.vom-stausee.de:50001 TCP] [Errno 99] error while attempting to bind on address ('81.174.133.68', 0): cannot assign requested address
May 14 18:56:00 core electrumx_server[14374]: INFO:PeerManager:[electrum.hsmiths.com:50001 TCP] [Errno -5] No address associated with hostname
May 14 18:56:00 core electrumx_server[14374]: INFO:PeerManager:[btc.theblains.org:50005 TCP] [Errno -5] No address associated with hostname
May 14 18:56:00 core electrumx_server[14374]: INFO:PeerManager:[electrum.vom-stausee.de:50001 TCP] [Errno -5] No address associated with hostname
May 14 18:56:00 core electrumx_server[14374]: INFO:PeerManager:[E-X.not.fyi:50002 SSL] [Errno -2] Name or service not known
May 14 18:56:00 core electrumx_server[14374]: INFO:PeerManager:[helicarrier.bauerj.eu:50002 SSL] [Errno -5] No address associated with hostname
May 14 18:56:00 core electrumx_server[14374]: INFO:PeerManager:[helicarrier.bauerj.eu:50001 TCP] [Errno 99] error while attempting to bind on address ('81.174.133.68', 0): cannot assign requested address
May 14 18:56:00 core electrumx_server[14374]: INFO:PeerManager:[E-X.not.fyi:50001 TCP] [Errno -2] Name or service not known
May 14 18:56:00 core electrumx_server[14374]: INFO:PeerManager:[helicarrier.bauerj.eu:50001 TCP] [Errno -5] No address associated with hostname
May 14 18:56:00 core electrumx_server[14374]: INFO:PeerManager:[E-X.not.fyi:50001 TCP] [Errno -2] Name or service not known

```

**Comment by shsmith** [comment]
I am getting something similar on my testnet server. It is behind a NAT router. It appears to be trying to bind to my external (report) address, which is not possible.

> error while attempting to bind on address ('76.174.26.91', 0)

76.174.26.91 is my external address.
```
May 19 10:32:31 testnet electrumx_server[65435]: INFO:electrumx:ElectrumX server starting
May 19 10:32:31 testnet electrumx_server[65435]: INFO:electrumx:logging level: INFO
May 19 10:32:31 testnet electrumx_server[65435]: INFO:Controller:Python version: 3.7.1 (default, Oct 22 2018, 11:21:55)  [GCC 8.2.0]
May 19 10:32:31 testnet electrumx_server[65435]: INFO:Controller:software version: ElectrumX 1.12
May 19 10:32:31 testnet electrumx_server[65435]: INFO:Controller:aiorpcX version: 0.18.1
May 19 10:32:31 testnet electrumx_server[65435]: INFO:Controller:supported protocol versions: 1.4-1.4.2
May 19 10:32:31 testnet electrumx_server[65435]: INFO:Controller:event loop policy: None
May 19 10:32:31 testnet electrumx_server[65435]: INFO:Controller:reorg limit is 8,000 blocks
May 19 10:32:31 testnet electrumx_server[65435]: INFO:Daemon:daemon #1 at 127.0.0.1:18332/ (current)
May 19 10:32:31 testnet electrumx_server[65435]: INFO:DB:switching current directory to /home/shsmith/.electrumx/testnetdb
May 19 10:32:31 testnet electrumx_server[65435]: INFO:DB:using leveldb for DB backend
May 19 10:32:31 testnet electrumx_server[65435]: INFO:DB:opened UTXO DB (for sync: True)
May 19 10:32:31 testnet electrumx_server[65435]: INFO:DB:DB version: 6
May 19 10:32:31 testnet electrumx_server[65435]: INFO:DB:coin: BitcoinSegwit
May 19 10:32:31 testnet electrumx_server[65435]: INFO:DB:network: testnet
May 19 10:32:31 testnet electrumx_server[65435]: INFO:DB:height: 1,517,257
May 19 10:32:31 testnet electrumx_server[65435]: INFO:DB:tip: 00000000000001ff675ef6954867ba1f03d05225d8809c7d3a54495924ede9a3
May 19 10:32:31 testnet electrumx_server[65435]: INFO:DB:tx count: 50,121,334
May 19 10:32:31 testnet electrumx_server[65435]: INFO:DB:flushing DB cache at 200 MB
May 19 10:32:31 testnet electrumx_server[65435]: INFO:History:history DB version: 0
May 19 10:32:31 testnet electrumx_server[65435]: INFO:History:flush count: 15,692
May 19 10:32:31 testnet electrumx_server[65435]: INFO:DB:deleted 1,387 stale undo entries
May 19 10:32:31 testnet electrumx_server[65435]: INFO:Prefetcher:catching up to daemon height 1,517,258 (1 blocks behind)
May 19 10:32:31 testnet electrumx_server[65435]: INFO:SessionManager:RPC server listening on localhost:8000
May 19 10:32:31 testnet electrumx_server[65435]: INFO:BlockProcessor:our height: 1,517,258 daemon: 1,517,258 UTXOs 0MB hist 0MB
May 19 10:32:31 testnet electrumx_server[65435]: INFO:BlockProcessor:processed 1 block size 0.01 MB in 0.0s
May 19 10:32:31 testnet electrumx_server[65435]: INFO:BlockProcessor:caught up to height 1517258
May 19 10:32:31 testnet electrumx_server[65435]: INFO:DB:flushed filesystem data in 0.00s
May 19 10:32:31 testnet electrumx_server[65435]: INFO:History:flushed history in 0.0s for 107 addrs
May 19 10:32:31 testnet electrumx_server[65435]: INFO:DB:flushed 1 blocks with 57 txs, 100 UTXO adds, 45 spends in 0.0s, committing...
May 19 10:32:31 testnet electrumx_server[65435]: INFO:DB:flush #15,693 took 0.0s.  Height 1,517,258 txs: 50,121,391 (+57)
May 19 10:32:31 testnet electrumx_server[65435]: INFO:DB:tx/sec since genesis: 2, since last flush: 132
May 19 10:32:31 testnet electrumx_server[65435]: INFO:DB:sync time: 281d 07h 27m  ETA: 00s
May 19 10:32:31 testnet electrumx_server[65435]: INFO:DB:closing DBs to re-open for serving
May 19 10:32:31 testnet electrumx_server[65435]: INFO:DB:opened UTXO DB (for sync: False)
May 19 10:32:31 testnet electrumx_server[65435]: INFO:DB:DB version: 6
May 19 10:32:31 testnet electrumx_server[65435]: INFO:DB:coin: BitcoinSegwit
May 19 10:32:31 testnet electrumx_server[65435]: INFO:DB:network: testnet
May 19 10:32:31 testnet electrumx_server[65435]: INFO:DB:height: 1,517,258
May 19 10:32:31 testnet electrumx_server[65435]: INFO:DB:tip: 00000000000000ade5f09bb61c9cd84858294b847c5035f7b50846cc12f710c4
May 19 10:32:31 testnet electrumx_server[65435]: INFO:DB:tx count: 50,121,391
May 19 10:32:31 testnet electrumx_server[65435]: INFO:History:history DB version: 0
May 19 10:32:31 testnet electrumx_server[65435]: INFO:History:flush count: 15,693
May 19 10:32:31 testnet electrumx_server[65435]: INFO:DB:deleted 1 stale undo entries
May 19 10:32:31 testnet electrumx_server[65435]: INFO:DB:populating header merkle cache...
May 19 10:32:31 testnet electrumx_server[65435]: INFO:MemPool:beginning processing of daemon mempool.  This can take some time...
May 19 10:32:32 testnet electrumx_server[65435]: INFO:SessionManager:max session count: 1,000
May 19 10:32:32 testnet electrumx_server[65435]: INFO:SessionManager:session timeout: 600 seconds
May 19 10:32:32 testnet electrumx_server[65435]: INFO:SessionManager:session cost hard limit 10,000
May 19 10:32:32 testnet electrumx_server[65435]: INFO:SessionManager:session cost soft limit 1,000
May 19 10:32:32 testnet electrumx_server[65435]: INFO:SessionManager:bandwidth unit cost 5,000
May 19 10:32:32 testnet electrumx_server[65435]: INFO:SessionManager:request sleep 2,500ms
May 19 10:32:32 testnet electrumx_server[65435]: INFO:SessionManager:request timeout 30s
May 19 10:32:32 testnet electrumx_server[65435]: INFO:SessionManager:initial concurrent 10
May 19 10:32:32 testnet electrumx_server[65435]: INFO:SessionManager:max response size 1,000,000 bytes
May 19 10:32:32 testnet electrumx_server[65435]: INFO:SessionManager:advertising service tcp://testnet.hsmiths.com:53011
May 19 10:32:32 testnet electrumx_server[65435]: INFO:SessionManager:advertising service ssl://testnet.hsmiths.com:53012
May 19 10:32:32 testnet electrumx_server[65435]: INFO:SessionManager:advertising service wss://testnet.hsmiths.com:53014
May 19 10:32:32 testnet electrumx_server[65435]: INFO:MemPool:compact fee histogram: []
May 19 10:32:32 testnet electrumx_server[65435]: INFO:MemPool:synced in 0.10s
May 19 10:32:32 testnet electrumx_server[65435]: INFO:MemPool:10 txs 0.00 MB touching 29 addresses
May 19 10:32:32 testnet electrumx_server[65435]: INFO:SessionManager:TCP server listening on all_interfaces:53011
May 19 10:32:32 testnet electrumx_server[65435]: INFO:SessionManager:SSL server listening on all_interfaces:53012
May 19 10:32:32 testnet electrumx_server[65435]: INFO:SessionManager:WSS server listening on all_interfaces:55014
May 19 10:32:32 testnet electrumx_server[65435]: INFO:PeerManager:peer discovery: ON
May 19 10:32:32 testnet electrumx_server[65435]: INFO:PeerManager:announce ourself: True
May 19 10:32:32 testnet electrumx_server[65435]: INFO:PeerManager:my clearnet self: testnet.hsmiths.com
May 19 10:32:32 testnet electrumx_server[65435]: INFO:PeerManager:force use of proxy: False
May 19 10:32:32 testnet electrumx_server[65435]: INFO:PeerManager:beginning peer discovery...
May 19 10:32:32 testnet electrumx_server[65435]: INFO:PeerManager:trying to detect proxy on "pfserver" ports [9050, 9150, 1080]
May 19 10:32:32 testnet electrumx_server[65435]: INFO:PeerManager:accepted new peer testnet.hsmiths.com from env
May 19 10:32:32 testnet electrumx_server[65435]: INFO:PeerManager:accepted new peer testnet.qtornado.com from env
May 19 10:32:32 testnet electrumx_server[65435]: INFO:PeerManager:accepted new peer testnet1.bauerj.eu from env
May 19 10:32:32 testnet electrumx_server[65435]: INFO:PeerManager:accepted new peer tn.not.fyi from env
May 19 10:32:32 testnet electrumx_server[65435]: INFO:PeerManager:accepted new peer bitcoin.cluelessperson.com from env
May 19 10:32:32 testnet electrumx_server[65435]: INFO:PeerManager:[testnet.hsmiths.com:53012 SSL] [Errno 99] error while attempting to bind on address ('76.174.26.91', 0)
May 19 10:32:32 testnet electrumx_server[65435]: INFO:PeerManager:[tn.not.fyi:55002 SSL] [Errno 99] error while attempting to bind on address ('76.174.26.91', 0): cannot
May 19 10:32:32 testnet electrumx_server[65435]: INFO:PeerManager:[testnet.hsmiths.com:53012 SSL] [Errno -2] Name or service not known
May 19 10:32:32 testnet electrumx_server[65435]: INFO:PeerManager:[testnet.qtornado.com:51002 SSL] [Errno 99] error while attempting to bind on address ('76.174.26.91', 0
May 19 10:32:32 testnet electrumx_server[65435]: INFO:PeerManager:[bitcoin.cluelessperson.com:51002 SSL] [Errno 99] error while attempting to bind on address ('76.174.26.
May 19 10:32:32 testnet electrumx_server[65435]: INFO:PeerManager:[testnet.hsmiths.com:53011 TCP] [Errno 99] error while attempting to bind on address ('76.174.26.91', 0)
May 19 10:32:32 testnet electrumx_server[65435]: INFO:PeerManager:[testnet.hsmiths.com:53011 TCP] [Errno -2] Name or service not known
May 19 10:32:32 testnet electrumx_server[65435]: INFO:PeerManager:[tn.not.fyi:55002 SSL] [Errno -5] No address associated with hostname
May 19 10:32:32 testnet electrumx_server[65435]: INFO:PeerManager:[tn.not.fyi:55001 TCP] [Errno 99] error while attempting to bind on address ('76.174.26.91', 0): cannot
May 19 10:32:32 testnet electrumx_server[65435]: INFO:PeerManager:[tn.not.fyi:55001 TCP] [Errno -5] No address associated with hostname
May 19 10:32:32 testnet electrumx_server[65435]: INFO:PeerManager:[bitcoin.cluelessperson.com:51002 SSL] [Errno -2] Name or service not known
May 19 10:32:32 testnet electrumx_server[65435]: INFO:PeerManager:[bitcoin.cluelessperson.com:51001 TCP] [Errno 99] error while attempting to bind on address ('76.174.26.
May 19 10:32:32 testnet electrumx_server[65435]: INFO:PeerManager:[bitcoin.cluelessperson.com:51001 TCP] [Errno -2] Name or service not known
May 19 10:32:32 testnet electrumx_server[65435]: INFO:PeerManager:[testnet.qtornado.com:51002 SSL] [Errno -5] No address associated with hostname
May 19 10:32:32 testnet electrumx_server[65435]: INFO:PeerManager:[testnet.qtornado.com:51001 TCP] [Errno 99] error while attempting to bind on address ('76.174.26.91', 0
May 19 10:32:32 testnet electrumx_server[65435]: INFO:PeerManager:[testnet.qtornado.com:51001 TCP] [Errno -5] No address associated with hostname
May 19 10:32:41 testnet electrumx_server[65435]: INFO:DB:header merkle cache populated in 9.6s
May 19 10:32:41 testnet electrumx_server[65435]: INFO:PeerManager:detected SOCKS5 proxy at pfserver:9050, auth: none
May 19 10:32:41 testnet electrumx_server[65435]: INFO:PeerManager:[testnet1.bauerj.eu:50002 SSL] [Errno 99] error while attempting to bind on address ('76.174.26.91', 0):
May 19 10:32:41 testnet electrumx_server[65435]: INFO:ElectrumX:[0] SSL 173.209.53.90:60482, 0 total

```

**Comment by shsmith** [comment]
This happened with HEAD.
Here is my environment:
```
TOR_PROXY_HOST=pfserver
SERVICES=tcp://:53011,ssl://:53012,wss://:55014,rpc://
REPORT_SERVICES=tcp://testnet.hsmiths.com:53011,ssl://testnet.hsmiths.com:53012,wss://testnet.hsmiths.com:53014
```

**Comment by shsmith** [comment]
Also spotted this  traceback in my logs:
```
May 19 13:54:45 testnet electrumx_server[65435]: INFO:PeerManager:accepted add_peer request from 50.2.13.165 for TN.not.fyi
May 19 13:54:45 testnet electrumx_server[65435]: INFO:PeerManager:accepted new peer TN.not.fyi from 50.2.13.165
May 19 13:54:45 testnet electrumx_server[65435]: ERROR:ElectrumX:[2358] exception handling Request('server.add_peer', [{'hosts': {'TN.not.fyi': {'tcp_port': 55001, 'ssl_p
May 19 13:54:45 testnet electrumx_server[65435]: Traceback (most recent call last):
May 19 13:54:45 testnet electrumx_server[65435]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcX-0.18.1-py3.7.egg/aiorpcx/session.py", line 463, in _throttled_requ
May 19 13:54:45 testnet electrumx_server[65435]:     result = await self.handle_request(request)
May 19 13:54:45 testnet electrumx_server[65435]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.12.0-py3.7.egg/electrumx/server/session.py", line 872, in hand
May 19 13:54:45 testnet electrumx_server[65435]:     return await coro
May 19 13:54:45 testnet electrumx_server[65435]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.12.0-py3.7.egg/electrumx/server/session.py", line 990, in add_
May 19 13:54:45 testnet electrumx_server[65435]:     return await self.peer_mgr.on_add_peer(features, self.remote_address())
May 19 13:54:45 testnet electrumx_server[65435]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.12.0-py3.7.egg/electrumx/server/peers.py", line 522, in on_add
May 19 13:54:45 testnet electrumx_server[65435]:     await self._note_peers([peer], check_ports=True)
May 19 13:54:45 testnet electrumx_server[65435]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.12.0-py3.7.egg/electrumx/server/peers.py", line 227, in _note_
May 19 13:54:45 testnet electrumx_server[65435]:     await self.group.spawn(self._monitor_peer(peer))
May 19 13:54:45 testnet electrumx_server[65435]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcX-0.18.1-py3.7.egg/aiorpcx/curio.py", line 148, in spawn
May 19 13:54:45 testnet electrumx_server[65435]:     self._add_task(task)
May 19 13:54:45 testnet electrumx_server[65435]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcX-0.18.1-py3.7.egg/aiorpcx/curio.py", line 123, in _add_task
May 19 13:54:45 testnet electrumx_server[65435]:     raise RuntimeError('task group is closed')
May 19 13:54:45 testnet electrumx_server[65435]: RuntimeError: task group is closed
May 19 13:54:45 testnet electrumx_server[65435]: INFO:PeerManager:[TN.not.fyi:55002 SSL] [Errno 99] error while attempting to bind on address ('76.174.26.91', 0): cannot
May 19 13:54:45 testnet electrumx_server[65435]: INFO:PeerManager:[TN.not.fyi:55002 SSL] [Errno -5] No address associated with hostname
May 19 13:54:45 testnet electrumx_server[65435]: INFO:PeerManager:[TN.not.fyi:55001 TCP] [Errno 99] error while attempting to bind on address ('76.174.26.91', 0): cannot
May 19 13:54:45 testnet electrumx_server[65435]: INFO:PeerManager:[TN.not.fyi:55001 TCP] [Errno -5] No address associated with hostname
May 19 13:54:46 testnet electrumx_server[65435]: INFO:ElectrumX:[2359] TCP 50.2.13.165:55287, 56 total

```

**Comment by shsmith** [comment]
I found this bit of code that assumes the first REPORT_SERVICES address is a local address that can be bound:
https://github.com/kyuupichan/electrumx/blame/a6bfc032674aac71eeffea3457ad10c456c1baa0/electrumx/server/peers.py#L259

Based on that, I was able to get peer discovery working by adding a dummy entry at the start of REPORT_SERVICES. 
 `REPORT_SERVICES=tcp://testnet:53011,tcp://testnet.hsmiths.com:53011,ssl://testnet.hsmiths.com:53012,wss://testnet.hsmiths.com:53014`

It would be better if the local IP was explicitly configured rather than assumed to be equal to the first reported service host.

**Comment by kyuupichan** [comment]
Good find @shsmith , thanks.  This was a mistaken change from the old config settings to the new.  I'm not really sure what the right solution is at the moment; let me think about it.

**Comment by SomberNight** [comment]
> Based on that, I was able to get peer discovery working by adding a dummy entry at the start of REPORT_SERVICES.

@shsmith if I try to add a dummy entry like that, outgoing peer discovery will still not work for me

```
2019-05-28T03:52:01.884737121Z INFO:PeerManager:[testnet.qtornado.com:51002 SSL] [Errno -2] Name or service not known
2019-05-28T03:52:01.886022088Z INFO:PeerManager:[testnet.qtornado.com:51002 SSL] [Errno -2] Name or service not known
2019-05-28T03:52:01.886414602Z INFO:PeerManager:no proxy detected, will try later
2019-05-28T03:52:01.887751652Z INFO:PeerManager:[testnet.qtornado.com:51001 TCP] [Errno -2] Name or service not known
2019-05-28T03:52:01.888775387Z INFO:PeerManager:[testnet.qtornado.com:51001 TCP] [Errno -2] Name or service not known
2019-05-28T03:52:01.895714642Z INFO:PeerManager:[bitcoin.cluelessperson.com:51002 SSL] [Errno -2] Name or service not known
2019-05-28T03:52:01.896260043Z INFO:PeerManager:[dummy:51001 TCP] [Errno -2] Name or service not known
2019-05-28T03:52:01.948204476Z INFO:PeerManager:[tn.not.fyi:55002 SSL] [Errno -2] Name or service not known
2019-05-28T03:52:09.141639411Z INFO:DB:header merkle cache populated in 7.3s
2019-05-28T03:52:09.147142113Z INFO:PeerManager:[testnet1.bauerj.eu:50002 SSL] [Errno -2] Name or service not known
2019-05-28T03:52:09.148068346Z INFO:PeerManager:[testnet.hsmiths.com:53012 SSL] [Errno -2] Name or service not known
2019-05-28T03:52:09.148580523Z INFO:PeerManager:[tn.not.fyi:55002 SSL] [Errno -2] Name or service not known
2019-05-28T03:52:09.148870758Z INFO:PeerManager:[dummy:51001 TCP] [Errno -2] Name or service not known
2019-05-28T03:52:09.148961479Z INFO:PeerManager:[bitcoin.cluelessperson.com:51002 SSL] [Errno -2] Name or service not known
2019-05-28T03:52:09.198198471Z INFO:ElectrumX:[0] SSL 95.216.22.155:54920, 0 total
2019-05-28T03:52:09.198609627Z INFO:PeerManager:[testnet1.bauerj.eu:50002 SSL] [Errno -2] Name or service not known
2019-05-28T03:52:09.198787909Z INFO:PeerManager:[tn.not.fyi:55001 TCP] [Errno -2] Name or service not known
2019-05-28T03:52:09.199185966Z INFO:PeerManager:[bitcoin.cluelessperson.com:51001 TCP] [Errno -2] Name or service not known
2019-05-28T03:52:09.200859936Z INFO:PeerManager:[tn.not.fyi:55001 TCP] [Errno -2] Name or service not known
2019-05-28T03:52:09.201699424Z INFO:PeerManager:[testnet1.bauerj.eu:50001 TCP] [Errno -2] Name or service not known
2019-05-28T03:52:09.202251354Z INFO:PeerManager:[bitcoin.cluelessperson.com:51001 TCP] [Errno -2] Name or service not known
2019-05-28T03:52:09.204479672Z INFO:PeerManager:[testnet1.bauerj.eu:50001 TCP] [Errno -2] Name or service not known
```

**Comment by shsmith** [comment]
My "dummy" entry had the local hostname instead of the external hostname. I doubt your local hostname is 'dummy'. 

Another way to work around this is to add your external report host to your local /etc/hosts file so that it resolves to your internal address. If you do that then the original REPORT_SERVICES will work again.

**Comment by SomberNight** [comment]
Oh I see. OK, I ended up putting the local NATted private IP there, and commenting out the sanitizing code from e-x. Other peers will not be happy :D but it works now

**Comment by kyuupichan** [comment]
I think this is now fixed

**Comment by SomberNight** [comment]
https://github.com/kyuupichan/electrumx/commit/a614e4f4cbe09215653b3360dc54b7012d81a4f9 seems to work
Thank you!
