### ISSUE TITLE
websocket service error: AttributeError: 'NoneType' object has no attribute 'serve'

### ISSUE THREAD

**Issue by vlddm** [kyuupichan/electrumx#832]
Got this error after adding ws://127.0.0.1:8050 to SERVICES list.

```
INFO:Prefetcher:cancelled; prefetcher stopping 
INFO:BlockProcessor:flushing to DB for a clean shutdown...
ERROR:root:task crashed: <Task finished coro=<Controller.serve() done, defined at /home/litecoind/electrumx-1.12.0/electrumx/server/controller.py:81> exception=AttributeError("'NoneType' object has no attribute 'serve'",)>
Traceback (most recent call last):
  File "/home/litecoind/.local/lib/python3.6/site-packages/aiorpcx/util.py", line 309, in check_task
    task.result()
  File "/home/litecoind/electrumx-1.12.0/electrumx/server/controller.py", line 134, in serve
    await group.spawn(wait_for_catchup())
  File "/home/litecoind/.local/lib/python3.6/site-packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/home/litecoind/.local/lib/python3.6/site-packages/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/home/litecoind/electrumx-1.12.0/electrumx/server/session.py", line 593, in serve
    await self._start_external_servers()
  File "/home/litecoind/electrumx-1.12.0/electrumx/server/session.py", line 191, in _start_external_servers
    await self._start_servers(service for service in self.env.services
  File "/home/litecoind/electrumx-1.12.0/electrumx/server/session.py", line 181, in _start_servers
    service.port, ssl=sslc)
  File "/home/litecoind/.local/lib/python3.6/site-packages/aiorpcx/websocket.py", line 132, in serve_ws
    return websockets.serve(ws_handler, *args, **kwargs)
AttributeError: 'NoneType' object has no attribute 'serve'
```
Im using:
electrumx-1.12.0 (release version)
aiorpcX             0.18.3
aiohttp             3.5.4
async-timeout       3.0.1
Python 3.6.8
ubuntu 16.04.5

config: 
```
DB_DIRECTORY=/home/litecoind/.electrumxdb
DAEMON_URL=http://ltc:somepass@127.0.0.1:9332/
COIN=Litecoin
SERVICES=ws://127.0.0.1:8050,tcp://127.0.0.1:5001
COST_HARD_LIMIT=0
COST_SOFT_LIMIT=0
PEER_ANNOUNCE=self
PEER_DISCOVERY=
```

**Comment by vlddm** [comment]
Fixed: I was running ElectrumX from source without running setup.py, so websockets package was not installed.
`pip3 install websockets` fixed it.

**Comment by minioff** [comment]
Encountered the same. `setup.py` did not install websockets in my case, there is no mention of that in requirements in the setup file.

Had to be done manually with already mentioned `pip3 install websockets`.

**Comment by kyuupichan** [comment]
The Electrum guys recently wanted websockets removed as a requirement of aiorpcX, so I've added aiorpcx[ws] as a requirement of ElectrumX now.
