### ISSUE TITLE
Crash on reorg (block 444,148)

### ISSUE THREAD

**Issue by shsmith** [kyuupichan/electrumx#84]
This happened in 0.9.12.

http://hastebin.com/ajetuvuhir.sql

INFO:Prefetcher:new block height 444,148 hash 0000000000000000016de40faa242807be536ebdb6847306651f6054d9df32f4
INFO:BlockProcessor:chain reorg detected
INFO:BlockProcessor:chain was reorganised: 1 blocks at heights 444,147-444,147 were replaced
INFO:BlockProcessor:backed up to height 444,146
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.9.12-py3.5.egg/server/block_processor.py", line 231, in advance_blocks
    await loop.run_in_executor(None, job)
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.9.12-py3.5.egg/server/block_processor.py", line 226, in job
    self.advance_block(block, touched)
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.9.12-py3.5.egg/server/block_processor.py", line 510, in advance_block
    raise ChainReorg
server.block_processor.ChainReorg

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.9.12-py3.5.egg/EGG-INFO/scripts/electrumx_server.py", line 68, in main
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.9.12-py3.5.egg/EGG-INFO/scripts/electrumx_server.py", line 59, in main_loop
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.9.12-py3.5.egg/server/protocol.py", line 197, in main_loop
    await future  # Note: future is not one of self.futures
  File "/usr/lib/python3.5/asyncio/tasks.py", line 492, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.9.12-py3.5.egg/server/block_processor.py", line 212, in main_loop
    await self.advance_blocks(blocks, touched)
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.9.12-py3.5.egg/server/block_processor.py", line 233, in advance_blocks
    await self.handle_chain_reorg(touched)
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.9.12-py3.5.egg/server/block_processor.py", line 276, in handle_chain_reorg
    self.backup_blocks(blocks, touched)
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.9.12-py3.5.egg/server/block_processor.py", line 590, in backup_blocks
    self.backup_flush(touched)
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.9.12-py3.5.egg/server/block_processor.py", line 431, in backup_flush
    self.backup_history(batch, hash168s)
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.9.12-py3.5.egg/server/block_processor.py", line 447, in backup_history
    for hash168 in sorted(hash168s):
TypeError: unorderable types: NoneType() < bytes()
CRITICAL:root:ElectrumX server terminated abnormally

**Comment by kyuupichan** [comment]
Yes, sorry this was recently introduced.  The one-line fix is in 0.9.15.  There's a chance simply restarting will fix it in the meantime.
