### ISSUE TITLE
Electrumx crash with EM: "AssertionError"

### ISSUE THREAD

**Issue by g574** [kyuupichan/electrumx#841]
I am running ElectrumX with Dash on two nodes, both crashed at the same time with an "AssertionError" message.
Troubleshooting:
- restart ElectrumX only: failed
- restart Dash, then ElectrumX: failed
- delete ElectrumX database and restart Dash+ElectrumX: it synchronized up to the current height, then it crashed with the same error message.
`INFO:SessionManager:closing down RPC, TCP listening servers
ERROR:root:task crashed: <Task finished coro=<Controller.serve() done, defined at /app/electrumx/electrumx/server/controller.py:81> exception=AssertionError()>
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/aiorpcx/util.py", line 118, in check_task
    task.result()
  File "/app/electrumx/electrumx/server/controller.py", line 134, in serve
    await group.spawn(wait_for_catchup())
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/aiorpcx/curio.py", line 240, in __aexit__
    await self.join()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/aiorpcx/curio.py", line 207, in join
    raise task.exception()
  File "/app/electrumx/electrumx/server/block_processor.py", line 658, in fetch_and_process_blocks
    await group.spawn(self._process_prefetched_blocks())
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/aiorpcx/curio.py", line 240, in __aexit__
    await self.join()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/aiorpcx/curio.py", line 207, in join
    raise task.exception()
  File "/app/electrumx/electrumx/server/block_processor.py", line 619, in _process_prefetched_blocks
    await self.check_and_advance_blocks(blocks)
  File "/app/electrumx/electrumx/server/block_processor.py", line 201, in check_and_advance_blocks
    for n, raw_block in enumerate(raw_blocks)]
  File "/app/electrumx/electrumx/server/block_processor.py", line 201, in <listcomp>
    for n, raw_block in enumerate(raw_blocks)]
  File "/app/electrumx/electrumx/lib/coins.py", line 248, in block
    txs = cls.DESERIALIZER(raw_block, start=len(header)).read_tx_block()
  File "/app/electrumx/electrumx/lib/tx.py", line 134, in read_tx_block
    return [read() for _ in range(self._read_varint())]
  File "/app/electrumx/electrumx/lib/tx.py", line 134, in <listcomp>
    return [read() for _ in range(self._read_varint())]
  File "/app/electrumx/electrumx/lib/tx.py", line 124, in read_tx_and_hash
    return self.read_tx(), self.TX_HASH_FN(self.binary[start:self.cursor])
  File "/app/electrumx/electrumx/lib/tx_dash.py", line 402, in read_tx
    assert self.cursor == end
AssertionError`

**Comment by kyuupichan** [comment]
Either your bitcoind's DB is corrupt or Dash has changed their block format.  No one seems to maintain the dash code for electrumx; I certainly have no idea

**Comment by alexculea** [comment]
Had the same issue - also working with Dash. I fixed it by updating to 1.12.0 and replacing `HOST`, `TCP_PORT` and `RPC_HOST` with `SERVICES = tcp://:50001,rpc://0.0.0.0:8000` in electrumx.conf

**Comment by g574** [comment]
https://github.com/kyuupichan/electrumx/issues/841#issuecomment-502731939
Thank you very much @alexculea, the update solved the issue.
