### ISSUE TITLE
RPC fails when argument list is long

### ISSUE THREAD

**Issue by shsmith** [kyuupichan/electrumx#85]
I am running a script to disconnect malicious connections and generating a single electrumx_rpc.py disconnect [id list] command line.  

When the number of malicious connections is large (maybe > 500) the command line triggers the following exception:

> Traceback (most recent call last):
  File "/home/shsmith/bin/electrumx", line 4, in <module>
    __import__('pkg_resources').run_script('electrumx==0.9.14', 'electrumx_rpc.py')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.9.14-py3.5.egg/EGG-INFO/scripts/electrumx_rpc.py", line 84, in <module>
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.9.14-py3.5.egg/EGG-INFO/scripts/electrumx_rpc.py", line 76, in main
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.9.14-py3.5.egg/EGG-INFO/scripts/electrumx_rpc.py", line 36, in send_and_wait
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.9.14-py3.5.egg/lib/jsonrpc.py", line 317, in encode_and_send_payload
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.9.14-py3.5.egg/lib/jsonrpc.py", line 295, in encode_payload
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.9.14-py3.5.egg/lib/jsonrpc.py", line 404, in check_oversized_request
lib.jsonrpc.RPCError

It would be helpful if the RPC was exempt from the check_oversized_request test.

**Comment by kyuupichan** [comment]
The limit is 5MB for RPC which seems sane - I cannot imagine you're sending 100,000 disconnect IDs?  I don't see how else this can trigger.

**Comment by kyuupichan** [comment]
Can you check your script?  Or please log the send size to check_oversized_request.  You can see at the bottom of protocol.py the RPC limit is 5MB; I cannot see how anything gets even close to that.
