### ISSUE TITLE
failing on BTC testnet

### ISSUE THREAD

**Issue by cgilliard** [kyuupichan/electrumx#905]
Trying to sync with the bitcoin testnet. Getting this error:

INFO:BlockProcessor:our height: 207,303 daemon: 1,580,872 UTXOs 431MB hist 576MB
INFO:Prefetcher:cancelled; prefetcher stopping 
INFO:BlockProcessor:flushing to DB for a clean shutdown...
ERROR:root:task crashed: <Task finished coro=<Controller.serve() done, defined at /home/ubuntu/electrumx/electrumx/server/controller.py:81> exception=AssertionError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aiorpcX-0.18.3-py3.6.egg/aiorpcx/util.py", line 309, in check_task
    task.result()
  File "/home/ubuntu/electrumx/electrumx/server/controller.py", line 134, in serve
    await group.spawn(wait_for_catchup())
  File "/usr/local/lib/python3.6/dist-packages/aiorpcX-0.18.3-py3.6.egg/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/usr/local/lib/python3.6/dist-packages/aiorpcX-0.18.3-py3.6.egg/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/home/ubuntu/electrumx/electrumx/server/block_processor.py", line 669, in fetch_and_process_blocks
    await self.flush(True)
  File "/home/ubuntu/electrumx/electrumx/server/block_processor.py", line 342, in flush
    await self.run_in_thread_with_lock(flush)
  File "/home/ubuntu/electrumx/electrumx/server/block_processor.py", line 198, in run_in_thread_with_lock
    return await asyncio.shield(run_in_thread_locked())
  File "/home/ubuntu/electrumx/electrumx/server/block_processor.py", line 197, in run_in_thread_locked
    return await run_in_thread(func, *args)
  File "/usr/local/lib/python3.6/dist-packages/aiorpcX-0.18.3-py3.6.egg/aiorpcx/curio.py", line 68, in run_in_thread
    return await get_event_loop().run_in_executor(None, func, *args)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/electrumx/electrumx/server/block_processor.py", line 341, in flush
    self.estimate_txs_remaining)
  File "/home/ubuntu/electrumx/electrumx/server/db.py", line 207, in flush_dbs
    self.flush_fs(flush_data)
  File "/home/ubuntu/electrumx/electrumx/server/db.py", line 247, in flush_fs
    assert len(flush_data.block_tx_hashes) == len(flush_data.headers)
AssertionError

**Comment by cgilliard** [comment]
Problem seems to have been a permissions issue on my side. Closing the issue.
