### ISSUE TITLE
Electrumx for Litecoin crashes on startup

### ISSUE THREAD

**Issue by cjamthagen** [kyuupichan/electrumx#906]
Electrumx has been working well for me for the past couple of months, both for BTC and LTC, and their testnets. However, recently its stopped working for LTC. It works well for BTC still.

It stops with the following output
```
okt 10 08:32:33 electrumx systemd[1]: Started Electrumx-ltc.
okt 10 08:32:33 electrumx electrumx_server[1759]: INFO:electrumx:ElectrumX server starting
okt 10 08:32:33 electrumx electrumx_server[1759]: INFO:electrumx:logging level: INFO
okt 10 08:32:33 electrumx electrumx_server[1759]: INFO:Controller:Python version: 3.6.8 (default, Oct  7 2019, 12:59:55)  [GCC 8.3.0]
okt 10 08:32:33 electrumx electrumx_server[1759]: INFO:Controller:software version: ElectrumX 1.11.0
okt 10 08:32:33 electrumx electrumx_server[1759]: INFO:Controller:aiorpcX version: 0.17.0
okt 10 08:32:33 electrumx electrumx_server[1759]: INFO:Controller:supported protocol versions: 1.4-1.4.2okt 10 08:32:33 electrumx electrumx_server[1759]: INFO:Controller:event loop policy: None
okt 10 08:32:33 electrumx electrumx_server[1759]: INFO:Controller:reorg limit is 800 blocks
okt 10 08:32:33 electrumx electrumx_server[1759]: INFO:Daemon:daemon #1 at localhost:9332/ (current)
okt 10 08:32:33 electrumx electrumx_server[1759]: INFO:DB:switching current directory to /home/user/db-ltc
okt 10 08:32:33 electrumx electrumx_server[1759]: INFO:DB:using rocksdb for DB backend
okt 10 08:32:33 electrumx electrumx_server[1759]: INFO:DB:opened UTXO DB (for sync: True)
okt 10 08:32:33 electrumx electrumx_server[1759]: INFO:DB:DB version: 6
okt 10 08:32:33 electrumx electrumx_server[1759]: INFO:DB:coin: Litecoin
okt 10 08:33:42 electrumx electrumx_server[1759]: INFO:DB:flushed filesystem data in 0.00s
okt 10 08:33:42 electrumx electrumx_server[1759]: ERROR:root:task crashed: <Task finished coro=<Controller.serve() done, defined at /usr/local/lib/python3.6/dist-packages/electrumX-1.11.0-py3.6.egg/electrumx/server/controller.py:81> exception=error("'H' format requires 0 <= number <= 65535",)>
okt 10 08:33:42 electrumx electrumx_server[1759]: Traceback (most recent call last):
okt 10 08:33:42 electrumx electrumx_server[1759]:   File "/usr/local/lib/python3.6/dist-packages/aiorpcX-0.17.0-py3.6.egg/aiorpcx/util.py", line 309, in check_taskory:history DB version: 0
okt 10 08:33:42 electrumx electrumx_server[1759]:     task.result()h count: 65,535
okt 10 08:33:42 electrumx electrumx_server[1759]:   File "/usr/local/lib/python3.6/dist-packages/electruokt 10 08:33:42 electrumx electrumx_server[1759]:     await self.flush(True).0.1', 8000): address alreadokt 10 08:33:42 electrumx electrumx_server[1759]:   File "/usr/local/lib/python3.6/dist-packages/electruokt 10 08:33:42 electrumx electrumx_server[1759]:     return await run_in_thread(func, *args)ges/aiorpcXokt 10 08:33:42 electrumx electrumx_server[1759]:   File "/usr/local/lib/python3.6/dist-packages/aiorpcX-0.17.0-py3.6.egg/aiorpcx/curio.py", line 68, in run_in_thread/local/lib/python3.6/dist-packages/electruokt 10 08:33:42 electrumx electrumx_server[1759]:     return await get_event_loop().run_in_executor(None, func, *args)2 electrumx electrumx_server[1759]:     return await asyncio.shield(run_in_thread_locked()okt 10 08:33:42 electrumx electrumx_server[1759]:   File "/usr/local/lib/python3.6/dist-packages/electruokt 10 08:33:42 electrumx electrumx_server[1759]:   File "/usr/local/lib/python3.6/dist-packages/electrumX-1.11.0-py3.6.egg/electrumx/server/history.py", line 133, in flushlush()maining) **self.kwargs)
okt 10 08:33:42 electrumx electrumx_server[1759]:     flush_id = pack_be_uint16(self.flush_count)
okt 10 08:33:42 electrumx electrumx_server[1759]: struct.error: 'H' format requires 0 <= number <= 65535
```

**Comment by cjamthagen** [comment]
Thank you, was not aware of that script. Running it with COIN=Litecoin and DB_DIRECTORY=/home/user/db-ltc however also crashes

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/electrumX-1.11.0-py3.6.egg/EGG-INFO/scripts/electrumx_compact_history", line 73, in main
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/electrumX-1.11.0-py3.6.egg/EGG-INFO/scripts/electrumx_compact_history", line 51, in compact_history
  File "/usr/local/lib/python3.6/dist-packages/electrumX-1.11.0-py3.6.egg/electrumx/server/db.py", line 147, in open_for_compacting
    await self._open_dbs(True, True)
  File "/usr/local/lib/python3.6/dist-packages/electrumX-1.11.0-py3.6.egg/electrumx/server/db.py", line 123, in _open_dbs]$ 
    self.utxo_db = self.db_class('utxo', for_sync)
  File "/usr/local/lib/python3.6/dist-packages/electrumX-1.11.0-py3.6.egg/electrumx/server/storage.py", line 31, in __init__
    self.open(name, create=self.is_new)
  File "/usr/local/lib/python3.6/dist-packages/electrumX-1.11.0-py3.6.egg/electrumx/server/storage.py", line 83, in open~]$ 
    max_open_files=mof)nv_base.Env:lowered maximum sessions from 1,000 to 674 because your open file lim  File "plyvel/_plyvel.pyx", line 247, in plyvel._plyvel.DB.__init__
  File "plyvel/_plyvel.pyx", line 91, in plyvel._plyvel.raise_for_status-ltc
plyvel._plyvel.CorruptionError: b'Corruption: VersionEdit: unknown tag'
CRITICAL:root:History compaction terminated abnormally

```

Do you know why that is?

**Comment by kyuupichan** [comment]
Unfortunately it seems your DB was corrupted somehow, you will need to delete it and re-sync.

**Comment by cjamthagen** [comment]
Ok, thank you.
