### ISSUE TITLE
Bitcoin testnet not parsing well

### ISSUE THREAD

**Issue by petrkr** [kyuupichan/electrumx#92]
Hi,
when trying catch-up testnet network from bitcoin-core daemon, it have problem with parsing TX's around 724,030+ height. Probably parser reply on some transaction binary format and does not support segwit (or something else). I already saw this issue on original electrum server, but that have try/catch and only logs "cannot parse transaction xxxx" messages. Seems like if implementation will use bitcoin's JSON's "decoderawtransaction" it would work, but I guess it would be super-slow compared to binary processing.

Here is stacktrace of crash>
  https://hastebin.com/vaxeviqoce.sql

Regards Petr

**Comment by kyuupichan** [comment]
It certainly seems like a transaction that is invalid on mainnet. I'm not sure of segwit details. 

Do you have an electrum client capable of handling testnet? Or are you intending to use the resulting DB for some other purpose?

**Comment by petrkr** [comment]
For now I wanna use DB for other purpose, It does not make sence create something what is already done and still I want use my own instance than using 3rd party services like "blockchain.info" API. Also if segwit will goes to production (mainnet) it would broke up all servers in actual situation.

Anyway I am also not sure about segwit details also do not know how to create such transaction, I just saw many TX's when I do "decoderawtransaction" with such scripts and mostly these are that TXs which fails on electrum's parser. Most bad is many TXs are somehow parsed, but results are really wrong, like different TX hash, amount and so on, so there was really random I couch some TX where hex decode made integer in negative and that's why struct.pack(<q) fails.

Also testnet electrum client would be also nice, but I not got time to refactor it.

**Comment by kyuupichan** [comment]
Can you confirm this is indeed testnet and not segnet? There should be no Segwit transactions on testnet so perhaps the current code is expecting something too strict. 

Either way it'll take some time before I can look into it

**Comment by petrkr** [comment]
Good question
I am using Bitcoin Core daemon version 0.13.1 with "testnet" flag = 1
Same blockchain uses mycelium testnet mobile app so I hope I am on same blockchain.

btw I little modified master version of electrum client to supports testnet, still have some bugs (probably due missing blockchain_headers bootstrap file). But it can generate address, send and receive transactions. For now it is enough to me.

it is at my forked tree at github.

**Comment by kyuupichan** [comment]
Flagged as a bug because we should at least fail better.  Perhaps there is a real parsing problem too.

**Comment by ecdsa** [comment]
@kyuupichan segnet is deprecated. segwit is activated on the current testnet

**Comment by kyuupichan** [comment]
@ecdsa - do you intend to add testnet support to the client?  If you do I'll get this sorted.

**Comment by ecdsa** [comment]
yes I plan to add testnet support soon. 
it would be great to have testnet in electrumx.

**Comment by ecdsa** [comment]
note that you do not need to send the "txinwitness" to the client.

**Comment by ecdsa** [comment]
great!

**Comment by shsmith** [comment]
Running 0.10.2 and got a parse failure somewhere after height 869,210:

>INFO:BlockProcessor:our height: 869,210 daemon: 1,064,026 UTXOs 86MB hist 84MB
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.10.2-py3.5.egg/EGG-INFO/scripts/electrumx_server.py", line 69, in main
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.10.2-py3.5.egg/EGG-INFO/scripts/electrumx_server.py", line 60, in main_lo                                                                               op
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.10.2-py3.5.egg/server/controller.py", line 187, in main_loop
    await future  # Note: future is not one of self.futures
  File "/usr/lib/python3.5/asyncio/tasks.py", line 492, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.10.2-py3.5.egg/server/block_processor.py", line 212, in main_loop
    await self.advance_blocks(blocks, touched)
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.10.2-py3.5.egg/server/block_processor.py", line 231, in advance_blocks
    await loop.run_in_executor(None, job)
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.10.2-py3.5.egg/server/block_processor.py", line 226, in job
    self.advance_block(block, touched)
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.10.2-py3.5.egg/server/block_processor.py", line 475, in advance_block
    header, txs = self.coin.read_block(block, self.height + 1)
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.10.2-py3.5.egg/lib/coins.py", line 228, in read_block
    return (header, deserializer(rest).read_block())
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.10.2-py3.5.egg/lib/tx.py", line 91, in read_block
    txs = [read_tx() for n in range(self._read_varint())]
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.10.2-py3.5.egg/lib/tx.py", line 91, in <listcomp>
    txs = [read_tx() for n in range(self._read_varint())]
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.10.2-py3.5.egg/lib/tx.py", line 84, in read_tx
    self._read_outputs(),   # outputs
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.10.2-py3.5.egg/lib/tx.py", line 109, in _read_outputs
    return [read_output() for i in range(self._read_varint())]
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.10.2-py3.5.egg/lib/tx.py", line 109, in <listcomp>
    return [read_output() for i in range(self._read_varint())]
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.10.2-py3.5.egg/lib/tx.py", line 113, in _read_output
    self._read_le_int64(),  # value
  File "/usr/local/lib/python3.5/dist-packages/electrumx-0.10.2-py3.5.egg/lib/tx.py", line 143, in _read_le_int64
    result, = unpack_from('<q', self.binary, self.cursor)
struct.error: unpack_from requires a buffer of at least 8 bytes
CRITICAL:root:ElectrumX server terminated abnormally

It fails again when I restart the deamon.
The full log is here: http://vps.hsmiths.com:49001/testNet_electrumx.log

**Comment by kyuupichan** [comment]
The logs show you're using the wrong NET. Please read the ChangeLog for
0.10.2 and the relevant part of coins.py of it helps.

On Mon, 9 Jan 2017, 02:53 shsmith, <notifications@github.com> wrote:

Running 0.10.2 and got a parse failure somewhere after height 869,210:

INFO:BlockProcessor:our height: 869,210 daemon: 1,064,026 UTXOs 86MB hist
84MB
Traceback (most recent call last):
File
"/usr/local/lib/python3.5/dist-packages/electrumx-0.10.2-py3.5.egg/EGG-INFO/scripts/electrumx_server.py",
line 69, in main
File
"/usr/local/lib/python3.5/dist-packages/electrumx-0.10.2-py3.5.egg/EGG-INFO/scripts/electrumx_server.py",
line 60, in main_lo op
File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in
run_until_complete
return future.result()
File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
raise self._exception
File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
result = coro.send(None)
File
"/usr/local/lib/python3.5/dist-packages/electrumx-0.10.2-py3.5.egg/server/controller.py",
line 187, in main_loop
await future # Note: future is not one of self.futures
File "/usr/lib/python3.5/asyncio/tasks.py", line 492, in _wait_for_one
return f.result() # May raise f.exception().
File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
raise self._exception
File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
result = coro.throw(exc)
File
"/usr/local/lib/python3.5/dist-packages/electrumx-0.10.2-py3.5.egg/server/block_processor.py",
line 212, in main_loop
await self.advance_blocks(blocks, touched)
File
"/usr/local/lib/python3.5/dist-packages/electrumx-0.10.2-py3.5.egg/server/block_processor.py",
line 231, in advance_blocks
await loop.run_in_executor(None, job)
File "/usr/lib/python3.5/asyncio/futures.py", line 361, in *iter*
yield self # This tells Task to wait for completion.
File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
future.result()
File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
raise self._exception
File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
result = self.fn(*self.args, **self.kwargs)
File
"/usr/local/lib/python3.5/dist-packages/electrumx-0.10.2-py3.5.egg/server/block_processor.py",
line 226, in job
self.advance_block(block, touched)
File
"/usr/local/lib/python3.5/dist-packages/electrumx-0.10.2-py3.5.egg/server/block_processor.py",
line 475, in advance_block
header, txs = self.coin.read_block(block, self.height + 1)
File
"/usr/local/lib/python3.5/dist-packages/electrumx-0.10.2-py3.5.egg/lib/coins.py",
line 228, in read_block
return (header, deserializer(rest).read_block())
File
"/usr/local/lib/python3.5/dist-packages/electrumx-0.10.2-py3.5.egg/lib/tx.py",
line 91, in read_block
txs = [read_tx() for n in range(self._read_varint())]
File
"/usr/local/lib/python3.5/dist-packages/electrumx-0.10.2-py3.5.egg/lib/tx.py",
line 91, in
txs = [read_tx() for n in range(self._read_varint())]
File
"/usr/local/lib/python3.5/dist-packages/electrumx-0.10.2-py3.5.egg/lib/tx.py",
line 84, in read_tx
self._read_outputs(), # outputs
File
"/usr/local/lib/python3.5/dist-packages/electrumx-0.10.2-py3.5.egg/lib/tx.py",
line 109, in _read_outputs
return [read_output() for i in range(self._read_varint())]
File
"/usr/local/lib/python3.5/dist-packages/electrumx-0.10.2-py3.5.egg/lib/tx.py",
line 109, in
return [read_output() for i in range(self._read_varint())]
File
"/usr/local/lib/python3.5/dist-packages/electrumx-0.10.2-py3.5.egg/lib/tx.py",
line 113, in _read_output
self._read_le_int64(), # value
File
"/usr/local/lib/python3.5/dist-packages/electrumx-0.10.2-py3.5.egg/lib/tx.py",
line 143, in _read_le_int64
result, = unpack_from('<q', self.binary, self.cursor)
struct.error: unpack_from requires a buffer of at least 8 bytes
CRITICAL:root:ElectrumX server terminated abnormally

It fails again when I restart the deamon.
The full log is here: http://vps.hsmiths.com:49001/testNet_electrumx.log

—
You are receiving this because you modified the open/close state.


Reply to this email directly, view it on GitHub
<https://github.com/kyuupichan/electrumx/issues/92#issuecomment-271166862>,
or mute the thread

**Comment by kyuupichan** [comment]
The logs show you're using the wrong NET. Please read the ChangeLog for 0.10.2 and the relevant part of coins.py of it helps.

**Comment by shsmith** [comment]
I changed NET from testnet to testnet-segwit and restarted the sync.
It ran to completion without any errors.
Thanks!
