### ISSUE TITLE
ModuleNotFoundError: No module named 'aiorpcx'

### ISSUE THREAD

**Issue by pedr0-fr** [kyuupichan/electrumx#934]
Running eletrumX for the first time. I followed the [guide](https://github.com/kyuupichan/electrumx/blob/master/docs/HOWTO.rst) and everything went smoothly: installed pre-requisites, cloned it, ran setup.py, set up the configuration files and started it with `systemctl start electrumx`. When I checked the log via `journalctl -u electrumx` I get:
```
Dec 16 01:46:11 lenovoW541 systemd[1]: Started Electrumx.
Dec 16 01:46:11 lenovoW541 electrumx_server[28383]: Traceback (most recent call last):
Dec 16 01:46:11 lenovoW541 electrumx_server[28383]:   File "/media/pedro/Portable_2TB/Bitcoin/electrumx/electrumx_server", line 16, in <module>
Dec 16 01:46:11 lenovoW541 electrumx_server[28383]:     from electrumx import Controller, Env
Dec 16 01:46:11 lenovoW541 electrumx_server[28383]:   File "/media/pedro/Portable_2TB/Bitcoin/electrumx/electrumx/__init__.py", line 4, in <module>
Dec 16 01:46:11 lenovoW541 electrumx_server[28383]:     from electrumx.server.controller import Controller
Dec 16 01:46:11 lenovoW541 electrumx_server[28383]:   File "/media/pedro/Portable_2TB/Bitcoin/electrumx/electrumx/server/controller.py", line 10, in <module>
Dec 16 01:46:11 lenovoW541 electrumx_server[28383]:     from aiorpcx import _version as aiorpcx_version, TaskGroup
Dec 16 01:46:11 lenovoW541 electrumx_server[28383]: ModuleNotFoundError: No module named 'aiorpcx'
Dec 16 01:46:12 lenovoW541 systemd[1]: electrumx.service: Main process exited, code=exited, status=1/FAILURE
Dec 16 01:46:12 lenovoW541 systemd[1]: electrumx.service: Failed with result 'exit-code'.
```

I have checked that this package is installed (which was confirmed durin the setup) don't know how I can possibly get this error. I have aiorpcx version 0.18.4 installed on python 3.7.3 on Ubuntu 18.04.3.

**Comment by SomberNight** [comment]
Make sure it's installed for the correct python version.

> python 3.7.3

Ubuntu 18.04  by default comes with python 3.6.x, so that means you have two different python interpreters at least.

**Comment by pedr0-fr** [comment]
I am using miniconda, I have a `/home/pedro/miniconda3/bin/python` which is version 3.7.3 and a `/home/pedro/miniconda3/bin/python3` which has the same version

**Comment by pedr0-fr** [comment]
Ok, seems like the issue were the old pre-installed pythons under `/usr/lib` Now I get:

```
Dec 16 02:18:05 lenovoW541 systemd[1]: Started Electrumx.
Dec 16 02:18:05 lenovoW541 electrumx_server[12068]: Could not find platform independent libraries <prefix>
Dec 16 02:18:05 lenovoW541 electrumx_server[12068]: Could not find platform dependent libraries <exec_prefix>
Dec 16 02:18:05 lenovoW541 electrumx_server[12068]: Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Dec 16 02:18:05 lenovoW541 electrumx_server[12068]: Fatal Python error: Py_Initialize: Unable to get the locale encoding
Dec 16 02:18:05 lenovoW541 electrumx_server[12068]: ModuleNotFoundError: No module named 'encodings'
Dec 16 02:18:05 lenovoW541 electrumx_server[12068]: Current thread 0x00007f645471b740 (most recent call first):
Dec 16 02:18:05 lenovoW541 systemd[1]: electrumx.service: Main process exited, code=dumped, status=6/ABRT
Dec 16 02:18:05 lenovoW541 systemd[1]: electrumx.service: Failed with result 'core-dump'.
```
Guess it will be solved by adding this under `/etc/electrumx.conf`:
PYTHONHOME=/home/pedro/miniconda3/bin/python

**Comment by pedr0-fr** [comment]
After setting `PYTHONHOME=/home/pedro/miniconda3/bin`, I get the error:

```
Dec 16 02:30:53 lenovoW541 systemd[1]: Started Electrumx.
Dec 16 02:30:53 lenovoW541 electrumx_server[17998]: Fatal Python error: Py_Initialize: Unable to get the locale encoding
Dec 16 02:30:53 lenovoW541 electrumx_server[17998]: ModuleNotFoundError: No module named 'encodings'
Dec 16 02:30:53 lenovoW541 electrumx_server[17998]: Current thread 0x00007fa95349c740 (most recent call first):
Dec 16 02:30:53 lenovoW541 systemd[1]: electrumx.service: Main process exited, code=dumped, status=6/ABRT
Dec 16 02:30:53 lenovoW541 systemd[1]: electrumx.service: Failed with result 'core-dump'.
```
This was solved by further adding the environment variable `PYTHONPATH=/home/pedro/miniconda3/lib/python3.7`. Now I am stuck with this error:

```
Dec 16 02:34:27 lenovoW541 systemd[1]: Started Electrumx.
Dec 16 02:34:27 lenovoW541 electrumx_server[19627]: Fatal Python error: Py_Initialize: can't initialize sys standard streams
Dec 16 02:34:27 lenovoW541 electrumx_server[19627]: Traceback (most recent call last):
Dec 16 02:34:27 lenovoW541 electrumx_server[19627]:   File "/home/pedro/miniconda3/lib/python3.7/_bootlocale.py", line 35, in getpreferredencoding
Dec 16 02:34:27 lenovoW541 electrumx_server[19627]:     if sys.flags.utf8_mode:
Dec 16 02:34:27 lenovoW541 electrumx_server[19627]: AttributeError: 'sys.flags' object has no attribute 'utf8_mode'
Dec 16 02:34:27 lenovoW541 systemd[1]: electrumx.service: Main process exited, code=dumped, status=6/ABRT
Dec 16 02:34:27 lenovoW541 systemd[1]: electrumx.service: Failed with result 'core-dump'.
```

Arrgggh...

**Comment by pedr0-fr** [comment]
Problem solved after adding the environment variable `PYTHONIOENCODING="utf-8"`, now I get the error:

```
Dec 16 02:49:42 lenovoW541 systemd[1]: Started Electrumx.
Dec 16 02:49:42 lenovoW541 electrumx_server[27074]: Traceback (most recent call last):
Dec 16 02:49:42 lenovoW541 electrumx_server[27074]:   File "/media/pedro/Portable_2TB/Bitcoin/electrumx/electrumx_server", line 12, in <module>
Dec 16 02:49:42 lenovoW541 electrumx_server[27074]:     import logging
Dec 16 02:49:42 lenovoW541 electrumx_server[27074]:   File "/home/pedro/miniconda3/lib/python3.7/logging/__init__.py", line 26, in <module>
Dec 16 02:49:42 lenovoW541 electrumx_server[27074]:     import sys, os, time, io, traceback, warnings, weakref, collections.abc
Dec 16 02:49:42 lenovoW541 electrumx_server[27074]:   File "/home/pedro/miniconda3/lib/python3.7/traceback.py", line 5, in <module>
Dec 16 02:49:42 lenovoW541 electrumx_server[27074]:     import linecache
Dec 16 02:49:42 lenovoW541 electrumx_server[27074]:   File "/home/pedro/miniconda3/lib/python3.7/linecache.py", line 11, in <module>
Dec 16 02:49:42 lenovoW541 electrumx_server[27074]:     import tokenize
Dec 16 02:49:42 lenovoW541 electrumx_server[27074]:   File "/home/pedro/miniconda3/lib/python3.7/tokenize.py", line 33, in <module>
Dec 16 02:49:42 lenovoW541 electrumx_server[27074]:     import re
Dec 16 02:49:42 lenovoW541 electrumx_server[27074]:   File "/home/pedro/miniconda3/lib/python3.7/re.py", line 123, in <module>
Dec 16 02:49:42 lenovoW541 electrumx_server[27074]:     import sre_compile
Dec 16 02:49:42 lenovoW541 electrumx_server[27074]:   File "/home/pedro/miniconda3/lib/python3.7/sre_compile.py", line 17, in <module>
Dec 16 02:49:42 lenovoW541 electrumx_server[27074]:     assert _sre.MAGIC == MAGIC, "SRE module mismatch"
Dec 16 02:49:42 lenovoW541 electrumx_server[27074]: AssertionError: SRE module mismatch
Dec 16 02:49:42 lenovoW541 systemd[1]: electrumx.service: Main process exited, code=exited, status=1/FAILURE
Dec 16 02:49:42 lenovoW541 systemd[1]: electrumx.service: Failed with result 'exit-code'.
```

I think I might need to reinstall python...

**Comment by pedr0-fr** [comment]
Ok, after a bit of struggle finally got it to work. These are the steps that made it work:
- Uninstall miniconda/anaconda as electrumX doesn't seem to work with it.
- Google what was the value I was supposed to use for 'COIN' to get it to work with bitcoin. I tried 'Bitcoin', 'BTC', 'BitcoinMixin' but figured out I was supposed to put 'BitcoinSegwit'.
- Set up an RPC username and password. Usually, I don't set these parameters in my `bitcoin.conf` file because I don't use the RPC externally but through the CLI which uses the .cookie file under `datadir` for authentification.
