### ISSUE TITLE
Flush data question

### ISSUE THREAD

**Issue by sinetek** [kyuupichan/electrumx#955]
Hi,

I am trying to add support for Veil, and I am running into an assert error, as follows:

`ERROR:root:task crashed: <Task finished name='Task-2' coro=<Controller.serve() done, defined at /home/sinetek/projects/electrumx/electrumx/server/controller.py:81> exception=AssertionError()>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/aiorpcx/util.py", line 309, in check_task
    task.result()
  File "/home/sinetek/projects/electrumx/electrumx/server/controller.py", line 134, in serve
    await group.spawn(wait_for_catchup())
  File "/usr/lib/python3.8/site-packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/usr/lib/python3.8/site-packages/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/home/sinetek/projects/electrumx/electrumx/server/block_processor.py", line 672, in fetch_and_process_blocks
    await self.flush(True)
  File "/home/sinetek/projects/electrumx/electrumx/server/block_processor.py", line 345, in flush
    await self.run_in_thread_with_lock(flush)
  File "/home/sinetek/projects/electrumx/electrumx/server/block_processor.py", line 201, in run_in_thread_with_lock
    return await asyncio.shield(run_in_thread_locked())
  File "/home/sinetek/projects/electrumx/electrumx/server/block_processor.py", line 200, in run_in_thread_locked
    return await run_in_thread(func, *args)
  File "/usr/lib/python3.8/site-packages/aiorpcx/curio.py", line 68, in run_in_thread
    return await get_event_loop().run_in_executor(None, func, *args)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/sinetek/projects/electrumx/electrumx/server/block_processor.py", line 343, in flush
    self.db.flush_dbs(self.flush_data(), flush_utxos,
  File "/home/sinetek/projects/electrumx/electrumx/server/db.py", line 207, in flush_dbs
    self.flush_fs(flush_data)
  File "/home/sinetek/projects/electrumx/electrumx/server/db.py", line 250, in flush_fs
    assert len(flush_data.block_tx_hashes) == len(flush_data.headers)
AssertionError
`

I don't understand what is going on, I've been reading the code around that part for days but I'm completely lost at what it's trying to do, what is the assert trying to do here?

The `headers` field is 320, and the `block_tx_hashes` is 321.  Do you have any idea why these might not be equal?

**Comment by sinetek** [comment]
sorry for the poor formatting, I do not know how to make it better.

the error in question is,

electrumx/server/db.py", line 250, in flush_fs assert len(flush_data.block_tx_hashes) == len(flush_data.headers)

**Comment by kyuupichan** [comment]
You might find #974 makes the underlying issue more obvious

**Comment by kyuupichan** [comment]
This is likely handled better in git HEAD, which should show the real cause.
