### ISSUE TITLE
UTXO cache is limited to a 32 bit bound on transaction count 

### ISSUE THREAD

**Issue by rt121212121** [kyuupichan/electrumx#975]
I don't fully understand how to update the db undo entries at this time otherwise I'd create a pull request.
```
Mar 13 06:48:08 electrumx-stn electrumx_server[2354]: ERROR:BlockProcessor:error prefetching
Mar 13 06:48:08 electrumx-stn electrumx_server[2354]: Traceback (most recent call last):
Mar 13 06:48:08 electrumx-stn electrumx_server[2354]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.14.0-py3.7.egg/electrumx/server/block_processor.py", line 677, in fetch_and_process_blocks
Mar 13 06:48:08 electrumx-stn electrumx_server[2354]:     await group.spawn(self._process_prefetched_blocks())
Mar 13 06:48:08 electrumx-stn electrumx_server[2354]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 242, in __aexit__
Mar 13 06:48:08 electrumx-stn electrumx_server[2354]:     await self.join()
Mar 13 06:48:08 electrumx-stn electrumx_server[2354]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 211, in join
Mar 13 06:48:08 electrumx-stn electrumx_server[2354]:     raise task.exception()
Mar 13 06:48:08 electrumx-stn electrumx_server[2354]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.14.0-py3.7.egg/electrumx/server/block_processor.py", line 638, in _process_prefetched_blocks
Mar 13 06:48:08 electrumx-stn electrumx_server[2354]:     await self.check_and_advance_blocks(blocks)
Mar 13 06:48:08 electrumx-stn electrumx_server[2354]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.14.0-py3.7.egg/electrumx/server/block_processor.py", line 216, in check_and_advance_blocks
Mar 13 06:48:08 electrumx-stn electrumx_server[2354]:     await self.run_in_thread_with_lock(self.advance_blocks, blocks)
Mar 13 06:48:08 electrumx-stn electrumx_server[2354]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.14.0-py3.7.egg/electrumx/server/block_processor.py", line 199, in run_in_thread_with_lock
Mar 13 06:48:08 electrumx-stn electrumx_server[2354]:     return await asyncio.shield(run_in_thread_locked())
Mar 13 06:48:08 electrumx-stn electrumx_server[2354]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.14.0-py3.7.egg/electrumx/server/block_processor.py", line 198, in run_in_thread_locked
Mar 13 06:48:08 electrumx-stn electrumx_server[2354]:     return await run_in_thread(func, *args)
Mar 13 06:48:08 electrumx-stn electrumx_server[2354]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 68, in run_in_thread
Mar 13 06:48:08 electrumx-stn electrumx_server[2354]:     return await get_event_loop().run_in_executor(None, func, *args)
Mar 13 06:48:08 electrumx-stn electrumx_server[2354]:   File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Mar 13 06:48:08 electrumx-stn electrumx_server[2354]:     result = self.fn(*self.args, **self.kwargs)
Mar 13 06:48:08 electrumx-stn electrumx_server[2354]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.14.0-py3.7.egg/electrumx/server/block_processor.py", line 395, in advance_blocks
Mar 13 06:48:08 electrumx-stn electrumx_server[2354]:     undo_info = self.advance_txs(block.transactions, is_unspendable)
Mar 13 06:48:08 electrumx-stn electrumx_server[2354]:   File "/usr/local/lib/python3.7/dist-packages/electrumX-1.14.0-py3.7.egg/electrumx/server/block_processor.py", line 424, in advance_txs
Mar 13 06:48:08 electrumx-stn electrumx_server[2354]:     tx_numb = to_le_uint32(tx_num)
Mar 13 06:48:08 electrumx-stn electrumx_server[2354]: struct.error: 'I' format requires 0 <= number <= 4294967295
```

**Comment by kyuupichan** [comment]
Not the UTXO cache but a fundamental part of the DB format.  Fixed in git HEAD.
